### ISSUE TITLE
Dataset Foo could not be loaded and cannot be activated.

### ISSUE THREAD

**Issue by zweinnullmarketing** [juicycleff/flutter-unity-view-widget#115]
Hi, 
try to integrate Unity 2019.3.5f1 and vuforia 9.0.12 in my flutter app.
In android i have no problems, but ios say the Dataset could not be loaded.
Any Ideas?

**Comment by juicycleff** [comment]
@zweinnullmarketing sorry we have not tested against vuforia with the latest improvements. I will take a look at it sometime. We are also open to contributions

**Comment by qqmikey** [comment]
@zweinnullmarketing 
You need to move Vuforia and Data folders inside Runner project
