### ISSUE TITLE
XR interaction toolkit with flutter android (ARFoundation 3.0.1)

### ISSUE THREAD

**Issue by skypu3** [juicycleff/flutter-unity-view-widget#118]
Hi All,

Recently, I tried to move my unity project into flutter.  And I had used the XR interaction toolkit 0.9.3 preview version.
If I build standalone unity project, and run I can tap (AR raycast), select, translate, and scale my object.
However, when I built into flutter, then the object manipulation doesn't work.
I watch the XR interaction toolkit source code, I found Input.touches is be cleared at "GestureTouchesUtility", the touch is be canceled so can't fire any touch event.
Do you know what's happened inside flutter and unity ?

**Comment by skypu3** [comment]
BTW, the iOS is fine, only android with flutter.

**Comment by skypu3** [comment]
I think the Input.touchCount is early cleared, so the touch.phase such as TouchPhase.End cannot be triggered.

**Comment by juicycleff** [comment]
@skypu3 I've not had time to test against Android, but yes iOS is fine. I will test against Android and fix it on Friday

**Comment by skypu3** [comment]
OK, the final test is only happened on tap gesture, that TouchPhase.Move and TouchPhase.End couldn't be triggered. However the drap, rotation, and scale gestures are fine. Thanks.

**Comment by skypu3** [comment]
@juicycleff, do you find any solutions about that ?

**Comment by taras-mashlyanka** [comment]
@juicycleff, any chance this will be fixed soon?
I experience this problem with Unity Fingers plugin on Android.

**Comment by guoguoguilai** [comment]
The same issue. Any update?

**Comment by juicycleff** [comment]
I have exposed all gesture interactions from Flutter to Unity in 2.0.0 and later
