### ISSUE TITLE
how export release flutter app android?

### ISSUE THREAD

**Issue by rahmanroohi** [juicycleff/flutter-unity-view-widget#128]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':flutter_unity_widget:profileRuntimeClasspath'.
   > Could not resolve project :UnityExport.
     Required by:
         project :flutter_unity_widget
      > Unable to find a matching variant of project :UnityExport:
          - Variant 'debugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'
.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Variant 'debugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'
.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'releaseApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'
.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Variant 'releaseRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'
.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --sc
an to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by TarekMedhat** [comment]
In UnityExport/build.gradle
Add 
```
android {
  buildTypes {
      profile {}
    }
....
}
```

**Comment by figux01** [comment]
> In UnityExport/build.gradle
> Add
> 
> ```
> android {
>   buildTypes {
>       profile {}
>     }
> ....
> }
> ```

This does not work for me, still get the error.

**Comment by Witchd0ct0r** [comment]
I have the same issue. I can make assetbundles but APKs.

**Comment by Witchd0ct0r** [comment]
> 
> 
> > In UnityExport/build.gradle
> > Add
> > ```
> > android {
> >   buildTypes {
> >       profile {}
> >     }
> > ....
> > }
> > ```
> 
> This does not work for me, still get the same error.

Found the solution. Do not add it to UnityExport. Add the buildTypes code to unityLibrary/build.gradle
