### ISSUE TITLE
[Unifbx] does not work in flutter-unity

### ISSUE THREAD

**Issue by zhangli-jerry** [juicycleff/flutter-unity-view-widget#131]
flutter-unity works fine in my project. 
But when I use unity [Unifbx] to load 2D/3D assets at runtime in our unity application,
it did not work in flutter-unity.

How can I do to fix this problem? Thanks a lot.

**Comment by juicycleff** [comment]
@zhangli-jerry that is a Unity problem, since we are just using UnityFramework internally
