### ISSUE TITLE
Load assets from Cloud with unity AR foundation

### ISSUE THREAD

**Issue by lupohirp** [juicycleff/flutter-unity-view-widget#135]
Hello,

I'm trying to do an AR app with flutter.
For now we are using Google Arcore for download the assets from Cloud and then  attach when Plane Is detected. It's possibile to do something similar with ar foundation?

Thanks.

**Comment by Darkmax** [comment]
I think this is not the correct forum for that, you will have better results on unity forum, because the question is more related to unity than to this plugin

**Comment by jamesncl** [comment]
Agreed, this isn't a flutter_unity_view issue, it's a Unity question - I'll close this issue but if you think it should be reopened just let us know!
