### ISSUE TITLE
APP crashes when change page from unity widget

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#137]
There are several situations that may cause crash. **These following are tested in Android**
1. When open a page with unity_widget, with a little probabalbily to crash.
2. Open a page with unity_widget, and go to other pages,  then go back. This will definitely cause crash.
3. Open a page with unity_widget, and close it. Then open again or open another page with unity_widget.

I found #107 #80 #105 #46 . 
80 and  105 refer to 46, but the solution has a side effect on it. And 107 said this issue had been solved by newest repo. However, after  downloading the newest repo, installing Unity2019.3.5, and replacing the newest [scripts folder](https://github.com/snowballdigital/flutter-unity-view-widget/tree/master/scripts/unity_2019_3_5_later),  the issue remains.
Could you give me some sugesstions? Any help will be appreciated!

**Comment by jbrantl8** [comment]
I am having the same problem. Specifically when using Navigator.of(context).pop(); after pushing to the Unity page.

**Comment by Jatin-Pawar** [comment]
@jbrantl8 I am also facing the same issue...Did you manage to solve it....if yes, How?

**Comment by TinyGiantDigital** [comment]
> @jbrantl8 I am also facing the same issue...Did you manage to solve it....if yes, How?

I forked from https://github.com/mpfaff/flutter-unity-view-widget, there is a fix on there.

I have since added the flutter 1.17 fixes to my fork too if they are of use: 

https://github.com/TinyGiantDigital/flutter-unity-view-widget

**Comment by jbrantl8** [comment]
Thanks @TinyGiantDigital . Do you have any insight on what the fix actually was?

**Comment by jbrantl8** [comment]
The repo @ https://github.com/mpfaff/flutter-unity-view-widget worked like a charm by the way. Just had to add it as a plugin rather than getting directly from pub, as the latest repo isn't available on pub. Thanks

**Comment by mrctrl69** [comment]
Im facing this issue right now,

@jbrantl8 did you mean by cloning [this](https://github.com/mpfaff/flutter-unity-view-widget) repo and using /path on the dependencies rather than calling from the git?

**Comment by jbrantl8** [comment]
Looks like you got it figured out [here](https://github.com/snowballdigital/flutter-unity-view-widget/issues/46#issuecomment-634190567), @mrctrl69 . It's more of a workaround than a fix, as we aren't able to actually unload the unity instance, but it works for now.

**Comment by mrctrl69** [comment]
Yeah, I forgot to mention that thread here as the solution, thanks mate

**Comment by juicycleff** [comment]
Fixed in v2

**Comment by AkhilRaja** [comment]
I still am facing the same issue, what is the fix please, i am very close to production and this suddenly comes up blocking everything. @juicycleff @slimmziy @OGmetamonkey  ? Thanks in advance

**Comment by MightyMike-98** [comment]
@AkhilRaja Did you solve your problem? I am very close to production too, and I have to solve the. Which Version do you use
