### ISSUE TITLE
AndroidJavaClass not working for UnityMessageManager.cs

### ISSUE THREAD

**Issue by OGmetamonkey** [juicycleff/flutter-unity-view-widget#142]
According to documentation, the following line is used to send a message from Unity to Flutter. (Assuming UnityMessageManager.cs, JsonDotNet and link.xml have been added to the Unity project.

`UnityMessageManager.Instance.SendMessageToFlutter("example string"); `

Which then initiates the following code from UnityMessageManager.cs:

`#if UNITY_ANDROID
        try
        {
            AndroidJavaClass jc = new AndroidJavaClass("com.rexraphael.flutterunitywidget.UnityUtils");
            jc.Call("onUnityMessage", message);
        }
        catch (Exception e)
        {
            print(e.Message);
        }`

The AndroidJavaClass class keeps failing to build which results in the exception print of the following error message:

> I/Unity   (10440): java.lang.NoSuchMethodError: no non-static method with name='onUnityMessage' signature='(Ljava/lang/String;)V' in class Ljava.lang.Object;

Any clue where the problem is?

**Comment by taras-mashlyanka** [comment]
Try to change js.Call(...) to js.CallStatic(...) in UnityMessageManager.cs

**Comment by jbrantl8** [comment]
That worked. Thank you! 

For future reference, any tips on why this case in particular was looking for a static call rather than instanced call? Or should it always be CallStatic?

**Comment by qiuguian** [comment]
change to CallStatic works fine in android debug，but when I build apk，issues still there

**Comment by OGmetamonkey** [comment]
I'm actually having the same issue @qiuguian . Any clues?

**Comment by OGmetamonkey** [comment]
Re-opened per @qiuguian clarification that the solution isn't working in production.

**Comment by qiuguian** [comment]
@OGmetamonkey

**Comment by qiuguian** [comment]
@OGmetamonkey

**Comment by qiuguian** [comment]
@OGmetamonkey   Add the following to android > unityLibrary > proguard-unity.txt                                                                       -keep class com.xraph.plugins.flutterunitywidget.UnityUtils { *; }.

**Comment by OGmetamonkey** [comment]
Now getting this: 


> > FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:lintVitalRelease'.
> > Could not resolve all artifacts for configuration ':flutter_unity_widget:profileRuntimeClasspath'.
>    > Could not resolve project :UnityExport.
>      Required by:
>          project :flutter_unity_widget
>       > Unable to find a matching variant of project :UnityExport:
>           - Variant 'debugApiElements' capability android:UnityExport:unspecified:
>               - Incompatible attributes:
>                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
>                   - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
>               - Other attributes:
>                   - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
>                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>           - Variant 'debugRuntimeElements' capability android:UnityExport:unspecified:
>               - Incompatible attribute:
>                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
>               - Other attributes:
>                   - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
>                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>                   - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
>           - Variant 'releaseApiElements' capability android:UnityExport:unspecified:
>               - Incompatible attributes:
>                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
>                   - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
>               - Other attributes:
>                   - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
>                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>           - Variant 'releaseRuntimeElements' capability android:UnityExport:unspecified:
>               - Incompatible attribute:
>                   - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
>               - Other attributes:
>                   - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
>                   - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>                   - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s

**Comment by bitk0der** [comment]
In Android release mode still not working: onUnitySceneLoaded, onUnityMessage.
