### ISSUE TITLE
Can't render anything on top of UnityWidget for iOS (in the example too)

### ISSUE THREAD

**Issue by ilyaviache** [juicycleff/flutter-unity-view-widget#145]
To reproduce this issue you can use example from this repo or this one https://github.com/juicycleff/flutter-unity-arkit-demo and the latest version of iOS

For example in this repo I CAN interact with the slider but I can't see it

iOS:
![image](https://user-images.githubusercontent.com/5510585/82229488-2d437980-9933-11ea-9cae-b833ee46622a.png)

Android:
![image](https://user-images.githubusercontent.com/5510585/82229470-2583d500-9933-11ea-802a-6426e32a73b2.png)

Here is an example from https://github.com/juicycleff/flutter-unity-arkit-demo repo for iOS that uses the same widget:
![image](https://user-images.githubusercontent.com/5510585/82229588-56fca080-9933-11ea-867d-633bf1d21067.png)

Any thoughts?

**Comment by mtwillet** [comment]
I am experiencing the same issue. I have months of development on my app where this was working before. This is a Major Issue! Please help!!

**Comment by mtwillet** [comment]
Solved!...ish. After trying to figure out what they heck I had changed to make my Flutter UI elements disappear, I realized that I have updated Flutter without thinking about it. This looks to be and issue using Flutter version 1.17.1. After downgrading back to 1.16.3 everything worked again!

**Comment by cobainmo** [comment]
Downgrading worked for me too.Not too happy about this. I am at the beginning of my  project and i would feel more comfortable to work with latest stable version :(

**Comment by ilyaviache** [comment]
@cobainmo @mtwillet you can use version 1.17.1 + this fix of the lib https://github.com/snowballdigital/flutter-unity-view-widget/issues/138. Works well in my case but I had to fork the lib and make described in the issue changes

**Comment by cobainmo** [comment]
@ilyaviache That's great. Will try that. Thank you.
