### ISSUE TITLE
Quit Unity App in flutter

### ISSUE THREAD

**Issue by Karan2896** [juicycleff/flutter-unity-view-widget#152]
Hi, I am running a unity game from flutter app. It is working fine. But when I try to quit from game nothing happens. I am using application.quit() inside unity.

**Comment by TarekMedhat** [comment]
How about quitting the game by navigating back using flutter Navigator.pop() instead? but check this first https://github.com/snowballdigital/flutter-unity-view-widget/issues/46#issuecomment-640148254

**Comment by Karan2896** [comment]
@TarekMedhat No I want to quit only Unity part. The Back button just closes the whole app. I want to run unity app from flutter...Press back button and get back again to my flutter app

**Comment by juicycleff** [comment]
Fixed in  v2
