### ISSUE TITLE
Unable to run ios build.

### ISSUE THREAD

**Issue by maxbhoria** [juicycleff/flutter-unity-view-widget#153]
I am getting this and tried many way out Please help

/Users/macbook/Documents/FlutterSetup/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.6+8/ios/Classes/FlutterUnityWidgetPlugin.m:100:29: No visible @interface for 'UnityAppController' declares the selector 'setUnityMessageHandler:'

**Comment by TarekMedhat** [comment]
Duplicated, use the XcodePostBuild.cs referred by SachinGanesh https://github.com/snowballdigital/flutter-unity-view-widget/issues/82#issuecomment-565432788

**Comment by maxbhoria** [comment]
> Duplicated, use the XcodePostBuild.cs referred by SachinGanesh [#82 (comment)](https://github.com/snowballdigital/flutter-unity-view-widget/issues/82#issuecomment-565432788)

i checked that solution but that solution is for AR unity file. Can you explain little more?
