### ISSUE TITLE
Is it possible to have this as a separate screen and pass paths to 3d models to it?

### ISSUE THREAD

**Issue by FiddlePlus** [juicycleff/flutter-unity-view-widget#155]
Hey! Awesome tool, I think this has huge potential.

I wonder if it's possible to pass a string (with path to 3d model) to a screen with this UNITY widget? I have a lots of models I want to display and I want to find the best way to do it. is it even possible? 

Would appreciate any advice or help

**Comment by juicycleff** [comment]
@FiddlePlus thanks, I believe you can
