### ISSUE TITLE
Android Build Fails

### ISSUE THREAD

**Issue by shubhamguptak** [juicycleff/flutter-unity-view-widget#162]
Launching lib\main.dart on POCO F1 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':UnityExport:javaPreCompileDebug'.
> Could not resolve all files for configuration ':UnityExport:debugCompileClasspath'.
   > Failed to transform artifact 'unity-classes.jar (project :unity-classes)' to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\unity-classes\unity-classes.jar.
         > Failed to transform 'E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\unity-classes\unity-classes.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\unity-classes\unity-classes.jar, to=E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\build\unity-classes\.transforms\3de176c389a5629fba1103d88fcf0d0f\jetified-unity-classes.jar)'. (Run with --stacktrace for more details.)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by phamtuongvan** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find :UnityAds:.
     Required by:
         project :app > project :flutter_unity_widget > project :UnityExport
   > Could not find :UnityAdsAndroidPlugin:.
     Required by:
         project :app > project :flutter_unity_widget > project :UnityExport

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by LaloBerro** [comment]
any solution?

**Comment by LaloBerro** [comment]
> Launching lib\main.dart on POCO F1 in debug mode...
> Running Gradle task 'assembleDebug'...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':UnityExport:javaPreCompileDebug'.
> 
> > Could not resolve all files for configuration ':UnityExport:debugCompileClasspath'.
> > Failed to transform artifact 'unity-classes.jar (project :unity-classes)' to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
> > > Execution failed for JetifyTransform: E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\unity-classes\unity-classes.jar.
> > > Failed to transform 'E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\unity-classes\unity-classes.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\unity-classes\unity-classes.jar, to=E:\Nexgo\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\build\unity-classes.transforms\3de176c389a5629fba1103d88fcf0d0f\jetified-unity-classes.jar)'. (Run with --stacktrace for more details.)
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> Exception: Gradle task assembleDebug failed with exit code 1

HI! Try to move the unity-classes.jar (UnityExport/lib) to folder unity-classes

**Comment by juicycleff** [comment]
Use the new improve build script in v2
