### ISSUE TITLE
Unity TextField keyboard not showing

### ISSUE THREAD

**Issue by WILLIAM-LOW** [juicycleff/flutter-unity-view-widget#164]
When select input field in unity the keyboard does not show up. Any solution to this issue?

**Comment by LucasTejero** [comment]
Did you see other flutter widget on top of the unity player?

**Comment by MuazamAli69** [comment]
Can you please help me for running this project successfully or share running sample with me. I am really thankful for this favour.

**Comment by jamesncl** [comment]
As far as I know, using a Unity TextField is not supported by this package.

My guess is that Flutter has control of the keyboard and input focus, and it doesn't know that a Unity TextField has been selected. You would have to move the UI with your text fields to the Flutter side.

@juicycleff is this correct? If so we could add this limitation to the documentation and close this issue

**Comment by dawiddszewczyk** [comment]
@jamesncl  Yeah you have 100% right there. 
If you have still problem there please reopen issue or create new.
