### ISSUE TITLE
I can't put a Flutter widget on top of a Unity widget.

### ISSUE THREAD

**Issue by sinano1107** [juicycleff/flutter-unity-view-widget#166]
I'm using UnityWidget to launch an AR and I want to put a UI on top of it.
However, as shown in the example, I used stack and positioned, but it didn't work as well as I would have liked.
Do you have a solution to this problem?

![IMG_0532](https://user-images.githubusercontent.com/45984123/85501906-41108880-b621-11ea-94e3-d667c21949aa.png)

**Comment by sinano1107** [comment]
My code.
But it's the same as the example.

```import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static final GlobalKey<ScaffoldState> _scaffoldKey =
  GlobalKey<ScaffoldState>();
  UnityWidgetController _unityWidgetController;
  double _sliderValue = 0.0;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        key: _scaffoldKey,
        appBar: AppBar(
          title: const Text('Unity Flutter Demo'),
        ),
        body: Card(
          margin: const EdgeInsets.all(8),
          clipBehavior: Clip.antiAlias,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: Stack(
            children: <Widget>[
              UnityWidget(
                onUnityViewCreated: onUnityCreated,
                isARScene: false,
                onUnityMessage: onUnityMessage,
              ),
              Positioned(
                bottom: 20,
                left: 20,
                right: 20,
                child: Card(
                  elevation: 10,
                  child: Column(
                    children: <Widget>[
                      Padding(
                        padding: const EdgeInsets.only(top: 20),
                        child: Text("Rotation speed:"),
                      ),
                      Slider(
                        onChanged: (value) {
                          setState(() {
                            _sliderValue = value;
                          });
                          setRotationSpeed(value.toString());
                        },
                        value: _sliderValue,
                        min: 0,
                        max: 20,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // Communcation from Flutter to Unity
  void setRotationSpeed(String speed) {
    _unityWidgetController.postMessage(
      'Cube',
      'SetRotationSpeed',
      speed,
    );
  }

  // Communication from Unity to Flutter
  void onUnityMessage(controller, message) {
    print('Received message from unity: ${message.toString()}');
  }

  // Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) {
    this._unityWidgetController = controller;
  }
}```

**Comment by LucasTejero** [comment]
I had the same error see this answer it work for me 
https://github.com/snowballdigital/flutter-unity-view-widget/issues/132#issuecomment-618892588

**Comment by dangkhoa0303** [comment]
@sinano1107 I think it's not the problem of the library itself. In iOS, the UnityWidget is in fact the **UIKitView** which is an official component of Flutter. According to this [post](https://www.gitmemory.com/issue/flutter/flutter/59751/646027336), it seems that since Flutter version 1.17.1, the **UIKitView** is always on top of other widgets in the **Stack** component.

**Comment by sinano1107** [comment]
> I had the same error see this answer it work for me
> [#132 (comment)](https://github.com/snowballdigital/flutter-unity-view-widget/issues/132#issuecomment-618892588)

Thank you, but doing so does not solve the problem I complain about in this issue, that the stack doesn't work properly.
The proof of this is that I also speak out on that issue.

**Comment by n0m4dz** [comment]
@sinano1107 did you solve problem? I have same issue

**Comment by sinano1107** [comment]
> @sinano1107 did you solve problem? I have same issue

https://github.com/flutter/flutter/issues/59751#issuecomment-661467571
I haven't tried it, but this comment suggests that downgrading to 1.16.3 will get around it.
Let me know if you've solved the problem.

**Comment by giovannowarli** [comment]
Experiencing the same problem. Anyone solved this yet? Right now, the solution that I have been using is downgrading to Flutter v1.12.13+hotfix.9

**Comment by behnamsattar** [comment]
This is not an issue for me on the latest version of the plugin. Please double-check this, and we can close this issue if it's resolved.

**Comment by timbotimbo** [comment]
Closing this issue as outdated, this is from the flutter 1.x era while were now at 3.3.x and higher.
