### ISSUE TITLE
Is AR stuff required or not?

### ISSUE THREAD

**Issue by NorseGaud** [juicycleff/flutter-unity-view-widget#168]
Hello, some of the folks trying this are following the video guide and noticing after running inside of the virtual android device the following error:

"UnsatisfiedLinkError: dlopen failed: library "libmain.so" not found"

From what I'm reading, AR stuff is required. Is that true? What if we don't want it? What options are there?

**Comment by juicycleff** [comment]
@NorseGaud AR is optional
