### ISSUE TITLE
Duplicated touch count

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#170]
When I hit the cube in the demo project, Flutter receievd "Received message from unity: The cube feels touched" twice. 
When I dive into Unity , I found that the number of Input.touchCount in Unity was 2. And I also found that when I touch the cube for the first time, this message was recieved only once(But the input.touchCount still to be 2)
When I build the original Unity project in Android Phone, it was normal. But when embeded it into flutter, the input.touchCount became 2.

**Comment by juicycleff** [comment]
@guoguoguilai fixed this in v2 :)

**Comment by novavision** [comment]
Still exist in 4.1.0 Unity 2019.4
[issue](#421)
