### ISSUE TITLE
UnityWidget always highest context IOS

### ISSUE THREAD

**Issue by phamtuongvan** [juicycleff/flutter-unity-view-widget#174]
UnityWidget always highest context on ios. Then i can't show dialog and unitywidget in one page. Need go other page to show alert or any thing.

**Comment by jamontes79** [comment]
Hello, I'm having the same problem. Any solution?

Thanks
Regards

**Comment by MuazamAli69** [comment]
Can you please help me for running this project successfully or share running sample with me. I am really thankful for this favour.

**Comment by juicycleff** [comment]
Fixed in v2
