### ISSUE TITLE
Unity Widget doesn't play video

### ISSUE THREAD

**Issue by vikramkapoor** [juicycleff/flutter-unity-view-widget#186]
I added a video player which plays fine in standalone Unity android APK but it doesn't play when packaged as a flutter widget. I am using Unity 19.3.

**Comment by juicycleff** [comment]
@vikramkapoor make sure you import your video player native libraries from the exported folder

**Comment by vikramkapoor** [comment]
@juicycleff All I did was to copy unity-classes.jar from UnityExport folder to unity-classes folder. How do I export the video player native libraries?

**Comment by juicycleff** [comment]
@vikramkapoor you should check in the exported folder `UnityExport` for android, look in the libs or jni folder you should fine find other .jar or .so files. You have to properly import those for your project.

**Comment by vikramkapoor** [comment]
@juicycleff Thanks. In UnityExport there is no other jar file but there is a  jniLibs/arm64-v8a with following files:
gamesdk_classes_dex.o
libil2cpp.so
libmain.so
libunity.so

I will try to import these.

**Comment by vikramkapoor** [comment]
I copied the jniLibs directory from UnityExport to android/app/src/main/jniLibs folder in the flutter application. All the *.so files are included in the APK but the unity video is still missing. I stacked flutter video play on top on Unity Widget and that works but I wanted the video to play in Unity as I have some text superimposed over it in Unity. Wondering if there are any instructions to clarify the steps needed.

**Comment by juicycleff** [comment]
Is this video on network or file?

**Comment by vikramkapoor** [comment]
It's a file.
    On Friday, August 14, 2020, 01:34:49 AM PDT, Rex Raphael <notifications@github.com> wrote:  
 
 


Is this video on network or file?

**Comment by juicycleff** [comment]
@vikramkapoor this is not a widget issue, please import your unity export native dependencies to your app

**Comment by Bodekaer** [comment]
@vikramkapoor were you able to find a solution to this? Our team is experiencing the same challenge with playing video within Unity within Flutter :)
