### ISSUE TITLE
Crash when run in android

### ISSUE THREAD

**Issue by Oskang09** [juicycleff/flutter-unity-view-widget#191]
* Flutter - 1.20.1
* Library - flutter_unity_widget: ^0.1.6+8
* Unity - 2020.1.0f1
* Logs - https://pastebin.com/E2Eiij6N

When app startup just crashed and only tried on androird, not sure about ios. anything i need provide to easier track the error? Your help will be much appreciated

**Comment by khalithartmann** [comment]
+1 please help

**Comment by juicycleff** [comment]
@khalithartmann this has been fixed. Just have a little patience a release will be out soon with an updated readme

**Comment by IluhinDotPro** [comment]
1. Open ./android/UnityExport/build.gradle
2. Change 
`afterEvaluate {
        if (project(':unityLibrary').tasks.findByName('mergeDebugJniLibFolders'))
            project(':unityLibrary').mergeDebugJniLibFolders.dependsOn BuildIl2CppTask
        if (project(':unityLibrary').tasks.findByName('mergeReleaseJniLibFolders'))
            project(':unity-classes').mergeReleaseJniLibFolders.dependsOn BuildIl2CppTask
    }`
to
`afterEvaluate {
        if (project(':unity-classes').tasks.findByName('mergeDebugJniLibFolders'))
            project(':unity-classes').mergeDebugJniLibFolders.dependsOn BuildIl2CppTask
        if (project(':unity-classes').tasks.findByName('mergeReleaseJniLibFolders'))
            project(':unity-classes').mergeReleaseJniLibFolders.dependsOn BuildIl2CppTask
    }`
3. In Terminal> cd ./android/UnityExport/
4. run  **gradle BuildIl2CppTask**
5. wait...
6. Ctrl+F5 to run your app on device (VSCode)

**Comment by juicycleff** [comment]
@Oskang09 this is fixed in v2 :)
