### ISSUE TITLE
This package cannot be used with GoogleSignIn

### ISSUE THREAD

**Issue by sinano1107** [juicycleff/flutter-unity-view-widget#196]
If you try to do a UnityWidget that is included in this package, the GoogleSignIn().SignIn() dialog will not be displayed properly.
I'm moving to AppleSignIn for now because I don't have time, but I'm hoping to solve this problem in the future.
Thanks in advance.

**Comment by juicycleff** [comment]
perhaps they are using the same window height on iOS. Advice is modifying the GoogleSigning and bump up the window height position
