### ISSUE TITLE
your app work on physical device but don't work on emulators it crashes and i get this error:

### ISSUE THREAD

**Issue by gbo999** [juicycleff/flutter-unity-view-widget#197]
FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 

i tried to put a icon widget instead just to see that the code works and i get the icon, but when put back the unity widget i get this error

**Comment by juicycleff** [comment]
@gbo999 you should check your unity player configuration
