### ISSUE TITLE
How to exit from Unity View to Flutter

### ISSUE THREAD

**Issue by gogame2020** [juicycleff/flutter-unity-view-widget#198]
After the game finishes, In Unity, we're trying to exit the game and go back to flutter instance. The message from unity is reaching to flutter but the game is not getting quit. And we're not able to reach back to flutter instance. Any kind of help will be very good hope for us.

**Comment by juicycleff** [comment]
@gogame2020 some this has been implemented in the unreleased version of the library as it exposes alot of the unity API directly. So if you are patient for a few days. It will be published. The docs needs to be updated before publishing

**Comment by juicycleff** [comment]
@gogame2020 please check out the new `2.0.0` version
