### ISSUE TITLE
Screenshot of UnityWidget is blank.

### ISSUE THREAD

**Issue by jaboyc** [juicycleff/flutter-unity-view-widget#200]
Hello, I am using a UnityWidget with my iOS device. I need to take a screenshot of the UnityWidget when a button is pressed. I am using the screenshot plugin to take the screenshot (https://pub.dev/packages/screenshot). It works perfectly with other widgets, but produces a blank white image when taking a screenshot of the UnityWidget. Here's what my code looks like:

```
...
Screenshot(
    controller: _screenshotController,
    child: UnityWidget(
        onUnityViewCreated: _onUnityCreated,
        isARScene: true,
        onUnityMessage: _onUnityMessage,
    )
),
...

Future<void> _takeScreenshot() async {
    File screenshotFile = await _screenshotController.capture();
    ...
}
```

When displaying the image the screenshot creates, it is a plain white image, whereas replacing `UnityWidget(...)` with another widget, like a colored Container, produces the desired screenshot. Therefore, I don't think it has something to do with the Screenshot widget itself.

I am showing an AR scene if that helps.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.16.3, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] Connected device
``` 

The reason I am on an unknown channel is that I had to go back to v1.16.3 in order to allow widgets to be overlaid on top of the UnityView, as mentioned here: https://github.com/snowballdigital/flutter-unity-view-widget/issues/145#issuecomment-633650063

**Comment by juicycleff** [comment]
@jaboyc never experienced this and have taken several screenshots really. Anyway I am working on a revamp of the plugin. I am quite done with both android and iOS and will publish it once its right to do so. This revamp will have to make me rewrite the docs as somethings has changed. Maybe it will fix your issue

**Comment by juicycleff** [comment]
@jaboyc released the revamped version :)

**Comment by Veerarma** [comment]
@jaboyc  Did you find any solution to the problem? I am also facing this issue.

**Comment by Veerarma** [comment]
Hey @jaboyc Unity saves the screen shot at default location [Application.persistentDataPath](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html). Where is this for flutter in unity application. I looked there , the screen shots were not present there. 
When I build the unit alone the screen shot were at the said location. Basically I need this to get image imported in flutter, besides this is there any way?
