### ISSUE TITLE
Cannot show ImagePicker after showing UnityWidget.

### ISSUE THREAD

**Issue by jaboyc** [juicycleff/flutter-unity-view-widget#201]
Hello, I am using UnityWidget with my iOS application. I have run into a problem where showing an image picker does not work after a UnityWidget has already been shown. I am a package for my image picker (https://pub.dev/packages/image_picker). Here's my code.

```
...
UnityWidget(
    onUnityViewCreated: _onUnityCreated,
    isARScene: true,
    onUnityMessage: _onUnityMessage,
),
...
Future<void> _pickImage() async {
    final pickedFile = await _imagePicker.getImage(source: ImageSource.gallery);
}
``` 

The IconButton that runs _pickImage is in another Scaffold. Essentially, if I go to page A -> page B -> page A, where page A has the IconButton to pick an image and page B is the UnityWidget, clicking the image picker button in page A afterwards will not result in anything and produces this log: `Warning: Attempt to present <UIImagePickerController: 0x118b8ea00> on <UnityDefaultViewController: 0x124e25bb0> whose view is not in the window hierarchy!`.

Given the fact that `_imagePicker.getImage(...)` works totally fine before running the Unity page, I do not think it has anything to do with the ImagePicker plugin.

I am showing an AR scene if that helps. 

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.16.3, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] Connected device
```

The reason I am on an unknown channel is that I had to go back to v1.16.3 in order to allow widgets to be overlaid on top of the UnityView, as mentioned here: #145 (comment)

**Comment by LucasTejero** [comment]
I have the same issue,its because unity use the view,but never release it.

**Comment by jaboyc** [comment]
Is there a way to release the Unity view?

**Comment by juicycleff** [comment]
@LucasTejero @jaboyc it's fixed now in v2
