### ISSUE TITLE
REPO MIGRATION

### ISSUE THREAD

**Issue by juicycleff** [juicycleff/flutter-unity-view-widget#202]
I have moved the repo back to my personal github. So it's easier to maintain as I am leaving my current company :)

**Comment by TarekMedhat** [comment]
Keep up the great work 👏 and good luck with your next step!

**Comment by juicycleff** [comment]
@TarekMedhat thanks you :)

**Comment by LucasTejero** [comment]
Hey its a really promising project but i think we have to make de documentation cleaner and more begginer friendly,i can help with that!
im thinking to create a video explaining how to properly implement it in Android and IOs with AR

**Comment by juicycleff** [comment]
@LucasTejero yes that's true. With the next release, you won't need a lot of those steps. In fact for Android, you won't need any step at all

**Comment by juicycleff** [comment]
2.0.0 with some sweet add-ons with improved stability

**Comment by LucasTejero** [comment]
> @LucasTejero yes that's true. With the next release, you won't need a lot of those steps. In fact for Android, you won't need any step at all

Thank you,i can help you if need it. And i can translate the documentation to spanish if you want.

**Comment by juicycleff** [comment]
@LucasTejero please do I am designing a new documentation website so it would come in handy :)

**Comment by Ahmadre** [comment]
If you need any help, just ping me :)
