### ISSUE TITLE
(Android) unity fails to send messages to flutter on release apk

### ISSUE THREAD

**Issue by vicmaurer** [juicycleff/flutter-unity-view-widget#203]
Hi there,
First of all thank you for working so vigorously on this project as it makes life much easier for many of us.
I have come across an issue on android after building an apk for my app. While in debug mode communication between flutter and unity is working both ways, for me, unity is failing to send messages to flutter on a release build.

I will take the cube example:
In the "rotate.cs" script i added `gameObject.transform.Rotate(new Vector3(20, 20, 20) * Time.deltaTime * 10);` just right after ` UnityMessageManager.Instance.SendMessageToFlutter("The cube feels touched.");`

Here is the debug version:
The cube receives messages from flutter and when touched rotates as expected (meaning that `SendMessageToFlutter()` was successfully called).
![SVID_20200904_200643_1](https://user-images.githubusercontent.com/31721157/92239118-0ebabb80-eeed-11ea-8a31-4668a1687de4.gif)

Here is the release version:
The cube receives messages from flutter but when touched does not rotate (meaning that `SendMessageToFlutter()` returned an error along the way so that `Rotate()` did not get called). 
![SVID_20200904_201105_1](https://user-images.githubusercontent.com/31721157/92239753-1c247580-eeee-11ea-90b5-b75c2f9a3a6a.gif)

This is happening with my main project as well which requires communication to go both ways. I am not sure whether I'm the only person having this issue.

Thanks.

**Comment by vicmaurer** [comment]
sorry I didnt look at the closed issues. answer was in [https://github.com/juicycleff/flutter-unity-view-widget/issues/172](url)

**Comment by juicycleff** [comment]
You can check the new example. It has a demo for that Uniy to Flutter

**Comment by kiesman99** [comment]
> sorry I didnt look at the closed issues. answer was in [https://github.com/juicycleff/flutter-unity-view-widget/issues/172](url)

Hey mate, you've got an error in your link.

Here's the correct one for anyone looking:

[https://github.com/juicycleff/flutter-unity-view-widget/issues/172](https://github.com/juicycleff/flutter-unity-view-widget/issues/172)
