### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by walidalbabi** [juicycleff/flutter-unity-view-widget#204]
DirectoryNotFoundException: Could not find a part of the path 'C:\Users\albab\Desktop\flutter_unity\example\unity\DemoApp\Builds\Unity Flutter Demo.apk\Unity Flutter Demo'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.Directory.InternalGetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.Directory.GetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <437ba245d8404784b9fbab9b439ac908>:0)
Build.Copy (System.String source, System.String destinationPath) (at Assets/Editor/Build.cs:104)
Build.DoBuildAndroid (System.String buildPath) (at Assets/Editor/Build.cs:55)
Build.DoBuildAndroidLegacy () (at Assets/Editor/Build.cs:31)

When i build to flutter i get this error, i tried to change unity , ndk, sdk, Restart , trying another versions still get same error

**Comment by juicycleff** [comment]
@walidalbabi please try version 2.0.0
