### ISSUE TITLE
ARCore Native Error

### ISSUE THREAD

**Issue by pagach** [juicycleff/flutter-unity-view-widget#205]
I have a setup where i pause and resume the AR unity scene multiple times in a widget.
After a few pauses and resumes the AR camera freezes and i get the error

android_camera.cc:758 [Camera=0; State=ERROR] Resetting camera from an ERROR state, best effort clean-up commencing.
I/native  (27884): cameras.cc:1309 Camera 0 changed state CLOSED->OPEN; Camera device opened successfully. i=5
I/native  (27884): cameras.cc:1309 Camera 0 changed state OPEN->ERROR; Failed to set repeating request. Code=-10000; Message=UNKNOWN: ACameraCaptureSession_setRepeatingRequest ACAMERA_ERROR_UNKNOWN [type.googleapis.com/util.ErrorSpacePayload='CameraStatusErrorSpaceClass::ACAMERA_ERROR_UNKNOWN'] i=6
I/native  (27884): logger.h:28 CameraMetrics: CloseCaptureSession: 0
E/native  (27884): cameras_async.cc:255 UNKNOWN: ACameraCaptureSession_setRepeatingRequest ACAMERA_ERROR_UNKNOWN

followed by constant errors

session_manager.cc:88 ArPresto::ArSession_update failed with status -2.
E/native  (27884): error_policy_util.cc:260 
E/native  (27884): ################ ARCore Native Error ##################
E/native  (27884): BUILD_CHANGELIST:327708039
E/native  (27884): BUILD_BASELINE_CHANGELIST:323488040
E/native  (27884): ################### Stack Trace Begin ################
E/native  (27884): ARCoreError: third_party/arcore/ar/infrastructure/cameras_external_state.cc:191	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/infrastructure/cameras_external_state.cc?g=0&l=191
E/native  (27884): ARCoreError: third_party/arcore/ar/core/session.cc:1483	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1483
E/native  (27884): ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:68	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=68
E/native  (27884): ################### Stack Trace End #################

Any idea how to fix this?

**Comment by juicycleff** [comment]
@pagach it's actually an issue with AR core. Seen it my self. I did some revamp to the plugin and even that did not solve the issue as it only gets solved on screen orientation change. There are some bugs with the Unity Player hoping the unity team will fix it soon

**Comment by pagach** [comment]
ok. thx for the reply
