### ISSUE TITLE
Not response when take or choose an image from ImagePicker

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#211]
Flutter-unity-view-widget is a great work!
I am using this plugin to build my own app. I tried both v1 and v2. I found that almost everytime when I return from ImagePicker, the Unity Scene gets stuck and  not reponse. But if I change the orientation  by spin around my phone, it just recovered.
PS: I am using ARScene
Thanks in advance!

**Comment by juicycleff** [comment]
@guoguoguilai this is a ARCore issue. You can manage this in your unity app.
