### ISSUE TITLE
Build issue on new update (UnityLibrary)

### ISSUE THREAD

**Issue by mrctrl69** [juicycleff/flutter-unity-view-widget#213]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :unityLibrary.
          - None of the consumable configurations have attributes.       

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

So i was following the new updates, and when i build, this message appears.
Anyone? how to

**Comment by AlbertoVosgerau** [comment]
Hi! I did run into this issue several times, actually it happens every time I generate a new export, fortunatelly it it seems to be pretty easy to solve.

I just go to unitylibrary/build.gradle and inside android{} I put this:

buildTypes {
      profile {}
}

Works like a charm, but it sure is something that would be nice to have fixed in the future too.

**Comment by mrctrl69** [comment]
I see, but in my case I didn't even get unity library folder exported.
May you tell me where the folder should be I I make one, and what it contains? Thanks

**Comment by Witchd0ct0r** [comment]
> 
> 
> Hi! I did run into this issue several times, actually it happens every time I generate a new export, fortunatelly it it seems to be pretty easy to solve.
> 
> I just go to unitylibrary/build.gradle and inside android{ ... } I put this:
> 
> buildTypes {
> profile {}
> }
> 
> Works like a charm, but it sure is something that would be nice to have fixed in the future too.

Works for me too! :) Also i have to mention that building an assetbundle is issue free (even without adding the buildtypes to the gradle).

**Comment by mrctrl69** [comment]
Aah, turns out that my Unity Project still using the exporter packaget from earlier version, that's why i didn't get those file
I updated everything and thing runs smooth 👍 
thanks @AlbertoVosgerau @Witchd0ct0r
