### ISSUE TITLE
Exception on message send from Unity to Android using Unity Package

### ISSUE THREAD

**Issue by E-Kaese** [juicycleff/flutter-unity-view-widget#216]
I'm getting the following error for a release build when sending a message from Unity to Android.
`java.lang.ClassNotFoundException: com.xraph.plugins.flutterunitywidget.UnityUtils`

I'm using ARFoundation for Image Tracking in the Unity project and it's simply a single scene with the AR Camera in it. The project runs smoothly with `flutter run` but a build will throw the exception with on message send.

**Comment by juicycleff** [comment]
@E-Kaese Have no idea why it is not properly referencing the Java static class. Might have something to do with your plugin version

**Comment by E-Kaese** [comment]
I'm on the latest version for both the Flutter plugin and the Unity Package which is in the scripts folder on git

**Comment by E-Kaese** [comment]
Any updates on this?

**Comment by novavision** [comment]
This issue still exist installing app bundles from GooglePlay internal testing OR unpacking release .aab file and installing directly to the device.
