### ISSUE TITLE
Recommended unity editor version

### ISSUE THREAD

**Issue by TarekMedhat** [juicycleff/flutter-unity-view-widget#217]
Is there a recommended unity editor version for the library?
Maybe the version which used to test the library? @juicycleff what version do you use?

Unity version may be playing a big role for issues that many face, if we unified a well-tested version with the library that is added to documentation might help alittle.

**Comment by juicycleff** [comment]
@TarekMedhat the minimum version is Unity 2019.3. The plugin should work with any future release without breaking. And yes that should be mentioned in the readme :)
