### ISSUE TITLE
Undefined symbols for architecture arm64:  "_onUnitySceneLoaded"

### ISSUE THREAD

**Issue by Kingtous** [juicycleff/flutter-unity-view-widget#221]
using Flutter 1.22 stable and flutter-unity-view-widget 2.0.0+2.

I've no idea about the solution for iOS build.

the error shows below:

```shell
 ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/kingtous/projects/cishi-app/ios/UnityLibrary/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
    Undefined symbols for architecture arm64:
      "_onUnitySceneLoaded", referenced from:
          _NativeAPI_onUnitySceneLoaded_m4741E4A6C2A3A84DC595DCA9E6715B0779372985 in Assembly-CSharp.o
         (maybe you meant: _NativeAPI_onUnitySceneLoaded_m4741E4A6C2A3A84DC595DCA9E6715B0779372985)
      "_onUnityMessage", referenced from:
          _NativeAPI_onUnityMessage_mD44345499E1125EA37D67E2892D48D89B448B012 in Assembly-CSharp.o
         (maybe you meant: _NativeAPI_onUnityMessage_mD44345499E1125EA37D67E2892D48D89B448B012)
    ld: symbol(s) not found for architecture arm64
```

Does this mean there's  a problem in my unityLibrary?

**Comment by Kingtous** [comment]
the full log shows below:

```shell
Running pod install...
Running Xcode build...
Xcode build done.                                           14.5s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-10-03 22:01:44.748 xcodebuild[5088:732449]  DTDeviceKit: deviceType from 2ea7bb242f78168621b05382a3cd2af4414df957 was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/kingtous/projects/cishi-app/ios/UnityLibrary/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
    Undefined symbols for architecture arm64:
      "_onUnitySceneLoaded", referenced from:
          _NativeAPI_onUnitySceneLoaded_m4741E4A6C2A3A84DC595DCA9E6715B0779372985 in Assembly-CSharp.o
         (maybe you meant: _NativeAPI_onUnitySceneLoaded_m4741E4A6C2A3A84DC595DCA9E6715B0779372985)
      "_onUnityMessage", referenced from:
          _NativeAPI_onUnityMessage_mD44345499E1125EA37D67E2892D48D89B448B012 in Assembly-CSharp.o
         (maybe you meant: _NativeAPI_onUnityMessage_mD44345499E1125EA37D67E2892D48D89B448B012)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by juicycleff** [comment]
@Kingtous please clean your build properly and remove the unityframework from runner and add it again. Should fix it

**Comment by Antriadus** [comment]
@juicycleff I've hot the same problem, and cleaning build and adding unityframework again did not repaired problem.

**Comment by Kingtous** [comment]
> @Kingtous please clean your build properly and remove the unityframework from runner and add it again. Should fix it

not working. I'll try changing api compatibility level mentioned by @Antriadus  then.

**Comment by Kingtous** [comment]
> @juicycleff I've hot the same problem, and cleaning build and adding unityframework again did not repaired problem. For me changing Api Compability Level (in Unity Player Settings) from .Net Standard 2.0 to .NET 4.x repaired iOS build.

I've changed to .NET 4.x but it's not working, neither

**Comment by Kingtous** [comment]
DemoAPP from this repository also has this issue now. It seems that there is a bug when upgrading to iOS 14 SDK.
I was able to build it when I dev for iOS 13+.

**Comment by Kingtous** [comment]
finally I delete `FlutterUnityIntegration` in my unity project and reimport `FlutterUnityPackage.unitypackage`, which solveed my iOS build.

**Comment by artificerchris** [comment]
Hey all, I'm having this issue too when running the build through my CI, manually editing the project at that point isn't really a viable solution. I tried toggling between different .net versions to no avail.

**Comment by Kingtous** [comment]
> Hey all, I'm having this issue too when running the build through my CI, manually editing the project at that point isn't really a viable solution. I tried toggling between different .net versions to no avail.
> 
> Edit: Just downloaded the example project and ran it too, it also fails with this same error.

try to what i have done.

**Comment by artificerchris** [comment]
> try to what i have done.
I have, none of those things work for me for iOS.

**Comment by juicycleff** [comment]
Will test and fix any issues in the example and also the unity package. But most times this is due to your ios project. Will update the project with a fix

**Comment by artificerchris** [comment]
I'm not sure if it's helpful, but the problem only started for me after the iOS 14 release. I have a machine that hasn't been upgraded yet an the same project builds on it fine, move the exact same files to the iOS 14 build tool machine and it fails.

**Comment by vertis** [comment]
When reimporting the FlutterUnityIntegration I noticed that the meta files for `NativeCallProxy.h` and `NativeCallProxy.mm`. This did fix the problem described above.

Specifically:
```
--- a/Assets/FlutterUnityIntegration/Plugins/iOS/NativeCallProxy.h.meta
+++ b/Assets/FlutterUnityIntegration/Plugins/iOS/NativeCallProxy.h.meta
@@ -6,22 +6,81 @@ PluginImporter:
   iconMap: {}
   executionOrder: {}
   defineConstraints: []
-  isPreloaded: 0
+  isPreloaded: 1
   isOverridable: 0
   isExplicitlyReferenced: 0
   validateReferences: 1
   platformData:
+  - first:
+      : Any
+    second:
+      enabled: 0
+      settings:
+        Exclude Android: 1
+        Exclude Editor: 1
+        Exclude Linux64: 1
+        Exclude OSXUniversal: 1
+        Exclude Win: 1
+        Exclude Win64: 1
+        Exclude iOS: 0
+        Exclude tvOS: 0
+  - first:
+      Android: Android
+    second:
+      enabled: 0
+      settings:
+        CPU: ARMv7
   - first:
       Any:
     second:
-      enabled: 1
+      enabled: 0
       settings: {}
   - first:
       Editor: Editor
     second:
       enabled: 0
       settings:
+        CPU: AnyCPU
         DefaultValueInitialized: true
+        OS: AnyOS
+  - first:
+      Standalone: Linux64
+    second:
+      enabled: 0
+      settings:
+        CPU: AnyCPU
+  - first:
+      Standalone: OSXUniversal
+    second:
+      enabled: 0
+      enabled: 0
+      settings:
+        CPU: x86_64
+  - first:
+      Standalone: Win
+    second:
+      enabled: 0
+      settings:
+        CPU: x86
+  - first:
+      Standalone: Win64
+    second:
+      enabled: 0
+      settings:
+        CPU: x86_64
+  - first:
+      iPhone: iOS
+    second:
+      enabled: 1
+      settings:
+        AddToEmbeddedBinaries: false
+        CPU: AnyCPU
+        CompileFlags:
+        FrameworkDependencies:
+  - first:
+      tvOS: tvOS
+    second:
+      enabled: 1
+      settings: {}
   userData:
   assetBundleName:
   assetBundleVariant:
```
(With the + being the reimported files)

I'm not entirely certain how these came to be changed (did I do it while trying to build directly for testing, I don't remember).

YMMV of course.

**Comment by juicycleff** [comment]
Just reimport for unity for iOS removed unity framework and attach it again, solves this problem. It happens when the exported unity project native integration has changed and your project still references old files

**Comment by sandrush73** [comment]
Hi I have tried all the steps mentioned above and also tried using unity package  FlutterUnityPackage-3.0.0.unitypackage but i still cant build
Undefined symbols for architecture arm64:
  "__NativeShare_Share", referenced from:
      _NativeShare__NativeShare_Share_mD7B457EC2F4BDC61F28DFF4BA10097FBB9575E50 in Assembly-CSharp-firstpass.o
     (maybe you meant: _NativeShare__NativeShare_Share_mD7B457EC2F4BDC61F28DFF4BA10097FBB9575E50)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by andyshephard** [comment]
I had some unfortunate issues getting it to work by reimporting the project. It seemed to be because of the Cocoapod dependency, so in order to solve this I had to do the following (it's a bit long-winded but it worked):
- Remove the Unity-iPhone.xcodeproj from my own project (Move to Trash).
- Remove any lingering framework references from my project.
- Comment out any flutter-unity-plugin code from my Xcode AND Flutter project.
- Comment out the flutter-unity-plugin line in pubspec.yml and run 'pub get'.
- Navigate to the 'ios' folder and run 'pod update' in order to ensure that the Cocoapod dependency was no longer present.

- Reintroduce the flutter-unity-plugin in Flutter pubspec.yml and run 'pub get'.
- Run 'pod install' in the 'ios' folder.
- Re-create the UnityLibrary folder by running 'Export iOS' in Unity.
- Add the Unity-iPhone.xcodeproj back to my project's xcworkspace.
- Import the UnityFramework again by using the instructions in this repo's README.md
- By this point you should be able to run the project in Xcode successfully.
- Uncomment out all of the code in Flutter & Xcode so that it's making use of the flutter plugin.
- Done.

**Comment by ernonemacher** [comment]
No solution works for me

**Comment by fch21** [comment]
This problem is caused by unity not using XCodePostBuild.cs, I could solve it by deleting this file and re-importing it into the unity project from the FlutterUnityIntegration-v4.1.0.unitypackage and then exporting the project to IOS again. If it doesn't work you can also try to delete the whole FlutterUnityIntegration folder and re-import the complete package.

**Comment by rzrobert** [comment]
> Just reimport for unity for iOS removed unity framework and attach it again, solves this problem. It happens when the exported unity project native integration has changed and your project still references old files

Delete the file and re export the unity iPhone project， works for me

**Comment by likwifi** [comment]
> Just reimport for unity for iOS removed unity framework and attach it again, solves this problem. It happens when the exported unity project native integration has changed and your project still references old files

@juicycleff  Do you even English?
Your library is a useless waste of time.
You're closing this issue with no clear solution.

**Comment by TonyHoyleRps** [comment]
2 years later and this bug is not fixed.. FFS.  The 'solution' of editing files manually kind of works when you're developing, but it's a complete no go when compiling using CI.   I've removed and readded both the FlutterUnityWidget and fuw projects (it's not clear which one is 'correct' but I've tried them all) loads of times.  That is not a solution.

**Comment by g0josh** [comment]
If anyone is looking for solution to this, I had to remove the compile flags 
 - around `ExportAddressables();` at `LearnItUnity/Assets/FlutterUnityIntegration/Editor/Build.cs:BuildIOS` 
 - `LearnItUnity/Assets/FlutterUnityIntegration/Editor/XCodePostBuild.cs`
