### ISSUE TITLE
error on using "export android" in unity 2020.2b5, wants to integrate arkit for some reason

### ISSUE THREAD

**Issue by subjectdenied** [juicycleff/flutter-unity-view-widget#222]
for some strange reason with unity 2020.2b5 when trying to use the android export menu entry, the build script seems to want to integrate arkit for some reasons, and errors with build only possible with arm64 architecture (and a note to change the settings). i don't know if this is caused by the new beta unity build having changed something in internal build processing (that might effect this plugin from now on), or it is some specific bug with this unity build. i just want to mention it here for future references, as it didnt happen with unity 2020.2b4

for people seeing this behaviour, this issue is solved by removing the arkit xr-plugin from packages-manager temporarely, and exporting to android using the flutter menu entry afterwards

**Comment by juicycleff** [comment]
@subjectdenied the project contains a demo with AR support, you just have to delete the demo project

**Comment by subjectdenied** [comment]
@juicycleff thanks for the hint ;-)
