### ISSUE TITLE
[Android] - build failed after export from unity (migration from 0.1.6+8 to 2.0.0+2)

### ISSUE THREAD

**Issue by DSkarzynski** [juicycleff/flutter-unity-view-widget#223]
I've upgraded my project from Flutter 1.12.13+hotfix.9 and flutter_unity_widget 0.1.6+8 to Flutter 1.22 and flutter_unity_widget 2.0.0+2 and I had to remove old config files. I've managed to correctly export and configure new version to iOS successfully, but I encountered an error in Android:

> Could not determine the dependencies of task ':unityLibrary:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':unityLibrary:debugCompileClasspath'.
   > Could not find :unity-classes:.
     Required by:
         project :unityLibrary
   > Could not find :ARPresto:.
     Required by:
         project :unityLibrary
   > Could not find :UnityARCore:.
     Required by:
         project :unityLibrary
   > Could not find :arcore_client:.
     Required by:
         project :unityLibrary
   > Could not find :unityandroidpermissions:.
     Required by:
         project :unityLibrary

I've removed old UnityExport and followed "Android Platform Only (Manual Steps)" from readme

**Comment by juicycleff** [comment]
@DSkarzynski what version of Unity are you on?

**Comment by DSkarzynski** [comment]
I am on 2019.3.9f1

I fixed the issue in my project. The cause was that I left separate dirs (like there was for unity-classes in previous version of flutter_unity_widget) for ARPresto, UnityARCore, etc... and moved .aar's from unityLibrary/libs to them. Readme still prompts to doing it in AR Foundation section. Simply leaving everything as is after export from unity (plus minor changes in unityLibrary/build.gradle) and it works even for AR Foundation project. And it turns out you don't need to Add as a library unity-classes.jar 

PS: In app/build.gradle in dependencies { } the line "implementation project(':unityLibrary')" is appended so after couple of exports there are multiple "implementation project(':unityLibrary')" lines, but it manages to run
