### ISSUE TITLE
Duplicate interface definition for class 'AppDelegate'  in 2.0.0+2

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#224]
I am running flutter-unity-widget in ios13. When I upgrade from 2.0.0 to 2.0.0.0+2, an error came up with: Duplicate interface definition for class 'AppDelegate'  in 2.0.0+2. 
How can I solve this problem?

**Comment by juicycleff** [comment]
@guoguoguilai please properly clean your project and remove all frameworks and add it again
