### ISSUE TITLE
Exit unity and open unity again, fail to call setstate inside onUnityMessage

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#225]
Unhandled Exception: setState() called after dispose(): _CreateAnimationPageState#b5200(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
#2      _CreateAnimationPageState.onUnityMessage

**Comment by juicycleff** [comment]
@guoguoguilai I can't help you here, this clearly has nothing to do with the package and more of a flutter implementation issue

**Comment by guoguoguilai** [comment]
> @guoguoguilai I can't help you here, this clearly has nothing to do with the package and more of a flutter implementation issue

I have tested it on both Android and iOS. Android was OK, but iOS didn't work.
Could you please tell me what method I should call when I exit/re-enter Unity?

**Comment by guoguoguilai** [comment]
I think it is not a flutter implementation issue but a issue inside package . 'Cause Andoird version dose a great job.
