### ISSUE TITLE
Build error, shows gradle not found in path when using unity asset to export [Flutter\Export to Android]

### ISSUE THREAD

**Issue by SplunkyDev** [juicycleff/flutter-unity-view-widget#227]
![FlutterProjectStructure](https://user-images.githubusercontent.com/60402652/95844722-dc5f7200-0d66-11eb-90c5-76ab04af2d4b.jpg)
![UnityProjectStructure_00](https://user-images.githubusercontent.com/60402652/95844729-e08b8f80-0d66-11eb-8937-a042262b1770.jpg)
![UnityProjectStructure_01](https://user-images.githubusercontent.com/60402652/95844735-e1bcbc80-0d66-11eb-9291-038ce923ba74.jpg)

That is my folder structure when I try exporting the project I get cannot find Gradle file e:\Flutter\android\app\build.gradle
I have made more android Gradle build successfully but this isn't working. 

It would be nice to know what I am doing wrong. Thank you.

**Comment by jjaine** [comment]
The interim folder seemed to be the problem for me... So, inside the `unity` folder should be directly the `Assets`, `Packages` etc. folders.
