### ISSUE TITLE
Flutter build after unity game export, gettting dupicate class error.

### ISSUE THREAD

**Issue by ramnim** [juicycleff/flutter-unity-view-widget#228]
java.lang.RuntimeException: Duplicate class bitter.jnibridge.JNIBridge found in modules unity-classes.jar (:unity-classes:) and unity-classes.jar (unity-classes.jar)

  Duplicate class bitter.jnibridge.JNIBridge$a found in modules unity-classes.jar (:unity-classes:) and unity-classes.jar (unity-classes.jar)

Is that some thing to do with Flutter build settings? Appreciate any pointers on this issue.

**Comment by DevJeeth** [comment]
@ramnim  and I are working on it. I made an android Gradle build from unity 2019.4.7
[CubeHover.zip](https://github.com/juicycleff/flutter-unity-view-widget/files/5376197/CubeHover.zip)
I have added the zipped gradle project if required. I faced the same issue that SplunkyDev mentioned, The build shows cannot find gradle file, that is why we chose to do the flutter setup manually. 
I gave the exported android gradle project to @ramnim and he followed the manual process to try and achieve this. 

I hope this is enough information to help out.
