### ISSUE TITLE
[ONLY ON IOS] Unable to call setState in onUnityMessage when re-open a page that contains a UnityWidget

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#229]
**The platform really matters!  Android works well but iOS fails.**

I have submitted a simliar issue(#225 ) before, but it was closed unexpectly. So I have to create another issue.
Is there any solution to call setState in onUnityMessage when re-open unity? 

Assume that I have two pages A&B. And B contains a unity widget. The main issue is :
1. (both Android and iOS)Everything goes well when A—>B for the first time. And I can call any setState in Page B.
2. (Only in iOS)But if I pop from B to A, then go B again(which means A—>B—>A—>B)，I can't call any setState in onUnityMessage. What's more, "this.mounted " inside OnUnityMessage turned out to be false.

In short, whenever I enter a page that contains a unity widget for the second or third time, setState inside onUnityMessage will not work. And this situation Only appeares in iOS.

To prove that, I did some code in Demo Project. The following is what I did on simple_screen.dart:
1. Add a new bool isTouched=false
2. Make isTouched as the condition to control the title of AppBar.
```this.isTouched ? Text("Don't touch me!") : Text("Touch me please!"),```
3. Call setState when recieve message from flutter.
```debugPrint("Mounted state: ${this.mounted.toString()}"); setState(() { this.isTouched = !this.isTouched; });```

Everything works well for the first time. However, when I reopen the same page, the setState fails. And also, the this.mounted turns out to be false, which means that this widget is not mounted. The full code is: 
```
import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';
import 'package:flutter_unity_widget_example/utils/screen_utils.dart';


class SimpleScreen extends StatefulWidget {
  @override
  _SimpleScreenState createState() => _SimpleScreenState();
}

class _SimpleScreenState extends State<SimpleScreen> {
  static final GlobalKey<ScaffoldState> _scaffoldKey =
      GlobalKey<ScaffoldState>();
  UnityWidgetController _unityWidgetController;
  double _sliderValue = 0.0;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final ScreenArguments arguments =
        ModalRoute.of(context).settings.arguments as ScreenArguments;

    return Scaffold(
      appBar: AppBar(
        title:
            this.isTouched ? Text("Don't touch me!") : Text("Touch me please!"), //-----------------------add code here----------------
      ),
      body: Card(
          margin: const EdgeInsets.all(8),
          clipBehavior: Clip.antiAlias,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: Stack(
            children: [
              UnityWidget(
                onUnityViewCreated: onUnityCreated,
                isARScene: arguments.enableAR,
                onUnityMessage: onUnityMessage,
              ),
              Positioned(
                bottom: 20,
                left: 20,
                right: 20,
                child: Card(
                  elevation: 10,
                  child: Column(
                    children: <Widget>[
                      Padding(
                        padding: const EdgeInsets.only(top: 20),
                        child: Text("Rotation speed:"),
                      ),
                      Slider(
                        onChanged: (value) {
                          setState(() {
                            _sliderValue = value;
                          });
                          setRotationSpeed(value.toString());
                        },
                        value: _sliderValue,
                        min: 0,
                        max: 20,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          )),
    );
  }

  void setRotationSpeed(String speed) {
    _unityWidgetController.postMessage(
      'Cube',
      'SetRotationSpeed',
      speed,
    );
  }

  bool isTouched = false; //-----------------------add code here----------------

  void onUnityMessage(controller, message) {
    debugPrint("Mounted state: ${this.mounted.toString()}");

    setState(() {  //-----------------------add code here----------------
      this.isTouched = !this.isTouched;
    });
    debugPrint(
        'Received message from unityffffff: ${message.toString()}  ${this.isTouched.toString()}');
  }


  // Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) async {
    this._unityWidgetController = controller;
  }
}
```

Can anyone help me to solve this problem? I really really need your help! 
Any help will be appreciated.

**Comment by ruslanou** [comment]
I have similar issue. But i resolve it by not changing the screen. I navigate through screen by using showmodalbottomsheet. So this.mounted still true.

**Comment by guoguoguilai** [comment]
> I have similar issue. But i resolve it by not changing the screen. I navigate through screen by using showmodalbottomsheet. So this.mounted still true.

Good idea. But I have about 6 screens containing UnityWdiget, so showmodalbottomsheet mignt not work for me. I am still loing for a solution.

**Comment by guoguoguilai** [comment]
I found a Temporary solution, 
Open unity_view.dart. Just replace "_controller = UnityWidgetController.init(id, this);" with "_controller = UnityWidgetController.init(0, this);" in _onPlatformViewCreated.
Or you can add a static variable：
···
  void _onPlatformViewCreated(int id) {
    if(defaultTargetPlatform == TargetPlatform.iOS){
      if(UnityWidget.iosId==null){ //iosId is a static variable defined in UnityWidget.
        UnityWidget.iosId = id;
      }
      else{
        id = UnityWidget.iosId;
      }
    }
    
    _controller = UnityWidgetController.init(id, this);
    if (widget.onUnityViewCreated != null) {
      widget.onUnityViewCreated(_controller);
    }
    print('*********************************************');
    print('** flutter unity controller setup complete **');
    print('*********************************************');
  }
···

**Comment by khalithartmann** [comment]
any updates on that. Im facing the same issue

**Comment by guoguoguilai** [comment]
> any updates on that. Im facing the same issue

See my temporary solution temporary solution [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/229#issuecomment-717353464).
