### ISSUE TITLE
When re-open app  untiy run error.

### ISSUE THREAD

**Issue by qiuguian** [juicycleff/flutter-unity-view-widget#230]
First time install app and run into unity page, it gos well

**Comment by qiuguian** [comment]
But when I close app and re-open again, unity has error: 
2020-10-20 12:20:19.035 928-1087/? E/ScreemCommon: jank frame opt scene object is null
2020-10-20 12:20:19.035 928-1087/? E/ScreemCommon: failed to recording jank bigdata of different frame rates
just happen in my android device,  other person's run well.

**Comment by qiuguian** [comment]
video file: https://github.com/qiuguian/plist/blob/master/1603168273184902.mp4?raw=true

**Comment by juicycleff** [comment]
@qiuguian please just call unictycontroller.quit in the flutter lifecycle manually. I will release a fix for this and also create a video tutorial for both dev and production release.

**Comment by juicycleff** [comment]
@qiuguian the reason for this is that Unity player is still hanging on to memory and so quitting and starting again should fix this issue.

**Comment by qiuguian** [comment]
@juicycleff Thank you for response,  but I had tried two days, quitting and starting again can't not fix this issue. Can you fix in the plugin?

**Comment by qiuguian** [comment]
Why Unity player is still hanging on to memory when I close the app and start again?

**Comment by qiuguian** [comment]
Please help me to fix it!  My project urgent, Thank you very much!

**Comment by ilkercankaya** [comment]
I would kindly appreciate a fix for this issue too as I am planning to release an app with this library in it, thank you for the efford 👀

**Comment by qiuguian** [comment]
@ilkercankaya @juicycleff  I fix it by use PlatformViewLink Widget instead of AndroidView Widget:
PlatformViewLink(
            surfaceFactory:
                (BuildContext context, PlatformViewController controller) {
              return AndroidViewSurface(
                controller: controller,
                gestureRecognizers: const <
                    Factory<OneSequenceGestureRecognizer>>{},
                hitTestBehavior: PlatformViewHitTestBehavior.opaque,
              );
            },
            viewType: _viewType,
            onCreatePlatformView: (PlatformViewCreationParams params) {
              return PlatformViewsService.initSurfaceAndroidView(
                id: params.id,
                viewType: _viewType,
                layoutDirection: TextDirection.rtl,
                creationParams: creationParams,
                creationParamsCodec: const StandardMessageCodec(),
              )
                ..addOnPlatformViewCreatedListener(params.onPlatformViewCreated)
                ..addOnPlatformViewCreatedListener(_onPlatformViewCreated)
                ..create();
            });

**Comment by juicycleff** [comment]
@qiuguian I hadn't had enough time to work on it and I am working on it now. Nice to know you've fixed it with that
