### ISSUE TITLE
Flutter ANR / Freeze - Is there a way to load new scenes in the background?

### ISSUE THREAD

**Issue by ilkercankaya** [juicycleff/flutter-unity-view-widget#235]
In my flutter application I am loading new scenes through flutter calls such as:
```
unityWidgetController.postMessage(
            GeneralStringUtil.sceneLoaderUnityObjectName,
            GeneralStringUtil.sceneLoaderLoadMethodName,
            GeneralStringUtil.sceneLoaderPhones,
          );
```

On Unity, I simply load the scene:
```
public void LoadScene(string type)
    {
        if (type == "phones")
        {
            SceneManager.LoadScene("Scene Phones");
        }
        else
        {
            SceneManager.LoadScene("Scene Tablets");
        }
    }
```

I am launching Unity in its own activity on Android.

Everythings works as expected new scene is loaded but there is one big problem. While the new scene is loading my flutter application is frozen. In my case it was for at least 2 to 3 seconds. I wanted to display a circular spinning bar within the loading time but flutter UI becomes frozen meaning even if I put a circular spinning bar, the spinning bar does not spin, it simply displays a frame meaning Flutter app is put into ANR (Application not responding) state. I also tried to navigate in my flutter side while the scene is loading but my touches are ignored until the new scene is loaded.

Are there any ways to load a new scene in the background so I would not cause ANR / freeze on Flutter side?

Tested On: Flutter Release Mode
Flutter Unity View Widget Version: ^2.0.0+2
Platform: Android
Flutter Version: 1.22.2
Unity Version: 2019.4.71f
Tested Phone: Samsung Note 10

**Comment by juicycleff** [comment]
@ilkercankaya there are plenty of ways to do this. There is an onSceneChanged event callback you can use to solve this issue, or just debounce, animate, or delay rendering
