### ISSUE TITLE
fullscreen argument is not working on Android

### ISSUE THREAD

**Issue by TaranenkoDenis** [juicycleff/flutter-unity-view-widget#238]
Hello. I faced the problem that when I start a page with the UnityWidget on Android, all system buttons are hidden and then do not come back, even if I exit the screen with the UnityWidget.

Can you help me with it?

version of UnityWidget - `flutter_unity_widget: ^2.0.0+2`

What the UnityWidget looks like on our screen:
```
UnityWidget(
        onUnityViewCreated: onUnityCreated,
        isARScene: true,
        onUnityMessage: onUnityMessage,
        fullscreen: false,
);
```

**Comment by Darkmax** [comment]
for me it work, just check that on unity project settings is not fullscreen enable

**Comment by juicycleff** [comment]
@Darkmax thats correct

**Comment by TaranenkoDenis** [comment]
Thanks. The problem was with Unity project settings.

**Comment by lachezartodorov** [comment]
@Darkmax @juicycleff Can you specify where I should disable this option, because I disabled everything related to fullscreen and it's still fullscreen 🤷‍♂️
