### ISSUE TITLE
Syntax errors in the source 

### ISSUE THREAD

**Issue by amodth** [juicycleff/flutter-unity-view-widget#239]
I'm getting syntax errors in following files
lib/main.dartlib/main.dart
lib/menu_screen.dart
lib/screens/api_screen.dart
lib/screens/simple_screen.dart

An example error in lib/menu_screen.dart line no 5; 

`"MenuScreen({Key key}) : super(key: key);"`
The parameter 'key' can't have a value of 'null' because of its type, and no non-null default value is provided.
Try adding either a default value or the 'required' modifier.

Same type of errors are in all the above mentioned files. 
My Flutter SDK is: flutter_macos_1.22.3-stable

**Comment by juicycleff** [comment]
@amodth can't reproduce this error in the examples
