### ISSUE TITLE
Can this project be used in a native Android project?

### ISSUE THREAD

**Issue by iopass4** [juicycleff/flutter-unity-view-widget#247]
Can this project be used in a native Android project? I have an app and I want to use unity to implement some game functions

thank you very much

**Comment by mathtasatlime** [comment]
That's exactly what this project is for.

**Comment by juicycleff** [comment]
@iopass4 this can be used with flutter applications and if you would want to use it in a pure native android app without flutter please just look at the android source. Thank you
