### ISSUE TITLE
App crashes on release 3.0.1

### ISSUE THREAD

**Issue by ljmatan** [juicycleff/flutter-unity-view-widget#254]
App crashes on release before the splash screen but it works normally in debug mode. No logs visible in terminal on crash. This is happening on 2 separate devices.

`import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  UnityWidgetController _unityWidgetController;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: UnityWidget(
          onUnityCreated: onUnityCreated,
          isARScene: true,
          onUnityMessage: onUnityMessage,
          onUnitySceneLoaded: onUnitySceneLoaded,
        ),
      ),
    );
  }

  // Communication from Unity to Flutter
  void onUnityMessage(message) {
    print('Received message from unity: ${message.toString()}');
  }

  // Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) {
    this._unityWidgetController = controller;
  }

  // Communication from Unity when new scene is loaded to Flutter
  void onUnitySceneLoaded(
    controller, {
    int buildIndex,
    bool isLoaded,
    bool isValid,
    String name,
  }) {
    print('Received scene loaded from unity: $name');
    print('Received scene loaded from unity buildIndex: $buildIndex');
  }
}
`

**Comment by ljmatan** [comment]
Doing another release build now and it works. I've added a few scenes but nothing else changed. Will keep the issue open.

**Comment by juicycleff** [comment]
@ljmatan sometimes it might be cached builds or files causing the problems. Please what device are you testing on?

**Comment by ljmatan** [comment]
It could be that as I most likely ran flutter clean, and as I've mentioned I did another export from unity editor. Device I've used is Galaxy A8 2018 and my customer used another device of which I don't know the brand and the model. 

Running another release build now everything's working so I'll just assume it had something to do with cached files.
