### ISSUE TITLE
Flutter tab goes missing in Unity editor

### ISSUE THREAD

**Issue by ljmatan** [juicycleff/flutter-unity-view-widget#256]
Sometimes, for no apparent reason, Flutter tab goes missing from the Unity editor. I'm able to fix the issue by deleting FlutterUnityIntegration folder and reimporting the package, however, this happens quite often and I'm wondering whether it's related to my system and if not, is there any fix for this.

Using Linux Lite based on Ubuntu 20.04.1 with 2019.3.3f1 Unity version.

**Comment by juicycleff** [comment]
@ljmatan should be related to linux and unity editor. I suggest you ask for it in unity forums :)
