### ISSUE TITLE
Error building for iOS on version 2.0.0+2, duplicate interface definition for AppDelegate

### ISSUE THREAD

**Issue by lucasgodt** [juicycleff/flutter-unity-view-widget#258]
I´m getting this error when building for iOS on version 2.0.0+2: 

In file included from /Users/builder/clone/ios/Runner/main.m:4:
    /Users/builder/clone/ios/Pods/Headers/Public/flutter_unity_widget/UnityUtils.h:47:1: error: duplicate interface definition for class 'AppDelegate'
    @interface AppDelegate : UIResponder<UIApplicationDelegate, UnityFrameworkListener>
    ^
    In file included from /Users/builder/clone/ios/Runner/main.m:3:
    /Users/builder/clone/ios/Runner/AppDelegate.h:6:12: note: previous definition is here
    @interface AppDelegate : FlutterAppDelegate
               ^
    1 warning and 1 error generated.

Clean cache. 

Unity 2019.3.5
flutter channel stable
Xcode 12.2

Plz help

**Comment by dawiddszewczyk** [comment]
@lucasgodt Firstly be sure that you use updated version of Unity Flutter Package, and Unity Flutter Widget. 
If this problem still exist please reopen issue or create new.
