### ISSUE TITLE
error running project

### ISSUE THREAD

**Issue by rubenteste** [juicycleff/flutter-unity-view-widget#261]
just downloaded the project from github, try to run in android studio and give me this error:

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :unityLibrary.
     Required by:
         project :app
      > No matching configuration of project :unityLibrary was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.gradle.internal.dependency.AndroidTypeAttr' with value 'Aar' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 480ms
Exception: Gradle task assembleDebug failed with exit code 1
![Captura de ecrã de 2020-11-27 15-39-05](https://user-images.githubusercontent.com/75133022/100465138-b7308400-30c6-11eb-824d-fa0980fd517a.png)

**Comment by bedirhanwerk** [comment]
I think if i am right. It means that you still miss one step you still have to export the unity app in order to build the required unitLibrary. Hope this help!

**Comment by juicycleff** [comment]
@rubenteste please follow the setup guide for Android in the readme
