### ISSUE TITLE
flutter Web implementation

### ISSUE THREAD

**Issue by DavidGutierrez94** [juicycleff/flutter-unity-view-widget#262]
I don't  see if anyone has tried to implement this on the web using flutter, I'm working on a project that actually would need to run on the web. but I don't see any information about it.

**Comment by steveny909** [comment]
Very interested if anyone has anything to share with trying this package on web.  Flutter 2.0 opens even more possibilities

**Comment by blackvitriol** [comment]
Same here. Dart has support for WebGL and OpenGL ES. 
How can we embed a Unity game into Flutter ?

**Comment by Ahmadre** [comment]
A complete plugin is available here: https://pub.dev/packages/unity_widget

**Comment by jamesncl** [comment]
I believe web is now supported but isn't documented yet.

@juicycleff is that right? I was thinking of doing a PR to tidy up the readme.md file and add more info, but I've seen you mention elsewhere that you're working on a documentation website. How is that going and should I hang fire on working on the readme?

**Comment by Ahmadre** [comment]
Web fixes are here:

Follow and upvote these Fixes:
- https://github.com/juicycleff/flutter-unity-view-widget/pull/616
- https://github.com/juicycleff/flutter-unity-view-widget/pull/617
- https://github.com/juicycleff/flutter-unity-view-widget/pull/618

**Comment by chadlyalan** [comment]
I'm trying to set up a project to run on the web right now. I don't see anywhere that has steps on how to setup either unity or flutter for web deployment. Can you guys point me to some doc on setting it up from the ground up? 
Even if it's not a clean doc, I'm happy to document the steps (I'll be doing it either way for my own team) for you guys to use as well.
