### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by parasshakya** [juicycleff/flutter-unity-view-widget#264]
1. error: The method 'AndroidViewSurface' isn't defined for the type 'MethodChannelUnityViewFlutter'. (undefined_method at [flutter_unity_widget] lib\src\device_method.dart:129).
2. error: The method 'initSurfaceAndroidView' isn't defined for the type 'PlatformViewsService'. (undefined_method at [flutter_unity_widget] lib\src\device_method.dart:136).

1. Go to 'lib' then go to src
2. Click on 'device_method.dart'
3. Scroll down to 'line 129 and line 136'

Desktop:
 - OS: [Windows 10 Home]
 - Browser [ Chrome]
 
Smartphone:
 - Device: [Xiaomi Mi A3]
 - OS: [Android 10]
 - Browser [Chrome]

**Comment by juicycleff** [comment]
@parasshakya you are using an outdated flutter version. Please do upgrade it

**Comment by parasshakya** [comment]
![errorDevicemethod](https://user-images.githubusercontent.com/60213461/100597597-c06b5c00-3325-11eb-9394-bb4cebcdc92e.PNG)
I updated the flutter version. Still, there is problem.

**Comment by dawiddszewczyk** [comment]
@parasshakya  Also try to use the updated Flutter Version, Flutter unity widget version, and try to reimport to Unity project updated [Unity widget package ](https://github.com/juicycleff/flutter-unity-view-widget/tree/master/unitypackages)
If this error still be reopened issue or crate new with information which are in template :)
