### ISSUE TITLE
error exporting

### ISSUE THREAD

**Issue by maxTeste** [juicycleff/flutter-unity-view-widget#267]
can i run this project in unity 2019.4.15f1 ? 
when i try to export, in the menu flutter give me this error:

InvalidOperationException: The build target does not support build appending.
UnityEditor.BuildPipeline.BuildPlayer (System.String[] scenes, System.String locationPathName, System.String assetBundleManifestPath, UnityEditor.BuildTargetGroup buildTargetGroup, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options) (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:277)
UnityEditor.BuildPipeline.BuildPlayer (UnityEditor.BuildPlayerOptions buildPlayerOptions) (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:258)
UnityEditor.BuildPipeline.BuildPlayer (System.String[] levels, System.String locationPathName, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options) (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:253)
Build.DoBuildAndroid (System.String buildPath) (at Assets/Editor/Build.cs:45)
Build.DoBuildAndroidLegacy () (at Assets/Editor/Build.cs:31)

**Comment by planetMatrix** [comment]
I too had that issue with Unity version

It's solved by
https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249

**Comment by dawiddszewczyk** [comment]
Hi, this error did resolve in the new Flutter Unity Widget version and package. Remember to reimport the Flutter Unity Widget package!
