### ISSUE TITLE
I can't get my head around _unityWidgetController.postMessage

### ISSUE THREAD

**Issue by planetMatrix** [juicycleff/flutter-unity-view-widget#268]
Hi there,

I have multiple scenes in unity and want to map them to their respective icons.

in Flutter I have
`void loadScene(String scene) {
    _unityWidgetController.postMessage(
        'go', "openScene", "Vuf2"
    );
  }`

In Unity I have.. Attached to go GameObject

`void openScene(String name)
    {
        SceneManager.LoadScene(name);
    }`

My issue is, where do I call void loadScene?

in SimpleScreen.dart or in main.dart?

**Comment by planetMatrix** [comment]
Just to add, I have 3 scenes in Unity
Scene index 1 is blank with "go" GameObject

**Comment by ljmatan** [comment]
Add the C# script to whichever gameobject will be active in the scene. In the first parameter you need to set the name of the gameobject you've added a script to, then call the function from wherever you want in your Flutter app. Name of the function is the second parameter ('openScene' in your case), and the third parameter can be either an optional parameter for your C# function or an empty string. It's not a good approach to call some Unity function in the Flutter app's main function.

Take a look at my code [here.](https://github.com/juicycleff/flutter-unity-view-widget/issues/269)

**Comment by planetMatrix** [comment]
Many thanks @ljmatan for your help..

Just to test, I tried calling loadScene in initState.. got error
`The method 'postMessage' was called on null.
Receiver: null
Tried calling: postMessage("go", "openScene", "Vuf2")`

Is this the right way? Surely scene at index 0 is loading if I do not call loadScene in SimpleScreen.

I have been searching the internet whole day, but no relevant results

@juicycleff Is it even possible to have multiple scenes in Unity Project mapped to Flutter?

**Comment by ljmatan** [comment]
In Unity editor go to File -> Build settings and there you'll see an option to "Add Open Scenes" to "Scenes In Build". Scene with index 0 (visible on the right side) will be the first one to load when the Unity widget starts.

**Comment by planetMatrix** [comment]
Yes Scene at index 0 is loading by default.

But I want Scene at index 1 to load. So I added a script to Scene at index 0 to push to which ever scene flutter passes on
`void openScene(String name) { SceneManager.LoadScene(name); }`

**Comment by planetMatrix** [comment]
Okay finally figured out...

` @override
  void initState() {
    _getThingsOnStartup().then((value){
    loadScene("Vuf1");
    });
    super.initState();`

**Comment by evelynxxx** [comment]
@planetMatrix Hi, could you share you flutter code here. For the _getThingsOnStartup() is from where ?
