### ISSUE TITLE
Issue with Unity to Flutter messages

### ISSUE THREAD

**Issue by Antriadus** [juicycleff/flutter-unity-view-widget#270]
Hi there. Thanks for great package. I cannot receive messages from Unity on Huawei P30 Pro. There're no problems with sending messages To Unity. On other smartphone there's no problem with messages.

To Reproduce:
Run demo and send message from Unity To Flutter.

Expected behaviour:
I can receive messages from Unity on Huawei P30 Pro.

Setup:
 - Device: Huawei P30 PRO, Android 10
 - Unity: 2019.4.10f1
 - Flutter: Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64)
 - package version: 3.0.1

**Comment by Antriadus** [comment]
My bad, I have wrong proguard settings.

**Comment by chenenyu** [comment]
> My bad, I have wrong proguard settings.
@Antriadus How to fix it ?

**Comment by gisinator** [comment]
How exactly did you fix this? Would you mind explaining where and how you edited the proguard settings? Thanks :)
