### ISSUE TITLE
Provide a way to check for AR availability

### ISSUE THREAD

**Issue by Zazo032** [juicycleff/flutter-unity-view-widget#272]
**Is your feature request related to a problem? Please describe.**
Some devices out there don't support AR (or ARCore Services from Google Play), so before launching the Unity view with AR features, we would like to check if AR support is available on the device, so we can provide a fallback feature for those devices.

**Describe the solution you'd like**
A method that returns `true` if AR is supported on that device

**Describe alternatives you've considered**
Almost all recent iPhones support AR (I think iPhone 6S and onwards), so the biggest downside is Android. If this plugin is using ARCore, the solution could be to check natively if ARCore is present on the device. I'm not sure how this could be checked for devices that don't support Google Play (latest Huawei and other devices from China), since they might support AR but not ARCore, and I can't test what would be the behavior of this plugin for that case.

cc/ @juicycleff

**Comment by kingkimohero69** [comment]
I think what you are looking for is in this link : [https://github.com/Unity-Technologies/arfoundation-samples](url)
you can find a script called checksupport.cs which we tell you if the device is supported or not

**Comment by juicycleff** [comment]
@Zazo032 I will recommend you use @kingkimohero69 suggestion.

**Comment by Zazo032** [comment]
If someone is in a similar situation, you can use this: https://pub.dev/packages/raavailability

**Comment by Tommy-Elliott** [comment]
Here's how I managed a silent check for AR support using Unity and flutter_unity_widget.  Create a Unity scene with just a light source and cube in it.  Attach the Unity Messenger script to the cube game object (named "Cube").  Create your own custom script and attach it to the cube game object (class named "ARCompatibilityManager") and make that a singleton monobehavior (see demo code in FlutterUnityIntegration).  Create a private bool property on that class (property named "DeviceIsARCapable").  In the Start method, set that to false or do nothing.  Create a public void function (function named "CheckForDeviceARCapability") that takes a string parameter (named "message") that just calls a custom coroutine that checks for device AR capability and sends a true/false message back to Flutter using `ARSession.CheckAvailability()` (a static method, no instance needed) and `UnityMessageManager.Instance.SendMessageToFlutter` (also static).
