### ISSUE TITLE
il2cpp error when building with version ^3.0.1

### ISSUE THREAD

**Issue by OGmetamonkey** [juicycleff/flutter-unity-view-widget#273]
**Describe the bug**
Tried upgrading to the latest implementation of the flutter unity widget. Previous working implementation was ^0.1.6+8. Getting errors related to il2cpp.

**To Reproduce**
1. Add flutter_unity_widget: ^3.0.1 to the flutter project as specified in the read me, including the addition of 'FlutterUnityPackage-3.0.0.unitypackage.
2. Open in Unity and build to Android
3. Try to build the flutter project to android device in debugger mode.

**Expected behavior**
Expected the app to build successfully as it did when using flutter unity widget version ^0.1.6+8

**Versions**
Flutter: 1.22.5
Dart: 2.10.4
Flutter unity widget: 3.0.1
Unity: 2020.1.16f1
Unity Hub: 2.4.2
Android Device: Nexus 5x using Android 8.1.0

**Debug Log**

> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Launching lib/main.dart on Nexus 5X in debug mode...
 lib/main.dart
Running il2cpp.exe in workstation GC mode.
il2cpp.exe didn't catch exception: System.Exception: Android NDK r19 or newer not detected at 'null'.
  at Unity.IL2CPP.Building.ToolChains.Android.AndroidNDKUtilities..ctor (NiceIO.NPath ndkRootPath, Unity.IL2CPP.Common.Architecture architecture, System.Boolean useDependenciesToolChain) [0x00078] in <ca1b90d094ae45268b05510b1d874a20>:0
  at Unity.IL2CPP.Building.ToolChains.AndroidToolChain..ctor (Unity.IL2CPP.Common.Architecture architecture, Unity.IL2CPP.Building.BuildConfiguration buildConfiguration, System.Boolean treatWarningsAsErrors, System.Boolean assemblyOutput, System.Boolean useDependenciesToolChain, NiceIO.NPath toolchainPath) [0x00008] in <ca1b90d094ae45268b05510b1d874a20>:0
  at Unity.IL2CPP.Building.Platforms.AndroidPlatformSupport.MakeCppToolChain (Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x00000] in <ca1b90d094ae45268b05510b1d874a20>:0
  at il2cpp.Compilation.CompilationDriver.Run (Unity.IL2CPP.Common.RuntimePlatform platform, Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x000c0] in <3be9f628f5fa469389bd6a91a579ba8a>:0
  at il2cpp.Program.DoRun (System.String[] args, Unity.IL2CPP.Common.RuntimePlatform platform, Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x0001f] in <3be9f628f5fa469389bd6a91a579ba8a>:0
  at il2cpp.Program.Run (System.String[] args, System.Boolean setInvariantCulture) [0x00063] in <3be9f628f5fa469389bd6a91a579ba8a>:0
  at il2cpp.Program.Main (System.String[] args) [0x00000] in <3be9f628f5fa469389bd6a91a579ba8a>:0

> Unhandled Exception:
> System.Exception: Android NDK r19 or newer not detected at 'null'.
>   at Unity.IL2CPP.Building.ToolChains.Android.AndroidNDKUtilities..ctor (NiceIO.NPath ndkRootPath, Unity.IL2CPP.Common.Architecture architecture, System.Boolean useDependenciesToolChain) [0x00078] in <ca1b90d094ae45268b05510b1d874a20>:0
>   at Unity.IL2CPP.Building.ToolChains.AndroidToolChain..ctor (Unity.IL2CPP.Common.Architecture architecture, Unity.IL2CPP.Building.BuildConfiguration buildConfiguration, System.Boolean treatWarningsAsErrors, System.Boolean assemblyOutput, System.Boolean useDependenciesToolChain, NiceIO.NPath toolchainPath) [0x00008] in <ca1b90d094ae45268b05510b1d874a20>:0
>   at Unity.IL2CPP.Building.Platforms.AndroidPlatformSupport.MakeCppToolChain (Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x00000] in <ca1b90d094ae45268b05510b1d874a20>:0 
>   at il2cpp.Compilation.CompilationDriver.Run (Unity.IL2CPP.Common.RuntimePlatform platform, Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x000c0] in <3be9f628f5fa469389bd6a91a579ba8a>:0
>   at il2cpp.Program.DoRun (System.String[] args, Unity.IL2CPP.Common.RuntimePlatform platform, Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x0001f] in <3be9f628f5fa469389bd6a91a579ba8a>:0
>   at il2cpp.Program.Run (System.String[] args, System.Boolean setInvariantCulture) [0x00063] in <3be9f628f5fa469389bd6a91a579ba8a>:0
>   at il2cpp.Program.Main (System.String[] args) [0x00038] in <3be9f628f5fa469389bd6a91a579ba8a>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Android NDK r19 or newer not detected at 'null'.
>   at Unity.IL2CPP.Building.ToolChains.Android.AndroidNDKUtilities..ctor (NiceIO.NPath ndkRootPath, Unity.IL2CPP.Common.Architecture architecture, System.Boolean useDependenciesToolChain) [0x00078] in <ca1b90d094ae45268b05510b1d874a20>:0
>   at Unity.IL2CPP.Building.ToolChains.AndroidToolChain..ctor (Unity.IL2CPP.Common.Architecture architecture, Unity.IL2CPP.Building.BuildConfiguration buildConfiguration, System.Boolean treatWarningsAsErrors, System.Boolean assemblyOutput, System.Boolean useDependenciesToolChain, NiceIO.NPath toolchainPath) [0x00008] in <ca1b90d094ae45268b05510b1d874a20>:0
>   at Unity.IL2CPP.Building.Platforms.AndroidPlatformSupport.MakeCppToolChain (Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x00000] in <ca1b90d094ae45268b05510b1d874a20>:0
>   at il2cpp.Compilation.CompilationDriver.Run (Unity.IL2CPP.Common.RuntimePlatform platform, Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x000c0] in <3be9f628f5fa469389bd6a91a579ba8a>:0
>   at il2cpp.Program.DoRun (System.String[] args, Unity.IL2CPP.Common.RuntimePlatform platform, Unity.IL2CPP.Building.BuildingOptions buildingOptions) [0x0001f] in <3be9f628f5fa469389bd6a91a579ba8a>:0
>   at il2cpp.Program.Run (System.String[] args, System.Boolean setInvariantCulture) [0x00063] in <3be9f628f5fa469389bd6a91a579ba8a>:0
>   at il2cpp.Program.Main (System.String[] args) [0x00038] in <3be9f628f5fa469389bd6a91a579ba8a>:0
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/me/Development/Project_Repo/project/project_upgrade/android/unityLibrary/build.gradle' line: 51
> 
> * What went wrong:
> Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> > Process 'command '/Applications/Unity/Hub/Editor/2020.1.16f1/Unity.app/Contents/MonoBleedingEdge/bin/mono'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

**Comment by OGmetamonkey** [comment]
Attempted to fix this by modifying the android/unityLibrary/build.gradle ndk location to the location of my Unity NDK install as follows:

`"--tool-chain-path=" + '/Applications/Unity/Hub/Editor/2020.1.16f1/PlaybackEngines/AndroidPlayer/NDK',`

With the above "fix", the flutter project will build, but the project crashes when the unity module is created. 'onUnityCreated' is called just before the crash. Debug log below:

> I/IL2CPP  ( 2304): JNI_OnLoad
> I/Choreographer( 2304): Skipped 73 frames!  The application may be doing too much work on its main thread.
> E/flutter ( 2304): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.RuntimeException: platformViewsController must be set before attempting to begin the frame
> E/flutter ( 2304): 	at io.flutter.embedding.engine.FlutterJNI.onBeginFrame(FlutterJNI.java:842)
> E/flutter ( 2304): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter ( 2304): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/flutter ( 2304): 	at android.os.Looper.loop(Looper.java:142)
> E/flutter ( 2304): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/flutter ( 2304): 	at java.lang.reflect.Method.invoke(Native Method)
> E/flutter ( 2304): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/flutter ( 2304): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> E/flutter ( 2304):
> F/flutter ( 2304): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1228)] Check failed: CheckException(env).
> I/flutter ( 2304): Unity is created!!
> I/flutter ( 2304): *********************************************
> I/flutter ( 2304): ** flutter unity controller setup complete **
> I/flutter ( 2304): *********************************************
> Lost connection to device.
> Exited (sigterm)
>

**Comment by OGmetamonkey** [comment]
Update: I attempted to refer to the NDK directory installed by Android Studio SDK Manager as follows: 

`            "--tool-chain-path=" + '/Users/me/Library/Android/sdk/ndk/22.0.6917172',
`

Same result. Log of attempt to open Unity below.

> 
> I/IL2CPP  (30164): JNI_OnLoad
> I/Choreographer(30164): Skipped 81 frames!  The application may be doing too much work on its main thread.
> E/flutter (30164): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.RuntimeException: platformViewsController must be set before attempting to begin the frame
> E/flutter (30164): 	at io.flutter.embedding.engine.FlutterJNI.onBeginFrame(FlutterJNI.java:842)
> E/flutter (30164): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (30164): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/flutter (30164): 	at android.os.Looper.loop(Looper.java:142)
> E/flutter (30164): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/flutter (30164): 	at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (30164): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/flutter (30164): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> E/flutter (30164):
> F/flutter (30164): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1228)] Check failed: CheckException(env).
> I/flutter (30164): Unity is created!!
> I/flutter (30164): *********************************************
> I/flutter (30164): ** flutter unity controller setup complete **
> I/flutter (30164): *********************************************
> Lost connection to device.
> Exited (sigterm)
>

**Comment by OGmetamonkey** [comment]
Tried a fresh install and build. Same result.

**[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.RuntimeException: platformViewsController must be set before attempting to begin the frame**

**Comment by khalithartmann** [comment]
any updates @OGmetamonkey . having same problem

**Comment by OGmetamonkey** [comment]
No @khalithartmann. I downgraded back to version: 0.1.6+8 after wasting a few days on it. Still hoping someone smarter than me figures it out.

**Comment by phamtuongvan** [comment]
use Unity 2019.4.3f

**Comment by Abhishek01039** [comment]
Hello @phamtuongvan 
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '/Users/abhishek/Downloads/flutterunity/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```


I am getting this error. So what should I do?

**Comment by esentis** [comment]
> Hello @phamtuongvan
> 
> ```
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> > A problem occurred starting process 'command '/Users/abhishek/Downloads/flutterunity/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 47s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> ```
> 
> I am getting this error. So what should I do?

Getting the exact same error :/

**Comment by jsolra** [comment]
> Hello @phamtuongvan
> 
> ```
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> > A problem occurred starting process 'command '/Users/abhishek/Downloads/flutterunity/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 47s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> ```
> 
> I am getting this error. So what should I do?

I get the same error, too.

**Comment by ROBYER1** [comment]
Any updates on this?

**Comment by Robinzon100** [comment]
https://prnt.sc/1qenetv

**Comment by f-mehues** [comment]
Hi any updates?

**Comment by crisifur19** [comment]
The solution is just to change the ndk.dir from "C:\Program Files\Unity\Hub\Editor\2020.1.8f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK" to "C:/Program Files/Unity/Hub/Editor/2020.1.8f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" ; it's a pretty silly error that the compilation seems to throw because a lecture error of directories.

**Comment by Abhi902** [comment]
how to do it on MacBook m1 .
