### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by jain-aayush1123** [juicycleff/flutter-unity-view-widget#277]
**Describe the bug**
Android builds fails when building from unity. Was facing build cannot be appended issue #234 so followed https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249 basically editing Build.cs to allow android being exported as android studio project. Now it says cannot copy temp manifest
`IOException: Failed to Copy File / Directory from 'Temp/StagingArea\AndroidLauncherManifest-main.xml' to 'Temp/StagingArea\LauncherManifest.xml': destination path already exists.
UnityEditor.FileUtil.CopyFileOrDirectory (System.String source, System.String dest) (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <12a2b75af02641e99fa5d5b4bf0b41f7>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <12a2b75af02641e99fa5d5b4bf0b41f7>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <12a2b75af02641e99fa5d5b4bf0b41f7>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <12a2b75af02641e99fa5d5b4bf0b41f7>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
Build:DoBuildAndroid(String, Boolean) (at Assets/FlutterUnityIntegration/Editor/Build.cs:56)
Build:DoBuildAndroidLibrary() (at Assets/FlutterUnityIntegration/Editor/Build.cs:23)
` 

**To Reproduce**
1. Clickin gon Flutter > Build Android

**Expected behavior**
Successful build?

**Screenshots**

**Desktop (please complete the following information):**
 - Flutter - 1.22.2
 - Unity - 2019.4.14f1

**Comment by OGmetamonkey** [comment]
Have you tried deleting your temp/StagingArea directory? @jain-aayush1123

**Comment by jain-aayush1123** [comment]
Ya. That didnt work. However dropping unity version down by 1 did. Closing the issue for now

**Comment by BlickwinkelTour** [comment]
> 
> 
> Ya. That didnt work. However dropping unity version down by 1 did. Closing the issue for now

Hi, dropping by 1, do you mean 2019.4.13 or 2019.3 ?

**Comment by jain-aayush1123** [comment]
> > Ya. That didnt work. However dropping unity version down by 1 did. Closing the issue for now
> 
> Hi, dropping by 1, do you mean 2019.4.13 or 2019.3 ?

2019.3. Also works for unity 2018
