### ISSUE TITLE
Android build fail.

### ISSUE THREAD

**Issue by lentinip** [juicycleff/flutter-unity-view-widget#279]
Hello everyone!
Can anyone help me?

I’m using Vuforia on Unity version 2020.1.14f1. flutter_unity_widget: ^3.0.1. AR project.

I didn’t understand the steps explained under Android and Vuforia in the README file.
Maybe the problem can be solved with one of those steps.

**What I did:**

Problem during building fixed in Build.cs as in:

 https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249

**Android Build:**

Changed the `minSdkVersion` in the `app/build.gradle` from 16 to 24 for some errors.

**And still error:**
```
Running Gradle task 'assembleDebug'...
[:arcore_client:] /Users/pietrolentini/.gradle/caches/transforms-2/files-2.1/a39d320a02bdc6c4cca0585f10641eb4/arcore_client/AndroidManifest.xml:30:9-54 Error:
	Missing 'package' key attribute on element package at [:arcore_client:] AndroidManifest.xml:30:9-54
[:arcore_client:] /Users/pietrolentini/.gradle/caches/transforms-2/files-2.1/a39d320a02bdc6c4cca0585f10641eb4/arcore_client/AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
```
I tried also to change the Gradle version but it still have some problems so I decided to step back to this position.

**Comment by lentinip** [comment]
Changing the Gradle I have this problem trying to build on a physical device:

``` bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '/Applications/Unity/Hub/Editor/2020.1.14f1/Unity.app/Contents/MonoBleedingEdge/bin/mono''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by khalithartmann** [comment]
did you solve the issue ? @lentinip

**Comment by lentinip** [comment]
> did you solve the issue ? @lentinip 

Not yet, same problem. I am using also Manomotion SDK in the Unity project. Maybe it does some conflicts?

**Comment by alexanderameye** [comment]
Having the same issue as you @lentinip, I also tried to change gradle version to 5.6.4. but then got another few issues. How did you change the gradle version?

**Comment by gisinator** [comment]
I had been facing the same error message "missing package key" and could finally get rid of it by upgrading Gradle. See my other [comment](https://github.com/juicycleff/flutter-unity-view-widget/issues/310#issuecomment-782585847) where I posted what I did. Good luck everyone :)

**Comment by skjagan** [comment]
> > did you solve the issue ? @lentinip
> 
> Not yet, same problem. I am using also Manomotion SDK in the Unity project. Maybe it does some conflicts?

Hi @lentinip , I am also working on Manomotion SDK - Unity - Flutter combination. I am able to build the apk but Manomotion is not detecting any hand gestures within the app. Can you please help me with it.
