### ISSUE TITLE
Multiple unity games without scene manager

### ISSUE THREAD

**Issue by ghost** [juicycleff/flutter-unity-view-widget#284]
If I'm not mistaken, the solution to getting multiple unity games is to use a scene manager. This means I can have many games inside a single unity project and change them within the unity project.

This is nice but is there a way I can actually load multiple unity projects? What I want is a list view on the home screen with a list of mini unity games. When a user taps on one of them, it will run that mini-game. 

Our project consists of a lot of these small games from different publishers. I feel like there is no support for this yet but will this be supported in the future?

**Comment by thassio-vinicius** [comment]
I'd love to get support for this too

**Comment by subzero911** [comment]
+1 for multiple Unity projects support

**Comment by thassio-vinicius** [comment]
That's not possible fellas, just found out that it's a limitation on [unity's end](https://docs.unity3d.com/2019.3/Documentation/Manual/UnityasaLibrary.html?_ga=2.180182052.149673779.1615331353-404343179.1614881404). The only way to go around it is to create some sort of launcher for all of your games and merge them into one single unity app
