### ISSUE TITLE
Unity widget is always on the top even if other routes are pushed

### ISSUE THREAD

**Issue by songgravel** [juicycleff/flutter-unity-view-widget#285]
Hi, everyone!
I loaded a unity widget in my project. Everything is ok until I pushed a new page by calling "Navigator.pushNamed". The unity widget seems to be always on the top even if other routes are pushed. All new pushed widgets are covered by the unity widget, and unity draws and refreshs are all well as usual. But when I tap on the screen, it seems that now the focus is on new pushed widgets and they can responses well.
I try to hide the unity widget, but it still shows on the top. When I "popAndPushNamed" a new page, the unity widget can be hidden by poping from navigator.
What can I do to hide the unity widget without poping current route?
Can anyone help me? Thanks a lot!

**Comment by ljmatan** [comment]
You can use a stack widget as a temporary solution until you decide to go native it seems.

**Comment by JuneLeo** [comment]
> You can use a stack widget as a temporary solution until you decide to go native it seems.

https://github.com/flutter/flutter/issues/72960
I have the same problem.

**Comment by JuneLeo** [comment]
I have the same problem, and my solution is to call unityPlayer.pause () and UnityView.removeview (UnityPlayer) when Navigation.pushName (),else  unityPlayer.resume() and unityPlayer.addView (UnityPlayer) when Navigation.pop();

**Comment by JuneLeo** [comment]
I'd like to ask you a question
In Android PlatformView, getView is always called，Why？
Can SurfaceTexture be used on Android? Flutter side using Texture Widget?

**Comment by cmd-dev** [comment]
> I have the same problem, and my solution is to call unityPlayer.pause () and UnityView.removeview (UnityPlayer) when Navigation.pushName (),else unityPlayer.resume() and unityPlayer.addView (UnityPlayer) when Navigation.pop();

How did you implement this?

**Comment by timbotimbo** [comment]
Closing this as outdated, as this doesn't seem to happen in recent versions.
If you think this is still valid, you can open it again.
