### ISSUE TITLE
Copy path wrongly set and error in build options

### ISSUE THREAD

**Issue by WouterVandenputte** [juicycleff/flutter-unity-view-widget#287]
**Describe the bug**
First of all, love it that there is finally support for adding Unity to flutter!
Now for the bug, the issue is twofold

1. The build options make the build fail
2. The path to copy the .apk is wrongly formatted

**To Reproduce**
When pressing Flutter > Export Android, line 55 of `build.cs` will crash. This is the exception thrown

> InvalidOperationException: The build target does not support build appending.
UnityEditor.BuildPipeline.BuildPlayer (System.String[] scenes, System.String locationPathName, System.String assetBundleManifestPath, UnityEditor.BuildTargetGroup buildTargetGroup, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options, System.String[] extraScriptingDefines) (at <1e441e8684a14fe4b8f8a926d91afc3a>:0)
UnityEditor.BuildPipeline.BuildPlayer (UnityEditor.BuildPlayerOptions buildPlayerOptions) (at <1e441e8684a14fe4b8f8a926d91afc3a>:0)
UnityEditor.BuildPipeline.BuildPlayer (System.String[] levels, System.String locationPathName, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options) (at <1e441e8684a14fe4b8f8a926d91afc3a>:0)
Build.DoBuildAndroid (System.String buildPath, System.Boolean isPlugin) (at Assets/FlutterUnityIntegration/Editor/Build.cs:55)
Build.DoBuildAndroidLibrary () (at Assets/FlutterUnityIntegration/Editor/Build.cs:23)

 I have manually been editing stuff and the problem lies with defining `var options = BuildOptions.AcceptExternalModificationsToPlayer;`. It seems that overwriting it with `options = BuildOptions.None;` at least mitigated it, but I assume that is not something a user actually needs. 

With this new options set, retrying Flutter > Export Android a new issue arises, this is the ouptut

> DirectoryNotFoundException: Could not find a part of the path 'D:\repositories\my_flutter_project\unity\MyUnityProject\Builds\MyUnityProject.apk\unityLibrary'.

I tracked the issue and the error can be traced back to `build.cs` line 23

`DoBuildAndroid(Path.Combine(apkPath, "unityLibrary"), false);`

This Path combines `apkPath` which is `D:\repositories\my_flutter_project\unity\MyUnityProject\Builds\MyUnityProject.apk\` and then tries to create a subfolder, yet you cannot create a folder inside a file. So I ASSUME the intended directory would be

`D:\repositories\my_flutter_project\unity\MyUnityProject\Builds\unityLibrary\MyUnityProject.apk\`

**Expected behavior**
The build succeeds and the copy is done to wherever the plug expects it to be.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity 2020.2.1f1
 - flutter_unity_widget 3.0.2

**Comment by BlickwinkelTour** [comment]
Hi, I just started with flutter development and nw integrated unity. I ran into the same issue and edited the build.cs a littlebit. the export works for now. But in my case handling with the integration of Unity into Flutter/Android feels a bit wonky. I also tried to edit all the dependencies and manifest from scratch, so that I could start from a clean Flutter project. But unfortunately I am too much of a noob to know what I was doing, and I couldn´t get the dependencies to work properly. I am glad my cs editing works now. I know, this has nothing to do with Flutter/Unity, but I hope that someone could make a deep dive (or point to a good tutorial) reagarding build.gradle, AndroidManifest (merging) SDK versions etc. Keep up the good work to all the plugin devs! Thank you!! B

and herés the whole script.
What  I did:  just added another variable for a "buildPath" so that the Copy functions don´t point to the apk-file.
Don´t expect me that I knew what I was doing, but it works ;P
[Build.cs.txt](https://github.com/juicycleff/flutter-unity-view-widget/files/5754796/Build.cs.txt)

**Comment by mathtasatlime** [comment]
@juicycleff I'm also running in the exact same error. Have you any solution for this problem?

**Comment by juicycleff** [comment]
Hi @mathtasatlime theres a v4 branch where I am fixing a lot, you can test it out will release fir alpha soon. Aside I have not seen this error, and I've done multiple exports, what version of unity are you using?

**Comment by mathtasatlime** [comment]
Thanks @juicycleff ! 
Atm I'm using 2019.4.18f1. 

Steps:
1. Download the current version of your repo.
2. open the example unity project with 2019.4.18f1
3. click on "Export Android"
4. exactly to above mentioned errors occur

**Comment by juicycleff** [comment]
@mathtasatlime its weird as I have exported fir that exact version, did you select *export Android* or *Export Android Plugin*

**Comment by mathtasatlime** [comment]
definitely export Android.

I successfully used the export function several times in last autemn. Yesterday I tried it again and the errors occured.

**Comment by alexanderameye** [comment]
I had this same issue but the fix was super easy.

This comment fixed it for me: https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249

**Comment by BlickwinkelTour** [comment]
Hi, it is a simple path error in the build.cs script. It tries to make a path in the apk file. just overwrite the build.cs with this:
That worked for me.

`using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using Application = UnityEngine.Application;
using BuildResult = UnityEditor.Build.Reporting.BuildResult;

public class Build
{
    static readonly string ProjectPath = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
    static readonly string buildPath = Path.Combine(ProjectPath, "Builds");
    static readonly string apkPath = Path.Combine(ProjectPath, "Builds/" + Application.productName + ".apk");

    static readonly string androidExportPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../android/unityLibrary"));
    static readonly string iosExportPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../ios/UnityLibrary"));
    static readonly string iosExportPluginPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../ios_xcode/UnityLibrary"));

    [MenuItem("Flutter/Export Android %&n", false, 1)]
    public static void DoBuildAndroidLibrary()
    {
        DoBuildAndroid(Path.Combine(buildPath, "unityLibrary"), false);

        // Copy over resources from the launcher module that are used by the library
        Copy(Path.Combine(apkPath + "/launcher/src/main/res"), Path.Combine(androidExportPath, "src/main/res"));
    }

    [MenuItem("Flutter/Export Android Plugin %&p", false, 2)]
    public static void DoBuildAndroidPlugin()
    {
        DoBuildAndroid(Path.Combine(buildPath, "unityLibrary"), true);

        // Copy over resources from the launcher module that are used by the library
        Copy(Path.Combine(apkPath + "/launcher/src/main/res"), Path.Combine(androidExportPath, "src/main/res"));
    }

    [MenuItem("Flutter/Legacy/Export Android", false, 5)]
    public static void DoBuildAndroidLegacy()
    {
        DoBuildAndroid(Path.Combine(buildPath, Application.productName), true);
    }

    public static void DoBuildAndroid(String buildPath, bool isPlugin)
    {
        if (Directory.Exists(Build.buildPath))
            Directory.Delete(Build.buildPath, true);
        Directory.CreateDirectory("E:/Blickwinkel_Tour/Unity_Projects/Remote_Client/Blickwinkel_Remote/Builds/unityLibrary");

        if (Directory.Exists(androidExportPath))
            Directory.Delete(androidExportPath, true);

        EditorUserBuildSettings.androidBuildSystem = AndroidBuildSystem.Gradle;

        var options = BuildOptions.AllowDebugging;
        //var options = BuildOptions.AcceptExternalModificationsToPlayer;
        var report = BuildPipeline.BuildPlayer(
            GetEnabledScenes(),
            Build.apkPath,
            BuildTarget.Android,
            options
        );

        if (report.summary.result != BuildResult.Succeeded)
            throw new Exception("Build failed");

        Copy(Path.Combine(Build.apkPath, "unityLibrary"), androidExportPath);

        // Modify build.gradle
        var build_file = Path.Combine(androidExportPath, "build.gradle");
        var build_text = File.ReadAllText(build_file);
        build_text = build_text.Replace("com.android.application", "com.android.library");
        build_text = build_text.Replace("bundle {", "splits {");
        build_text = build_text.Replace("enableSplit = false", "enable false");
        build_text = build_text.Replace("enableSplit = true", "enable true");
        build_text = build_text.Replace("implementation fileTree(dir: 'libs', include: ['*.jar'])", "implementation(name: 'unity-classes', ext:'jar')");
        build_text = Regex.Replace(build_text, @"\n.*applicationId '.+'.*\n", "\n");
        File.WriteAllText(build_file, build_text);

        // Modify AndroidManifest.xml
        var manifest_file = Path.Combine(androidExportPath, "src/main/AndroidManifest.xml");
        var manifest_text = File.ReadAllText(manifest_file);
        manifest_text = Regex.Replace(manifest_text, @"<application .*>", "<application>");
        Regex regex = new Regex(@"<activity.*>(\s|\S)+?</activity>", RegexOptions.Multiline);
        manifest_text = regex.Replace(manifest_text, "");
        File.WriteAllText(manifest_file, manifest_text);

        if (isPlugin)
        {
            AndroidGetSomeRestWillYaPlugin();
        }
        else
        {
            AndroidGetSomeRestWillYa();
        }
    }

    [MenuItem("Flutter/Export IOS %&i", false, 3)]
    public static void DoBuildIOS()
    {
        if (Directory.Exists(iosExportPath))
            Directory.Delete(iosExportPath, true);

        EditorUserBuildSettings.iOSBuildConfigType = iOSBuildType.Release;

        var options = BuildOptions.AcceptExternalModificationsToPlayer;
        var report = BuildPipeline.BuildPlayer(
            GetEnabledScenes(),
            iosExportPath,
            BuildTarget.iOS,
            options
        );

        if (report.summary.result != BuildResult.Succeeded)
            throw new Exception("Build failed");

        // Automate so manual steps
        GetSomeRestWillYa();
    }


    [MenuItem("Flutter/Export IOS Plugin %&o", false, 4)]
    public static void DoBuildIOSPlugin()
    {
        if (Directory.Exists(iosExportPluginPath))
            Directory.Delete(iosExportPluginPath, true);

        EditorUserBuildSettings.iOSBuildConfigType = iOSBuildType.Release;

        var options = BuildOptions.AcceptExternalModificationsToPlayer;

        var report = BuildPipeline.BuildPlayer(
            GetEnabledScenes(),
            iosExportPluginPath,
            BuildTarget.iOS,
            options
        );


        if (report.summary.result != BuildResult.Succeeded)
            throw new Exception("Build failed");

        // Automate so manual steps
        GetSomeRestWillYaPlugin();

        // Build Archive
        buildArchive();

    }

    static void Copy(string source, string destinationPath)
    {
        if (Directory.Exists(destinationPath))
            Directory.Delete(destinationPath, true);

        Directory.CreateDirectory(destinationPath);

        foreach (string dirPath in Directory.GetDirectories(source, "*",
            SearchOption.AllDirectories))
            Directory.CreateDirectory(dirPath.Replace(source, destinationPath));

        foreach (string newPath in Directory.GetFiles(source, "*.*",
            SearchOption.AllDirectories))
            File.Copy(newPath, newPath.Replace(source, destinationPath), true);
    }

    static string[] GetEnabledScenes()
    {
        var scenes = EditorBuildSettings.scenes
            .Where(s => s.enabled)
            .Select(s => s.path)
            .ToArray();

        return scenes;
    }

    /// <summary>
    /// This method tries to autome the build setup required for Android
    /// </summary>
    static void AndroidGetSomeRestWillYa()
    {
        string androidPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../android"));
        string androidAppPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../android/app"));
        var proj_build_path = Path.Combine(androidPath, "build.gradle");
        var app_build_path = Path.Combine(androidAppPath, "build.gradle");
        var settings_path = Path.Combine(androidPath, "settings.gradle");

        var proj_build_script = File.ReadAllText(proj_build_path);
        var settings_script = File.ReadAllText(settings_path);
        var app_build_script = File.ReadAllText(app_build_path);

        // Sets up the project build.gradle files correctly
        if (!Regex.IsMatch(proj_build_script, @"flatDir[^/]*[^}]*}"))
        {
            Regex regex = new Regex(@"allprojects \{[^\{]*\{", RegexOptions.Multiline);
            proj_build_script = regex.Replace(proj_build_script, @"
allprojects {
    repositories {
        flatDir {
            dirs ""${project(':unityLibrary').projectDir}/libs""
        }
");
            File.WriteAllText(proj_build_path, proj_build_script);
        }

        // Sets up the project settings.gradle files correctly
        if (!Regex.IsMatch(settings_script, @"include "":unityLibrary"""))
        {
            settings_script += @"

include "":unityLibrary""
project("":unityLibrary"").projectDir = file(""./unityLibrary"")
";
            File.WriteAllText(settings_path, settings_script);
        }


        // Sets up the project app build.gradle files correctly
        if (!Regex.IsMatch(app_build_script, @"dependencies \{"))
        {
            app_build_script += @"

dependencies {
    implementation project(':unityLibrary')
}
";
            File.WriteAllText(app_build_path, app_build_script);
        }
        else
        {
            if (!Regex.IsMatch(app_build_script, @"implementation project(':unityLibrary')"))
            {
                Regex regex = new Regex(@"dependencies \{", RegexOptions.Multiline);
                app_build_script = regex.Replace(app_build_script, @"
dependencies {
    implementation project(':unityLibrary')
");
                File.WriteAllText(app_build_path, app_build_script);
            }
        }
    }


    /// <summary>
    /// This method tries to autome the build setup required for Android
    /// </summary>
    static void AndroidGetSomeRestWillYaPlugin()
    {
        string androidPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../android"));
        var proj_build_path = Path.Combine(androidPath, "build.gradle");
        var settings_path = Path.Combine(androidPath, "settings.gradle");

        var proj_build_script = File.ReadAllText(proj_build_path);
        var settings_script = File.ReadAllText(settings_path);

        // Sets up the project build.gradle files correctly
        if (Regex.IsMatch(proj_build_script, @"// BUILD_ADD_UNITY_LIBS"))
        {
            Regex regex = new Regex(@"// BUILD_ADD_UNITY_LIBS", RegexOptions.Multiline);
            proj_build_script = regex.Replace(proj_build_script, @"
        flatDir {
            dirs ""${project(':unityLibrary').projectDir}/libs""
        }
");
            File.WriteAllText(proj_build_path, proj_build_script);
        }

        // Sets up the project settings.gradle files correctly
        if (!Regex.IsMatch(settings_script, @"include "":unityLibrary"""))
        {
            settings_script += @"

include "":unityLibrary""
project("":unityLibrary"").projectDir = file(""./unityLibrary"")
";
            File.WriteAllText(settings_path, settings_script);
        }
    }

    static void GetSomeRestWillYa()
    {
        string iosRunnerPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../ios/Runner"));
        var info_file = Path.Combine(iosRunnerPath, "info.plist");
        var info_text = File.ReadAllText(info_file);

        if (!Regex.IsMatch(info_text, @"<key>io.flutter.embedded_views_preview</key>"))
        {
            Regex regex = new Regex(@"</dict>", RegexOptions.Multiline);
            info_text = regex.Replace(info_text, @"
				<key>io.flutter.embedded_views_preview</key>
				<true/>
			</dict>
			");
            File.WriteAllText(info_file, info_text);
        }
    }

    static void GetSomeRestWillYaPlugin()
    {
        string iosRunnerPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../ios"));
        var pubsec_file = Path.Combine(iosRunnerPath, "flutter_unity_widget.podspec");
        var pubsec_text = File.ReadAllText(pubsec_file);

        if (!Regex.IsMatch(pubsec_text, @"\w\.xcconfig(?:[^}]*})+") && !Regex.IsMatch(pubsec_text, @"tar -xvjf UnityFramework.tar.bz2"))
        {
            Regex regex = new Regex(@"\w\.xcconfig(?:[^}]*})+", RegexOptions.Multiline);
            pubsec_text = regex.Replace(pubsec_text, @"
	spec.xcconfig = {
        'FRAMEWORK_SEARCH_PATHS' => '""${PODS_ROOT}/../.symlinks/plugins/flutter_unity_widget/ios"" ""${PODS_ROOT}/../.symlinks/flutter/ios-release"" ""${PODS_CONFIGURATION_BUILD_DIR}""',
        'OTHER_LDFLAGS' => '$(inherited) -framework UnityFramework \${PODS_LIBRARIES}'
    }

    spec.vendored_frameworks = ""UnityFramework.framework""
			");
            File.WriteAllText(pubsec_file, pubsec_text);
        }
    }

    static async void buildArchive()
    {
        string framework = "UnityFramework";
        string xcproj_name = iosExportPluginPath + "/Unity-iPhone.xcworkspace";
        string scheme_name = $"{framework}";
        string project_dir = iosExportPluginPath;
        string buildPath = iosExportPluginPath + "/build";
        string framework_name_with_ext = $"{framework}.framework";
        string iosRunnerPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../ios/"));
        string framePath = Path.GetFullPath(Path.Combine(iosRunnerPath, $"{framework}"));
        string ios_archive_dir = "Release-iphoneos-archive";
        string ios_universal_dir = "Release-universal-iOS";
        string ios_archive_framework_path = $"{buildPath}/{ios_archive_dir}/Products/Library/Frameworks/{framework_name_with_ext}";
        string dsym_name_with_ext = $"{framework_name_with_ext}.dSYM";

        try
        {
            Debug.Log("### Cleaning up after old builds");
            await $" - rf {framePath}.tar.bz2".Bash("rm");
            await $" - rf {buildPath}".Bash("rm");
        }
        catch (Exception)
        {
            // Debug.Log(e);
        }


        try
        {
            Debug.Log("### BUILDING FOR iOS");
            Debug.Log("### Building for device (Archive)");
            await $"archive -workspace {xcproj_name} -scheme {scheme_name} - sdk iphoneos -archivePath {buildPath}/Release-iphoneos.xcarchive ENABLE_BITCODE=NO |xcpretty".Bash("xcodebuild");

            Debug.Log("### Copying framework files");
            await $" {buildPath}/Release-iphoneos.xcarchive {buildPath}/{ios_archive_dir}".Bash("mv");
            await $" -p {buildPath}/{ios_universal_dir}".Bash("mkdir");

            Debug.Log("### Copying framework files");
            await $" -RL {ios_archive_framework_path} {buildPath}/{ios_universal_dir}/{framework_name_with_ext}".Bash("cp");
            await $" -RL {ios_archive_framework_path}/{dsym_name_with_ext} {buildPath}/{ios_universal_dir}/{dsym_name_with_ext}".Bash("cp");

            Debug.Log("### Copying iOS files into zip directory");
            string target_dir = iosRunnerPath;
            await $" -cjvf {target_dir}/{framework}.tar.bz2 {buildPath}/{ios_universal_dir}/{framework_name_with_ext} {buildPath}/{ios_universal_dir}/{dsym_name_with_ext}".Bash("tar");

            Debug.Log("### Zipped resulting framework and dSYM to $TAR_DIR/$FRAMEWORK.tar.bz2");
        }
        catch (Exception e)
        {
            Debug.Log(e);
        }


    }
}`

**Comment by BlickwinkelTour** [comment]
Oh I am Sorry, I hardcoded my project folder . you might need to change it.
`public static void DoBuildAndroid(String buildPath, bool isPlugin)
    {
        if (Directory.Exists(Build.buildPath))
            Directory.Delete(Build.buildPath, true);
        Directory.CreateDirectory("E:/Blickwinkel_Tour/Unity_Projects/Remote_Client/Blickwinkel_Remote/Builds/unityLibrary"); //Change this!

        if (Directory.Exists(androidExportPath))
            Directory.Delete(androidExportPath, true);

        EditorUserBuildSettings.androidBuildSystem = AndroidBuildSystem.Gradle;

        var options = BuildOptions.AllowDebugging;
        //var options = BuildOptions.AcceptExternalModificationsToPlayer;
        var report = BuildPipeline.BuildPlayer(
            GetEnabledScenes(),
            Build.apkPath,
            BuildTarget.Android,
            options
        );`

**Comment by BlickwinkelTour** [comment]
Damn int, can somebody explain how to use this github codesnippe t thing correctly ? :D

**Comment by mathtasatlime** [comment]
> I had this same issue but the fix was super easy.
> 
> This comment fixed it for me: [#234 (comment)](https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249)

It fixed it for me as well! Thank you a lot 👍

**Comment by mathtasatlime** [comment]
> I had this same issue but the fix was super easy.
> 
> This comment fixed it for me: [#234 (comment)](https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249)

btw, do I have to change to BuildOptions.None for a release build ?

**Comment by ksroo** [comment]
work with me 
[Build.cs.txt](https://github.com/juicycleff/flutter-unity-view-widget/files/6553107/Build.cs.txt)

**Comment by dibenedetto** [comment]
> Hi, it is a simple path error in the build.cs script. It tries to make a path in the apk file. just overwrite the build.cs with this:
> [Build.cs.txt](https://github.com/juicycleff/flutter-unity-view-widget/files/5924871/Build.cs.txt)

i suspect there is still an error where resources are copied:
`Copy(Path.Combine(apkPath + "/launcher/src/main/res"), Path.Combine(androidExportPath, "src/main/res"));`

looking at the unity project directory, the subtree "/launcher/src/main/res" is inside <unity_project>/Temp/gradleOut/

so shouldn't we replace the apkPath here with the aforementioned gradleOut subfolder?
