### ISSUE TITLE
Callbacks failed on default unity URP Project

### ISSUE THREAD

**Issue by invlabz** [juicycleff/flutter-unity-view-widget#302]
**Describe the bug**
I have create default unity URP project. In the default scene created a empty gameobject and added UnityMessageManager.cs as component. Then performed export android.

In flutter screen create UnityWidget with onUnityCreated and onUnitySceneLoaded callbacks. When I ran it was crashing. Then I added isARScene to true. Ran it, now app shows the scene but no callbacks are called.

W/MessageQueue(16518): 	at android.hardware.display.IDisplayManagerCallback$Stub.onTransact(IDisplayManagerCallback.java:84)
W/MessageQueue(16518): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
W/MessageQueue(16518): 	at android.os.Binder.execTransact(Binder.java:994)
I/SwappyDisplayManager(16518): Terminating looper thread
I/SwappyDisplayManager(16518): Starting looper thread
V/SwappyVk(16518): SwappyVk initialized for VkDevice 0x741464f750 using VK_GOOGLE_display_timing on Android
I/SwappyVk(16518): Returning refresh duration of 16666666 nsec (approx 60.000002 Hz)
3
E/SwappyVk(16518): Failed to wait for fence 2
D/        (16518): PlayerBase::stop() from IPlayer
D/AudioTrack(16518): stop(2507): called with 6442560 frames delivered
Lost connection to device.
Exited (sigterm)

**Comment by juicycleff** [comment]
Fixed in v4
