### ISSUE TITLE
No app, only grayish area when downloaded from google play

### ISSUE THREAD

**Issue by WouterVandenputte** [juicycleff/flutter-unity-view-widget#303]
**Describe the bug**
Ok so this is really difficult to reproduce so hear me out.

When running my app through my IDE (Android Studio) on my physical devices, the plugin works just fine.
But when building a signed bundle and uploading it to Google Play and the installing it from Google Play, all I get is a grayish area instead of the app I developped. I removed any other plugin and did a binary search and deducted the problem to be this specific plugin.

Now, this is ONLY when downloading it from Google Play. Running it directly from Android Studio gives no problem.

**Screenshots**
![Screenshot_20210121-220054](https://user-images.githubusercontent.com/23052815/105412200-adde1680-5c34-11eb-85d4-980a1fdc3a57.png)

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - Devices: both my Huawei Nova smartphone as my Samsung Galaxy Tab 2018 tablet.

**Comment by ruslanou** [comment]
i have the same issue. My app already in google play. But when downloaded, it stuck when first open

**Comment by WouterVandenputte** [comment]
> i have the same issue. My app already in google play. But when downloaded, it stuck when first open

Shalle we make a deal that if one of us can find a working solution, we also tell the other one?

**Comment by ruslanou** [comment]
Finally i can solved this problem. Just add this 2 line code in your android/unityLibrary/proguard-unity.txt

-keep class com.unity3d.plugin.* { *; }
-keep class com.xraph.plugins.flutterunitywidget.UnityUtils { *; }

**Comment by WouterVandenputte** [comment]
> Finally i can solved this issue. Just add this 2 line code in your android/unityLibrary/proguard-unity.txt
> 
> -keep class com.unity3d.plugin.* { *; }
> -keep class com.xraph.plugins.flutterunitywidget.UnityUtils { *; }

Awesome that you found a solution! I also tried it by building it, publishing it to my internal testers (being only myself) and then downloading it on 2 devices. I howevre encountered the problem that it finally works on my tablet (Samsung galaxy tab 2018) (thanks to you!) but it still remains gray on my (older) Huawei Nova so I do advice you caution when rolling out your app to the general public as it seems that the problem might still be present on certain devices

**Comment by ruslanou** [comment]
Glad to hear that! Btw when in unity, Are you using ARCore or ARFoundation? In my device is running smoothly just like in debug mode. Btw i'm using samsung s10 and samsung a51

**Comment by WouterVandenputte** [comment]
> Glad to hear that! Btw when in unity, Are you using ARCore or ARFoundation? In my device is running smoothly just like in debug mode. Btw i'm using samsung s10 and samsung a51

I am not using AR actually. I just wanted to use it for the 3D part.
If you want, you can give me the pacakge name of your app and then I will install it on my Huawei Nova (on which my app is still gray) and I'll let you know if your app works on that. That might give you some more comfort to know that it works on other devices too.

**Comment by WouterVandenputte** [comment]
I finally managed to fix it by adding these two lines in gradle.properties

android.enableR8.libraries=false
android.enableR8=false
