### ISSUE TITLE
Flutter to Unity Communication: The method 'postMessage' was called on null.

### ISSUE THREAD

**Issue by BlickwinkelTour** [juicycleff/flutter-unity-view-widget#313]
Issue:

When calling `_unityWidgetController.postMessage(args)`, it logs an Exception saying:
```
The method 'postMessage' was called on null.
Receiver: null
Tried calling: postMessage("BlickwinkelBehaviour", "TheRemotewasPressed", "02_Kongress_01.jpg")
```
Behaviour:
OnUnityCreated shoud bind a controller to `this._unityWidgetController`, 
but when checking the content of the __unityWidgetController right before the method-call, it logs it´s content as null.

Steps taken to solve the issue:

My flutter project is successfully loading the unity player and showing my Unity app.

I added `-keep class com.xraph.plugins.** {*;}` to proguard as suggested for UnityMessaging
(I do not understand the relevance of steps 4. and 5. from the documentation though)

I added GameManager in Unity, which is loading the UnityMessageManager.cs script, just like in the DemoApp
But Unity throws an exception regarding that script: 
`UnityException: Internal_CreateGameObject is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'UnityMessageManager' on game object 'GameManager'.`

I do not need any AR functionality.

I could not build the DemoApp in Unity 2019.4.20lts. The build.cs script is not working correctly.

My own App built sucessfully, but not until I altered the Buid-script a bit, becaus it was throwing path errors.

The dependency injections in the gradle files should be setup correctly, as I can start the Unity player from Flutter.

I do not know what else to do now. I hope someone can help.

Thank you!

Rene

Unity: Unity 2019.4.20lts
Unity Flutter Widget: 3.0.3
Android Platform: SDK 29

**Comment by juicycleff** [comment]
@BlickwinkelTour if the controller was created, that shouldn't be null. You can try the latest alpha release

**Comment by jain-aayush1123** [comment]
you need to call the method after onUnityCreated has completed as only after that the _unityWidgetController is initialised

**Comment by BlickwinkelTour** [comment]
Hi, 
I´d like to give an update to this issue.

Thanks @jain-aayush1123  for pointing me to it, although this was only part of the issue:

My App has a ScreenView Toggle, which means  I am toggling the UnityView Widget in a Stack above and below my Flutter UI.
At first I am drawing the UI and Unity is loading in the background. Then I activate Unity by toggling the Unity screen on top of the UI. But this means I am redrawing the whole state of my Widget tree, thus redrawing the Unity class aswell. At this point, probably a new controller is created. I am not sure what then happens, but the controller instance is Null at this point.
I bypassed this behaviour for testing and now it runs as it should.

So here´s the question @juicycleff :

Is there any way to keep the controller binding even if we redraw the unity widget? Has someone experience with that? Can we store that controller in a Provider-like helper class? Otherwise we cannot change the Unity window during the whole lifetime of the app, as there is no way to redraw the Unity widget without losing controll over the messaging system.

Thanks for helping,

best

**Comment by juicycleff** [comment]
@BlickwinkelTour except you really need to, there's no use storing unity controller in a provider, because unity session will be thesame throughout the app runtime and your last action on a scene will always be thesame whether or not you destroy unity widget

**Comment by BlickwinkelTour** [comment]
@juicycleff yes I noticed that, which is good. But when temporarily "closing" the Unity window, the player activity is turning into kind of "sleep mode" in the background. For me, the whole issue it is not that big deal, I need to keep Unity active and running all the time anyway, as I have Mirror Networking running and if I send the Unity session in the background mode, I would loose server connection. 
But I don´t quite understand how to be able to do a message send after redrawing. What am I missing?
thanks

**Comment by juicycleff** [comment]
@BlickwinkelTour I see, I will make a new release today to optionally disable pause unity as that is the current case

**Comment by juicycleff** [comment]
@BlickwinkelTour one way to solve this is to have a unity widget running in every scene but make it invisible and push it out of the interactive scene. That will solve your problem

**Comment by omarsalem15** [comment]
> @BlickwinkelTour one way to solve this is to have a unity widget running in every scene but make it invisible and push it out of the interactive scene. That will solve your problem

how to make it invisible
