### ISSUE TITLE
Android 'unityStreamingAssets' error in V4

### ISSUE THREAD

**Issue by OGmetamonkey** [juicycleff/flutter-unity-view-widget#319]
**Describe the bug**
Attempted to upgrade flutter unity widget to V4. Flutter build fails with the following message:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/me/project/android/unityLibrary/build.gradle' line: 35
> 
> * What went wrong:
> A problem occurred evaluating project ':unityLibrary'.
> > Could not get unknown property 'unityStreamingAssets' for object of type com.android.build.gradle.internal.dsl.AaptOptions.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> Exception: Gradle task assembleDebug failed with exit code 1
> 

**To Reproduce**
1. Set up project as shown in [V4 Readme](https://github.com/juicycleff/flutter-unity-view-widget/tree/v4)
2. Export unity library from unity
3. Attempt to build android flutter project from Android Studio or VS Code

**Expected behavior**
Expected app to build

**Comment by juicycleff** [comment]
@OGmetamonkey there were some bugs with Android. Fixed now. You can try it out

**Comment by OGmetamonkey** [comment]
@juicycleff , I did a complete re-build to test the new V4. Same issue.

**Comment by juicycleff** [comment]
@OGmetamonkey which version of unity are you using plus you need to look at this file "Users/me/project/android/unityLibrary/build.gradle' line: 35"

**Comment by OGmetamonkey** [comment]
@juicycleff Yeah I'm looking at it but it doesn't make much send to me. Unity version 2020.2.3f1.

Here's the code snippet:

>  aaptOptions {
**(line 35) >         noCompress = ['.ress', '.resource', '.obb'] + unityStreamingAssets.tokenize(', ')**
>         ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
>     }

**Comment by juicycleff** [comment]
@OGmetamonkey please down grade, the package does not yet support that version of unity

**Comment by juicycleff** [comment]
Or you have to manually fix the Gradle issue

**Comment by OGmetamonkey** [comment]
I tried Unity version 2019.3.14f1 (which is what I usually do for my working Android build that used version 0.1.6+8 of this widget) with V4 and got a new issue that seems unrelated, but that I didn't previously get. I also tried unity version 2019.4.20f1 and kept getting different issues that i didn't previously get. Will keep trying. @juicycleff

**Comment by Hypnotistas** [comment]
Add this line to **gradle.properties** file (not to unityLibrary gradle!):

unityStreamingAssets=.unity3d, google-services-desktop.json, google-services.json, GoogleService-Info.plist

**Comment by OGmetamonkey** [comment]
Sorry for late response. This did not work for me.

**Comment by jvankooo** [comment]
> Sorry for late response. This did not work for me.

`unityStreamingAssets=.unity3d, google-services-desktop.json, google-services.json, GoogleService-Info.plist`

This line needs to be added to the **gradel.properties** file ( in the **native application root folder** ).
