### ISSUE TITLE
Taps with XR Interaction Toolkit (again)

### ISSUE THREAD

**Issue by avasich** [juicycleff/flutter-unity-view-widget#320]
**Describe the bug**
This issue has been mentioned at least twice by now (#243 and #118), but not exactly resolved. On android, with XR Interaction Toolkit, taps need to be repeated with high frequency to be registered. Other gestures work well. In #243 the issue was resolved by using more performant device, but, firstly, I experience this issue on xiaomi mi 9t, and I'm not sure it's especially slow, and secondly, unity widget from [this package](https://pub.dev/packages/flutter_unity) doesn't have this issue on my device, so in principle it is possible. And, of course, it would be great if the widget predictably worked on a wide range of devices.

**To Reproduce**
1. Create simple project with flutter-unity-view-widget
2. And build it for android, for example, with [this xr interaction toolkit example project](https://github.com/Unity-Technologies/XR-Interaction-Toolkit-Examples/tree/master/AR)

**Expected behavior**
The same as with standalone build: every single tap on the plane is registered and prefab is instantiated.

 - Device: xiaomi mi 9t
 - OS: android 11

**Comment by juicycleff** [comment]
@avasich please use v4.0.0-alpha-2

**Comment by avasich** [comment]
I used this version, yes.

I've made a [minimal working example](https://github.com/avasich/fuw_with_xr_interactions), you may take a look if you have time. The example is build with 2020.1.17f1, but I've also tried 2019.4.20f1.

**Comment by juicycleff** [comment]
@avasich I've seen it. There's little I can do at the moment on Android as it all depends on unity as a library. To take full advantage of unity bug fixes, try upgrading your unity project to use latest unity bug fixes
