### ISSUE TITLE
Unity 2019.4.16f with ARFoundation 2.1.16 works, 2020.1 with ARFoundation 3 doesnt: NDK is not installed

### ISSUE THREAD

**Issue by gisinator** [juicycleff/flutter-unity-view-widget#322]
First of all, big thumbs up for this awesome plugin. I really appreciate the time and efforts you guys put into this. Thank you all!

Now, after struggling a little bit with integrating Unity with ARFoundation into Flutter I finally made it work yesterday. The missing part was Upgrading Gradle in Android Studio and I posted my solution [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/310#issuecomment-782585847).

Problem is: This solution only works with Unity 2019.4 and ARFoundation 2.1.16. When I do the exact same steps using Unity 2020.1 (or later, I tried a couple) and ARFoundation 3 (or 4), I get the following error when building in AndroidStudio:

_FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\XYZ\AndroidStudioProjects\flun\android\unityLibrary\build.gradle' line: 66
* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> NDK is not installed_

Am I making a mistake? It would be awesome if the plugin would support ARFoundation 4.1, since occlusion and therefor an even more realistic AR experience only started in those newer versions of ARFoundation.

I am using Windows 10, Unity 2019.4.16f (which is working) and 2020er versions of Unity, which are not working.
My AndroidStudio version is 4.1.2

In case this is not a plugin error, but an error on my side, I would appreciate any help :)

Thank you

**Comment by avasich** [comment]
You probably bumped gradle version too high. I have the save issue with gradle plugin v4+.

Flutter (stable channel) creates project with gradle plugin 3.5.0 and gradle 5.6.2. Updating plugin up to 3.6.4 and gradle to 5.6.4 was enough for me to make ARFoundation work.

**Comment by gisinator** [comment]
Thank you, sir, for your response. I'll try a Gradle version between the one I had had before and the one I switched to, would be nice if that was the solution. I'll post the result once I get back to work.

**Comment by gisinator** [comment]
I just tried again with Unity 2020.1.17f and ARFoundation 3.1.10 and then on AndroidStudio side, I use:

distributionUrl = https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
classpath 'com.android.tools.build:gradle:3.6.4'

So, the exact same versions as you did I guess. But still, I get the same error when trying to build in AndroidStudio:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\XYZ\AndroidStudioProjects\flun\android\unityLibrary\build.gradle' line: 66

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> NDK is not installed

Any other ideas? :)

**Comment by gisinator** [comment]
Update: It is now working with 2020.1.17f and ARFoundation 3.1.10. I should have just done what the error told me to do and install the NDK :D 

So, in AndroidStudio I went to "Tools/SDKManager", then opened "SDK Tools" tab. Here, the "NDK (side by side)" wasnt installed, so I installed it and tried building again. New error:

"NDK version is not matching, version xyz is required".

So, again in "SDK Tools" tab, I checked "Show package details" in the bottom and got all available NDK versions listed. I picked the one that was asked for, removed the wrong one, tried again to build and:

Success :)

**Comment by avasich** [comment]
Interesting! I've tried to specify the path to different ndk locations, including the one provided with unity, and was able to move past this error, but in the end the build always failed for some reason when I was using gradle plugin 4.x.x

**Comment by alexanderameye** [comment]
> "NDK version is not matching, version xyz is required".

What NDK version did you end up using? I didn't get the 'wrong version' error but instead got this.

`clang++: error: invalid linker name in argument '-fuse-ld=gold.exe'`

Which seems to be related to NDK, so maybe I should get the same version as you? My Unity/AR Foundation versions match as well.

**Comment by gisinator** [comment]
glad to hear you  made it. My NDK version in Android Studio was different when using ARFoundation 3, now that I upgraded to ARFoundation 4.1.5 I am running NDK 21.0.6113669

I even tried to make Unity 2020.2 work, but no chance. I get the "missing libmain.so" error and there seem to be people all over the place seeing this error after 2020.2 upgrade. So, for now I'm fine with 2020.1 with ARFoundation 4.1.15

**Comment by juicycleff** [comment]
@avasich this `NDK is not installed`  has nothing to do with the plugin and you should manage your unity project yourself. I advise you to ask this in the unity forum. So I will close this

**Comment by kafiarifin** [comment]
Hi @gisinator try to add ndk.dir in your android/local.properties

```
dk.dir=path_to_sdk/Android/sdk
ndk.dir=path_to_ndk/Android/sdk/ndk/your_ndk_version_folder
flutter.sdk=path_to_flutter_sdk/fvm/versions/2.5.0
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
```
