### ISSUE TITLE
Communication from Unity to Flutter not working on iOS

### ISSUE THREAD

**Issue by ChrisLmis** [juicycleff/flutter-unity-view-widget#325]
**Describe the bug**
I am trying to send a message from Unity to Flutter but somehow nothing happens. No text appears in the console and no error occurs. I am using the flutter-unity-view-widget without any changes. I followed every step of the tutorial and everything is working as expected. Only the communication from unity to Flutter doesnt work. The communication from Flutter to Unity works as expected.

**Expected behavior**
"Received message from unity: hey man" printed in the console.

**Desktop (please complete the following information):**
 - OS: [MacOS 11.2.1]
 - Browser [Mozilla Firefox]

**Smartphone (please complete the following information):**
 - Device: [iPad Pro 2. Generation]
 - OS: [e.g. iOS 14.4]
 - Browser [Stock browser]

**Comment by phamtuongvan** [comment]
same with me, just working when build debug or release from xcode to device but not working on archive

**Comment by ChrisLmis** [comment]
It wont even work with a debug build on my end. I havent tried a release build yet

**Comment by juicycleff** [comment]
@ChrisLmis what version of the package are you using?

**Comment by ChrisLmis** [comment]
@juicycleff i am using version 3.0.0

**Comment by gisinator** [comment]
@ChrisLmis try the new 4.0 package:
https://github.com/juicycleff/flutter-unity-view-widget/releases/tag/v4.0.0

I had had trouble with 3.0 as well but 4.0 fixed the issues with messages from Unity to Flutter.

**Comment by ChrisLmis** [comment]
@gisinator The 4.0 package solved the problem for me. Thank you!
