### ISSUE TITLE
Flutter & Unity /lib/arm64/libmain.so not found

### ISSUE THREAD

**Issue by invlabz** [juicycleff/flutter-unity-view-widget#329]
**Describe the bug**

I am trying to build android application using flutter by integrating Unity as native library.

When I run on my real 64 bit device, getting below error.

```
E/Unity   ( 7676): Failed to load 'libmain.so'
E/Unity   ( 7676):
E/Unity   ( 7676): java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/com.invlabz.invlabzapp-mteqoVLiXwj6vIuS6YZwsw==/lib/arm64/libmain.so" not found
E/Unity   ( 7676): Your hardware does not support this application.
```

But the libmain.so is present in arm64-v8i folder.

![image](https://user-images.githubusercontent.com/77716524/109459098-20d47b80-7a84-11eb-82c8-43ce1dab008a.png)

Flutter version

```
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

`Unity version 2020.2.1f1`

How to solve this issue?

Another question: Why app is looking at arm64 folder instead of arm64-v8i folder?

Same issue with armeabi-v7a, searching in arm folder instead of armeabi-v7a folder

```
2021-03-01 11:37:17.694 12703-12703/com.invlabz.invlabzapp E/Unity: Failed to load 'libmain.so'
    
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/com.invlabz.invlabzapp-sFxrcRVFGsIhiYhJWoU6iw==/lib/arm/libmain.so" not found
2021-03-01 11:37:17.694 12703-12703/com.invlabz.invlabzapp E/Unity: Your hardware does not support this application.

```

**Comment by gisinator** [comment]
Downgrade to Unity 2020.1.something
I also had this issue with 2020.2 and googled for many, many other people having this issue with 2020.2

**Comment by invlabz** [comment]
Yes, need work around to this. @juicycleff could you please throw some light on this.

**Comment by invlabz** [comment]
> 
> 
> Downgrade to Unity 2020.1.something
> I also had this issue with 2020.2 and googled for many, many other people having this issue with 2020.2

Did you able solve it by downgrading unity?

**Comment by gisinator** [comment]
> > Downgrade to Unity 2020.1.something
> > I also had this issue with 2020.2 and googled for many, many other people having this issue with 2020.2
> 
> Did you able solve it by downgrading unity?

I did, check [my response here](https://github.com/juicycleff/flutter-unity-view-widget/issues/322#issuecomment-783543085)

**Comment by invlabz** [comment]
@gisinator thanks, it worked by downgrading Unity

**Comment by nmfisher** [comment]
Repeating what I said [here](https://forum.unity.com/threads/app-not-working-on-some-devices-failed-to-load-libmain-so.1031137/?gq=libmain.so), in case it's useful for some people:

This is still an issue with 2020.3.0f1 (also the gradle.properties workaround is not working in my Flutter project either).

EDIT:

Actually adding android:extractNativeLibs="true" to the element in AndroidManifest.xml as a temporary workaround does work with 2020.3.0f1. This might be specific to my version of Gradle (per | Android Developers, this is set to false by default in Android Gradle plugin 3.6.0).

This isn't a long-term solution as Unity should be able to handle loading native libraries without extracting to the filesystem first.

I also confirm this is still present in 2021.1.0b11
