### ISSUE TITLE
Failed to load 'libmain.so'

### ISSUE THREAD

**Issue by DirtyNative** [juicycleff/flutter-unity-view-widget#330]
I spent the last 2 days to get my flutter app running with this unity view. I am now at this point where the unity game builds and the app starts. Now when the UnityView will be displayed, I get an error:

![image](https://user-images.githubusercontent.com/10748827/109855153-3d291180-7c58-11eb-8e2a-bc0a64adfb02.png)

**To Reproduce**
1. Create a new flutter project
2. Create a new Unity Project inside the "unity" folder
3. Setup the android build as described inside the doc
4. Import the .unitypackage
5. Build via the flutter/android menu
6. Implement the UnityView as described inside the docs
7. Run the code

**Expected behavior**
A running flutter app with Unity inside

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Android Emulator, Nexus 6P 
 - OS: Android 10.0+ Api 30

**Comment by DirtyNative** [comment]
Oh forgot to say, that I am using Unity 2019.4.21f1 which is the LTS version

**Comment by gisinator** [comment]
Try running it on an actual device. I also get this message when running in emulator, but it perfectly runs fine on a real device.

**Comment by DirtyNative** [comment]
Jep, you are right, running on a physical android device works.. Is there a way to run in simulator?

**Comment by thassio-vinicius** [comment]
Since version 2019.2, Unity doesn't support the x86 architecture that simulators use. It only supports ARM64 and ARMv7, which means you can only test with real devices.

> Jep, you are right, running on a physical android device works.. Is there a way to run in simulator?

**Comment by DirtyNative** [comment]
I am using the Android 10.0+ x86_64 Image inside the AVD manager. Isn't this a 64 bit version of Android? If yes, I still get the error

**Comment by juicycleff** [comment]
@DirtyNative you should test unity projects preferable with real devices instead of emulators

**Comment by thassio-vinicius** [comment]
@juicycleff is there a situation where the plugin works on simulators? For me personally, it only works on real devices, both on Android and iOS

**Comment by juicycleff** [comment]
@thassio-vinicius in the unity player settings you need to select simulator mode to be able to run on simulator
