### ISSUE TITLE
failed to emit precompiled header

### ISSUE THREAD

**Issue by DirtyNative** [juicycleff/flutter-unity-view-widget#331]
I was importing the lib as described in the docs, but ending with an build error in flutter

`Launching lib/main.dart on iPhone von Daniel in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: UM3UVMPGY5
Xcode build done.                                            5,4s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[20902]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1f66e8188) and ?? (0x1149a02b8). One of the two will be used. Which one is undefined.
    objc[20902]: Class AMSupportURLSession is implemented in both ?? (0x1f66e81d8) and ?? (0x1149a0308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

*Some other warnings*

rror: 'UnityUtils.h' file not found
    #import "UnityUtils.h"
            ^
    1 error generated.
    <unknown>:0: error: failed to emit precompiled header '/Users/dirtynative/Library/Developer/Xcode/DerivedData/Runner-bioenbbzgsbdnpanlyghtbrgehhe/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1BOWT2VFPP1RK-clang_1YV9FR8F1B8Y.pch' for bridging header '/Users/dirtynative/dev/projects/AstroGame/AstroGame/Frontend/apps/astrogame_app/ios/Runner/Runner-Bridging-Header.h'
    2 errors generated.
    <unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: OpenGLES is deprecated. Consider migrating to Metal instead. (in target 'UnityFramework' from project 'Unity-iPhone')
`

**Steps to reproduce:**
- Just follow the tutorial integrating this project to a iOS flutter project

**Desktop:**
 - OS: macOS Big Sur with M1 MacBook

**Smartphone:**
 - Device: iPhone 11

**Comment by ROBYER1** [comment]
How did you fix this?
