### ISSUE TITLE
Unity freezes on splash logo screen IOS

### ISSUE THREAD

**Issue by kingkimohero69** [juicycleff/flutter-unity-view-widget#333]
The error on Xcode was "Failed to initialize subsystem ARKIT-meshing [error 1]",
I made a release ios version before and it was working fine until I improved the UI in unity and made some changes in the flutter main app, then I face this error now when I open unity in flutter.

**Comment by juicycleff** [comment]
@kingkimohero69 from your statement this has nothing to do with the package itself. I suggest you look at your unity project and test it to be working fine
