### ISSUE TITLE
No such module 'flutter_unity_widget' / 'UnityUtils.h' file not found in iOS

### ISSUE THREAD

**Issue by thassio-vinicius** [juicycleff/flutter-unity-view-widget#335]
I'm able to build and export everything as expected in Android, but for iOS I've tried with versions 4.0.0 alpha and 3.0.3 by now, and for both of them, there seems to be an issue with the integration. I'm following every step described in the documentation and double checking over and over again, but I still can't find a way to get rid of this. I've read pretty much all the other issues and couldn't find any similar issue. I'm opening this issue for two different versions because I believe it's the same error. 

For 3.0.3 the error is: "'UnityUtils.h' file not found" in Runner/Runner/Runner-Bridging-Header.h
For 4.0.0 the error is: "No such module 'flutter_unity_widget'" in AppDelegate.swift

Apparently XCode isn't able to access the plugin files for some reason?

I've also tried exporting with Unity 2019.4.14f1 and Unity 2020.1.17f1

Flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```

**Comment by thassio-vinicius** [comment]
I was finally able to fix it. It was some kind of issue with my podfiles. I think I've set them up manually but they're supposed to be created automatically in flutter apps (?). Not sure tbh, I'm very unexperienced with iOS integration. Anyways, here's how I fixed the issue https://github.com/flutter/flutter/issues/67156#issuecomment-703236777

**Comment by dantetwc** [comment]
In case of anyone encounter this after upgrading to 4.0.0 release, try to remove the line 
`#import "UnityUtils.h"` from Runner-Bridging-Header.h as it is no longer needed for this plugin
