### ISSUE TITLE
Unity Project as a submodule

### ISSUE THREAD

**Issue by subzero911** [juicycleff/flutter-unity-view-widget#337]
Is it possible to move Unity Project to the separate repository and link it to the Flutter project as a submodule?
Or to link it via pubspec somehow.
Because it's not cool to make a Unity project as a subfolder. Unity developers can be the separate team, and they don't need the whole Flutter repository.

**Comment by mathtasatlime** [comment]
We managed it by splitting the two projects into two seperate git repos and only one person manages the integration and deployment of flutter and unity

**Comment by subzero911** [comment]
That's cool that you managed to.
But how exactly? What steps to perform?

**Comment by mathtasatlime** [comment]
By using two seperate git repos:

repo1 : flutter app, containing the folder 'unity', which contains
repo2: unity game project.

the games folder is ignored in repo1

**Comment by subzero911** [comment]
Do you mean you put it into .gitignore? What for?
I tried to add repo2 as a submodule, and it looks like a link to repo2 in the GitLab
![image](https://user-images.githubusercontent.com/12999702/110636806-c0e57f80-81bd-11eb-90c9-a387490f79a0.png)
![image](https://user-images.githubusercontent.com/12999702/110636656-93003b00-81bd-11eb-83f3-5118a87e2486.png)
So it looks adequate already.

**Comment by subzero911** [comment]
@thassio-vinicius is this structure correct?
![image](https://user-images.githubusercontent.com/12999702/110700631-3aeb2800-8201-11eb-998c-8bee22a567ef.png)

**Comment by thassio-vinicius** [comment]
Yes, that's exactly how I'm doing it. If you feel like you should test it just to be safe, you can commit and push something to your unity repo, run `git submodule init` + `git submodule update` and export to see your changes.

> @thassio-vinicius is this structure correct? (you-app is my Flutter project)
> ![image](https://user-images.githubusercontent.com/12999702/110700631-3aeb2800-8201-11eb-998c-8bee22a567ef.png)

**Comment by juicycleff** [comment]
@subzero911 this can be solved by just using git submodules, so I'm closing this issue
