### ISSUE TITLE
issue in v 4.0.0 on iOS

### ISSUE THREAD

**Issue by bashar963** [juicycleff/flutter-unity-view-widget#340]
when opening the unity page in iOS the app crashed with this error 

`Thread 1: EXC_BAD_ACCESS (code=1, address=0x60)`

pointing to the line code `_mainDisplay.surface->allowScreenshot = 1;` line 102 in `UnityAppController+Rendering.mm` file 

and from what I see in the debugger 

`_mainDisplay` is `nil` and `_unityView` is `nil` also

**Comment by nmfisher** [comment]
Looks like the FlutterUnityIntegration scripts have changed and the old (pre-4.0.0) version(s) aren't compatible with the new version.

Replace the contents of your Assets/FlutterUnityIntegration folder with the current version  https://github.com/juicycleff/flutter-unity-view-widget/tree/master/example/unity/DemoApp/Assets/FlutterUnityIntegration and it should be working fine. Also take care to reimplement the fixes in #234 if they're relevant to you (which I suspect they are).

**Comment by bashar963** [comment]
Thank you, yes indeed I replaced it with this https://github.com/juicycleff/flutter-unity-view-widget/tree/master/example/unity/DemoApp/Assets/FlutterUnityIntegration and all works fine now
