### ISSUE TITLE
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.

### ISSUE THREAD

**Issue by iagognunes** [juicycleff/flutter-unity-view-widget#346]
I don't know what are causing this error.

Full console error:

Note: C:\Users\Iago\Documents\ProjetosLocais\teste_plugin_android\android\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\Users\Iago\Documents\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-4.0.1+1\android\src\main\kotlin\com\xraph\plugin\flutter_unity_widget\FlutterUnityWidgetPlugin.kt: (95, 13): Class 'ProxyLifecycleProvider' is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: C:\Users\Iago\Documents\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-4.0.1+1\android\src\main\kotlin\com\xraph\plugin\flutter_unity_widget\FlutterUnityWidgetPlugin.kt: (104, 9): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by teipeps** [comment]
Same error

**Comment by xcxooxl** [comment]
https://github.com/juicycleff/flutter-unity-view-widget/pull/356
hopefully will solve it.

**Comment by iagognunes** [comment]
Thanks so much! It's working now.
