### ISSUE TITLE
V4 Unity Package causing generic XCode Archive

### ISSUE THREAD

**Issue by dantetwc** [juicycleff/flutter-unity-view-widget#349]
Hi, just upgraded to the v4 release and trying to upload it to testflight. When I try to archive the app, XCode will generate a generic archive instead of iOS app archive. The reason for this is because it also exports the unity framework in the product directory. 
After reading the XCodePostBuild.cs, I found the culprit of this is following line
` pbx.SetBuildProperty(targetGuid, "SKIP_INSTALL", "NO");`

After modifying to YES, everything runs fine.

**Comment by sundong212** [comment]
Same here. Not sure if the modification influence anything.

**Comment by mathtasatlime** [comment]
I changed this parameter manually to YES for Unity and it worked.

**Comment by timbotimbo** [comment]
Closing this as outdated, as this was fixed in later unitpackages.
