### ISSUE TITLE
Android build error when update to 4.0.1

### ISSUE THREAD

**Issue by guoguoguilai** [juicycleff/flutter-unity-view-widget#350]
The error message is point to 
FlutterUnityWidgetPlugin.registerWith(registry.registrarFor("com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetPlugin"));

I am using flutter 1.22.2, Unity2019.4.14f1.

**Comment by juicycleff** [comment]
@guoguoguilai cam you share your error message

**Comment by guoguoguilai** [comment]
Sorry for the late reply.

![image](https://user-images.githubusercontent.com/47267017/115207659-5f0a2500-a12e-11eb-9ac9-d5b6d7048f81.png)

**Comment by guoguoguilai** [comment]
I switch the package to v4.1.0, and still have the issue.

**Comment by guoguoguilai** [comment]
Temporary solution is delete the section which is specific to Flutter in [here](https://github.com/juicycleff/flutter-unity-view-widget/blob/4b70c8a968d8176126337ca0f6aaf5feee66a617/pubspec.yaml#L35).
```
# The following section is specific to Flutter.
# flutter: 
#   # This section identifies this Flutter project as a plugin project.
#   # The 'pluginClass' and Android 'package' identifiers should not ordinarily
#   # be modified. They are used by the tooling to maintain consistency when
#   # adding or updating assets for this project.
#   plugin:
#     platforms:
#       android:
#         package: com.xraph.plugin.flutter_unity_widget
#         pluginClass: FlutterUnityWidgetPlugin
#       ios:
#         pluginClass: FlutterUnityWidgetPlugin
```
