### ISSUE TITLE
Pushing and popping a page doesn't work. 

### ISSUE THREAD

**Issue by cmd-dev** [juicycleff/flutter-unity-view-widget#351]
Whenever I push another page or pop the current one containing the unity widget the Unity Widget is still rendered on top while the rest of the widgets are loaded underneath. How to fix this?

**Comment by juicycleff** [comment]
@cmd-dev , could you describe your device and package version

**Comment by cmd-dev** [comment]
Got fixed by updating to the latest package.

**Comment by MaxymShtoyko** [comment]
@juicycleff @cmd-dev  did you manage to find any solutions?

**Comment by MaxymShtoyko** [comment]
@juicycleff did you manage to find any solutions?
