### ISSUE TITLE
Null-Safety

### ISSUE THREAD

**Issue by funwithflutter** [juicycleff/flutter-unity-view-widget#352]
Amazing package and thanks for all of the work @juicycleff 

When can we expect null-safety . All of the dependencies for this package are now null safe, so should be an easy transition with the dart migrate tool.

This video is really helpful, showing how to use the migrate tool: https://www.youtube.com/watch?v=bvq7wbn4VAA

Also happy to contribute and make a pull request for a null-safe version.

**Comment by juicycleff** [comment]
@funwithflutter thank you. Null safe version will be out in the next release, I haD thought about it but needed version4 to be stable. Thanks for being this up. Next weekend we should have bull safety

**Comment by jaboyc** [comment]
@juicycleff When is the null-safety update coming? As I have been migrating my packages to null-safe versions, I noticed that flutter_unity_widget is dependent on stream_transform 1.2.0 but most other null-safe packages use stream_transform 2.0.0, so I can't progress with my project until flutter_unity_widget is updated to null-safety. Thank you for your time and energy into this amazing package!

**Comment by CLD1994** [comment]
@juicycleff permission_handler >=6.1.1 requires plugin_platform_interface ^2.0.0.
flutter_unity_widget >=4.0.0-alpha.1 depends on plugin_platform_interface ^1.0.3
flutter_unity_widget ^4.0.1 and permission_handler ^6.1.1, version solving failed.

**Comment by subzero911** [comment]
You said you published null-safe version, but there's no null-safe version on pub.dev (it is not marked with "null-safety" label and no info about null-safety in the changelog).
