### ISSUE TITLE
Export to iOS fail in Unity 2020.3.0f1 : The build target does not support build appending.

### ISSUE THREAD

**Issue by Jomaazz** [juicycleff/flutter-unity-view-widget#355]
When I try to export to iOS in unity 2020.3.0f1 I get this error : InvalidOperationException: The build target does not support build appending.

**Comment by mathtasatlime** [comment]
Answer: [#234](https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249)

**Comment by dawiddszewczyk** [comment]
We recommend to work with Unity 2021.3.4f1 and fuw-2022.1.1 package and update Flutter Unity Widget version.
