### ISSUE TITLE
Exporting Azure Spatial Anchors from Unity to Flutter.

### ISSUE THREAD

**Issue by git-radiusmedia** [juicycleff/flutter-unity-view-widget#359]
Hey guys im trying to implement unity through flutter using azure cloud anchors.

After trying to apply azure spatial anchors to flutter through unity the problem occurs that when you create/start the azure service it gets stuck at the processing part. In the debug it says the following:
Unable to find azurespatialanchorsndk
E/Unity (31820): DllNotFoundException: Unable to load DLL 'azurespatialanchorsndk': The specified module could not be found.
note this error only occurs when trying to launch from within flutter. When launching directly from unity it runs as it should

**Comment by juicycleff** [comment]
@git-radiusmedia you need to manually setup up azure libs in flutter android and ios
