### ISSUE TITLE
Build error on iOS

### ISSUE THREAD

**Issue by akramaskar** [juicycleff/flutter-unity-view-widget#363]
`error: my/dir/Build/Products/Debug-iphoneos/flutterUnityDemo.app: No such file or directory (in target 'Runner' from project 'Runner')
`

I keep getting this error when building the App on iOS. I have done all the steps given in the README other than the last step. I can't find App.framework and Flutter.framework

<img width="806" alt="Bildschirmfoto 2021-03-25 um 20 37 18" src="https://user-images.githubusercontent.com/26750512/112533405-33538380-8daa-11eb-9009-f718e4426dfb.png">

**Comment by dinesh4official** [comment]
@akramaskar , I don't think it is required because i can able to build my application without these frameworks. 

**Pods_Runner.framework** and **UnityFramework.framework** are required.

**Comment by akramaskar** [comment]
I forgot the exact reason why it works this way, but I ended up forking the repository and do some modifications on my own. This version here works: [https://github.com/akramaskar/flutter-unity-widget--nullsafe](https://github.com/akramaskar/flutter-unity-widget--nullsafe)

**Comment by Horum-dev** [comment]
<img width="844" alt="Снимок экрана 2022-04-14 в 13 56 30" src="https://user-images.githubusercontent.com/67152395/163377725-edde915c-b555-4dc2-b35b-8b09110b516e.png">
Found `ValtaB2B.app` here! Delete it and everything works, I used this fork

> I forgot the exact reason why it works this way, but I ended up forking the repository and do some modifications on my own. This version here works: https://github.com/akramaskar/flutter-unity-widget--nullsafe

**Comment by dawiddszewczyk** [comment]
To resolve this error you have to click on Data directory :
<img width="267" alt="Zrzut ekranu 2022-07-16 o 23 02 54" src="https://user-images.githubusercontent.com/58904662/179371842-e51175e2-6b33-41e9-a6be-4962c6d5482e.png">

Next, set target ship like below:

<img width="267" alt="Zrzut ekranu 2022-07-16 o 23 04 18" src="https://user-images.githubusercontent.com/58904662/179371865-3f1484d7-a8b6-4985-a6f6-7a3b2dc4ef39.png">

(Sometimes Xcode has problem with recognize UnityFramework then only what you have to do its reimport package to unity project again and do this steps again)
