### ISSUE TITLE
Is there support for lazy loading?

### ISSUE THREAD

**Issue by JovanShandro** [juicycleff/flutter-unity-view-widget#366]
Is lazy loading possible for this widget? If yes how can it be done? I am trying to build an app in which you see the unity screen only after clicking a button and was curious if it was possible to start loading the project only once the button is pressed.

Thank you!

**Comment by juicycleff** [comment]
I'm sorry unity will load once you add the unity widget to the tree

**Comment by juicycleff** [comment]
And there are no panned support for lazy loading internally for now
