### ISSUE TITLE
App crashes when open Unity - iOS

### ISSUE THREAD

**Issue by vipatronon** [juicycleff/flutter-unity-view-widget#368]
Hey
Whenever I try to open Unity from flutter the app immediately crashes, with no further messages on the console... :(
I'm using flutter_unity_widget: ^4.0.1+1 and the v4 in unity's plugin as well

I've done the Xcode setup a million times, but I still couldn't make it work 

![image](https://user-images.githubusercontent.com/9328789/112920529-85184880-90df-11eb-8b5c-86d53c9a0ea8.png)

![image](https://user-images.githubusercontent.com/9328789/112920559-96615500-90df-11eb-962b-720951b4cb91.png)

AppDelegate.swift file is the same as the [example](https://pub.dev/packages/flutter_unity_widget)

Xcode error
![image](https://user-images.githubusercontent.com/9328789/112921008-6ebebc80-90e0-11eb-8d11-b073b219fc3a.png)

Any help is welcome

Thx!

**Comment by dinesh4official** [comment]
@vipatronon ,

I'm using the same package i.e.**flutter_unity_widget: ^4.0.1+1** and the **v4** in unity's plugin. I can able to build my application in iPhone. 

Unity Editor : **2019.4.22**

From the screenshots, I assume that you can build the application and while deploying the application, you are facing this issue. Can you please try it in a simple application?

Please give a try to open the project from 'Runner.xcworkspace' instead 'Runner.xcodeproj' in XCode. Hope you can find the error log.

**Comment by TudorAxinte** [comment]
I've been getting the exact same issue for a week, on 2 different unity and flutter projects, following the tutorial and all the suggested fixes with no luck. Full error code:

`Built from '2019.4/staging' branch, Version '2019.4.9f1 (50fe8a171dd9)', Build type 'Release', Scripting Backend 'il2cpp'
-> applicationDidFinishLaunching()


Setting UIViewControllerBasedStatusBarAppearance to NO is no longer supported.
Apple actively discourages that, and all application-wide methods of changing status bar appearance are deprecated


-> applicationWillEnterForeground()
-> applicationDidBecomeActive()
flutter: *********************************************
flutter: ** flutter unity controller setup complete **
flutter: *********************************************
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:45:12: warning: unused variable '_0_prevRect'
    float4 _0_prevRect = float4(-1.0, -1.0, -1.0, -1.0);
           ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:35:12: warning: unused variable '_tmp_1_inPosition'
    float2 _tmp_1_inPosition = (_globals._anonInterface0->ulocalMatrix_Stage0 * float3(_in.inPosition, 1.0)).xy;
           ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:40:12: warning: unused variable '_0_prevRect'
    float4 _0_prevRect = float4(-1.0, -1.0, -1.0, -1.0);
           ^
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A13 GPU
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x5c)
    frame #0: 0x000000010527c250 UnityFramework`-[UnityAppController(self=0x0000000283b6c120, _cmd="callbackGfxInited") callbackGfxInited] at UnityAppController+Rendering.mm:102:43
   99       [_renderDelegate mainDisplayInited: _mainDisplay.surface];
   100      [_unityView recreateRenderingSurface];
   101  
-> 102      _mainDisplay.surface->allowScreenshot = 1;
                                                  ^
   103  }
   104  
   105  - (void)callbackPresent:(const UnityFrameStats*)frameStats
Target 0: (Runner) stopped.
Lost connection to device.
`

**Comment by dinesh4official** [comment]
Are you still experiencing this issue with the latest stable version of flutter?

**Comment by TudorAxinte** [comment]
> Are you experiencing this issue with the latest stable version of flutter?

Running on the latest version of dev, trying stable and will edit once done.
@dinesh4official can you drop on a skype? tudor.20014

**Comment by vipatronon** [comment]
Seems like this was and error with my Unity Project. Fixing that solved my problem. I's odd that I didn't saw any error message...
