### ISSUE TITLE
'flutter_unity_widget.swift.h' file not found - Objective-C - iOS

### ISSUE THREAD

**Issue by CarloTerracciano** [juicycleff/flutter-unity-view-widget#372]
**Describe the bug**
I have integrated the flutter-unity-widget plugin into my flutter project but have been unable to build it on iOS. 
Preamble: my project uses Objective-C.

I had difficulties implementing steps 3 and 4. Below is a screenshot:
![image](https://user-images.githubusercontent.com/21176829/113325429-b465ca00-9318-11eb-8191-937cf2fbd4c7.png)
Error said: 
 *'flutter_unity_widget.swift.h' file not found*
 *Implicit declaration of function 'InitUnityIntegration' is invalid in C99*

**To Reproduce**
Steps to reproduce:
1. Configure a flutter project (flutter version 1.22.5) in Objective-C
2. Insert flutter_plugin_widget

Thanks in advance

**Comment by leegohi04517** [comment]
same with me

**Comment by leegohi04517** [comment]
How to import from static library?Does moudlemap from flutter_unity_widget lib have something wrong?

**Comment by leegohi04517** [comment]
looks like -umbrella.h not export right interface

**Comment by laravelian** [comment]
Did you ever figure this out? Getting this while archiving.

**Comment by lalalaring** [comment]
same error here

**Comment by luoei** [comment]
same with me

**Comment by Linspirit98** [comment]
any solution? same error

**Comment by yixiaonaihe2430** [comment]
> 我解决了这个问题，新建一个快速文件包，如下： ![图片](https://user-images.githubusercontent.com/12251529/131065502-5a9f12a7-1812-48ad-82fe-4c2ae89580a2.png) ![图片](https://user-images.githubusercontent.com/12251529/131065502-5a9f12a7-1812-48ad-82fe-4c2ae89580a2.png)
> 
> ![图片](https://user-images.githubusercontent.com/12251529/131065558-e2816720-e758-4f73-bd7a-9e1669db91e9.png)

Hi, do you have an example? I want to refer to it.

**Comment by dawiddszewczyk** [comment]
In the latest update, I never see this issue.
