### ISSUE TITLE
Ar Black screen (Unity 2019.3.13f1)

### ISSUE THREAD

**Issue by nikiforosper** [juicycleff/flutter-unity-view-widget#376]
Hello! Im new to Flutter. I need to display a 3D Model in AR.
I followed these [steps](https://www.notion.so/UAAL-3a4d77089d09420b9ceb00fdd4d37a99).
I run my app and the screen displays the Unity placeholder. Then i see a black screen instead of my 3D model.

I removed AR from unity project, so 3D model is running in unity scene and my app displays it normally.
Any ideas?

**Comment by juicycleff** [comment]
@nikiforosper maybe you should check if your app has access to camera
