### ISSUE TITLE
Value of type 'UnityAppController' has no member 'unityMessageHandler'

### ISSUE THREAD

**Issue by mrdavidrees** [juicycleff/flutter-unity-view-widget#377]
**Describe the bug**
Latest Bitcode fix has broken iOS builds

UnityPlayerUtils.swift line 96
Value of type 'UnityAppController' has no member 'unityMessageHandler'

I can see this is related to the latest change to enable building with bitcode enabled.

**Comment by mrdavidrees** [comment]
Was due to not updating the UnityFlutterIntegration.package

**Comment by LaTrita97** [comment]
Excuse me, I have the same error, what do you mean by `not updating the UnityFlutterIntegration.package`?
Do you mean the `flutter_unity_widget` package on `flutter`?

Thanks

**Comment by TaiTrien** [comment]
Any solutions? :(

**Comment by mrdavidrees** [comment]
This file needs to be updated for 4.1

https://github.com/juicycleff/flutter-unity-view-widget/blob/master/scripts/FlutterUnityIntegration-v4.1.0.unitypackage

**Comment by rocaforarnelo** [comment]
Any solutions?

**Comment by mrdavidrees** [comment]
Sometimes these extra lines that the build process is meant to add in fails to generate.

There should be two entries in UnityAppController.h and UnityAppController.m

I think if you look back at your git history you may be able to restore these files. Alternatively I've just had to keep runnning the build until they actually generate.

<img width="823" alt="Screen Shot 2021-05-04 at 4 30 05 pm" src="https://user-images.githubusercontent.com/811705/116967583-fd34e800-acf5-11eb-838b-66e6b6195678.png">

**Comment by andyshephard** [comment]
To get this to work, I had to remove the Unity-iPhone.xcodeproj from within my project (Move to Trash), then regenerate the Unity project entirely. Be sure to also clean your build folder(s) to ensure that there are no leftover files that could interfere with any of the fresh build process.
