### ISSUE TITLE
Xcode Archive archive does not contain an iOS App Archive but rather is a Generic Xcode archive

### ISSUE THREAD

**Issue by mrdavidrees** [juicycleff/flutter-unity-view-widget#381]
**Describe the bug**
from fastlane: exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc

or

from xcode: Xcode Archive archive does not contain an iOS App Archive but rather is a Generic Xcode archive that cannot be exported for AdHoc or the app store.

I've ran into this issue using the flutter unity v4.1 which I had never seen before but seems to be related[ to this](https://developer.apple.com/library/archive/technotes/tn2215/_index.html)
I solved it by setting the Unity-iPhone & UnityFramework Targets to SKIP_INSTALL YES which I'm not quite sure is the correct way to approach this issue however did let me export the archive correctly. What are your thoughts on this? Is this the right way to approach the issue?

I notice that you explicitly set SKIP INSTALL to NO in [XCodePostBuild.cs](https://github.com/juicycleff/flutter-unity-view-widget/blob/602cc6f1712490ad4e8768bc237e9a6265ddc9f6/example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/XCodePostBuild.cs#L76) which makes me wonder if I am taking the correct approach.

What are your thoughts?

Also, thank-you for maintaining this library, we're a week or two away from using it production and it all seems to be going fairly well.

**Comment by juicycleff** [comment]
@mrdavidrees I believe SKIP_INSTALL to yes is correct and should be used when archiving.

**Comment by andyshephard** [comment]
Hi guys, thanks for mentioning this. I was troubleshooting the issue for a couple of days already but this solved it!
@juicycleff would you be able to add this to the README.md for future reference? I think if there are already a lot of people using this library (also, have to give you my thanks for creating this - it's excellent!) they'll likely need to archive at some point when uploading to App Store.

I'm happy to make a pull request myself if it's easier?

**Comment by juicycleff** [comment]
@andyshephard would be cool if you make a PR on it. Happy to merge it in

**Comment by kjyv** [comment]
This is still an issue
