### ISSUE TITLE
Project with path ':unityLibrary' could not be found in project ':flutter_unity_widget'.

### ISSUE THREAD

**Issue by tariq-alskran** [juicycleff/flutter-unity-view-widget#385]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-3.0.3\android\build.gradle' line: 47

* What went wrong:
A problem occurred evaluating project ':flutter_unity_widget'.
> Project with path ':unityLibrary' could not be found in project ':flutter_unity_widget'.

**Comment by juicycleff** [comment]
@tariq-alskran could you follow the instruction here for v3 https://github.com/juicycleff/flutter-unity-view-widget/tree/v3
