### ISSUE TITLE
FileNotFoundException: Could not find file "E:\android\build.gradle"

### ISSUE THREAD

**Issue by xiaojiedeVX** [juicycleff/flutter-unity-view-widget#389]
FileNotFoundException: Could not find file "E:\android\build.gradle"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <fb001e01371b4adca20013e0ac763896>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <fb001e01371b4adca20013e0ac763896>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <fb001e01371b4adca20013e0ac763896>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <fb001e01371b4adca20013e0ac763896>:0)
System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <fb001e01371b4adca20013e0ac763896>:0)
System.IO.StreamReader..ctor (System.String path) (at <fb001e01371b4adca20013e0ac763896>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
System.IO.File.ReadAllText (System.String path) (at <fb001e01371b4adca20013e0ac763896>:0)
Build.SetupAndroidProject () (at Assets/FlutterUnityIntegration/Editor/Build.cs:164)
Build.DoBuildAndroid (System.String buildPath, System.Boolean isPlugin) (at Assets/FlutterUnityIntegration/Editor/Build.cs:85)
Build.DoBuildAndroidLibrary () (at Assets/FlutterUnityIntegration/Editor/Build.cs:23)

**Comment by xiaojiedeVX** [comment]
When I exported Android

**Comment by ChrisLmis** [comment]
I had the same issue. Activate "Export Project" in the Build Settings resolved that issue for me

**Comment by hetthummar** [comment]
You have to copy unity project inside flutter project's unity file. So make sure you did that.
[https://github.com/juicycleff/flutter-unity-view-widget#steps](url)
