### ISSUE TITLE
Failure to initialize 

### ISSUE THREAD

**Issue by We2Am-BaSsem** [juicycleff/flutter-unity-view-widget#393]
I'm trying to use a unity project in flutter ,android, application, after exporting to flutter from unity and try to run it on flutter it breaks with  messages "Failure to initialize ", "Your hardware does not support this application", "failed to load linmain.so" and then the application closes.

**Screenshots**
![image](https://user-images.githubusercontent.com/58189568/116340968-5c6b9780-a7e0-11eb-9137-b8aa0f286785.png)

**Comment by planetMatrix** [comment]
Did you exported in IL2CPP?

**Comment by We2Am-BaSsem** [comment]
> Did you exported in IL2CPP?

yes

**Comment by planetMatrix** [comment]
My Guess:
Select ".Net 4.x"

**Comment by juicycleff** [comment]
@We2Am-BaSsem Unity as a library does not support emulators. It's in the readme

**Comment by We2Am-BaSsem** [comment]
> @We2Am-BaSsem Unity as a library does not support emulators. It's in the readme

can I use a lower version such as 4.0.1+1 it's not mentioned that it doesn't support the emulator ?
