### ISSUE TITLE
onUnityMessage does not get called in Release Mode/APK

### ISSUE THREAD

**Issue by planetMatrix** [juicycleff/flutter-unity-view-widget#394]
Many thanks for this sweet plugin. Now unity app too can have awesome UI/UX. Really appreciate your time and efforts.

@juicycleff 
I am on the latest version
dependencies:
  flutter_unity_widget: ^4.1.0

I have a circular progress indicator overlay between flutter and unity load (in Full screen). As soon as unity loads it sends a message to hide the loader overlay. In debug mode all works perfectly.

But as the title suggest I am unable to release app because when I build via App Bundle or Release APK the logic doesn't work.

I tried
https://github.com/juicycleff/flutter-unity-view-widget/issues/172

Unchecked R8 in Unity as well as
(In gradle.properties)
android.enableR8.libraries=false
android.enableR8=false

Nothing worked.. 

Any pointers?

**Comment by juicycleff** [comment]
Thanks for the kind words. It weird if does not work in release build. Is this on Android?

**Comment by planetMatrix** [comment]
Yes on Android.. I haven't checked on iOS because this app is for Android only

**Comment by planetMatrix** [comment]
Same issue even if I Run in Release mode

**Comment by planetMatrix** [comment]
@juicycleff 
Okay MY BAD! I didn't read the instruction carefully so missed this crucial step

6.4. If you use minifyEnabled true in your android/app/build.gradle file, open the android/unityLibrary/proguard-unity.txt and change the following:

+    -keep class com.xraph.plugin.** {*;}

Nevertheless many thanks and take care!
