### ISSUE TITLE
Execution failed for task ':unityLibrary:BuildIl2CppTask'

### ISSUE THREAD

**Issue by maciej-szulc** [juicycleff/flutter-unity-view-widget#395]
Hey, any ideas what can be wrong ?

`* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> A problem occurred starting process 'command '.../android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''`

build --info

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_unity_widget:compileInnerTestAidl'.
> Could not resolve all task dependencies for configuration ':flutter_unity_widget:innerTestCompileClasspath'.
   > Could not resolve project :unityLibrary.
     Required by:
         project :flutter_unity_widget
      > No matching variant of project :unityLibrary was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'innerTest', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'debugApiElements' capability android:unityLibrary:unspecified declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'innerTest'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugRuntimeElements' capability android:unityLibrary:unspecified declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'innerTest'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseApiElements' capability android:unityLibrary:unspecified declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'innerTest'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseRuntimeElements' capability android:unityLibrary:unspecified declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'innerTest'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
`

**Comment by maciej-szulc** [comment]
After following this issue: [](https://github.com/juicycleff/flutter-unity-view-widget/issues/213)
Previous error changed to error: `Execution failed for task ':flutter_plugin_android_lifecycle:compileDebugJavaWithJavac'.
> Cannot invoke "javax.tools.JavaCompiler.getStandardFileManager(javax.tools.DiagnosticListener, java.util.Locale, java.nio.charset.Charset)" because "this.delegate" is null
`

**Comment by planetMatrix** [comment]
I guess you should not add anything to unitylibrary/build.gradle.. It's takem care by Flutter Unity Plugin.

Instead add the below to android/app/build.gradle
`buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
              }
        profile {
            signingConfig signingConfigs.debug
               }
        innerTest {
             matchingFallbacks = ['debug', 'release']
              }
    }`

**Comment by maciej-szulc** [comment]
I know the issue. I tried to build fultter app on another machine than Flutter Export in Unity was made. After making Flutter Export on the desired machine it worked.

**Comment by suryanadiminti99** [comment]
> I guess you should not add anything to unitylibrary/build.gradle.. It's takem care by Flutter Unity Plugin.
> 
> Instead add the below to android/app/build.gradle
> `buildTypes { release { signingConfig signingConfigs.debug } debug { signingConfig signingConfigs.debug } profile { signingConfig signingConfigs.debug } innerTest { matchingFallbacks = ['debug', 'release'] } }`

After adding this code in my gradle , still i am facing same issue.NDK already installed in my system.

**Comment by novavision** [comment]
I had the same issue on Unity 2020.1 and 2020.2. Had to move back to 2019.4 to make it work.
Why so?
