### ISSUE TITLE
How do I restart after shutting down Unity?

### ISSUE THREAD

**Issue by AuMaHub** [juicycleff/flutter-unity-view-widget#400]
**Describe the bug**
When I use quit() on Android, the app quits. And when I use unload() the screen freezes when recreating Unity. Am I misunderstanding the function?

**Log when the app is terminated with quit()**
```
D/et.likersneten(19933): PlayerBase::stop() from IPlayer
D/AudioTrack(19933): stop(3385): called with 2632896 frames delivered
W/libEGL  (19933): EGLNativeWindowType 0x72fa66eee0 disconnect failed
Lost connection to device.
Exited (sigterm)
```

**To Reproduce**
1. Access the Unity page from the app
2. Page exit (use quit before dispose)
3. error

**Unity (please complete the following information):**
 - OS: windows
 - Version 20.3.4f1

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Android 11
 - Version Android API 30

**Additional context**

**Comment by AuMaHub** [comment]
I haven't been able to solve this problem for a month.

So I made a GIF of the app I ran as an example. 
Please, I just want you to check it out.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48949226/120982869-20026280-c7b4-11eb-9b38-c2344dcb3ba0.gif)

**Comment by AlceoMazza** [comment]
I'm having the same issue in debug. The Unity Widget works fine when testing with ADB, but otherwise it freezes after exiting and re-opening the screen that contains it. To me this is happening with or without calling unload().

**Comment by nikiforosper** [comment]
I have the same issue too

**Comment by nikiforosper** [comment]
I "fixed" this issue whith this way:

1. Wrap Scaffold with 
```
WillPopScope(
      onWillPop: () async {
        await _unityWidgetController.pause();
        Navigator.of(context).pop();
        return false;
      }, child: Scaffold 
...etc, to pause the unity
```
2. In the onUnityCreated, add this:
```
void onUnityCreated(UnityWidgetController controller) async {
    this._unityWidgetController = controller;
    final _isPaused = await this._unityWidgetController.isPaused();
    if(_isPaused){
    Future.delayed(
      Duration(milliseconds: 50),
      () async {
        await this._unityWidgetController.resume();
      },
    );
   }
  }
```

**Comment by AlceoMazza** [comment]
Great, thanks! This works for me.
Althought I think this is not an expected behaviour, I have a project with Unity 2019.4.3f1 and Vuforia (vs the bugged one with Unity 2020.3.11f1 and ARCore) where this freeze is not happening and the Unity Widget works fine and this extra code is not needed.

**Comment by qiuguian** [comment]
it's not work for me with unity 2020.3.11

**Comment by nikiforospertselis** [comment]
> it's not work for me with unity 2020.3.11

Another step I followed is to removeView in tha native code.
Specifically, go to
_C:\YOUR_FLUTTER_FOLDER\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-.2.0\android\src\main\kotlin\com\xraph\plugin\flutter_unity_widget\UnityPlayerUtils.kt_
and change the following functions to:
```
fun addUnityViewToBackground(activity: Activity) {
    if (unityPlayer == null) {
        return
    }
    if (unityPlayer!!.parent != null) {
        (unityPlayer!!.parent as ViewGroup).removeView(unityPlaye
    }
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        unityPlayer!!.z = -1f
    }
    val layoutParams = ViewGroup.LayoutParams(1, 1)
    activity.addContentView(unityPlayer, layoutParams)
    isUnityInBackground = true
}
```
```
fun restoreUnityViewFromBackground(activity: Activity) {
            if (unityPlayer == null) {
                return
            }

            if (unityPlayer!!.parent != null) {
                (unityPlayer!!.parent as ViewGroup).removeView(unityPlayer);
                (unityPlayer!!.parent as ViewGroup).addView(unityPlayer)
            }

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                unityPlayer!!.z = 1f
            }

            val layoutParams = ViewGroup.LayoutParams(1, 1)
            activity.addContentView(unityPlayer, layoutParams)
            isUnityInBackground = false
        }
```
```
fun addUnityViewToGroup(group: ViewGroup) {
            if (unityPlayer == null) {
                return
            }

            if (unityPlayer!!.parent != null) {
                (unityPlayer!!.parent as ViewGroup).removeView(unityPlayer)
            }

            val layoutParams = ViewGroup.LayoutParams(MATCH_PARENT, MATCH_PARENT)
            group.addView(unityPlayer, 0, layoutParams)

            unityPlayer!!.windowFocusChanged(true)
            unityPlayer!!.requestFocus()
            unityPlayer!!.resume()
        }
```

I don't know if it will work, but you can try

**Comment by smashmountainstudio** [comment]
The code below work for me:

void _onUnityCreated(controller) async  {
    _unityWidgetController = controller;

    await _unityWidgetController.pause();

    Future.delayed(
      Duration(milliseconds: 100),
          () async {
        await this._unityWidgetController.resume();
      },
    );
  }

**Comment by smichalak** [comment]
Cheers mate @smashmountainstudio!

**Comment by muck27** [comment]
My game scene does not render the second time I try to play it.
I tried adding a WillPopScope as mentioned in the comment. The scene renders successfully the second time sometimes but most of the times it doesnt. Is there a fix for this issue yet?

**Comment by OGmetamonkey** [comment]
> 

Cheers @smashmountainstudio :)

This is the only solution that worked for FUW 4.1.0 for me. Also tried all solutions from [#46](https://github.com/juicycleff/flutter-unity-view-widget/issues/46#issuecomment-634190567), [#230](https://github.com/juicycleff/flutter-unity-view-widget/issues/230) [#245](url), [#452](https://github.com/juicycleff/flutter-unity-view-widget/issues/452), [#413](https://github.com/juicycleff/flutter-unity-view-widget/issues/413)

**Comment by deepatavy** [comment]
Upgrading to ^2022.1.0 from ^4.2.1 Worked for me.

**Comment by voolf00** [comment]
Hello, i have problem with unity when I minimize the program and resume. Widget unity is white and writes console. added GIF

`E/BufferQueueProducer(22043): [SurfaceTexture-0-22043-0](id:561b00000002,api:0,p:-1,c:22043) dequeueBuffer: BufferQueue has no connected producer`

![ezgif-3-242a19e4f4](https://github.com/juicycleff/flutter-unity-view-widget/assets/6012151/210cd16f-f9d6-4a94-b74c-956dbe80754b)



unity 2022.3.5

flutter doctor -v

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale ru-RU)
    • Flutter version 3.10.5 on channel stable at /Users/voolf/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 недель назад), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/voolf/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM G975F (mobile) • R58M162P24M • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
