### ISSUE TITLE
Camera not working in Release Mode Android

### ISSUE THREAD

**Issue by MirceaX2Mobile** [juicycleff/flutter-unity-view-widget#405]
**Describe the bug**
On Android if I build the app in release mode the camera permission is not showing from Unity and then the view remains blank. If I build in debug everything works fine, the permission is showing and then the camera is working within Unity View.   
I think the problem is because of the generated Manifest file but I couldn't find any solution.

Below I will attach 2 videos RELEASE and DEBUG.

**To Reproduce**
1. Just Go to the Unity embedded screen (the code is exactly like in the demo app)

**Expected behavior**
The camera permission should be displayed and then Unity View should display the camera feed.

**Screenshots**

https://user-images.githubusercontent.com/33491440/119394025-65b22c00-bcda-11eb-875b-d3b8602d3acd.mp4

https://user-images.githubusercontent.com/33491440/119394040-6945b300-bcda-11eb-89d1-8562bbfa3e0f.mp4

**Unity (please complete the following information):**
 - OS: macOS 
 - Version 2021.1.4.f1

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android
 - Version 11

**Comment by bitk0der** [comment]
Related to https://github.com/juicycleff/flutter-unity-view-widget/issues/129#issuecomment-621861492 , there is solution.

**Comment by MirceaX2Mobile** [comment]
@bitk0der 
Thanks, this fixed my issue. I will close this bug.
