### ISSUE TITLE
AndroidJavaException in release build

### ISSUE THREAD

**Issue by conmaxo** [juicycleff/flutter-unity-view-widget#410]
My app with AR foundation in debug build run very good, but in release build it come with this error:
"AndroidJavaExeception: java.lang.ClassNotFoundException: com.unit3d.plugin.UnityAndroidPermissions"

![Capture](https://user-images.githubusercontent.com/25227717/121079877-ed348a80-c804-11eb-9d24-ced8bb9c49ec.PNG)

thank for your advice

**Comment by timbotimbo** [comment]
Closing this as outdated.

Some relevant info for anyone finding this:
This can be prevented by adding `-keep class com.unity3d.plugin.UnityAndroidPermissions** { *; }` to a custom proguard-user file in unity.

More recent unitpackages automatically add `-keep class com.unity3d.plugin.* { *; }` during the export, which has the same result.
