### ISSUE TITLE
Unity widget Stuck on screen

### ISSUE THREAD

**Issue by EhsanBrd** [juicycleff/flutter-unity-view-widget#412]
Hello guys,

Hello friends
I used flutter-unity-view-widget in my project, and as you can see in the video, it has been executed in my background.
When I click on the details of each product to display the corresponding window, my background which is the same as the unity file is fixed ، It stays and finds the details of my products on the back of that screen.
Thank you for guiding me.

@juicycleff

https://user-images.githubusercontent.com/25132414/121141558-5a214200-c850-11eb-8efb-c77257655d85.mp4

**Comment by AuMaHub** [comment]
I have the same problem, hope there is a solution
