### ISSUE TITLE
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. 

### ISSUE THREAD

**Issue by manildayma** [juicycleff/flutter-unity-view-widget#414]
**Description**

I made a basic AR app to spawn an object using AR Foundation.
After that to setup flutter-plugin I imported "FlutterUnityIntergration.unitypackagev" and as it imported, these two errors popped up.
* Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/FlutterUnityIntegration/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.dll)

* Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (C:/Users/Admin/Desktop/uf/unity/uf-u/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)

**To Resolve**
I deleted one of the .dll file from later popped error address. "C:/Users/Admin/Desktop/uf/unity/uf-u/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll"
Then "Flutter" option appeared at nav bar but the errors were still there. 

Even on hitting"CLEAR" on console, the error persisted.

**To Reproduce**
-told in description 

**Expected behavior**
clear console logs with "Flutter" option in navbar at first import, without multiple .dll files.
**Screenshot**
![Screenshot (29)](https://user-images.githubusercontent.com/31439780/121587556-93290480-ca52-11eb-97bb-97839375195b.png)

**Unity (please complete the following information):**
 - OS: windows 10 
- Unity 2020.3.11f1

**Smartphone (please complete the following information):**
 - Device: MI A3
 - OS: android 11

**Comment by ifelsebegin** [comment]
Import without JsonDotNet folder

![image](https://user-images.githubusercontent.com/54210/121591445-2c035400-ca42-11eb-9b5a-685154fafd17.png)

**Comment by manildayma** [comment]
thank you so much! worked perfectly  :)
