### ISSUE TITLE
PrecompiledAssemblyException in Unity 2020.3.11f1 caused by FlutterUnityIntegration-v4.1.0.unitypackage

### ISSUE THREAD

**Issue by witi42** [juicycleff/flutter-unity-view-widget#419]
**Describe the bug**
*FlutterUnityIntegration-v4.1.0.unitypackage* causes the following error in *Unity 2020.3.11f1*:
```
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/FlutterUnityIntegration/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.dll)

Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (C:/Users/user/Projects/Test/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)
```
I noticed this when upgrading from *Unity 2020.3.5f1* to *Unity 2020.3.11f1*

**To Reproduce**
1. Create empty 3D project in *Unity 2020.3.11f1*
2. Import custom package *FlutterUnityIntegration-v4.1.0.unitypackage*
3. See error in Console

**Screenshots**
![image](https://user-images.githubusercontent.com/62439015/122071749-d9ac9500-cdab-11eb-8494-0821c5b87903.png)

**Unity**
 - *Unity 2020.3.11f1*
 - OS: *Windows 10 Pro Version 10.0.19043 Build 19043*

**Comment by ElegantSyntax** [comment]
You probably have the unity package with it included, just delete Assets/FlutterUnityIntegration/JsonDotNet/ and you should be fine.
