### ISSUE TITLE
Unity-Framework not found Help!!!!!!!!!!!!

### ISSUE THREAD

**Issue by shubhamguptak** [juicycleff/flutter-unity-view-widget#420]
**Describe the bug**
Even if I try adding Unity-Framework it still gives build errors

Xcode build Error : 'UnityFramework/UnityFramework.h' file not found

**To Reproduce**
1. Created the IOS-Build from Unity
2. Open the Project in XCode and Build and run
3. Issue Arises

**Expected behavior**
It should build successfully

**Unity (please complete the following information):**
 - OS: Big Sur 
 - Version 2019.4.26f1

**Smartphone (please complete the following information):**
 - Device: Iphone12 & Simulator
 - OS: IOS 12.0

**Comment by juicycleff** [comment]
@shubhamguptak did you follow the readme guide?

**Comment by shubhamguptak** [comment]
@juicycleff  Yes I followed the readme guide correctly

**Comment by shubhamguptak** [comment]
Can you please create a tutorial video on how to buid for IOS. That will help us a lot @juicycleff

**Comment by camao-apo** [comment]
The readme guide have already main steps which should be enough, but there are some additional stuff that you need to consider.

1. All your components (so Pods, target project etc.) need to have the same Target iOS version.
2. If you are using some additional configurations, you need to update Unity-iPhone (mainly UnityFramework target) project, to have the same configurations. (so i have additional schemes and that was the main problem for me, because it did not build it with the correct configuration)
3. You cannot build the same export from Unity for Device and Simulator, you need to set in Unity the correct SDK (Device SDK or Simulator SDK).

**Comment by Chris-the-Intern** [comment]
> The readme guide have already main steps which should be enough, but there are some additional stuff that you need to consider.
> 
> 1. All your components (so Pods, target project etc.) need to have the same Target iOS version.
> 2. If you are using some additional configurations, you need to update Unity-iPhone (mainly UnityFramework target) project, to have the same configurations. (so i have additional schemes and that was the main problem for me, because it did not build it with the correct configuration)
> 3. You cannot build the same export from Unity for Device and Simulator, you need to set in Unity the correct SDK (Device SDK or Simulator SDK).

What do you do if Unity-iPhone does NOT appears when opening the workspace of Runner? What do I do instead?

**Comment by camao-apo** [comment]
Then you need to add it yourself (it is also written in the readme guide).

**Comment by shubhamguptak** [comment]
@Chris-the-Intern Hey man if you are able to successfully build for IOS. Can you please help me out. I am trying to solve this issue from 3 months. My Email id is sg83108@gmail.com.

**Comment by akramaskar** [comment]
Any updates about this? @shubhamguptak 
Did you figure it out?

**Comment by shubhamguptak** [comment]
No bro @akramaskar

**Comment by EskAere** [comment]
Any progress here ? 
I can't build on iOS too due to UnityFramework.h not found

**Comment by cc-setwo** [comment]
Hello,

Guys, don't waist your time trying to build iOS under simulator target - **it doesn't work on simulator**. The only working option is to run on real device. And for publishing you need to make an archive using xCode. The only problem I faced when making archive is that distribute button wasn't available, this answer helped me: https://stackoverflow.com/questions/55467829/xcode-10-1-doesnt-show-distribute-app-option-when-archiving-cant-archive

@EskAere fyi.

Regards.

**Comment by IronHeartDan** [comment]
I totally solved this issue by just deleting iOS folder from flutter project (rm -r ios) and the again generating the iOS project with "flutter create ."

Then one change I did is I kept the package name or bundle id of my flutter app and unity export the same by going into player and then configuration and override package name or bundle. 
Exported as iOS 
from flutter root director go inside iOS (cd ios)
edit the pod file and uncomment the "platform : ios" line and set the version to 12 
save
and do a pod install
open in Xcode import the unity exported iOS and inside that select data and make sure your target is only checked to unity framework
that's it It just magically started working and I decided to inform here just after the successful build as it could really motivate you to try and make it working.

**Comment by IronHeartDan** [comment]
> Any progress here ?
> I can't build on iOS too due to UnityFramework.h not found

I just wrote what worked for me you can give it a shot

**Comment by khalithartmann** [comment]
go to Product > Scheme > UnityFramework and then Run. After that change the Scheme back to Runner and you should be good to go.

**Comment by dawiddszewczyk** [comment]
Hi there is [solution](https://github.com/juicycleff/flutter-unity-view-widget/issues/83#issuecomment-1186234502) :)
