### ISSUE TITLE
Double touches registered on single finger touch.

### ISSUE THREAD

**Issue by novavision** [juicycleff/flutter-unity-view-widget#421]
**Describe the bug**
Using the widget Unity register 2 touched on mobile devices on single finger. 

**To Reproduce**
1. Just add some script to demo project with the code:
```
if (Input.touchCount > 0)
        {
            foreach (Touch touch in Input.touches)
            {
                if (touch.phase == TouchPhase.Began || touch.phase == TouchPhase.Ended)
                    Debug.Log($"Finger Id: {touch.fingerId} phase: {touch.phase}, tap count: {touch.tapCount}, type: {touch.type}");
            }
        }
```
2. Export for Android
3. Run the build in Android Studio
4. See 2 fingers registered on a single touch

**Expected behavior**
1 finger should be 1 touch

**Unity (please complete the following information):**
 - OS: Android, didn't test on iOS but most likely same case there
 - Version 2019.4.26F1

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi9T Pro
 - OS: Android 10

**Comment by jaboyc** [comment]
I'm having the same issue. Were you able to find a solution @novavision ?

**Comment by novavision** [comment]
@jaboyc nope, I didn't. But it's possible to create a workaround to detect duplicated touches and ignore 1 of 2. 
Another way is set Tap detect on 2 touches (it's possible using LeanTouch input manager asset).

**Comment by jaboyc** [comment]
Thanks, I'll try that out. My Unity app also uses two-finger drag gestures, so I'm hoping that it'll still work when the user actually *does* want two touches
