### ISSUE TITLE
iOS issues with UnityFramework.

### ISSUE THREAD

**Issue by Chris-the-Intern** [juicycleff/flutter-unity-view-widget#433]
**Goal:**
Run Flutter_Unity_widget on iOS devices.

**Describe the bug:**
When running on Xcode I keep running into a specific issue:

/Users/chriswilliams/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-4.2.1/ios/Classes/FLTUnityView.swift:10:8: error: no such module 'UnityFramework'
    import UnityFramework

I created my own widget from scratch following your guys' instructions. I followed the instructions in the README (they didn't help with this issue) and the video tutorial by Lorant Csonka. Csonka used Xcode in the video, so I followed along. When opening the Runner Workspace in Xcode, I noticed that unlike in Csonka's video, my project navigation did not display "Unity-iPhone.xcodeproj". It seems I can't move forward without resolving this.

**To Reproduce:**
Starting from when the platform is already set to iOS within Unity 3D:
1. Go to 'Build Settings > Player Settings'
2. Change Product Name and Company Name
3. Go to 'Other Settings'
4. Color Space: Linear
5. Auto Graphics API does **NOT** appear as an option.
6. Bundle Identifier is already handled.
7. Under 'Configuration':
- Target Device: iPhone + iPad
- Target SDK: Device SDK
- Architecture: ARM64
- No XR settings available.

8. Click on "Flutter > Export iOS"
9. Find and open the Runner workspace in Xcode
10. See that Runner and Pods are the only things available and that the files in them regarding frameworks are red. 
11. See that "Unity-iPhone" is not available.

**Expected behavior:**
To see the appropriate projects/workspaces/files to complete the flutter and unity integration for iOS devices. Specifically seeing "Unity-iPhone" within the project workspace inside Xcode.

**Screenshots:**

_Project Navigation from Example/Video:_
![image](https://user-images.githubusercontent.com/85965390/126531525-5164a741-f650-4eb2-a269-79f91759d70e.png)

_My Project Navigation:_
![Screen Shot 2021-07-21 at 8 41 26 AM](https://user-images.githubusercontent.com/85965390/126523360-d3ce7ad7-76b6-4388-814e-1d31926967ae.png)

![Screen Shot 2021-07-21 at 9 05 01 AM](https://user-images.githubusercontent.com/85965390/126522860-02545e17-bb69-4e02-a7c9-dfb4977c17cc.png)

![image](https://user-images.githubusercontent.com/85965390/126522921-9e220716-fe5c-483e-9f2a-5cc9f7a89e3a.png)

**Resulting in:**
![Screen Shot 2021-07-22 at 1 26 08 PM](https://user-images.githubusercontent.com/85965390/126705147-4c697c71-9639-40a3-8bc7-045635a1ebb8.png)

**Unity:**
 - Unity Version: 2020.3.13f1
 - OS: macOS Big Sur

**Smartphone:**
 - Device: any iPhone
 - OS: iOS
 - Version:  minimum 11.0
 
 **Additional Context:**
- Unity-iPhone is inside my Unity Library folder just like how it is in the example.
- I've tried to make the example work a multiple amount of times but no luck with the example you guys have either.

------------------------------------------

Update: I figured out how to add the Unity-iPhone portion thanks to the README. Now the only thing stopping me is inside of FLTUnityView.swift, on line 10 where it says import UnityFramework. It says, 

No such module 'UnityFramework'

**Comment by Qnetis** [comment]
I have the same problem

**Comment by Chris-the-Intern** [comment]
> I have the same problem

I've been dealing with so many bugs that by the time I fixed them I forgot to check back at the README. Luckily if you just do what's in the README and there are no other issues, then you should be able to add the Unity-iPhone to the project. I'm going to close this issue. and start a new one with my current and more relevant issue. But if you still need help let me know.

**Comment by Chris-the-Intern** [comment]
I somehow, after following further instructions in the README, have circled back to this issue. So I'm reopening it.
