### ISSUE TITLE
Error at Export Android or Export iOS

### ISSUE THREAD

**Issue by roberto-donext** [juicycleff/flutter-unity-view-widget#436]
I´m following the tutorial steps, and after import the custom package, and selecting Export Android or Export iOS from Flutter menu, I´m getting this error:

InvalidOperationException: The build cannot be appended.
UnityEditor.BuildPipeline.BuildPlayer (System.String[] scenes, System.String locationPathName, System.String assetBundleManifestPath, UnityEditor.BuildTargetGroup buildTargetGroup, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options, System.String[] extraScriptingDefines) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:329)
UnityEditor.BuildPipeline.BuildPlayer (UnityEditor.BuildPlayerOptions buildPlayerOptions) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:295)

**Comment by camao-apo** [comment]
See https://github.com/juicycleff/flutter-unity-view-widget#troubleshooting

(Update the unity scripts)

**Comment by roberto-donext** [comment]
Ok thanks! that is the solution! thanks!
