### ISSUE TITLE
No such module 'flutter_unity_widget'

### ISSUE THREAD

**Issue by roberto-donext** [juicycleff/flutter-unity-view-widget#437]
Hi, following the tutorial steps, I read this:
6.3.1. If you're using Swift, open the ios/Runner/AppDelegate.swift file and change the following:
import flutter_unity_widget

Where this module come??
My xcode is launching this error 
No such module 'flutter_unity_widget'

I opened the sample project, and I see that this module is reference in the file GeneratedPluginRegistrant.m but this file is different in my Xcode project:

This is my current file content:

```
#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
}

@end
```

And this is the same file in the sample project:

```
#import "GeneratedPluginRegistrant.h"

#if __has_include(<flutter_unity_widget/FlutterUnityWidgetPlugin.h>)
#import <flutter_unity_widget/FlutterUnityWidgetPlugin.h>
#else
@import flutter_unity_widget;
#endif

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FlutterUnityWidgetPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterUnityWidgetPlugin"]];
}

@end
```
I follow the entire steps, but I don´t know why this fails.
Thanks!

**Comment by roberto-donext** [comment]
Could be something related with Cocoa Pods?? Watching the example project, I found this in podfile:

```
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

But in my xcode project, I don´t have podfile, and in the tutorial, there is nothing about this.
Thanks

**Comment by roberto-donext** [comment]
I have been researching. The solution to this problem is that we need to delete the default xcworkspace and create a new one using pod install.
Could bee nice to add this step in the tutorial. I don´t know why, but in my case, the initial workspace do not contain any reference to pods.

**Comment by andyshephard** [comment]
FWIW, it'd just be enough to run `pod install` in the iOS directory as that'll generate the necessary pods and frameworks for you.
