### ISSUE TITLE
Android release build causes crash when requesting camera permission

### ISSUE THREAD

**Issue by maxkreja** [juicycleff/flutter-unity-view-widget#438]
I am using Unity and AR Foundation in my Flutter app on android. Building & running the app in debug mode works flawless. Unity asks for the camera permission and when granted, the camera live view is getting enabled. However, when building in release mode, the Unity scene loads but does not request the camera permission and stays black.

Inspecting the logcat I got the following error message:

```
08-04 11:06:38.180 27321 27370 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions
08-04 11:06:38.180 27321 27370 E Unity   : java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions
08-04 11:06:38.180 27321 27370 E Unity   :      at java.lang.Class.classForName(Native Method)
08-04 11:06:38.180 27321 27370 E Unity   :      at java.lang.Class.forName(Class.java:454)
08-04 11:06:38.180 27321 27370 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-04 11:06:38.180 27321 27370 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
08-04 11:06:38.180 27321 27370 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83)
08-04 11:06:38.180 27321 27370 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
08-04 11:06:38.180 27321 27370 E Unity   :      at android.os.Looper.loop(Looper.java:223)
08-04 11:06:38.180 27321 27370 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
08-04 11:06:38.180 27321 27370 E Unity   : Caused by: java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions
08-04 11:06:38.180 27321 27370 E Unity   :      ... 8 more
08-04 11:06:38.180 27321 27370 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
08-04 11:06:38.180 27321 27370 E Unity   :   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0
08-04 11:06:38.180 27321 27370 E Unity   :   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className,
```

In the Android app settings (long tap the app icon -> more information) the camera permission is on denied permanently from now on and granting the permission manually won't fix the problem. 

However, the error indicates that the class `UnityAndroidPermissions` has been stripped in the release build, but not in the debug build. I could confirm this by adding the following line to the `proguard-unity.txt` file inside `android/unityLibrary` after exporting to Android using the Unity plugin:

```
-keep class com.unity3d.plugin.* { *; }
```

I don't know if this happens on iOS too, because I don't have access to a Mac & iOS device.

**To Reproduce**
1. add AR Foundation to the Unity project
2. create an AR session with camera
3. embed Unity using the Flutter widget
4. create a release build using `flutter build apk`
5. install and start the app

**Expected behavior**
The app should ask the user for camera permission, when granted the live camera view should become visible.

**Unity:**
 - OS: Android
 - Version 2020.3.13f1

**Smartphone:**
 - Device: Pixel 2 (probably any Android device)
 - OS: Android 11

**Comment by camao-apo** [comment]
As I understand it, it's more of a Unity export bug than an issue with this plugin. 

For my project i added a more specific proguard setting:
-keep class com.unity3d.plugin.UnityAndroidPermissions** { *; }

**Comment by timbotimbo** [comment]
Closing this as outdated.
Recent unitypackage versions include the proguard setting `-keep class com.unity3d.plugin.* { *; }`, which also includes the UnityAndroidPermissions.
