### ISSUE TITLE
Unload on iOS

### ISSUE THREAD

**Issue by roberto-donext** [juicycleff/flutter-unity-view-widget#441]
I´m calling Application.Unload(); from Unity. This should unload the unity view in flutter , but doesn´t work.
I´m testing on iOS.
I´m using this feature in a native development (I mean using Unity as library in a Swift project) and this works properly. In this project, when I push for example a button with this method, the Unity View in Swift is unloaded. But here, in Flutter is not.

Even using the sample demo in this repo, the Scene is not unload. I´m going to Unity Load and unload unity demo, and play the UNLOAD buttom, but nothing happen.
Thanks.

**Comment by juicycleff** [comment]
Please use latest version of unity as there is a bug with pre 2019.3.8f

**Comment by roberto-donext** [comment]
Thanks. I updated Unity, but now, I can´t use the unity package.
I drag the file FlutterUnityIntegration-v4.1.0.unitypackage
And I getting this error:

Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (/Users/roberto_interaction/Desktop/flutter_application_1/unity_last_version/ciudad_last_version/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)

This new version is : 2020.3.15f2

So now is worse. 

I will open a new bug with this bug.

**Comment by TaiTrien** [comment]
I find something in unload method ! 
![Screenshot 2021-08-20 at 01 42 02](https://user-images.githubusercontent.com/32502320/130126407-cb1b894b-a93b-4a9f-9761-68d3a08debeb.png)
