### ISSUE TITLE
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by roberto-donext** [juicycleff/flutter-unity-view-widget#443]
With Unity version 2020.3.15f2 when I drag the file FlutterUnityIntegration-v4.1.0.unitypackage into Unity, I´m getting this error:
`Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (/Users/roberto_interaction/Desktop/flutter_application_1/unity_last_version/ciudad_last_version/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)`
Any solution?
Thanks

**Comment by HazWard** [comment]
You should probably take a look at some previously opened issues like this one: https://github.com/juicycleff/flutter-unity-view-widget/issues/414

**Comment by roberto-donext** [comment]
Ok, works now!, thanks!
