### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by samueltenoriosis** [juicycleff/flutter-unity-view-widget#444]
im using flutter 2.2.3
Unity 2021.1.16f1

i configured for AR foundation following documentation: https://github.com/juicycleff/flutter-unity-view-widget
but give's this error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :arcore_client.
     Required by:
         project :app
      > No matching configuration of project :arcore_client was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.
   > Could not resolve project :unityandroidpermissions.
     Required by:
         project :app
      > No matching configuration of project :unityandroidpermissions was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

**Comment by samueltenoriosis** [comment]
Same error

**Comment by mathtasatlime** [comment]
Are you building a release or a debug version?
