### ISSUE TITLE
On iOS unity project, SKIP_INSTALL build property is set to NO, but it causes problems with archiving the iOS project

### ISSUE THREAD

**Issue by jpsarda** [juicycleff/flutter-unity-view-widget#446]
In `XCodePostBuild.cs`, _SKIP_INSTALL_ properties is set to _NO_. But when I archive the iOS project, it produces a generic archive (that contains the app AND the unity framework). This kind of archives can't be published as a .ipa (see this post on [Stack](https://stackoverflow.com/questions/20369290/xcode-is-creating-generic-xcode-archive-instead-of-ios-app-archive)). So I have to set _SKIP_INSTALL_ to YES manually to be able to make the archive. Having _YES_ for _SKIP_INSTALL_ doesn't seem to be a problem to run the app, so what is the purpose of it being set to _NO_ in `XCodePostBuild.cs `?

<img width="847" alt="Screenshot 2021-08-07 at 21 43 16" src="https://user-images.githubusercontent.com/517839/128612231-06333b13-d108-4d6c-88ad-ee290dfb5502.png">

**Comment by mathtasatlime** [comment]
It's exactly the same for me. Also wondering...

**Comment by timbotimbo** [comment]
Looks like this setting was updated in june 2022.
https://github.com/juicycleff/flutter-unity-view-widget/commit/60b317cc1181453c9870680803cd36dc0fb73a4a
