### ISSUE TITLE
Quit  Unity app and Flutter is crashed 

### ISSUE THREAD

**Issue by TaiTrien** [juicycleff/flutter-unity-view-widget#447]
**Describe the bug**
In my Flutter app, I use a view to launching a unity project.
Inside the Unity project, my partner used "Application.Quit()" to close the whole program when the user tries to press the "x" button in the game,  but my Flutter app is crashed.

**My Logs in Flutter **
flutter: ** flutter unity controller setup complete **
flutter: *********************************************
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A13 GPU
Initialize engine version: 2020.1.14f1 (d81f64f5201d)
Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x15ed2e610>.
UnloadTime: 2.430625 ms
#Battle# Initialized peer 0129ed9b, 'Example', 2-4 players
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
BattleNetworkManager:Start()
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.297500 ms
Unloading 13 unused Assets to reduce memory usage. Loaded Objects now: 2199.
Total: 0.839750 ms (FindLiveObjects: 0.246333 ms CreateObjectMapping: 0.024833 ms MarkObjects: 0.557792 ms  DeleteObjects: 0.010458 ms)
[connection] nw_endpoint_handler_set_adaptive_read_handler [C5.1 52.220.254.33:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C5.1 52.220.254.33:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
yes4all-wartank?fbclid=IwAR0lscMK9rIyS8RyXtmWB_lGU1d_56Q7j_760TMlpnC50cKkqNKCstmVW6E:
Received:| {"code":200,"message":"OK","data":{"id":11,"name":"War tank","description":"War tank","status":1,"setting":"{\r\n  \"balance\": 0.4\r\n}","image":"","updated_at":"2021-07-25T11:34:44.000+00:00","created_at":"2021-03-10T21:17:34.000+00:00"}}
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
<GetRequest>d__2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Setting up 1 worker threads for Enlighten.
  Thread -> id: 16f04f000 -> priority: 1
Lost connection to device.

Any ideas to quit a game from the Unity project? Many thanks

**Comment by samueltenoriosis** [comment]
same problem, any solution?

**Comment by TaiTrien** [comment]
I solved it in this way, I know that is ugly but I think it's the only to support 2 platforms is Android and Ios
![Screenshot 2021-08-24 at 20 17 05](https://user-images.githubusercontent.com/32502320/130623341-68c8dbd7-3d48-442c-a2dd-c8e41899e817.png)

**Comment by TaiTrien** [comment]
I sent a message from Unity and Flutter will catch that message

**Comment by timbotimbo** [comment]
`Application.Quit` kills the entire app when used in Unity.
Calling Quit on the unityWidgetController does the same, which in turns kill the entire flutter app.
This matches the expected behavior from Unity.

Change to an empty scene in Unity or use `unload` if you want to free up some resources.

**Comment by Krazy-kungfu** [comment]
> I solved it in this way, I know that is ugly but I think it's the only way to support 2 platforms is Android and Ios ![Screenshot 2021-08-24 at 20 17 05](https://user-images.githubusercontent.com/32502320/130623341-68c8dbd7-3d48-442c-a2dd-c8e41899e817.png)

This is the way I am doing it, however I have noticed the first time the unity instance runs it displays the unity logo, however upon coming back to flutter view and then reopening unity scene the unity logo does not display. There should be a way to completely kill the unity instance

**Comment by SandyCompetent** [comment]
This is the way I am doing it, however I have noticed the first time the unity instance runs it displays the unity logo, however upon coming back to flutter view and then reopening unity scene the unity logo does not display. There should be a way to completely kill the unity instance.

Please reply on this.
