### ISSUE TITLE
java.lang.ClassNotFoundException: com.xraph.plugin.flutter_unity_widget.UnityPlayerUtils

### ISSUE THREAD

**Issue by jsonsuxing** [juicycleff/flutter-unity-view-widget#453]
**Describe the bug**
I/AudioTrack( 7429): isLongTimeZoreData zoer date time 4 Seconds
I/Unity   ( 7429): **java.lang.ClassNotFoundException: com.xraph.plugin.flutter_unity_widget.UnityPlayerUtils**
I/Unity   ( 7429): UnityEngine.Events.UnityAction:Invoke()
I/Unity   ( 7429): UnityEngine.Events.UnityEvent:Invoke()
I/Unity   ( 7429): UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
I/Unity   ( 7429): UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
I/Unity   ( 7429): UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
I/Unity   ( 7429): UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
I/Unity   ( 7429): UnityEngine.EventSystems.StandaloneInputModule:Process()
I/Unity   ( 7429):  
I/Unity   ( 7429): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
I/Unity   ( 7429): 
I/AudioTrack( 7429): isLongTimeZoreData zoer date time 5 Seconds
I/AudioTrack( 7429): isLongTimeZoreData zoer date time 6 Seconds

**To Reproduce**
Flutter can send messages to Unity, but unity cannot send messages to flutter，
This happens when I call this method **UnityMessageManager.Instance.SendMessageToFlutter()**

- macOS Big Sur 11.4
- Unity 2021.1.16 f1c1
- Flutter Channel stable 2.2.3
- Android SDK 30.0.3

**Comment by novavision** [comment]
Can confirm that @tingleestudios solutions works. Now .aab files includes the missing library

**Comment by adam-fu** [comment]
this is somehow an issue for since upgrading to flutter 3.0.x and adding the proguard settings fixed the problem. Is there any plan to add this to the new version of the flutter unity widget so it exists by default?

**Comment by timbotimbo** [comment]
Both `-keep class com.xraph.plugin.** { *; }` and `-keep class com.unity3d.plugin.* { *; }` are automatically included in the last couple of unitypackage versions that I checked.

Closing this as fixed / outdated.
