### ISSUE TITLE
Error running Unity in example project

### ISSUE THREAD

**Issue by Invixvb** [juicycleff/flutter-unity-view-widget#461]
**Describe the bug**
Whenever I load up the example project, I get this error with any of the options.

**To Reproduce**
Steps to reproduce the behaviour:
Just load up the sample project in Intellij and run it in flutter. 

**Expected behaviour**
It needs to start up Unity.

**Screenshots**
![Screenshot 2021-09-07 161114](https://user-images.githubusercontent.com/74636900/132359585-1a641f66-69f5-4bef-bb80-c1864e512110.png)

**Unity (please complete the following information):**
 - OS: Windows Version 10.0.19042 Build 19042
 - Unity: 2020.3.17f1 LTS
 - Intellij: 2021.2.1

**Smartphone (please complete the following information):**
Used the browser emulator.

**Comment by Samuelbrandani** [comment]
this plugin doesn't support flutter web
run in device
