### ISSUE TITLE
I am unable to quit unity screen and get back to Flutter native screen . Unity screen is always in background. Is it possible to kill unit scene .

### ISSUE THREAD

**Issue by suryanadiminti99** [juicycleff/flutter-unity-view-widget#470]
****I am unable to quit unity screen and get back to Flutter native screen . Unity screen is always in background. Is it possible to kill unit scene . And I want to go back to native screen**.**

**I added below code for click on the back button . Here app is going back my native screen . But again i go to AR screen , the previous data is appears in AR scene.**

Navigator.pop(context); 

**If i add below code app was crashed.**

_unityWidgetController.unload().then((value) => Navigator.pushAndRemoveUntil(
                          context,
                          MaterialPageRoute(builder: (context) => HomeActivity()),
                              (Route<dynamic> route) => false,
                        ));

**If I add below code , my entire app was quit.**

_unityWidgetController.quit();

Any one please suggest some solution for this . 
Thankyou

@juicycleff @thomas-stockx @krispypen @xcxooxl

**Comment by suryanadiminti99** [comment]
Okay , Thankyou . Is there any way to kill unity before going to native screen? Any idea please .

**Comment by suryanadiminti99** [comment]
Actually what we are doing here for temporary purpose, We are destroying all unity data and deleting 3D assets from AR scene . Now we are reset the unity scene . So now native side we are using this **Navigator.pop(context);** for closing the unity Widget screen . It working if we have simple 3D assets in AR . If the 3D content is high, the destroy will suddenly stopped and app was closed. This is the way we are doing .

**Comment by NileshTech** [comment]
Hello everyone. First of all, thanks to the team who developed this plugin. and it helped me a lot to think in different wy for two technologies. I need a help to control multiple games in single app. So is there any way to control the unity scene with help of sceneManager function? If yes, how to do it?
