### ISSUE TITLE
Failed assertion: line 733 pos 15: ‘borderRadius != null || clipper != null’: is not true

### ISSUE THREAD

**Issue by limdp99** [juicycleff/flutter-unity-view-widget#481]
**Describe the bug**
There is no problem until the example builds and installs.
Running the example throws an error where Unity should render.

_**Failed assertion: line 733 pos 15: ‘borderRadius != null || clipper != null’: is not true**_

**Screenshots**
 - https://i.ibb.co/GkxpDpY/IMG-3905.png

**Smartphone**
 - Device: iPhone11 Pro
 - OS: 14.5.1

**Unity** 
 - 2019.4.31f LTS
 
**Build Environment** 
 - Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale ko-KR)
 - Xcode (v13.0)

Thanks for your help.

**Comment by pmstudios** [comment]
Solved. Thanks!

**Comment by limdp99** [comment]
Solved. Thanks!
