### ISSUE TITLE
Undefined Symbols for arm64 intermittent Issue

### ISSUE THREAD

**Issue by zamvar** [juicycleff/flutter-unity-view-widget#485]
Bug Description 
Duplicate of #454 
Tested in M1 Mac Mini
![image](https://user-images.githubusercontent.com/20177817/138932620-fc223451-cd08-4690-aeed-f58f90365086.png)
 
 Tested in Macbook Air Intel
 
![image](https://user-images.githubusercontent.com/20177817/138932742-d78626af-e0ab-4771-b04a-0aee0611ab41.png)

Both applying the fix in #454 
multiple times

**Comment by yusufkorkmaz** [comment]
Change target sdk to 11.0 and edit podfile. 
platform :ios, '9.0' -> platform :ios, '11.0'

**Comment by zamvar** [comment]
> yusufkorkmaz

thanks for the response

unfortunately it doesn't seem to work still.

**Comment by ewajs** [comment]
I can confirm I have this same issue intermittently and still haven't found a consistent solution besides uninstalling and reinstalling everything from scratch multiple times until it resolves itself and haven't been able to pin down the exact fix.

**Comment by Philipp-M** [comment]
I'm repeating what I've found while investigating it in my PR:

The issue as it seems is that the script `XCodePostBuild.cs` is not compiled when a different buildTarget was set in the editor previously, so `UNITY_IOS` is not set when trying to build the library, so no `OnPostBuild` (in this script) is executed, which generates these definitions.

The solution/workaround we are using currently is, to just start unity set with the correct buildTarget (so using the editor gui, switch to the right platform (iOS) and probably restart unity with it).

For CI/CD add the `-buildTarget` option like this:

`sh
path/to/editor/Unity -buildTarget "iOS" ...  -executeMethod "Build.DoBuildIOS"
`

This seems to work consistently for us now

**Comment by zamvar** [comment]
thanks @Philipp-M will check this you and close this ticket if this works out
