### ISSUE TITLE
Value of type 'UnityAppController' has no member 'unityMessageHandler'

### ISSUE THREAD

**Issue by Ahmadre** [juicycleff/flutter-unity-view-widget#486]
I can't RUN or Build ios because of this:

![Bildschirmfoto 2021-10-28 um 20 14 44](https://user-images.githubusercontent.com/18512224/139312268-4dd0089a-2964-4b09-b8db-30f078f2798d.png)

Why is everytime a new bug appearing in this project?

**Comment by Ahmadre** [comment]
Forget it. I'll leave this Plugin. The other plugin is working much better.

**Comment by silpyy** [comment]
what is this other plugin that you speak of?

**Comment by impayru** [comment]
add:

Classes/UnityAppController.mm
- (void)application:(UIApplication*)application handleEventsForBackgroundURLSession:(nonnull NSString ...

+
// Added by https://github.com/juicycleff/flutter-unity-view-widget
extern "C" void OnUnityMessage(const char* message)
{
    if (GetAppController().unityMessageHandler) {
        GetAppController().unityMessageHandler(message);
    }
}

extern "C" void OnUnitySceneLoaded(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid)
{
    if (GetAppController().unitySceneLoadedHandler) {
        GetAppController().unitySceneLoadedHandler(name, buildIndex, isLoaded, IsValid);
    }
}

Classes/UnityAppController.h
@property (nonatomic, copy)                                 void (^quitHandler)(void);...
+
@property (nonatomic, copy)                                 void(^unitySceneLoadedHandler)(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid);
@property (nonatomic, copy)                                 void(^unityMessageHandler)(const char* message);

**Comment by dmgcoding** [comment]
> add:
> 
> ```
> Classes/UnityAppController.mm
> - (void)application:(UIApplication*)application handleEventsForBackgroundURLSession:(nonnull NSString ...
> 
> +
> // Added by https://github.com/juicycleff/flutter-unity-view-widget
> extern "C" void OnUnityMessage(const char* message)
> {
>     if (GetAppController().unityMessageHandler) {
>         GetAppController().unityMessageHandler(message);
>     }
> }
> 
> extern "C" void OnUnitySceneLoaded(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid)
> {
>     if (GetAppController().unitySceneLoadedHandler) {
>         GetAppController().unitySceneLoadedHandler(name, buildIndex, isLoaded, IsValid);
>     }
> }
> 
> Classes/UnityAppController.h
> @property (nonatomic, copy)                                 void (^quitHandler)(void);...
> +
> @property (nonatomic, copy)                                 void(^unitySceneLoadedHandler)(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid);
> @property (nonatomic, copy)                                 void(^unityMessageHandler)(const char* message);
> ```

This helped. Thanks a lot.

**Comment by rickdijk** [comment]
Where do I add this exactly? Running in to this issue now

**Comment by utkubagdas** [comment]
> add:
> 
> ```
> Classes/UnityAppController.mm
> - (void)application:(UIApplication*)application handleEventsForBackgroundURLSession:(nonnull NSString ...
> 
> +
> // Added by https://github.com/juicycleff/flutter-unity-view-widget
> extern "C" void OnUnityMessage(const char* message)
> {
>     if (GetAppController().unityMessageHandler) {
>         GetAppController().unityMessageHandler(message);
>     }
> }
> 
> extern "C" void OnUnitySceneLoaded(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid)
> {
>     if (GetAppController().unitySceneLoadedHandler) {
>         GetAppController().unitySceneLoadedHandler(name, buildIndex, isLoaded, IsValid);
>     }
> }
> 
> Classes/UnityAppController.h
> @property (nonatomic, copy)                                 void (^quitHandler)(void);...
> +
> @property (nonatomic, copy)                                 void(^unitySceneLoadedHandler)(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid);
> @property (nonatomic, copy)                                 void(^unityMessageHandler)(const char* message);
> ```

Hi,

It has syntax errors, it doesn't accept it. Can u help me?

**Comment by TJRoger** [comment]
You should add Unity Message Manager to your unity object first, then export. It solves my problem

**Comment by MarkAlexanderDev** [comment]
This actually worked @impayru thanks!!

@rickdijk and for others who need more details :

In `ios/UnityLibrary/Classes/UnityAppController.mm` after the function `handleEventsForBackgroundURLSession` add :

```
extern "C" void OnUnityMessage(const char* message)
{
    if (GetAppController().unityMessageHandler) {
        GetAppController().unityMessageHandler(message);
    }
}

extern "C" void OnUnitySceneLoaded(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid)
{
    if (GetAppController().unitySceneLoadedHandler) {
        GetAppController().unitySceneLoadedHandler(name, buildIndex, isLoaded, IsValid);
    }
}
```

In `ios/UnityLibrary/Classes/UnityAppController.h` after :

`@property (nonatomic, copy)                                 void (^quitHandler)(void);`

Add :

```
@property (nonatomic, copy)                                 void(^unitySceneLoadedHandler)(const char* name, const int* buildIndex, const bool* isLoaded, const bool* IsValid);
@property (nonatomic, copy)                                 void(^unityMessageHandler)(const char* message);
```

**Comment by timbotimbo** [comment]
I just found a reliable way to replicate this error.


## Reproduction
- Set the build target in Unity build settings to anything NOT iOS, like Android or Desktop.
- Now click Flutter-> Export iOS.

This results in an incomplete build, because any code in 
`#if UNITY_IOS` blocks is skipped.
However you still see the build successful message.

The build script will change the buildtarget automatically, but somehow the `#If UNITY_` keeps the old value.

## Current solution
Change the Unity build target before clicking Flutter -> Export.

You don't have to paste any code like in the comments above, that should be done by the export script automatically.

If you use batchmode or command line, make sure to include `-buildTarget iOS` in your command.

**Comment by el-mimoso** [comment]
I am facing this exact issue,  I have selected ios as the platform before clicking futter-> export
the code provided @MarkAlexanderDev  did the trick.

**Comment by WillowWisp** [comment]
> I just found a reliable way to replicate this error.
> ## Reproduction
> 
>     * Set the build target in Unity build settings to anything NOT iOS, like Android or Desktop.
> 
>     * Now click Flutter-> Export iOS.
> 
> 
> This results in an incomplete build, because any code in `#if UNITY_IOS` blocks is skipped. However you still see the build successful message.
> 
> The build script will change the buildtarget automatically, but somehow the `#If UNITY_` keeps the old value.
> ## Current solution
> 
> Change the Unity build target before clicking Flutter -> Export.
> 
> You don't have to paste any code like in the comments above, that should be done by the export script automatically.
> 
> If you use batchmode or command line, make sure to include `-buildTarget iOS` in your command.

Thank you! This should be in the Troubleshooting section. One thing I would like to add to the solution, that is you need to close & reopen the Unity project first.

**Comment by hafizramiz** [comment]
Sometime when click Export Ios (Release) 
UnityController.h would change like this
![image](https://github.com/juicycleff/flutter-unity-view-widget/assets/102408138/8977f7bc-bca9-402b-b449-bc07aaceeed2)
 And UNityController.mm  file like this
![image](https://github.com/juicycleff/flutter-unity-view-widget/assets/102408138/00eb9af4-7851-44f8-a9aa-5a2c6fceb674)
 After export  Export Ios (Release)  control this two files if it was changed rollback these
