### ISSUE TITLE
Getting error while building Ios application

### ISSUE THREAD

**Issue by suryanadiminti99** [juicycleff/flutter-unity-view-widget#487]
ld: warning: directory not found for option '-L/Users/shivajiyerra/Library/Developer/Xcode/DerivedData/Runner-gxknsbbljvutmhbeycjqgmbcwnfu/Build/Products/Debug-iphoneos/nanopb'
ld: library not found for -lFirebaseABTesting

**Comment by yusufkorkmaz** [comment]
Try this: Enter the ios folder on project in terminal and run "pod install" command.

**Comment by juicycleff** [comment]
Yeah this is not related to this package
