### ISSUE TITLE
Untiy The project screen cannot be displayed

### ISSUE THREAD

**Issue by zhuidong** [juicycleff/flutter-unity-view-widget#488]
**Describe the bug**
To Start, a Unity widget with a height of 10 pixels will be created for the Unity project. Execute Awake and Start functions. After completion, remove the Unity widget with a height of 10 pixels from the Element Tree. Create a new UnityWidget(normal screen resolution) that doesn't show the Unity project, but you can hear the Music in the Unity project, and from the log output, you can tell that Unity is running

**To Reproduce**

**Expected behavior**
I want to be able to see the Unity project screen after creating the UnityWidget for the second time

**Screenshots**

**Unity (please complete the following information):**
 - Windows
 - 2019.4.3

**Smartphone (please complete the following information):**
 - HUAWEI MLA-AL10
 - Android
 - 6
 - opengl 1.4

**Additional context**
I find that there is no relevant OpenGLRender output in the log, but I am on another mobile phone produced in the last one or two years (Android 10), the project is running perfectly, and the log can see the start of OpenGLRender. This is the problem I suspect, but I don't know how to solve it

**Comment by zhuidong** [comment]
There were no error logs during the execution of the problem project

**Comment by zhuidong** [comment]
Example procedures, click the Simple Unity Demo button picture situation
![Screenshot_2021-11-02-17-48-59 1](https://user-images.githubusercontent.com/48434620/139824840-d4d1c2ea-5e22-405a-92b4-616411efbe9d.png)
Android 6

**Comment by zhuidong** [comment]
log
Launching lib\main.dart on HUAWEI MLA AL10 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:9935/v3-xQlHi5aE=/ws
I/Choreographer(31859): Skipped 43 frames!  The application may be doing too much work on its main thread.
I/flutter (31859): *********************************************
I/flutter (31859): ** flutter unity controller setup complete **
I/flutter (31859): *********************************************
I/Unity   (31859): SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 3559mb
I/Unity   (31859): SystemInfo ARM big.LITTLE configuration: 8 big (mask: 0xff), 0 little (mask: 0x0)
I/Unity   (31859): ApplicationInfo com.xraph.plugin.flutter_unity_widget_example version 1.0 build 41a26a9c-b81b-40f3-9ffc-d7e604eed2d3
I/Unity   (31859): Built from '2019.4/release' branch, Version '2019.4.3f1 (f880dceab6fe)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
I/        (31859): counter >= 5, send pause/stop state to pg, counter: 0

**Comment by juicycleff** [comment]
@zhuidong could create a sample project?
