### ISSUE TITLE
Archive in Xcode appears under Other Items when I am using Unity Flutter Widget

### ISSUE THREAD

**Issue by yusufkorkmaz** [juicycleff/flutter-unity-view-widget#489]
When I want to distribute an iOS application that I developed using the Flutter unity widget, the following options appear. I don't see "App Store Connect" choice. How can I solve this problem?

<img width="1022" alt="Screen Shot 2021-11-03 at 16 50 38" src="https://user-images.githubusercontent.com/32537154/140282686-2d774164-52a1-4c91-ae93-96fa48d2c224.png">

**Comment by TinyGiantDigital** [comment]
I believe this is related to the Skip Install issue that has appeared with newer versions:  (https://github.com/juicycleff/flutter-unity-view-widget/issues/446)

I found that i needed to change the flag to Yes on both the Unity-iPhone and Unity Framework targets (see image)

<img width="1147" alt="Screenshot 2021-11-05 at 11 55 54" src="https://user-images.githubusercontent.com/1552423/140506963-133ddf64-dce6-4515-a4f8-ae1dcbac1dc3.png">

**Comment by yusufkorkmaz** [comment]
Thank you. Fixed my problem.

**Comment by WouterVandenputte** [comment]
> I believe this is related to the Skip Install issue that has appeared with newer versions: (#446)
> 
> I found that i needed to change the flag to Yes on both the Unity-iPhone and Unity Framework targets (see image)
> 
> <img alt="Screenshot 2021-11-05 at 11 55 54" width="1147" src="https://user-images.githubusercontent.com/1552423/140506963-133ddf64-dce6-4515-a4f8-ae1dcbac1dc3.png">

Damn... took me hours. You sir, are a hero
