### ISSUE TITLE
iOS inputfield click works only the first time.

### ISSUE THREAD

**Issue by AkhilRaja** [juicycleff/flutter-unity-view-widget#491]
**Describe the bug**
The inputfield and tmpro inputfield both only work for the first time in the flutter unity widget. My use case requires me to use the unity inputs, can you please provide a solution or a workaround ? 

**To Reproduce**
Add an inputfield in a view from unity. Build tha app and test. The keyboard doesn't open up. It just flashes and closes. 

**Expected behavior**

**Screenshots**

**Unity (please complete the following information):**
 - 2013.3.21

**Smartphone (please complete the following information):**
 - iPAD

**Additional context**

**Comment by joelshaffer** [comment]
Seeing the same behavior on iPad (keyboard doesn't open, flashes and closes) on an app built in unity 2019.4.32f1

**Comment by juicycleff** [comment]
Is this input in unity?

**Comment by joelshaffer** [comment]
Yes, It's an InputField (I've tried the standard InputField and the TextMeshPro one) that is on a Panel inside a Canvas. When interacting with it it will work once (the keyboard comes up and you can fill it out) but subsequent interactions cause a white flash and the keyboard opens/closes instantly.

**Comment by Teogai** [comment]
@AkhilRaja  @joelshaffer 
Not sure if this will affect anything else but it worked as a hot fix for me.
![image](https://user-images.githubusercontent.com/12045004/147098225-e9bbd215-5dce-4c0c-9627-d25ed3662494.png)
Remove line 29: uView?.removeFromSuperview() from FLTUnityView.swift
Now keyboard works normally in Unity Text Field.

**Comment by AkhilRaja** [comment]
@Teogai  that fixes it for me, and nothing seems to have broken -- Yet.  Appreciate the find, I was writing a tough workaround, using messages from unity to flutter, then opening flutter keyboard -> sending each keystroke. This hotfix is a really good one.

**Comment by huzhiju** [comment]
Scaffold(
      resizeToAvoidBottomInset: false,
)
effectively solve this problem

**Comment by carnagexx** [comment]
I am getting a similar issue in android. In my case, keyboard does open but it doesn't update the text after I confirm it. I have to press power button 2 times then I can see the value I entered.
