### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by MDoennebrink** [juicycleff/flutter-unity-view-widget#493]
Are there any plans to support flutter_unity_widget for Linux in the future?

Similar to "Windows desktop support"
https://github.com/juicycleff/flutter-unity-view-widget/issues/468

**Comment by juicycleff** [comment]
@MDoennebrink Linux is not supported by UaaL, hence we can only support whats here https://docs.unity3d.com/Manual/UnityasaLibrary.html
