### ISSUE TITLE
Unity scene displays over flutter screen

### ISSUE THREAD

**Issue by IgeeTheron** [juicycleff/flutter-unity-view-widget#496]
I use unity as my home screen and when you click on an object in unity I pause the unity scene and go to a flutter page. The unity screen also has a bottom navigation bar. 

When I push a page on android sometimes the unity scene gets display over other flutter pages and I will still be able to press on buttons behind the unity scene, I can basically still control the app but i can not sea what is happening. Also the bottom navigation bar does not get displayed over the other pages so the unity scene only fills like 90% of the screen. When I go back to the unity screen the bug goes away and the unity screen works.

On Iphone the unity scene also gets displayed over other pages but you can only see the outline of the unity scene not the full scene.

My expected behavior is that the unity scene does not get displayed over other pages

What i think happens:
It is as if the unity screen is called from another page even tho i did not call it and the unity screen still remains the first screen in the stack even thou it is getting displayed over the other pages. I tried using ModalRoute.of(context).isCurrent to determine when the unity screen should be resumed but it gets called and returns a true when the screen is displayed over other pages. I also tried to use ModalRoute.of(context).isFirst to determine if it is first screen in stack but it also returns true when the unity screen is displayed over other pages.

Using visibility_aware_state package with this code below:

`@override
  void onVisibilityChanged(WidgetVisibility visibility) async {

    switch(visibility) {
      case WidgetVisibility.VISIBLE: {
        if (ModalRoute.of(context).isCurrent) {
          if (_unityWidgetController != null) {
            final _isPaused = await this._unityWidgetController.isPaused();

            initStart(_isPaused);
          } else {
            initStart(false);
          }
        }
      }
      break;

      case WidgetVisibility.INVISIBLE: {
        if (ModalRoute.of(context).isCurrent) {
          await _unityWidgetController.pause();
        }
      }
      break;

      case WidgetVisibility.GONE: {
        print("=============== GONE =============");
      }
      break;
    }

    super.onVisibilityChanged(visibility);
  }`

Unity version : 2019.4.32f1

Bug does not happen much on this phone
Phone: Android Galaxy A31
Version: 10

Bug happens on almost every flutter screen:
Phone: Hauwei P10 Plus
Version: Android 7

Bug happens on almost every flutter screen but can see only the outline of unity scene:
Phone: Iphone 8 plus
Version: ios 15.1

**Comment by juicycleff** [comment]
Hmmm this is very weird, as this issue has been fixed. What version of the plugin are you using?

**Comment by IgeeTheron** [comment]
I am Using FlutterUnityIntegration-v4.1.0.unitypackage with plugin version flutter_unity_widget: ^4.2.3

**Comment by Ahmadre** [comment]
@IgeeTheron that's not an issue of this plugin, but an issue of Flutter and iOS:

See here: https://github.com/flutter/flutter/issues/70936
and here: https://github.com/flutter/flutter/issues/43902

Issue is still open.

@juicycleff I would close this and wait for Flutter Team to solve this PlatformView Issue.

**Comment by dawiddszewczyk** [comment]
@Ahmadre And info about this issue?

**Comment by klepov** [comment]
any news?

**Comment by dawiddszewczyk** [comment]
Maybe use the stack, and try to manage states with cubit builder like : 
displayUnityWidget()
displayHomePage(),
Then Unity still works but is in the background. Also pls join to discord channel for more help.

**Comment by champ96k** [comment]
@klepov @dawiddszewczyk you can try this approch

## UI Implementation

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';
import 'package:push_notification/modules/unityrummy/unity_wrapper/cubit/unity_wrapper_cubit.dart';

class UnityWrapper extends StatelessWidget {
  final Widget child;
  const UnityWrapper({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _size = MediaQuery.of(context).size;
    final _cubit = context.watch<UnityWrapperCubit>();
    return Scaffold(
      body: WillPopScope(
        onWillPop: () async {
          await context.read<UnityWrapperCubit>().exitGame();
          return true;
        },
        child: BlocBuilder<UnityWrapperCubit, UnityWrapperState>(
          builder: (context, state) {
            return Stack(
              children: [
                UnityWidget(
                  onUnityCreated: _cubit.onUnityCreated,
                  onUnityMessage: _cubit.onUnityMessage,
                  onUnitySceneLoaded: _cubit.onUnitySceneLoaded,
                ),
                if (!state.isVisible)
                  Container(
                    width: _size.width,
                    height: _size.height,
                    color: Colors.black,
                  ),
                if (!state.isVisible) child,
              ],
            );
          },
        ),
      ),
    );
  }
}
```

## Cubit

```dart

part 'unity_wrapper_state.dart';

class UnityWrapperCubit extends Cubit<UnityWrapperState> {
  UnityWrapperCubit() : super(UnityWrapperInitialState(isVisible: false));

  UnityWidgetController? _unityWidgetController;

  Future<void> onUnityCreated(UnityWidgetController controller) async {
    try {
      _unityWidgetController = controller;
      await postUnityMessage(
        gameObject: 'name',
        methodName: 'name',
        message: "tempmsg";
      );
    } catch (e) {
      emit(UnityGameErrorState('Error: $e'));
    }
  }

  Future<void> launchGame({
    required String startGame,
    required String configId,
  }) async {
    try {
      await postUnityMessage(
        gameObject: Constants.unityGameObjectName,
        methodName: Constants.unityFunctionName,
        message: {msg}
      );
      emit(ShowUnityGameState(true));
    } catch (e) {
      emit(UnityGameErrorState('Error: $e'));
    }
  }

  Future<void> onUnityMessage(message) async {
    if (message == Constants.splashEnd) {
      await postUnityMessage(
        gameObject: 'obj'
        methodName: "name",
        message: {msg}
      );
    } else if (message == Constants.exit) {
      emit(UnityGameExitState(false));
    } 
  }

  Future<void> exitGame() async {
    try {
      await _unityWidgetController?.unload();
      _unityWidgetController?.dispose();
      _unityWidgetController = null;
      return;
    } catch (e) {
      log("Error: $e");
    }
  }

  Future<void> onUnitySceneLoaded(SceneLoaded? scene) async {
    log('Scene : $scene');
  }

  Future<void> onUnityUnloaded() async {
    log('Unity unloaded');
  }

  ///
  /// Post message to unity from flutter. This method takes in a string [message].
  /// The [gameObject] must match the name of an actual unity game object in a
  /// scene at runtime, and the [methodName],
  ///
  Future<void> postUnityMessage({
    required String gameObject,
    required String methodName,
    dynamic message,
  }) async {
    if (_unityWidgetController != null) {
      final _isReady = await _unityWidgetController?.isReady();
      if (_isReady != null && _isReady) {
        log("message info: post call $gameObject, $methodName, $message");
        _unityWidgetController?.postMessage(gameObject, methodName, message);
      }
    }
  }
}

```

## State

```dart
part of 'unity_wrapper_cubit.dart';

abstract class UnityWrapperState extends Equatable {
  final bool isVisible;
  UnityWrapperState(this.isVisible);
}

class UnityWrapperInitialState extends UnityWrapperState {
  UnityWrapperInitialState({required bool isVisible}) : super(isVisible);
  @override
  List<Object?> get props => ['UnityWrapperInitialState'];
}

class ShowUnityGameState extends UnityWrapperState {
  ShowUnityGameState(bool isVisible) : super(isVisible);
  @override
  List<Object?> get props => ['ShowUnityGameState'];
}

class UnityGameErrorState extends UnityWrapperState {
  final String errorMessage;
  UnityGameErrorState(this.errorMessage) : super(false);
  @override
  List<Object?> get props => [errorMessage];
}

class UnityGameExitState extends UnityWrapperState {
  UnityGameExitState(bool isVisible) : super(isVisible);
  @override
  List<Object?> get props => ['UnityGameExitState'];
}

```


Hope this help you :)
