### ISSUE TITLE
Unity crash on page change.

### ISSUE THREAD

**Issue by inakis** [juicycleff/flutter-unity-view-widget#498]
Hi, i'm getting continuous crashes while changing screen.  I change screens by making this call `vm.onNext(context, _pageController),`, using PageController. ¿Should i pass aswell the unitywidgetcontroller as BuildContext and PageController do?

Flutter doctor: 
√] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [VersiÃ³n 10.0.19043.1348], locale es-ES)
    • Flutter version 2.4.0-4.0.pre at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (5 months ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\inaki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • POCOPHONE F1 (mobile) • cac28908 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)            • edge     • web-javascript • Microsoft Edge 96.0.1054.29

! Doctor found issues in 1 category.

**Comment by juicycleff** [comment]
This problem has to do with how you structure your Widget. use a global key that is initialized at the root of the flutter application to create a unity global widget. This will solve your issue.
