### ISSUE TITLE
Error - Unable to initialize the Unity Engine 

### ISSUE THREAD

**Issue by gOzaru** [juicycleff/flutter-unity-view-widget#499]
**Describe the bug**
I am using the latest safety-null package of Flutter Unity Widget: flutter_unity_widget: ^4.2.3
I am trying to run the example available from current library.
I added some files from unityLibrary made by [Andrious](https://github.com/Andrious/unityLibrary)
I tested on Redmi 6A which uses Android 9.0 (a real device). 
I had changed some of the codes to fulfill the null safety procedures. 

**To Reproduce**
Steps to reproduce:
1. Clone this [repository](https://github.com/gOzaru/unity_flutter) 
2. Plug real Android smartphone
3. Debug
4. Tap on one of the example
5. Error -> Unable to initialize the Unity Engine

**Expected behavior**
It should have run the 3D cube rotation scene, but nothing happened except for error.

**Screenshots**
![SS - Unity Flutter Widget Error - Unable to init Unity Engine](https://user-images.githubusercontent.com/3258483/143793425-85a21047-e819-48a4-9d8c-5214b1f75d0a.png)

**Unity:**
 - OS: Windows 10
 - Version: I used the scene from example 

**Smartphone:**
 - Device: Redmi 6A
 - OS: Android 9.0

**Comment by juicycleff** [comment]
You just need to run on real device and not emulator

**Comment by bkoznov** [comment]
I'm getting the same errror, has happened on a Pixel 3a XL and a Pixel 6a (both real devices, neither emulators). Let me know what other information would be most helpful @juicycleff or if I should open a new ticket.

**Comment by bkoznov** [comment]
It happens both on a different project and if I clone  @gOzaru 's project (with a kotlin and compilesdkversion update). Might this not be something done incorrectly in project configuration rather than just emulators ?

**Comment by hdjddvxjxvxjxbdjdjdjjd-gif** [comment]
Unable to initialize the Unity Engine.
