### ISSUE TITLE
Could not resolve project :arcore_client

### ISSUE THREAD

**Issue by CodeFoxLk** [juicycleff/flutter-unity-view-widget#500]
![image](https://user-images.githubusercontent.com/85751396/144642868-54b8df53-7893-4e42-96bf-c60e4baef575.png)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :arcore_client.
     Required by:
         project :app
      > No matching configuration of project :arcore_client was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by juicycleff** [comment]
Sometimes, the unity build script on android might change and will require some manual intervention. Please make sure all your dependencies in unity are properly imported
