### ISSUE TITLE
Multiple Android FUW/Unity version combos failing with same error

### ISSUE THREAD

**Issue by OGmetamonkey** [juicycleff/flutter-unity-view-widget#502]
**Describe the bug**
Trying to build this for Android with a Flutter Unity Widget (FUW) pre null-safety version. Can debug all combos to the point of this error:

> GeneratedPluginRegistrant.java:42: error: cannot find symbol
>     FlutterUnityWidgetPlugin.registerWith(registry.registrarFor("com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetPlugin"));

**To Reproduce**
1. Add a working unity build to the flutter project via the directions for the applicable FUW version. Try these combos:
A. Unity 2019.3.14f1 & FUW 4.1.0
B. Unity 2020.2.3f1 & FUW 4.1.0
C. Unity 2021.1.15f1 & FUW 4.1.0
D. All three Unity's above with ^4.0.0-alpha.2 & 4.0.0 (Which shows as 4.1.0 in the pubspec.lock)
2. Configure with the appropriate flutter unity integration package. (Tried may combinations)
3. Flutter --> Export to Android
4. Open in Android studio, sync and try to build to android device.

**Expected behavior**
I expected the app to build. Instead it fails with the error shown above.

**Unity (please complete the following information):**
A. Unity 2019.3.14f1 & FUW 4.1.0
B. Unity 2020.2.3f1 & FUW 4.1.0
C. Unity 2021.1.15f1 & FUW 4.1.0
D. All three Unity's above with ^4.0.0-alpha.2 & 4.0.0 (Which shows as 4.1.0 in the 
macOS Monteray 12.0.1
Android Studio 4.1.2
Flutter 1.22.6 
Dart 2.10.5

**Additional context**
Also tried to also revert to the old method and 0.1.6+8 but ran into lots of PackageCache errors. Deleting the PackageCache does not help that.

What is a good (PRE NULL SAFETY) working combo of unity/FUW/flutter unity integration package version numbers that actually works?

**Comment by juicycleff** [comment]
Thanks @OGmetamonkey will take a look at this

**Comment by OGmetamonkey** [comment]
> Thanks @OGmetamonkey will take a look at this

Thank you! I also just tried using a new combo.

FUW version 0.1.6+8, FlutterUnityIntegration-v4.1.0.unitypackage, and Unity version 2019.3.14f1. 

The flutter project compiled and opened, however trying to open Unity crashed with a 'couldn't find "libmain.so"' error.

I also tried to attempt this with an older version of FlutterUnityIntegration package with the same result.

**Comment by OGmetamonkey** [comment]
Another attempt in with FUW version 0.1.6+8, UnityExport method (using Build.cs, XCodePostBuild.cs, UnityMessageManager.cs, JsonDotNet and link.xml , and Unity version 2019.3.14f1.

Exported using 'Flutter--> Export Android (Unity 2019.3*)
1. It builds UnityExport folder in android.
2. Right click unity-classes.jar and add as library to project. This created items inside UnityExport/libs/unity-classes.jar
3. Added  following to settings.gradle
```
 include ":UnityExport"
 project(":UnityExport").projectDir = file("./UnityExport")
```
Error:

> Build file 'project/flutter-unity-view-widget-master/android/build.gradle' line: 39 .. can't find unity-classes

So I removed that line. Then I got:

> 1: Task failed with an exception.
> -----------
> * Where:
> Build file '/project/android/UnityExport/build.gradle' line: 9
> 
> * What went wrong:
> A problem occurred evaluating project ':UnityExport'.
> > Project with path ':unity-classes' could not be found in project ':UnityExport'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> A problem occurred configuring project ':UnityExport'.
> > compileSdkVersion is not specified.

* What went wrong:
A problem occurred evaluating project ':flutter_unity_widget'.
> Project with path ':unity-classes' could not be found in project ':flutter_unity_widget'.

**Comment by OGmetamonkey** [comment]
> Another attempt in with FUW version 0.1.6+8, UnityExport method (using Build.cs, XCodePostBuild.cs, UnityMessageManager.cs, JsonDotNet and link.xml , and Unity version 2019.3.14f1.
> 
> Exported using 'Flutter--> Export Android (Unity 2019.3*)
> 
> 1. It builds UnityExport folder in android.
> 2. Right click unity-classes.jar and add as library to project. This created items inside UnityExport/libs/unity-classes.jar
> 3. Added  following to settings.gradle
> 
> ```
>  include ":UnityExport"
>  project(":UnityExport").projectDir = file("./UnityExport")
> ```
> 
> Error:
> 
> > Build file 'project/flutter-unity-view-widget-master/android/build.gradle' line: 39 .. can't find unity-classes
> 
> So I removed that line. Then I got:
> 
> > ## 1: Task failed with an exception.
> > 
> > * Where:
> >   Build file '/project/android/UnityExport/build.gradle' line: 9
> > * What went wrong:
> >   A problem occurred evaluating project ':UnityExport'.
> > 
> > > Project with path ':unity-classes' could not be found in project ':UnityExport'.
> > 
> > 
> > 
> > * Try:
> >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> >   ==============================================================================
> > 
> > ## 2: Task failed with an exception.
> > 
> > * What went wrong:
> >   A problem occurred configuring project ':UnityExport'.
> > 
> > > compileSdkVersion is not specified.
> 
> * What went wrong:
>   A problem occurred evaluating project ':flutter_unity_widget'.
> 
> > Project with path ':unity-classes' could not be found in project ':flutter_unity_widget'.

Added include ':app'**, ':unity-classes'** to settings.gradle. Resulted in:

> Could not determine the dependencies of task ':UnityExport:compileDebugAidl'.
> > Could not resolve all task dependencies for configuration ':UnityExport:debugCompileClasspath'.
>    > Could not resolve project :unity-classes.
>      Required by:
>          project :UnityExport
>       > Unable to find a matching configuration of project :unity-classes:
>           - None of the consumable configurations have attributes.
>

**Comment by OGmetamonkey** [comment]
Tried most recent config with Unity 2021.1.15f1. Same issue.

I noticed in an old working project I have (Can no longer update the unity build in it), there is a unity-classes.jar folder in both the UnityExport/libs folder and the root/android folder. When I export now, I only get unity-classes.jar in the UnityExport/libs folder, even after adding as library.

**Comment by OGmetamonkey** [comment]
OK @juicycleff , I gave up on older implementations. PLEASE IGNORE THE PREVIOUS ATTEMPTS AND, IF YOU CAN :), HELP WITH THIS ONE. I am trying 4.1.0 with Unity 2020.2.241 exactly according to the README, as the tutorial video is extremely outdated. The error that keeps sticking me is at the bottom, and I documented everything I did to get there.

To begin, I cleared all previous evidence of a UnityFlutterWidget integration from my project, deleted my pub cache, cleaned my project, invalidated my caches and restarted android studio.

Note: The README says to put the FlutterUnityIntegration package file in the main unity project folder, while the example shows it in the unity project assets folder. Probably irrelevant.

Note: I copied my NDK path from Unity into the gradle.properties file of my project/android folder as instructed in the guide.

I then closed Android studio and opened the unity project in unity.

**When following directions exactly, these warnings show up on import of FlutterUnityIntegration package:**

> Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. Project/unity/unityproject/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)

> Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/FlutterUnityIntegration/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.dll)

To fix this, I had to [remove the JsonDotNet folder from the FlutterUnityIntegration package.](https://github.com/juicycleff/flutter-unity-view-widget/issues/414)

**Then I got the "build cannot be appended" error on export android, which I fixed with [this]**(https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249).

**Android Export gave two weird exceptions regarding the build paths, where it was trying to build at another projects path. I opened unity preferences --> GI Cache and cleaned the cache:** 

I then used "Export Unity" again and it created the UnityLibrary folder. Saved and closed Unity.

**Got this error when trying to compile the flutter project in android studio:**
* Where:

> Build file '/Project/android/unityLibrary/build.gradle' line: 35
> 
> * What went wrong:
> A problem occurred evaluating project ':unityLibrary'.
> > Could not get unknown property 'unityStreamingAssets' for object of type com.android.build.gradle.internal.dsl.AaptOptions.

Fixed that with [this](https://github.com/juicycleff/flutter-unity-view-widget/issues/319#issuecomment-871286167), and synced the project with grade files.

AND AFTER ANOTHER ATTEMPT HERE WE ARE WITH THE SAME OLD ERROR:

> /Project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:42: error: cannot find symbol
>     FlutterUnityWidgetPlugin.registerWith(registry.registrarFor("com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetPlugin"));
>                             ^
>   symbol:   method registerWith(Registrar)
>   location: class FlutterUnityWidgetPlugin
> 1 error
> 
> FAILURE: Build failed with an exception.

**Comment by juicycleff** [comment]
@OGmetamonkey lets get on Skype I have a private fix for you write me on juicycleff on Skype. I will need some explanation to give

**Comment by OGmetamonkey** [comment]
> @OGmetamonkey lets get on Skype I have a private fix for you write me on juicycleff on Skype. I will need some explanation to give

Just created a skype account and messaged you. FYI I also tried a fresh install of the latest recommended Android Studio Beta. Same error.

**Comment by OGmetamonkey** [comment]
Hi @juicycleff ... I have been troubleshooting for days and cannot get past 

> GeneratedPluginRegistrant.java:42: error: cannot find symbol

If you have a lead at all, please share! Thanks

**Comment by OGmetamonkey** [comment]
I discovered something interesting. If I delete the UnityLibrary folder before exporting it gets re-created, however unity-classes.jar and proguard-unity.txt show a "Date Modified" from days ago, while the rest of the files show the current time. This tells me there is a cache issue. Any thoughts? @juicycleff

**Comment by OGmetamonkey** [comment]
Still have not solved this problem. May try to migrate the entire app to null safety in order to use the latest FUW implementation.

**Comment by juicycleff** [comment]
@OGmetamonkey fyi I never got the message on Skype

**Comment by juicycleff** [comment]
@OGmetamonkey this is old, but yes, unity does sometimes cache the build. If you have a messed-up export, the advice is to delete it manually and rexport.

**Comment by OGmetamonkey** [comment]
@juicycleff Any thoughts on where I'm missing a cache? I clean everything I know of and I still get a new proguard and unity-classes.far from Feb 12.... so still getting this error:

> android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:43: error: cannot find symbol
>     FlutterUnityWidgetPlugin.registerWith(registry.registrarFor("com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetPlugin"));

**Comment by juicycleff** [comment]
Will take a look and get back to you @OGmetamonkey

**Comment by OGmetamonkey** [comment]
Thanks @juicycleff 

After days of trial and error I finally got the app running, however now unity gives me a 

Failure to initialize! Your hardware does not support this application.
Failed to load 'libmain.so'
....

 I'm not running an emulator. Running on a Google Nexus 5X, Android 8.1.0

**Comment by OGmetamonkey** [comment]
@juicycleff Upgrading to Unity 2020.3.24f1 fixed that issue. So, 4.1.0 finally works on Android after a lot of version edits, etc. 

..Unfortunately the upgrade didn't improve performance on Android, and in fact seems to have reduced it a bit.
