### ISSUE TITLE
Unity scene zooms in on IOS Phone after Xcode build first time entering.

### ISSUE THREAD

**Issue by IgeeTheron** [juicycleff/flutter-unity-view-widget#503]
On IOS when I run the app from Xcode and then login on the phone the unity scene displays but the scene is zoomed in like it filled a screen 4 times the size than the screen it should be displayed on. Only the top left corner of the scene is displayed. When i log out and log back in it displays the whole scene. If i stop the run from Xcode, run the app and log back in it zooms back in.

On android it works normal and the whole scene is used.

Scene example (Cant show my scene so just using an image to show what happens): 

Full scene:
![476323 por](https://user-images.githubusercontent.com/53433477/145224879-76b4bd6c-f735-4a62-8243-b7ef53ab849c.jpg)

Scene displayed on IOS phone:
![476323 cut](https://user-images.githubusercontent.com/53433477/145224952-bc48fa1d-2a33-48b7-9a61-1f085fa3612f.jpg)

What can I do to fix this issue on IOS?

**Comment by ibmiz** [comment]
I have the same issue when loading an xr camera view on iOS. Going back a page and then loading the unity widget fixes the zoom for me

**Comment by juicycleff** [comment]
It's weird if that's the case, I suggest you look at how your widget is stacked in your app. But sometimes properly handling your app lifecycle on the Unity end does help alot. Trying making sure the unity game is optimized for mobile, profile and see the performance sometimes it might just be just the memory footprint from Unity.

If that's still the case try another unity version, but it shouldn't crop the view even if you go out and come back to the app.

**Comment by juicycleff** [comment]
I will close feel free to reopen

**Comment by javalotte** [comment]
FYI, I had a workaround by downgrading Unity.  I looked through 2019.4.20 (working) and 2019.4.32 (bugged) changelogs and the closest thing I found was this: https://issuetracker.unity3d.com/issues/ios-display-dot-main-dot-systemwidth-slash-height-displays-the-rendering-resolution-instead-of-system-resolution

Picked a version right before this went live (applicable across all 20**.) and it seemed to fix my issue.  YMMV

**Comment by aidan-playxd** [comment]
@ibmiz Did you ever manage to solve this? We are seeing this problem on all our projects since updating them to unity 2020.3.25. As a stand alone ios build they look fine, but when embedded we see the exact same scaling issue.

**Comment by johnfriedrich** [comment]
Same here, using 2020.3.25. iOS Standalone unity builds are fine. When integrating with flutte it breaks. Android looks good in flutter

**Comment by ibmiz** [comment]
> @ibmiz Did you ever manage to solve this? We are seeing this problem on all our projects since updating them to unity 2020.3.25. As a stand alone ios build they look fine, but when embedded we see the exact same scaling issue.

Unfortunately not. My attempts were passing in the parameter 'uiLevel: 2' and also pausing the widgetcontroller and resuming it during initState(). I suggest trying those out, and see if they might work for you.

**Comment by aidan-playxd** [comment]
@ibmiz thanks, will give it try. 

We only see this on smaller IOS devices. The iPhone 6 & iPhone SE (2020) are the main culprits at the moment, no matter what we do to the container in Flutter always seems to have this 'zoomed in' effect.

**Comment by Techflinch** [comment]
> @ibmiz thanks, will give it try.
> 
> We only see this on smaller IOS devices. The iPhone 6 & iPhone SE (2020) are the main culprits at the moment, no matter what we do to the container in Flutter always seems to have this 'zoomed in' effect.

did you try that? did it work?

**Comment by aidan-playxd** [comment]
@Techflinch yep we tried this out, no difference unfortunately.
