### ISSUE TITLE
Trouble following Setup steps

### ISSUE THREAD

**Issue by Drkstr** [juicycleff/flutter-unity-view-widget#506]
**Describe the bug**
Not seeing a Flutter menu option after importing Custome Package in step 4. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the steps described in the setup process. https://github.com/juicycleff/flutter-unity-view-widget/blob/master/README.md#setup 
2. After importing the FlutterUnityPackage.unitypackage downloaded from [here](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/scripts/FlutterUnityIntegration-v4.1.0-WithDemo.unitypackage) as a Custom Package 

**Expected behavior**
Expect to see a new menu option Flutter where we can Export to Android or iOS

**Screenshots**
<img width="1440" alt="Screen Shot 2021-12-14 at 11 57 17 pm" src="https://user-images.githubusercontent.com/3590464/146004298-9920ae2c-528a-495e-a456-526fa8cc4a41.png">

**Unity (please complete the following information):**
 - OS: MacOS Big Sur
 - Unity Version: 2020.3.24f1 LTS

**Additional context**
I am working on a 13 inch M1 Mac, not sure if this is relevant.

**Comment by nurlan-dzhavadov** [comment]
So did you solve this problem? If so, how did you do it?
