### ISSUE TITLE
Question: is unity running in the background all the time?

### ISSUE THREAD

**Issue by omgmax** [juicycleff/flutter-unity-view-widget#508]
Just wondering if unity is running in the background all the time with this implementation.

**Comment by OGmetamonkey** [comment]
I believe after Unity launches for the first time it will continue running for the entire app session. You can minimize the impact of this by switching to an empty scene when you don't need Unity running.

**Comment by MysteryKang** [comment]
you can turn PlayerLoop to false to shut down unity to save energy, and when you want to run unity again you can just turn it back on.

**Comment by AkhilRaja** [comment]
@MysteryKang can you please provide some more details on how to do that ?
I'm facing a lot of issues when trying to unload/dispose. A lot of crashes and freezes.

**Comment by juicycleff** [comment]
@AkhilRaja you do that in unity just fire an event from a flutter to tell unity to go into this mode https://docs.unity3d.com/ScriptReference/LowLevel.PlayerLoop.SetPlayerLoop.html and yes Unity always runs in the background after the first launch.
