### ISSUE TITLE
Unity to Flutter Communication Steps Unclear

### ISSUE THREAD

**Issue by jafitz26** [juicycleff/flutter-unity-view-widget#512]
I am very new to Unity, but one of the Unity-Flutter Communications steps was unclear to me.

I created the Unity Message Manager component, and I know I'm supposed to add:

UnityMessageManager.Instance.SendMessageToFlutter("Message to send");

somewhere in the GameObject. But what are the steps exactly to "Create a new MonoBehaviour subclass and add to the same GameObject as a script."? And where would I add the line of code above?

Thank you.

**Comment by ama22ni** [comment]
can you help me please the steps are unclear to me:(
