### ISSUE TITLE
Flutter button does not appear in unity after importing the unitypackge  

### ISSUE THREAD

**Issue by Mohammed200923** [juicycleff/flutter-unity-view-widget#522]
Flutter button does not appear in unity after importing the unitypackge

**Comment by mamonraab** [comment]
same here

**Comment by khalithartmann** [comment]
same

**Comment by timbotimbo** [comment]
Closing this as outdated, multiple new unitypackges have been added since this issue was opened.

If anyone somehow runs into this, check for compile errors in the Unity console.
The c# scripts not compiling will prevent the Flutter menu option from showing up.
