### ISSUE TITLE
Dispose should be called last

### ISSUE THREAD

**Issue by alberto-sf** [juicycleff/flutter-unity-view-widget#525]
You should always call `super.dispose()` last. The bug is [here](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/lib/src/unity_widget.dart#L123-L126)

This

```dart
super.dispose();
UnityWidgetController controller = await _controller.future;
controller.dispose();
```

should be

```dart
UnityWidgetController controller = await _controller.future;
controller.dispose();
super.dispose();
```

**Comment by juicycleff** [comment]
Yes, thanks for this feedback. Been fixed, but will be updated soon.

**Comment by juicycleff** [comment]
So for now it won't be fixed as the widget in most cases gets disposed of before super.disposed is called, thereby causing a crash in production. Thanks for the feedback 💯
