### ISSUE TITLE
Compilation error  Unresolved reference: MultiWindowSupport

### ISSUE THREAD

**Issue by maciej-szulc** [juicycleff/flutter-unity-view-widget#526]
Hey, **after upgrading to compileSdk 31** , while building I receive   "Unresolved reference: MultiWindowSupport" error.
Does anyone have an idea what is the reason?

`  ​e: /Users/maciejszulc/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-4.2.4/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt: (228, 17): Unresolved reference: MultiWindowSupport

[  +90 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.`

**Comment by maciej-szulc** [comment]
From 29. Still looking for a problem..

**Comment by bkoznov** [comment]
Interestingly, downgrading to 29 didn't fix it for me. Very interested in what you find, will update here if I find anything.

**Comment by maciej-szulc** [comment]
Now it doesn't work in any scenario... No idea what is it about

**Comment by maciej-szulc** [comment]
I rebuilt everything together with the unity project and it started working. Closing.

**Comment by jaboyc** [comment]
@maciej-szulc What do you mean you rebuilt everything together? I ran into the same problem today. I ran flutter clean, redownloaded the FlutterUnityIntegration Package, Rebuilt the Android project, and am still running into the same problem. What am I missing here?
