### ISSUE TITLE
UnityMessageManager.SendMessageToFlutter not working on android release build

### ISSUE THREAD

**Issue by sabio-dev** [juicycleff/flutter-unity-view-widget#528]
**Describe the bug**
When running the flutter app in debug mode, everything works fine. but when making a release version with "flutter build apk" the communication from unity to flutter stops working. Flutter to unity communication still works normally.

**To Reproduce**
I saw this error in a bigger project, but for demonstration I've created this example project : https://github.com/sabio-dev/unity_cube_example.

1. Clone the project
2. Simple communication from unity to flutter is done is unity/Cube/Assets/Scripts/ARTapToPlaceObject.cs
3. in Unity Flutter > Export Android
4. run the flutter app in debug. When UnityWidget opens it will change the name in the appbar to "ola" (coming from unity message)
5. run "flutter build apk" The AR wont work without updating unityandroidpermissions.aar, but that's not a problem for the test
6. flutter apk does not change appbar text when unity opens (so message is not coming)  

**Expected behavior**
Unity - Flutter Messaging working in debug and release

**Unity (please complete the following information):**
 - OS:  Ubuntu building for Android
- Version 2020.3.19f1

**Smartphone (please complete the following information):**
 - Device:  Moto Edge 20
 - OS: Android 
 - Version 11

**Comment by johnfriedrich** [comment]
Did you add proguard exclusions like described in the Readme?

**Comment by sabio-dev** [comment]
> Did you add proguard exclusions like described in the Readme?

I did not. this solved my issue. Thanks a lot.

**Comment by johnfriedrich** [comment]
> > @droncaglio In https://github.com/juicycleff/flutter-unity-view-widget#readme Expand Android Step 6.4
> 
> Thank you! Thank you! Thank you! Now its working!
> 
> I thought that this 6.4 step was only if I had enabledMinify = true, which its not my case.

Ran into the same issue. I think it gets somehow auto enabled in Release builds unless explicitibly turned off
