### ISSUE TITLE
[Question] Big Unity Package + Flutter 180mb not able to upload to Google Play Store

### ISSUE THREAD

**Issue by zamvar** [juicycleff/flutter-unity-view-widget#529]
Hello i would like to ask anybody if they have any success using this package to upload an app exceeding 150mb limit on playstore by either using Play Asset Delivery of Flutter Deferred Components?

**Comment by juicycleff** [comment]
Please use unity addressable to reduce size.

**Comment by zamvar** [comment]
great! will refer this to our unity dev
