### ISSUE TITLE
Change Unity project without re-doing all the steps

### ISSUE THREAD

**Issue by nurlan-dzhavadov** [juicycleff/flutter-unity-view-widget#532]
Hello!

Thanks for this library! I have a question: is it possible to change the Unity project inside my 'unity' folder (in my flutter project) without re-doing all the required steps?

**Comment by johnfriedrich** [comment]
If you have the unity package imported, the Export Context Menu does everything for you with a single click. If you have a lot of android libs, you can extend the Postprocess script to automize adding it to the build.gradle file.
But the export thing is necessary, thats a Unity limitation

**Comment by juicycleff** [comment]
Thanks @johnfriedrich
