### ISSUE TITLE
MonoBehaviour.OnApplicationPause(bool) is not working on iOS Platform

### ISSUE THREAD

**Issue by jungleesubbu** [juicycleff/flutter-unity-view-widget#533]
OnApplicationPause(pause) callback is not being triggered when we minimize/maximize the app.We are getting the following error when app goes into background

 Runner[21395:1581819] Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)

**Comment by jgP2verma** [comment]
I'm also getting it @juicycleff plz let us know if this is a known issue
