### ISSUE TITLE
Error when opening DemoApp with Unity version 2020.3.28f1

### ISSUE THREAD

**Issue by jyashi** [juicycleff/flutter-unity-view-widget#536]
**Describe the bug**
Error message on load 

`Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/FlutterUnityIntegration/JsonDotNet/Assemblies/Standalone/Newtonsoft.Json.dll)`

**To Reproduce**
1. Open fresh DemoApp project using the stated engine version
2.  Continue to open after ignoring the enter safe mode message
3.  See the error

**Expected behavior**

**Screenshots**

**Unity (please complete the following information):**
 - OS: Windows 10
 - Version 2020.3.28f1

**Comment by johnfriedrich** [comment]
Remove the Assets/FlutterUnityIntegration/JsonDotNet folder

**Comment by jyashi** [comment]
> Remove the Assets/FlutterUnityIntegration/JsonDotNet folder

Thanks for the reply. It solved that problem but now i am getting this problem:

> DirectoryNotFoundException: Could not find a part of the path 'C:\Users\UserName\Documents\GitHub\flutter-unity-view-widget\example\unity\DemoApp\Builds\flutterunitywidgets.apk\unityLibrary'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.Directory.InternalGetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.Directory.GetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Build.Copy (System.String source, System.String destinationPath) (at Assets/FlutterUnityIntegration/Editor/Build.cs:162)
Build.DoBuildAndroid (System.String buildPath, System.Boolean isPlugin) (at Assets/FlutterUnityIntegration/Editor/Build.cs:62)
Build.DoBuildAndroidLibrary () (at Assets/FlutterUnityIntegration/Editor/Build.cs:26)

 I thought after using Flutter ---> Export Android  the output was supposed to go directly to android folder so why is it looking for 

> flutterunitywidgets.apk\unityLibrary

**Comment by johnfriedrich** [comment]
Please read the full ReadMe. If you follow all steps, you should not encounter this issue

**Comment by jyashi** [comment]
> Please read the full ReadMe. If you follow all steps, you should not encounter this issue

I did read the whole readme before attempting though...

The one thing I am unsure of is in the docs they refer to having FlutterUnityPackage.unitypackage 

But I can only see a FlutterUnityIntegration.unitypackage in the folders. Are these the same files right?

**Comment by jyashi** [comment]
Closing here and starting new issue here ----> https://github.com/juicycleff/flutter-unity-view-widget/issues/537
