### ISSUE TITLE
Android: screen is frozen even with ^2020.3.25 and OpenGLES3 

### ISSUE THREAD

**Issue by selamisafa** [juicycleff/flutter-unity-view-widget#538]
**Describe the bug**
Scenes and Scripts loads and works but the screen is frozen
I'm closing the page to close the unity.
```
Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => MainApp(0)));
```
The scene loads and all the debug messages from unity show up at the console. Even the sound plays but the screen is frozen.

**To Reproduce**
The code and required info are attached.
```
Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: WillPopScope(
        onWillPop: () {},
        child: SafeArea(
          bottom: true,
          child: Container(
            color: Colors.black,
            child: UnityWidget(
              borderRadius: BorderRadius.zero,
              onUnityCreated: onUnityCreated,
              onUnityMessage: onUnityMessage,
              onUnityUnloaded: onUnityUnloaded,
              onUnitySceneLoaded: (SceneLoaded sceneInfo) {
                _unityWidgetController.pause().then((_) {
                  _unityWidgetController.resume();
                });
              },
              fullscreen: false,
            ),
          ),
        ),
      ),
    );
  }

  void onUnityCreated(UnityWidgetController controller) {
    this._unityWidgetController = controller;

    controller.pause().then((_) {
      controller.resume();
    });
  }
```

**Expected behavior**
The scene opens and renders correctly.

**Unity (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] 2020.3.25f1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung S7
 - OS: [e.g. iOS8.1] Android

**Comment by j1mmyto9** [comment]
When I open another screen that doesn't contain UnityWidget. Android was frozen after switching between backgrounds.

**Comment by n00bsys0p** [comment]
Yeah the latest commits haven't changed anything for us either. I've ended up putting in some workarounds in place and mostly stabilised it for our particular use case. The way I did it was to make Unity switch itself to a "loading" scene after messaging Flutter to tell it that it was finished, and then pausing it manually after a 1 second delay. Then when we want Unity to start working again, we tell it to change scene, it informs us that it's done so, and then we do the pause/unpause dance. It's very messy, but it works pretty stably for us.

**Comment by sevantasci** [comment]
@n00bsys0p @j1mmyto9 @selamisafa 
just change unity-classes.jar manually before build , will solve every freeze problems on android
[unity-classes.zip](https://github.com/juicycleff/flutter-unity-view-widget/files/8077551/unity-classes.zip)
.

**Comment by n00bsys0p** [comment]
@sevantasci Thank you for your help. I'm not going to download a binary blob from Github and install it anywhere though - that's a very high risk approach to solving any problem, and not sustainable as it could stop working at any time. If you can provide details of how we can produce this file ourselves, I will be very happy to try it out.

**Comment by selamisafa** [comment]
> Yeah the latest commits haven't changed anything for us either. I've ended up putting in some workarounds in place and mostly stabilised it for our particular use case. The way I did it was to make Unity switch itself to a "loading" scene after messaging Flutter to tell it that it was finished, and then pausing it manually from Flutter after a 1 second delay. Then when we want Unity to start working again, we tell it to change scene, it informs us that it's done so, and then we do the pause/unpause dance. It's very messy, but it works pretty stably for us.
> 
> Also, avoid trying to `unload` at all costs - this just caused the entire app to crash for us.

I tried what you have explained in the other issues but not with the 1-second delay and it worked. But, it closes when I run "flutter run" but doesn't even close the app at the first try when I "flutter build apk --release". Any idea? Thanks for the information by the way.

**Comment by sevantasci** [comment]
@n00bsys0p its unity-classes.jar which i found from one unity version. I don't remember which unity version it was. But i only remember it was 2019.4.x . or 2019.3.x It's exact size is : 99,2 KB (101.658 byte) and disk size 100 KB (102.400 byte) . You have to download all unity 2019.4 + and 2019.3 + versions and find it. 
But you can be sure it solves all freeze problems. So it will worth to find.

**Comment by selamisafa** [comment]
The solution is expleanied by @n00bsys0p. The first comment of his on this thread solved it for me <3
