### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by lswd** [juicycleff/flutter-unity-view-widget#543]
1、implementation files('libs/unity-classes.jar') build error,The JAR package is referenced repeatedly

![图片](https://user-images.githubusercontent.com/24218775/155691032-dc240573-204e-43c5-bec1-e37289238f9e.png)

2、Implementation changed to compileOnly,build success
3、build apk success,but Flash back to run

![图片](https://user-images.githubusercontent.com/24218775/155690689-cfbb41a5-b7fc-4950-bab9-50c91f6c1c48.png)

Please help me

PS:
Flutter:
environment:
  sdk: ">=2.12.0 <3.0.0"

Unity Version:
Unity 2019.4.36f1c1 (64-bit)

**Comment by jenishkumar88** [comment]
@iswd any update ?

**Comment by juicycleff** [comment]
Please look at the example project should work just fine

**Comment by juicycleff** [comment]
Please look at the example project should work just fine
