### ISSUE TITLE
[Android] Double touch issue

### ISSUE THREAD

**Issue by tianyongpoh** [juicycleff/flutter-unity-view-widget#547]
**Describe the bug**
In android, there is a double touch input registered by the plugin.

**Expected behavior**
Touch function works as normal

**Additional context**
i noticed that in this pull request `https://github.com/juicycleff/flutter-unity-view-widget/pull/490/files` ,  the file has been correctly changed to fix the issue. however when i look at the repo even in the most recent version, `https://github.com/juicycleff/flutter-unity-view-widget/blob/master/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityView.kt`, the file still has the old code, basically replicating the issue that was supposed to be fixed.

i confirmed that this is the issue by going to the downloaded package in my pub.dartlang.org folder in my flutter folder and editing the code according to the fix. 

maybe @juicycleff can do the simple file change back and update the repo to fix this issue?

**Comment by juicycleff** [comment]
I have fixed this and removed multi-touch

**Comment by juicycleff** [comment]
I have fixed this and removed multi-touch
