### ISSUE TITLE
Android multiple pointers register per touchDown

### ISSUE THREAD

**Issue by PhiFry** [juicycleff/flutter-unity-view-widget#552]
**Describe the bug**
Every tap after the first one the UnityWidget Unity's `Input.touchCount` becomes 2 or even as high as 3 on tapDown for a brief moment to come down to 1 as intended for the rest of the gesture. This causes many issues.

**To Reproduce**

### Flutter
```dart
Scaffold(
  key: _scaffoldKey,
  body: Stack(
    children: [
      UnityWidget(
        onUnityCreated: onUnityCreated,
        onUnityMessage: _onUnityMessage,
        onUnitySceneLoaded: _onUnitySceneLoaded,
        gestureRecognizers: {
          Factory(() => EagerGestureRecognizer())
        }
      )
    ]
  )
)
```

### Unity
```c#
void Update() {
  print(Input.touchCount);
}
```
Run on Android and start tapping.

**Expected behavior**
I expect Unity to only register one touch when I tap with one finger.

**Unity (please complete the following information):**
 - OS: MacOS BigSur
 - Version: 2020.3.31f1

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android10 (api 29)

**Additional context**
FlutterUnityWidget 4.2.5

When I build directly from Unity to the device this issue doesnt occur.

**Comment by PhiFry** [comment]
@abdo400 I didnt, I had to hack it in the C# code. My problem was using the LeanTwistRotateAxis which I modified to remove any touches that are within 1px distance from another.

### From

```c#
var _fingers = Use.UpdateAndGetFingers();
```

### Into

```c#
var _fingers = Use.UpdateAndGetFingers();
var fingers = new System.Collections.Generic.List<LeanFinger>();
if (_fingers.Count >= 2) {
	for (int i = 0; i < _fingers.Count; i++) {
		bool add = true;
		for (int ii = i+1; ii < _fingers.Count; ii++) {
			var distance = Vector2.Distance(_fingers[i].StartScreenPosition, _fingers[ii].StartScreenPosition);
			// print($"Check for duplicate touches: {i} {_fingers[i].StartScreenPosition} <-> {ii} {_fingers[ii].StartScreenPosition} = {distance}");
			if (distance < 1f) {
				add = false;
				break;
			}
		}
		if (add) fingers.Add(_fingers[i]);
	}
}
```

**Comment by abdo400** [comment]
@PhiFry For me, just clicking on a UI button was registering multiple times.

I took the 
`  gestureRecognizers: {
          Factory(() => EagerGestureRecognizer())
        }`
from your example and changed it to `TapGestureRecognizer()` and it worked, though closing from the widget and opening it again detects input in the console but doesn't accept input in the app.

**Comment by juicycleff** [comment]
Please test out the latest, I removed the multi touch events on unity for Android

**Comment by PhiFry** [comment]
@juicycleff I removed my hack and my app is still working as expected :) Seems your fix has fixed it.
