### ISSUE TITLE
[Android] Touch.phase will often skip the TouchPhase.Began state

### ISSUE THREAD

**Issue by ShawkiSW** [juicycleff/flutter-unity-view-widget#553]
On Android, when trying to detect a new touch input, the app will often skip the TouchPhase.Began state. The touch as a whole will still be detected.

**To Reproduce**
In Update(), use this block of code to detect when hitting a TouchPhase.Began state.

if (Input.touchCount == 1 && Input.GetTouch(0).phase == TouchPhase.Began)
{
//log something here, or provide some indication that a touch began
}

**Expected behavior**
On every single-finger touch, we should be entering the if statement provided above

 - OS: Android
 - Unity Version 2020.3.25f1

 - Device: Samsung Galaxy S10
 - Android
 - Version 12

**Comment by juicycleff** [comment]
I think I realized this bug in my previous android implementation, it should be fixed in the latest release as of today.

**Comment by juicycleff** [comment]
I think I realized this bug in my previous android implementation, it should be fixed in the latest release as of today.
