### ISSUE TITLE
[Android-APK] Build freeze when open Camera with AR

### ISSUE THREAD

**Issue by iletai** [juicycleff/flutter-unity-view-widget#561]
**Describe the bug**
When I run flutter and debug mode, all features work without problem. But when I export build apk with release mode. App freeze with Unity when I try open AR mode.
**To Reproduce**
1. Build APK with `flutter build apk`
2. Install APK on Real Device
3. Click the button on Unity using AR with Camera
4. App freeze.

**Expected behavior**
App working normally

**Unity (please complete the following information):**
 - OS: Android
 - Version Unity 2020.3.25f1
 - 

**Smartphone (please complete the following information):**
 - Device: Samsung A20
 - OS: Android 9+

**Additional context**
In debug mode with VSCode-Flutter. App working perfectly.
I try to research to fix it (Enable OpenUsing OpenGL3, send request permission to App Flutter, ..) but seems I can't detect it.

**Comment by Kishikawa1286** [comment]
Set `UnityWidget.useAndroidViewSurface` as `false`.  This worked for me.

- Device: Oppo Reno 5
- OS: Color OS
- Version Android: 9
- Version Unity: 2020.3.31f1
- Version [flutter-unity-view-widget](https://github.com/juicycleff/flutter-unity-view-widget): 2020.3.25
- Version Flutter: 2.10.4

**Comment by iletai** [comment]
> Kishikawa1286 ありがとうございます
