### ISSUE TITLE
unitywidget is black screen

### ISSUE THREAD

**Issue by yixiaonaihe2430** [juicycleff/flutter-unity-view-widget#562]
using Flutter 2.10.4 stable and flutter-unity-view-widget 2020.3.25 and unity 2020.3.32， my mac is m1 

When I open unity with unitywidget, the screen goes black

Have you ever had this problem? Is there any solution? Thanks！

**Comment by iletai** [comment]
Read the readme and check permission needed example camera. If you using AR, please find option enable AR in PlayerSetting Unity

**Comment by yixiaonaihe2430** [comment]
> Read the readme and check permission needed example camera. If you using AR, please find option enable AR in PlayerSetting Unity

But my unity project doesn't have any permission and doesn't use AR. Does it need to be added on Info?

**Comment by changyiyao** [comment]
> 

https://github.com/juicycleff/flutter-unity-view-widget/issues/540

**Comment by juicycleff** [comment]
Black screen in unity for AR projects is a camera permissions issue, and not a flutter unity widget issue. I will close this but you can solve it using any of the flutter permissions library.

**Comment by juicycleff** [comment]
Black screen in unity for AR projects is a camera permissions issue, and not a flutter unity widget issue. I will close this but you can solve it using any of the flutter permissions library.
