### ISSUE TITLE
FlutterUnityWidgetFactory.kt: (10, 1): Class 'FlutterUnityWidgetFactory' is not abstract

### ISSUE THREAD

**Issue by LeQuangTho** [juicycleff/flutter-unity-view-widget#563]
[](https://user-images.githubusercontent.com/47267017/156560054-7f8c4274-3f18-48b3-b8f2-90e5d9664cd0.png)Describe the bug
Fail to build with the newest version of flutter_unity_widget(^2020.3.25). And the 4.2.5+1 is fine.

To Reproduce
flutter run -v
Expected behavior

Screenshots 

![image](https://user-images.githubusercontent.com/54834124/164418797-5ac768db-d74d-47b5-98da-28c1ed2529a5.png)

Unity (please complete the following information):

OS: Android
Version: 2020.3.29f1
Smartphone (please complete the following information):

Device: [e.g. iPhone6] Mi10
OS: [e.g. iOS8.1] Android
Version [e.g. 22] 31

Additional context

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.13.0-0.0.pre.655, on Microsoft Windows [Version 10.0.19044.1645], locale vi-VN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.66.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

**Comment by juicycleff** [comment]
This error looks very weird. Please try the latest version and repone this if you are still having this issue :)

**Comment by juicycleff** [comment]
This error looks very weird. Please try the latest version and repone this if you are still having this issue :)

**Comment by LeQuangTho** [comment]
![image](https://user-images.githubusercontent.com/54834124/166642448-a7f1b1f9-d4c2-4c69-8a7f-331c261efe49.png)
my project is a unity 2D application. Is it related to my error

**Comment by LeQuangTho** [comment]
[√] Flutter (Channel master, 2.13.0-0.0.pre.887, on Microsoft Windows [Version 10.0.19044.1645], locale vi-VN)
    • Flutter version 2.13.0-0.0.pre.887 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b3838eb3de (23 minutes ago), 2022-05-04 03:24:08 -0400
    • Engine revision 84d3539062
    • Dart version 2.18.0 (build 2.18.0-82.0.dev)
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\Admin\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8309675\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Users\Admin\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8309675
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by LeQuangTho** [comment]
![image](https://user-images.githubusercontent.com/54834124/166643225-73f40a62-154f-478d-b17f-1efe4eca2800.png)
