### ISSUE TITLE
A problem occurred evaluating project ':unityLibrary'.

### ISSUE THREAD

**Issue by Roxgame95** [juicycleff/flutter-unity-view-widget#566]
**Describe the bug**
am working with flutter guy am unity developer i build the project with help of this repo and i send him the UnityLibrary folder 
he tried to integrate it but he is getting an error 

* Where:
Build file 'E:\Project\Flutter\test\android\unityLibrary\build.gradle' line: 36

* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
Could not get unknown property 'unityStreamingAssets' for object of type com.android.build.gradle.internal.dsl.AaptOptions.

**Comment by juicycleff** [comment]
This has been fixed with the latest unitypackage please take a look or us the example project.

**Comment by juicycleff** [comment]
This has been fixed with the latest unitypackage please take a look or us the example project.
