### ISSUE TITLE
[iOS] Sample scene app opens only once

### ISSUE THREAD

**Issue by grayhong** [juicycleff/flutter-unity-view-widget#575]
**Describe the bug**

Hello! 
First of all, Thanks for the awesome work! 

I succeeded in building the SampleScene and export to iOS, and it works well in the first build. 
However, if I try to open the build again after terminating the app, it won't open again. 
Since the app is quitted and reopened, I can't check the Xcode log..
Any idea?

**To Reproduce**
1. Export a sample scene in iOS
2. Runs well for the first time
3. Quit the app
4. Rerun the app by touching the icon
5. Cannot open it.

**Expected behavior**

Reopened..

**Screenshots**

**Unity (please complete the following information):**
 - OS: iOS
 - Version 2020.03

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15
 - Version 

**Additional context**

Unity 2020.03 Xcode 13.1
flutter-unity-view-widget unitypackage [v4.1](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/unitypackages/FlutterUnityIntegration-v4.1.0-WithDemo.unitypackage) from current master branch [90ac4b0](https://github.com/juicycleff/flutter-unity-view-widget/commit/90ac4b005c21d42b8040332cbaf221327e634058) 
pubspec dependency `flutter_unity_widget: 4.2.1`

**Comment by grayhong** [comment]
> Hi @grayhong! Please provide a few more details for an appropriate solution.
> 
> * Does quitting the app mean terminating or moving background? Which one?
> 
> If it is moving BG, #148 might be helpful.

Hello @Anishishi ! Thanks for the reply!
The issue happens when I terminate the app and try to reopen the app. 
The app shuts down immediately when I touch the app icon. :(

**Comment by Anishishi** [comment]
It could be because you are running the app in [the debug mode of Flutter](https://docs.flutter.dev/testing/build-modes).
In the debug mode, the app installed cannot reopen. So, if you want to reopen the app after terminating, you can run the app in the release mode. 
`
flutter run --release
`

**Comment by Anishishi** [comment]
@grayhong 
It could be because you are running the app in [the debug mode of Flutter](https://docs.flutter.dev/testing/build-modes).
In the debug mode, the app installed cannot reopen. So, if you want to reopen the app after terminating, you can run the app in the release mode. 
`
flutter run --release
`
