### ISSUE TITLE
[iOS] Massive warning when the app goes to background

### ISSUE THREAD

**Issue by grayhong** [juicycleff/flutter-unity-view-widget#576]
**Describe the bug**

When the iOS build is in background state, the warning saying `Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background)` appears a lot.
Is there any way to suppress this warning message?
Thank you.

**To Reproduce**
1. Run the Sample Scene
2. Pause the app by going to the background mode
3. Xcode warning message comes out.

**Expected behavior**

No warning

**Screenshots**

**Unity (please complete the following information):**
 - OS: iOS
 - Version 2020.03

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15
 - Version 

**Additional context**

Unity 2020.03 Xcode 13.1
flutter-unity-view-widget unitypackage [v4.1](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/unitypackages/FlutterUnityIntegration-v4.1.0-WithDemo.unitypackage) from current master branch [90ac4b0](https://github.com/juicycleff/flutter-unity-view-widget/commit/90ac4b005c21d42b8040332cbaf221327e634058) 
pubspec dependency `flutter_unity_widget: 4.2.1`

**Comment by dawiddszewczyk** [comment]
Hi @grayhong, can you upgrade Unity to the 2021.3.4f1 version and import the latest unity package? Also, we recommend using the newest flutter unity versions. If problem still exist please reopen this issue.
