### ISSUE TITLE
C# compile errors in NativeApi.cs

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#577]
**Describe the bug**
NativeApi.cs has compile errors due to missing `using` statements if the build target is set to Android.
These were probably removed to get rid of warnings because some other build targets do no use them.

Location:
- `example/unity/DemoApp/Assets/FlutterUnityIntegration/NativeAPI.cs`
- `unitypackages/fuw-2022.1.0.unitypackage` (file included in package)

Can be fixed by adding some using statements.
```
#if UNITY_ANDROID
    using System;
    using UnityEngine;
#endif
```

**To Reproduce**
1. Open the example unity project, or import the unitypackage in a new project.
2. Switch build target to Android.

**Expected behavior**
You shouldn't have to fix compile errors when opening an example project.

**Screenshots**
![errors](https://user-images.githubusercontent.com/11444698/167818070-7166c8e1-0657-4522-8c55-09f5a4d97241.jpg)

**Unity:**
 -  Unity 2022.1.0b16

**Comment by Ahmadre** [comment]
Already Fixed. Please use this new unitypackage: https://github.com/juicycleff/flutter-unity-view-widget/blob/master/unitypackages/fuw-2022.1.1-v2.unitypackage
