### ISSUE TITLE
how to configure my .gitIgnored file

### ISSUE THREAD

**Issue by ZhZhZhen** [juicycleff/flutter-unity-view-widget#579]
I work in a multi-person team，but the file under '/unityLibrary/src/main/Il2CppOutputProject/Source/il2cppOutput/lumpedcpp/' include local path.
and there are many folders named build，I'm not sure if I want to ignore them
plz help me

**Comment by ZhZhZhen** [comment]
if i add the 'build/'  in gitignord
it will occur when i run project，because i lose the IL2CPP/build folder
android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp

**Comment by dawiddszewczyk** [comment]
@ZhZhZhen  I think every one of you on the team needs to have a Unity project and re-export the iOS/ Android version.
Back to your question, I recommend you to 
`.gitignore`

`#Android`

`android/unityLibrary/build/**`
`android/unityLibrary/libs/**`
`android/unityLibrary/symbols/**`
`android/unityLibrary/src/**`
`/config_files/**`

`#iOS`

`ios/unityLibrary/*`
