### ISSUE TITLE
FlutterUnityWidgetFactory.kt 

### ISSUE THREAD

**Issue by blink616** [juicycleff/flutter-unity-view-widget#580]
I am running Flutter-unity-widget on unity 2019.4.35f1 using the latest release of the flutter_unity_package in repo

I keep getting this error. Tried building the project multiple times and removed the cache for unity project.
Can anyone please tell what to do?

**Expected behavior**
Integrate Unity in to flutter

**Screenshots**

**Unity (please complete the following information):**

D:\flutter_windows_2.5.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-2022.1.0+4\android\src\main\kotlin\com\xraph\plugin\flutter_unity_widget\FlutterUnityWidgetFactory.kt: (9, 1): Class 'FlutterUnityWidgetFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: D:\flutter_windows_2.5.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-2022.1.0+4\android\src\main\kotlin\com\xraph\plugin\flutter_unity_widget\FlutterUnityWidgetFactory.kt: (14, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.
> Compilation error. See log for more details
2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jaboyc** [comment]
I was also experiencing this issue when using Flutter 3. I have confirmed that downgrading flutter to v2.10 using `flutter downgrade v2.10.0` _does_ avoid this issue though. I'm also seeing this issue appearing in other dart packages. I'm wondering @juicycleff  if there is anything that can be done to fix this issue in this repo, or if a flutter update is mandatory before any builds can be made in Flutter 3.

**Comment by blink616** [comment]
> I was also experiencing this issue when using Flutter 3. I have confirmed that downgrading flutter to v2.10 using `flutter downgrade v2.10.0` _does_ avoid this issue though. I'm also seeing this issue appearing in other dart packages. I'm wondering @juicycleff if there is anything that can be done to fix this issue in this repo, or if this is completely on Flutter's side and we need to wait for them to release an update before any apps with this package can be used in Flutter 3.

So I just downgrade the flutter sdk to 2? And use tht one instead?

**Comment by Anishishi** [comment]
@blink616 
This problem is caused by the change in the 'PlatformViewFactory' implementation. So, the problem will be solved by changing the implementation as follows.

In FlutterUnityWidgetFactory.kt,

```
override fun create(context: Context, id: Int, args: Any): PlatformView {

...

return builder.build(
                id,
                context,
                binaryMessenger,
                lifecycleProvider
        )
```
to
```
override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {

...

return builder.build(
                viewId,
                context!!,
                binaryMessenger,
                lifecycleProvider
        )
```

**Comment by juicycleff** [comment]
There is a breaking change in Flutter 3.0.0, will fix it in the next release. it's affecting most packages too

**Comment by Anishishi** [comment]
Thank you very much. I will temporarily close my pull request. I'm looking forward to releasing the new flutter-unity-widget. Thank you!

**Comment by LeQuangTho** [comment]
I also mentioned this problem before
https://github.com/juicycleff/flutter-unity-view-widget/issues/563#issuecomment-1117031574

**Comment by LeQuangTho** [comment]
> @blink616 This problem is caused by the change in the ['PlatformViewFactory' implementation](https://api.flutter.dev/javadoc/io/flutter/plugin/platform/PlatformViewFactory.html) for Flutter3.0.0. So, the problem will be solved by changing the implementation as follows.
> 
> In FlutterUnityWidgetFactory.kt,
> 
> ```
> override fun create(context: Context, id: Int, args: Any): PlatformView {
> 
> ...
> 
> return builder.build(
>                 id,
>                 context,
>                 binaryMessenger,
>                 lifecycleProvider
>         )
> ```
> 
> to
> 
> ```
> override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {
> 
> ...
> 
> return builder.build(
>                 viewId,
>                 context!!,
>                 binaryMessenger,
>                 lifecycleProvider
>         )
> ```

thank you bro. 🙌🙌🙌🙌

**Comment by LeQuangTho** [comment]
@juicycleff in the next version you can edit the file "FlutterUnityWidgetFactory.kt" okay?. So that I don't have to manually edit in other new projects

and i want to ask is there any way to completely shutdown the Unity app but keep the Flutter app running. Because when I call Quit() the whole application stops (Unity + Flutter)

Thanks!

**Comment by juicycleff** [comment]
Hi @LeQuangTho this is a limitation from unity as a library. Unity is attached to the process that calls it and as sun has calling quit totally kills the process unity is attached to which is the process Flutter Activity is attached to and hence it kills the app. Only solution is lunch unity in a separate activity, there's support for that or use the unload feature if you need to save some memory.

**Comment by juicycleff** [comment]
> Thank you very much. I will temporarily close my pull request. I'm looking forward to releasing the new flutter-unity-widget. Thank you!

It's been released but it comes with some issues for Android, please look at the notice in the readme

**Comment by LeQuangTho** [comment]
> @juicycleff in the next version you can edit the file "FlutterUnityWidgetFactory.kt" okay?. So that I don't have to manually edit in other new projects
> 
> and i want to ask is there any way to completely shutdown the Unity app but keep the Flutter app running. Because when I call Quit() the whole application stops (Unity + Flutter)
> 
> Thanks!

thank you so much! 😉😉😉

**Comment by LeQuangTho** [comment]
> Hi @LeQuangTho this is a limitation from unity as a library. Unity is attached to the process that calls it and as sun has calling quit totally kills the process unity is attached to which is the process Flutter Activity is attached to and hence it kills the app. Only solution is lunch unity in a separate activity, there's support for that or use the unload feature if you need to save some memory.

Thank you so much! 😉😉😉
