### ISSUE TITLE
Different Unity Scene(Android)

### ISSUE THREAD

**Issue by kepinpinn** [juicycleff/flutter-unity-view-widget#582]
I have 2 objects in 2 different unity scene. There's a BoxScene and SphereScene.
What should i do if i want to show different scene in android flutter? Thankyou

**Comment by gneL1** [comment]
hello, you should use `SceneManager` api to load different scene, and you can get useage in next url.  
[https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html)
after this, you can use `postMessage` meshod in `Flutter` to notify` Unity` load different scene.

**Comment by kepinpinn** [comment]
> hello, you should use `SceneManager` api to load different scene, and you can get useage in next url. https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html after this, you can use `postMessage` meshod in `Flutter` to notify` Unity` load different scene.

Thankyou! i'll try it

**Comment by juicycleff** [comment]
The feedbacks are right just fire events to unity to change scenes, Maybe a might add such functionality hmmm. knowing a lot of people only use flutter

**Comment by omarsalem15** [comment]
I want to make a button in Flutter screen to open a specific scene in unity
I don't want to change the scenes from unity , I want to change it from a screen in flutter

**Comment by felpower** [comment]
> I want to make a button in Flutter screen to open a specific scene in unity I don't want to change the scenes from unity , I want to change it from a screen in flutter

Make sure you have a GameObject in your Unity Scene. For example I have a dummy scene, which is just black. You can add the  SceneLoader.cs from the FlutterUnityIntegration to the Scene. Then you can call the LoadScene method from your Flutter Code like that unityWidgetController?.postMessage('SceneLoader', 'LoadScene', levelIdx);
Just make sure you do not load it directly in the onUnityCreatedMode but rather start a timer in the initState Method

```dart
 @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback(_changeScene);
  }
```
