### ISSUE TITLE
EditorUserBuildSettings errors after deleting JsonDotNet folder

### ISSUE THREAD

**Issue by rmib200** [juicycleff/flutter-unity-view-widget#585]
**Describe the bug**
Two errors appear after deleting the JsonDotNet folder:

Assets\FlutterUnityIntegration\Editor\Build.cs(276,37): error CS0117: 'EditorUserBuildSettings' does not contain a definition for 'iOSXcodeBuildConfig'

Assets\FlutterUnityIntegration\Editor\Build.cs(276,59): error CS0103: The name 'XcodeBuildConfig' does not exist in the current context

I'm building for android so I don't know why those errors appears. I would really appreciate some help.

**To Reproduce**
1. Import Package as directed in readme
2. Delete JsonDotNet folder
3. Implement this reply https://github.com/juicycleff/flutter-unity-view-widget/issues/581#issuecomment-1126810164

**Expected behavior**
A "Flutter" option should appear in the navbar.

**Screenshots**

**Unity (please complete the following information):**
  OS: Windows 10
  Version 2020.3.28f1

**Smartphone (please complete the following information):**
  OS: Android

**Additional context**

**Comment by MostafaSolimanMO** [comment]
Same Here

**Comment by rmib200** [comment]
Issue was resolved here: https://github.com/juicycleff/flutter-unity-view-widget/issues/581#issuecomment-1131607649
