### ISSUE TITLE
Why need com.unity3d.player.UnityPlayer.addPhoneCallListener()? It need TelephonyPermissions.checkReadPhoneState

### ISSUE THREAD

**Issue by Arlen0615** [juicycleff/flutter-unity-view-widget#586]
Hi, 

I use 2022.1.0+4 version, TelephonyManager permission request.

**android.telephony.TelephonyManager.listen(android.telephony.PhoneStateListener, int) (TelephonyManager.java:6798)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void com.unity3d.player.UnityPlayer.addPhoneCallListener() ((null):-1)**

Bug Trace:
F/le.nft_contrac(29691): java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.SecurityException: listen
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at java.lang.Exception android.os.Parcel.createExceptionOrNull(int, java.lang.String) (Parcel.java:2437)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at java.lang.Exception android.os.Parcel.createException(int, java.lang.String) (Parcel.java:2421)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void android.os.Parcel.readException(int, java.lang.String) (Parcel.java:2404)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void android.os.Parcel.readException() (Parcel.java:2346)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(int, java.lang.String, java.lang.String, com.android.internal.telephony.IPhoneStateListener, int[], boolean) (ITelephonyRegistry.java:1036)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void android.telephony.TelephonyRegistryManager.listenFromListener(int, java.lang.String, java.lang.String, android.telephony.PhoneStateListener, int, boolean) (TelephonyRegistryManager.java:250)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void android.telephony.TelephonyManager.listen(android.telephony.PhoneStateListener, int) (TelephonyManager.java:6798)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void com.unity3d.player.UnityPlayer.addPhoneCallListener() ((null):-1)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at boolean com.unity3d.player.UnityPlayer.access$300(com.unity3d.player.UnityPlayer) ((null):-1)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):-1)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:226)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void android.os.Looper.loop() (Looper.java:313)
F/le.nft_contrac(29691): java_vm_ext.cc:579]   at void com.unity3d.player.UnityPlayer$e.run() ((null):-1)
F/le.nft_contrac(29691): java_vm_ext.cc:579] Caused by: android.os.RemoteException: Remote stack trace:
F/le.nft_contrac(29691): java_vm_ext.cc:579] 	at com.android.internal.telephony.TelephonyPermissions.enforceCarrierPrivilege(TelephonyPermissions.java:634)
F/le.nft_contrac(29691): java_vm_ext.cc:579] 	at com.android.internal.telephony.TelephonyPermissions.checkReadPhoneState(TelephonyPermissions.java:149)
F/le.nft_contrac(29691): java_vm_ext.cc:579] 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadPhoneState(TelephonyPermissions.java:94)
F/le.nft_contrac(29691): java_vm_ext.cc:579] 	at com.android.server.TelephonyRegistry.checkListenerPermission(TelephonyRegistry.java:3145)
F/le.nft_contrac(29691): java_vm_ext.cc:579] 	at com.android.server.TelephonyRegistry.listen(TelephonyRegistry.java:1037)
F/le.nft_contrac(29691): java_vm_ext.cc:579] 
F/le.nft_contrac(29691): java_vm_ext.cc:579] (Throwable with no stack trace)
F/le.nft_contrac(29691): java_vm_ext.cc:579] 
F/le.nft_contrac(29691): java_vm_ext.cc:579]     in call to CallVoidMethodV
F/le.nft_contrac(29691): java_vm_ext.cc:579]     from boolean com.unity3d.player.UnityPlayer.nativeRender()

**I have tried 2020.3.25, it is ok.**

**Comment by juicycleff** [comment]
@Arlen0615 the package does not use TelephonyManager.
