### ISSUE TITLE
No such file as local.properties exists

### ISSUE THREAD

**Issue by rmib200** [juicycleff/flutter-unity-view-widget#587]
**Describe the bug**
When I try to build the demo-app in android studio an error msg appears that flutter-unity-view-widget-master\example\android\local.properties file does not exists.

I am copying the log of the msg. 
Settings file 'C:\Users\MSI\Downloads\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\settings.gradle' line: 6

A problem occurred evaluating settings 'android'.
> assert localPropertiesFile.exists()
         |                   |
         |                   false
         C:\Users\MSI\Downloads\flutter-unity-view-widget-master\flutter-unity-view-widget-master\example\android\local.properties

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I've seen the tutorial video and the file "local.properties" is there from the beginning. So I don't know what is happening.

Please, any help would be appreciated.

**To Reproduce**
1. Download demo-app
2. Build android export
3. Open the demo app in android studio
4. Run into error

**Expected behavior**
The demo-app should build

**Screenshots**

**Unity (please complete the following information):**
 - OS: Windows 10
 - Version 2022.1.0f1

**Smartphone (please complete the following information):**
 
 - OS: Android
 - Version SDK 31

**Additional context**

**Comment by Anishishi** [comment]
Hi @rmib200 ,
Do you have the `local.properties` in the right place? 

In the README file, below the thing is mentioned.
> Copy the path by right click and paste the path here in your android/local.properties:

>     ndk.dir=/Applications/Unity/Hub/Editor/2020.3.19f1/PlaybackEngines/AndroidPlayer/NDK
> That's it! You don't need to tell your Android App in your app/build.gradle the NDK version or other NDK settings. It's all connected to Unity now.

Please note that the local.properties file is normally gitignored.

**Comment by rmib200** [comment]
So, from what I understand. I need to create the file "local.properties" and inside copy that line with the correct directory. Right?

**Comment by Anishishi** [comment]
Yes👍
That's right!

**Comment by rmib200** [comment]
> Yes👍 That's right!

Thanks, it worked!
