### ISSUE TITLE
Screen layout bugs when UnityWidget starts

### ISSUE THREAD

**Issue by ernonemacher** [juicycleff/flutter-unity-view-widget#589]
**Describe the bug**
Screen layout bugs when UnityWidget starts, the borders of the app start to behave like a standard Unity app. Closing the UnityWidget doesn't revert this behavior, changing the AppBar of the home screen, but would affect every screen of the app.

**To Reproduce**
1. Run the Demo app
2. Click on anything that opens a UnityWidget
3. Click on the back arrow going back to the HomeScreen

(In order to run with this versions I did the steps specified in this [issue](https://github.com/juicycleff/flutter-unity-view-widget/issues/581))

**Expected behavior**
The screen stays with the flutter pattern of the AppBar even when the UnityWidget is active. Or at least when after it closes.

**Screenshots**
<img width="211" alt="1" src="https://user-images.githubusercontent.com/52502707/169293143-2a9a9c5f-3062-4e22-bb58-00b60d3d815b.png"> <img width="211" alt="2" src="https://user-images.githubusercontent.com/52502707/169293155-f67c8411-4128-4c0e-b7f3-2fb2fac818fb.png"> <img width="211" alt="3" src="https://user-images.githubusercontent.com/52502707/169293389-dfa49c6c-da60-45f5-a795-c1a80a1f0ed2.png">

**Unity:**
 - OS: macOS BigSur 11.5.2
 - Version: 2020.3.20f1
 
**Smartphone:**
 - Device: Redmi Note 8
 - OS: Android 
 - Version Android version: 10, MIUI version: 12.0.4

**Additional context**
If this is considered the standard behavior, consider marking the issue with FeatureRequest instead of a bug.

Notice when I said "AppBar behavior or borders", I mean the Screen layout and behavior as a whole. Most noticeable in the AppBar.

This might be related to some updates in the **`Resolution and Presentation`** config on Unity. I tried using `FullscreenWindowed` and `Windowed`, with different variants of `Windown Size`, `Resizeble Windowm` etc. The only noticeable changes are marking the `Hide Navigation Bar` and `Render outside safe area` that change the behavior of the Screen, but they work just as before, changing the AppBar when UnityWidget is opened.
<img width="492" alt="Screen Shot 2022-05-19 at 09 24 36" src="https://user-images.githubusercontent.com/52502707/169299955-fc0c9fc0-d117-4d4d-9930-33d7c67d0b2b.png">

**Comment by ernonemacher** [comment]
I just saw the update about the flutter 3.0.0 in the Readme, this is probably related because I am using flutter 3.0.0. I will be closing the issue for new and be doing further investigations since I used 2022.1.0+4 to test. If the problem continues I'll reopen it.

**Comment by lorisgir** [comment]
Hi have the same issue with flutter 3.19 and this library 2022.2 version, how can i fix this?

**Comment by timbotimbo** [comment]
@lorisgir 
Flutter 3.19 has a bug. Use a lower version, or wait for 3.22 that is likely to release in the coming weeks.

https://github.com/juicycleff/flutter-unity-view-widget/issues/929

**Comment by lorisgir** [comment]
Actually I just saw another issue that mentioned to flag "Render outside safe area" inside project settings. Doing so fixed the issue!
