### ISSUE TITLE
How to run unitylibrary exported from windows on MAC?

### ISSUE THREAD

**Issue by yixiaonaihe2430** [juicycleff/flutter-unity-view-widget#590]
I run someone else's exported unitylibrary folder on Mac. But I can't run it. This folder is exported from windows and Mac can't execute it .exe file.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/23164931/169486105-8d428718-1b98-4e72-87d1-f00edd07193d.png">

**Comment by jamesncl** [comment]
You can't. They're completely different builds, and are incompatible. You need to open the Unity project inside Unity on a Mac, switch the build platform to iOS, and follow the instructions to configure and export unityLibrary for iOS.

**Comment by kilroy80** [comment]
Unity Project builds android module (aar) using Android Studio
