### ISSUE TITLE
Flutter Android app show Black screen using flutter_unity_widget package

### ISSUE THREAD

**Issue by rahulkhatri19** [juicycleff/flutter-unity-view-widget#602]
AIM : To load specific element from unity 3D into flutter Android App.

Issue: 
I am using flutter_unity_widget in flutter to show unity 3D content. I work fine until i use method like _unityWidgetController.postJsonMessage, It show black screen and content is not accessable.

current code in flutter 
```
// Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) {
    _unityWidgetController = controller;
    unity(_unityWidgetController);
  }

 unity(UnityWidgetController _unityWidgetController){
_unityWidgetController.postJsonMessage("Model Selector" , "SelectModel", {"value" : 3});

 _unityWidgetController.postMessage("Model Selector" , "SelectModel", "3");

}
```
 flutter_unity_widget: ^2020.3.25

**Comment by jamesncl** [comment]
We need a bit more information to go on:
- What version of Unity are you using?
- What version of the package are you using (you say 2020.3.25 but this doesn't appear to match any of [the versions on pub.dev](https://pub.dev/packages/flutter_unity_widget/changelog))
- Have you followed all the setup steps in the [readme](https://pub.dev/packages/flutter_unity_widget) including adding the correct Unity package to your unity project?
- Do you have a game object in your project called "Model Selector" which has a component with a method called "SelectModel"
- What shows in the console logs when this happens?

**Comment by rahulkhatri19** [comment]
Unity : 2020.3.0f1,
flutter_unity_widget : 2020.3.25
Have you followed all the setup steps : Yes
Do you have a game object : yes

**Comment by jamesncl** [comment]
`2020.3.25` doesn't seem to be on this list: [[storeFile](https://pub.dev/packages/flutter_unity_widget/changelog)](https://pub.dev/packages/flutter_unity_widget/changelog) so maybe that is the problem? I would try using the latest version of the package (currently 2022.1.1+3) and using Unity 2022.1.1

**Comment by Ahmadre** [comment]
@rahulkhatri19 I had the same problem. This is realted to Unity itself! You need to upgrade Unity to minimum 2021.* and use our new unitypackage for 2022.*. I also uploaded a new fixed version of our unitypackage Use this: https://github.com/juicycleff/flutter-unity-view-widget/blob/master/unitypackages/fuw-2022.1.1-v2.unitypackage

**Comment by Ahmadre** [comment]
note: that's also working for Unity `2022.1.4f1`!
