### ISSUE TITLE
Missing .so files

### ISSUE THREAD

**Issue by vonbv** [juicycleff/flutter-unity-view-widget#604]
In Step 7 it says:
Open the lib/architecture/ folder and check if there are both libUnityARCore.so and libarpresto_api.so files. There seems to be a bug where a Unity export does not include all lib files. If they are missing, use Unity to build a standalone .apk of your AR project, unzip the resulting apk, and copy over the missing .lib files to the unityLibrary module.

I unpacked the apk file for my project and I did not see those files. Here are all I got...
![image](https://user-images.githubusercontent.com/870921/171636990-81a431e7-55f6-46f6-92e7-17a66e08d155.png)

Where can I find those files?

I am using fuw-2022.1.1 and Unity 2022.1.2f1. Downgrading my project to Unity 2022.1.1f1 did not help.

**Comment by dawiddszewczyk** [comment]
Hi @vonbv , you launch app on Virtual Device or Physical? Try to update to 2022.3.4.f1 this version works very fine.
