### ISSUE TITLE
The type or namespace name 'Newtonsoft' could not be found

### ISSUE THREAD

**Issue by VivianKuKu** [juicycleff/flutter-unity-view-widget#605]
**Describe the bug**
Assets/FlutterUnityIntegration/UnityMessageManager.cs(3,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Assets/FlutterUnityIntegration/UnityMessageManager.cs(58,16): error CS0246: The type or namespace name 'JObject' could not be found (are you missing a using directive or an assembly reference?)

Assets/FlutterUnityIntegration/UnityMessageManager.cs(34,64): error CS0246: The type or namespace name 'JToken' could not be found (are you missing a using directive or an assembly reference?)

Assets/FlutterUnityIntegration/UnityMessageManager.cs(15,26): error CS0246: The type or namespace name 'JToken' could not be found (are you missing a using directive or an assembly reference?)

**Unity (please complete the following information):**
 - OS: iOS
 - Version: 2019.4.36f1

**Comment by Ortes** [comment]
The Newtonsoft package is in one of the .unitypackage try import another one like this [one](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/unitypackages/FlutterUnityIntegration-v4.1.0.unitypackage)

**Comment by VivianKuKu** [comment]
Hello,
Thank you for your reply.
After I import **FlutterUnityIntegration-v4.1.0.unitypackage** , these errors show up. Do you happen to know how to fix it?

Assets/FlutterUnityIntegration/Demo/GameManager.cs(4,7): error CS0246: The type or namespace name 'FlutterUnityIntegration' could not be found (are you missing a using directive or an assembly reference?)

Assets/FlutterUnityIntegration/Demo/Rotate.cs(2,7): error CS0246: The type or namespace name 'FlutterUnityIntegration' could not be found (are you missing a using directive or an assembly reference?)

Assets/FlutterUnityIntegration/Demo/SceneLoader.cs(3,7): error CS0246: The type or namespace name 'FlutterUnityIntegration' could not be found (are you missing a using directive or an assembly reference?)

**Comment by VivianKuKu** [comment]
I changed the Unity version from 2019.4.36f1 to 2021.3.3.f1 and the problem solved!
