### ISSUE TITLE
Xcode- Library not loaded: @rpath/Vuforia.framework/Vuforia   Referenced from:

### ISSUE THREAD

**Issue by VivianKuKu** [juicycleff/flutter-unity-view-widget#610]
Hi,
I am building iOS app with Vuforia. When I click on Run on Xcode, the App will install on my physical device but only has the white blank window. And the following information shows up.

*I followed the steps from here- https://github.com/juicycleff/flutter-unity-view-widget/issues/314#

<img width="1280" alt="Screenshot 2022-06-04 at 18 48 44" src="https://user-images.githubusercontent.com/52306317/172019508-7fd39350-1531-40f3-aa9d-7074dd4922a5.png">

<img width="1206" alt="Screenshot 2022-06-04 at 18 54 29" src="https://user-images.githubusercontent.com/52306317/172019700-61558480-2bb6-46c4-8b29-91e7eec3b3df.png">

**Unity (please complete the following information):**
 - OS: iOS
 - Version: 2021.3.3.f1

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS15

**Comment by Marcoslima016** [comment]
@VivianKuKu  you find a solution?

**Comment by el-mimoso** [comment]
I am facing the exact same error. Followed the instructions but didn't work.
