### ISSUE TITLE
App will not start due to "FATAL EXCEPTION: UnityMain"

### ISSUE THREAD

**Issue by vonbv** [juicycleff/flutter-unity-view-widget#612]
My app will not start due to the error described below.
I'm using:
- fuw 2022.1.1+3
- Unity 2022.1.1f1

**ERROR:**
[log] *********************************************
[log] ** flutter unity controller setup complete **
[log] *********************************************
E/tter_unity_dem(20952): {project_root}/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/external/mono/mono/metadata/mono-hash.c:282: assertion 'hash != NULL' failed
E/tter_unity_dem(20952): {project_root}/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/external/mono/mono/metadata/mono-hash.c:442: assertion 'hash != NULL' failed
E/tter_unity_dem(20952): {project_root}/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/external/mono/mono/metadata/mono-hash.c:442: assertion 'hash != NULL' failed
E/tter_unity_dem(20952): {project_root}/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/external/mono/mono/metadata/mono-hash.c:442: assertion 'hash != NULL' failed
F/tter_unity_dem(20952): * Assertion at {project_root}/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/external/mono/mono/mini/debugger-agent.c:3427, condition `tls' not met
E/CRASH   (20952): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
E/CRASH   (20952): Version '2022.1.2f1 (9427c1534183)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
E/CRASH   (20952): Build fingerprint: 'samsung/d2sxx/d2s:12/SP1A.210812.016/N975FXXU8HVE5:user/release-keys'
E/CRASH   (20952): Revision: '24'
E/CRASH   (20952): ABI: 'arm64'
E/CRASH   (20952): Timestamp: 2022-06-06 22:50:15+0800
E/CRASH   (20952): pid: 20952, tid: 21018, name: UnityMain  >>> com.example.flutter_unity_demo <<<
E/CRASH   (20952): uid: 10014
E/CRASH   (20952): signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
E/CRASH   (20952):     x0  0000000000000000  x1  000000000000521a  x2  0000000000000006  x3  0000007288dddbf0
E/CRASH   (20952):     x4  00000076436b7000  x5  00000076436b7000  x6  00000076436b7000  x7  0000000001e13d88
E/CRASH   (20952):     x8  00000000000000f0  x9  0000007626b9b280  x10 ffffff00fffffbdf  x11 0000000000000001
E/CRASH   (20952):     x12 0000007288ddb980  x13 00000000000000b9  x14 0000000000000000  x15 00001e817ec48e98
E/CRASH   (20952):     x16 0000007626c3c058  x17 0000007626c18da0  x18 0000007286fbe000  x19 00000000000000ac
E/CRASH   (20952):     x20 00000000000051d8  x21 00000000000000b2  x22 000000000000521a  x23 00000000ffffffff
E/CRASH   (20952):     x24 000000728f542470  x25 00000074133d92c0  x26 0000000000000018  x27 0000007288ddec50
E/CRASH   (20952):     x28 0000007287e40885  x29 0000007288dddc70
E/CRASH   (20952):     sp  0000007288dddbd0  lr  0000007626bca33c  pc  0000007626bca36c
E/CRASH   (20952): backtrace:
E/CRASH   (20952):       #00 pc 000000000005136c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId: eb0c8b7f827292af83855e89b431276a)
E/CRASH   (20952):       #01 pc 00000000061702e4  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #02 pc 0000000006170158  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #03 pc 00000000061701f0  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #04 pc 000000000617021c  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #05 pc 0000000006187948  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #06 pc 00000000061e1a44  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #07 pc 00000000061e17fc  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #08 pc 0000000006202088  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #09 pc 00000000061f9bbc  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (il2cpp_init+28) (BuildId: 9dcce88abd1ec1f5f8ad3a06c4a8d694d4a5e96f)
E/CRASH   (20952):       #10 pc 000000000028d13c  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: dbc6f4cc39c2341ac182ae517e78aa27eb913d2f)
E/CRASH   (20952):       #11 pc 00000000003053b8  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: dbc6f4cc39c2341ac182ae517e78aa27eb913d2f)
E/CRASH   (20952):       #12 pc 00000000003061b8  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: dbc6f4cc39c2341ac182ae517e78aa27eb913d2f)
E/CRASH   (20952):       #13 pc 000000000031d390  /data/app/~~7dQvyL9siRR5seNr4br80Q==/com.example.flutter_unity_demo-J36fn_SS0m7UBlTFF8h78g==/base.apk (BuildId: dbc6f4cc39c2341ac182ae517e78aa27eb913d2f)
E/CRASH   (20952):       #14 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #15 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #16 pc 00000000002851f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #17 pc 00000000003e70f0  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+400) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #18 pc 00000000003e1cec  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+804) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #19 pc 0000000000760fcc  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1036) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #20 pc 0000000000203914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #21 pc 00000000007631a0  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+2152) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #22 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #23 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #24 pc 00000000003e1254  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #25 pc 00000000003e1cc8  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+768) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #26 pc 000000000075df18  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1568) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #27 pc 0000000000203a14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #28 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #29 pc 00000000007464b4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #30 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 600193f4a9fcf9ced238223aee6c1164)
E/CRASH   (20952):       #31 pc 0000000002009db4  /memfd:jit-cache (deleted)
E/CRASH   (20952): Tombstone written to: /storage/emulated/0/Android/data/com.example.flutter_unity_demo/files/tombstone_02
E/AndroidRuntime(20952): FATAL EXCEPTION: UnityMain
E/AndroidRuntime(20952): Process: com.example.flutter_unity_demo, PID: 20952

Need help @juicycleff

**Comment by juicycleff** [comment]
Are running on a real device?

**Comment by vonbv** [comment]
Yes I am running on Android 12

**Comment by vonbv** [comment]
Could it be because I did not copy the required _.so_ files? But I could not find those files as I've mentioned [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/604).

**Comment by vonbv** [comment]
Problem solved! I looked into the Closed issues and check similar problems and found [one that helped me](https://github.com/juicycleff/flutter-unity-view-widget/issues/573#). Rex's suggestion [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/573#issuecomment-1129366979) definitely helped. But like the other guy who were asking there, I'm curious as to why those lines caused the issue.
