### ISSUE TITLE
flutter_unity_widget >=2022.1.0 depends on webviewx ^0.2.1 which depends on webview_flutter ^2.0.13

### ISSUE THREAD

**Issue by sayhellotogithub** [juicycleff/flutter-unity-view-widget#615]
**Describe the bug**
Because flutter_unity_widget >=2022.1.0 depends on webviewx ^0.2.1 which depends on webview_flutter ^2.0.13, flutter_unity_widget >=2022.1.0 requires webview_flutter ^2.0.13.
So, because *** depends on both webview_flutter ^3.0.1 and flutter_unity_widget ^2022.1.1+3, version solving failed.

**To Reproduce**
flutter pub upgrade

**Expected behavior**
we can use webview_flutter ^3.0.1

**Comment by Ahmadre** [comment]
Use [dependency-overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides). This is not an issue with this Plugin.

**Comment by jamesncl** [comment]
Agreed, this isn't a bug in the package but I think still a valid request. Using dependency-overrides can lead to unexpected behaviour, and `webview_flutter ^2.0.13` is quite an old version. Looking at the [changelog](https://pub.dev/packages/webview_flutter/changelog#300), most changes seem to be quite minor, except for a breaking change in 3.0.0:

> BREAKING CHANGE: On Android, hybrid composition (SurfaceAndroidWebView) is now the default. The previous default, virtual display, can be specified with WebView.platform = AndroidWebView()

**Comment by Ahmadre** [comment]
> Agreed, this isn't a bug in the package but I think still a valid request. Using dependency-overrides can lead to unexpected behaviour, and `webview_flutter ^2.0.13` is quite an old version. Looking at the [changelog](https://pub.dev/packages/webview_flutter/changelog#300), most changes seem to be quite minor, except for a breaking change in 3.0.0:
> 
> > BREAKING CHANGE: On Android, hybrid composition (SurfaceAndroidWebView) is now the default. The previous default, virtual display, can be specified with WebView.platform = AndroidWebView()

Actually the package maintainer is not responding: https://github.com/adrianflutur/webviewx/pull/53

Maybe I will update the version on our own plugin...

**Comment by Ahmadre** [comment]
please consider using our latest version. Web is now stable.

**Comment by sayhellotogithub** [comment]
ok,Thanks
