### ISSUE TITLE
flutter_unity_widget >=2022.1.0 requires webview_flutter ^2.0.13

### ISSUE THREAD

**Issue by RoyalCoder88** [juicycleff/flutter-unity-view-widget#622]
Hi friends, 

Thanks for your great package, please fix the version issue:

`Because flutter_unity_widget >=2022.1.0 depends on webviewx ^0.2.1 which depends on webview_flutter ^2.0.13, flutter_unity_widget >=2022.1.0 requires webview_flutter ^2.0.13.
So, because myproject depends on both flutter_unity_widget ^2022.1.1+3 and webview_flutter ^3.0.2, version solving failed.
pub get failed (1; So, because myproject depends on both flutter_unity_widget ^2022.1.1+3 and webview_flutter ^3.0.2, version solving failed.)
exit code 1`

**Comment by Ahmadre** [comment]
This is not an issue with this Plugin.

Please make yourself familiar with: https://dart.dev/tools/pub/dependencies#dependency-overrides in Flutter.

And consider following:

```yaml
dependency_overrides:
  webview_flutter: 2.0.13
```

**Comment by Ahmadre** [comment]
Please also follow: https://github.com/adrianflutur/webviewx/pull/53
