### ISSUE TITLE
Screenshot issue: Trying to embed a platform view but the PrerollContext does not support embedding

### ISSUE THREAD

**Issue by RoyalCoder88** [juicycleff/flutter-unity-view-widget#628]
Flutter doctor:

[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.739], locale en-GB) [√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4) [√] Chrome - develop for the web [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10) [√] Android Studio (version 2020.3) [√] VS Code (version 1.68.1) [√] Connected device (5 available) [√] HTTP Host Availability

I'm using  [screenshot 1.2.3](https://pub.dev/packages/screenshot) I'm trying to capture the **UnityWidget** screenshot image but I get this error:

`[ERROR:flutter/flow/layers/platform_view_layer.cc(20)] Trying to embed a platform view but the PrerollContext does not support embedding`

Please guide me on how to fix this issue, thanks in advance!

**Comment by jamesncl** [comment]
Can you check your `android/app/src/main/AndroidManifest.xml`file and see if there is this tag somewhere inside your `<application>` section:
```
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

If not, try adding it and build again

**Comment by RoyalCoder88** [comment]
Hi @jamesncl ,

I checked, I have this line:
![Screenshot 2022-06-19 143719](https://user-images.githubusercontent.com/6507433/174483895-4aecab79-e13c-46f2-918b-64cb844760bb.png)

**Comment by Ahmadre** [comment]
> Flutter doctor:
> 
> [√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.739], locale en-GB) [√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4) [√] Chrome - develop for the web [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10) [√] Android Studio (version 2020.3) [√] VS Code (version 1.68.1) [√] Connected device (5 available) [√] HTTP Host Availability
> 
> I'm using [screenshot 1.2.3](https://pub.dev/packages/screenshot) I'm trying to capture the **UnityWidget** screenshot image but I get this error:
> 
> `[ERROR:flutter/flow/layers/platform_view_layer.cc(20)] Trying to embed a platform view but the PrerollContext does not support embedding`
> 
> Please guide me on how to fix this issue, thanks in advance!

Actually you can't!

This is again a Flutter Framework issue :/

I know what you need. Please consider making screenshots on Unity-Side.

You can do that for example with this:

```cs
public void TakeScreenshot(string data) {
  RenderTexture rt = new RenderTexture(Screen.width, Screen.height, 24);
  FenztaManager.GetCurrentCamera().targetTexture = rt;
  Texture2D screenShot = new Texture2D(Screen.width, Screen.height, TextureFormat.RGB24, false);
  FenztaManager.GetCurrentCamera().Render();
  RenderTexture.active = rt;
  screenShot.ReadPixels(new Rect(0, 0, Screen.width, Screen.height), 0, 0);
  FenztaManager.GetCurrentCamera().targetTexture = null;
  RenderTexture.active = null; // Added to avoid errors
  Destroy(rt);
  byte[] bytes = screenShot.EncodeToPNG();
  
  UnityMessageManager.Instance.SendMessageToFlutter($"{Convert.ToBase64String(bytes)}");
}
```

To receive them in Flutter

```dart
final bytes = base64.decode(value);
```

**Comment by RoyalCoder88** [comment]
Hi @Ahmadre ,

Thanks for your support, I managed to make it work, I thought about capturing the screenshot in **Unity** and transferring it  **Flutter** but I used the wrong image bytes encoding :P thanks a lot for your help!!!

If somebody else needs this to work following the example above, and in **flutter** to preview the **Image** you just need to:
`    Image img = Image.memory(base64Decode(message));

    //PREVIEW IMAGE *****************************************
    setState(() {
      img2 = img;
      screenshotMade = true;
    });`

**To save the picture on the device just:**
`  saveScreenshot(/* Uint8List image */ String stringImage) async {
    List<int> imageData = const Base64Decoder().convert(stringImage);

    final result = await ImageGallerySaver.saveImage(
        Uint8List.fromList(imageData),
        quality: 100,
        name: "MyScreenshot");
    print(result);
  }`

P.S using this package from pub.dev [image_gallery_saver ](https://pub.dev/packages/image_gallery_saver)

Good luck!

**Comment by RoyalCoder88** [comment]
Thanks a lot @jamesncl for the information provided! Good luck!

P.S: I created a server for Discord, for the devs: [Unity & Flutter](https://discord.gg/n6J4krnr)
