### ISSUE TITLE
Trying to run new scenes in demo project crashes

### ISSUE THREAD

**Issue by rmib200** [juicycleff/flutter-unity-view-widget#629]
**Describe the bug**
Hi, I was trying to build scenes from a different unity project in the demo flutter project. Just adding another button to the menu and run this new project. When I build it from Unity everything is fine but when I try to run the flutter project, it crashes when I click on the new button I made for the new scene, or with any button really. I thought trying this would be easier. Is there a guide on how to setup new scenes into new flutter screens. I'm very new to Flutter.

**To Reproduce**
1. Replaced old unity folder with new project.
2. Build scene (current scene in the unity build list)
3. Compile Flutter app
4. Run app in android and app crashes when level is selected.

**Expected behavior**
Demo App should run my game when selected.

**Screenshots**

**Unity (please complete the following information):**
 - OS: Windows 10
 - Version 2022.1.0f1

**Smartphone (please complete the following information):**
 - Device: Techno Spark 6 Go
 - OS: Android
 - Version 10

**Additional context**
I used the no_interaction_screen.dart file as a template for the new scence I made. Is there any part where the scene path to Unity should be referenced? I don't know if you need to reference that in the screen file.

This is the screen file for the New Scene. 

```
import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

class NewScreen extends StatefulWidget {
  NewScreen({Key key}) : super(key: key);

  @override
  _NewScreenState createState() => _NewScreenState();
}

class _NewScreenState extends State<NewScreen> {
  static final GlobalKey<ScaffoldState> _scaffoldKey =
      GlobalKey<ScaffoldState>();

  UnityWidgetController _unityWidgetController;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _unityWidgetController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: Text('New Screen'),
      ),
      body: Card(
          margin: const EdgeInsets.all(8),
          clipBehavior: Clip.antiAlias,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: Stack(
            children: [
              UnityWidget(
                onUnityCreated: _onUnityCreated,
                onUnityMessage: onUnityMessage,
                onUnitySceneLoaded: onUnitySceneLoaded,
                webUrl: 'http://localhost:6080/',
              ),
            ],
          )),
    );
  }

  // void setRotationSpeed(String speed) {
  //   _unityWidgetController.postMessage(
  //     'Cube',
  //     'SetRotationSpeed',
  //     speed,
  //   );
  // }

  void onUnityMessage(message) {
    print('Received message from unity: ${message.toString()}');
  }

  void onUnitySceneLoaded(SceneLoaded scene) {
    print('Received scene loaded from unity: ${scene.name}');
    print('Received scene loaded from unity buildIndex: ${scene.buildIndex}');
  }

  // Callback that connects the created controller to the unity controller
  void _onUnityCreated(controller) {
    controller.resume();
    this._unityWidgetController = controller;
  }
}
```

**Comment by jamesncl** [comment]
Can you clarify a few things:
- Have you successfully got this to run on Android without modifying the demo scene?
- "it crashes when I click on the new button I made for the new scene" - just want to make sure I understand, do you mean that it loads okay without a crash and you can see your Unity game - but it only crashes when you tap a button in the Unity game? What does the button do? Are there any error messages?
- When you say "Run app in android and app crashes when level is selected" what do you mean by "when level is selected"?
- I noticed you're using the `webUrl` parameter:
```
UnityWidget(
onUnityCreated: _onUnityCreated,
onUnityMessage: onUnityMessage,
onUnitySceneLoaded: onUnitySceneLoaded,
webUrl: 'http://localhost:6080/',  // <=================
),
```
but you're deploying for Android - you probably want to remove the webUrl parameter, that's only used when you're building for web

**Comment by jamesncl** [comment]
Also, when you created your Unity project, what template did you use? It needs to be URP (Universal Render Pipeline)

**Comment by rmib200** [comment]
Thank you for your response, these are the clarifications in order:
-"Replaced old unity folder with new project." - I'm not sure what you mean by this, can you explain a bit more?
-> In the example project, there is a folder called "unity". Inside the folder there is another folder called "DemoApp", which contains the project assets of the example unity scenes.  What I did was replace the "DemoApp" with my own Unity project. That has all the dependencies of the flutter unity widget.
- Have you successfully got this to run on Android without modifying the demo scene?
- > Yes I did, and it works.
- "it crashes when I click on the new button I made for the new scene" - just want to make sure I understand, do you mean that it loads okay without a crash and you can see your Unity game - but it only crashes when you tap a button in the Unity game? What does the button do? Are there any error messages?
- >There is a main menu when you start the flutter demo app that list all the unity demo scenes. I created a new item in that list for my unity scene. And no, I cannot see my Unity game as it crashes every time I try to select it from the list.
- When you say "Run app in android and app crashes when level is selected" what do you mean by "when level is selected"?
- > When my "Unity scene" is selected.
- I noticed you're using the webUrl parameter.
- > The demo app is using it. I didn't touch that parameter at all. And the original demo was working well.
- The flutter widget will always load the first scene in the "scenes in build" list in the Unity build settings
- > My game is only one scene and is the first (and only) scene in the build list in Unity.
- Also, when you created your Unity project, what template did you use? It needs to be URP (Universal Render Pipeline)
- > It is using URP right now.

**Comment by Ahmadre** [comment]
@rmib200 regarding the webUrl: I updated and uploaded a new unitypackage which fixes this and makes is easier for users. Consider using an url without the last `/` at the end!

Regarding your other questions:

I agree with you that this is unfortunately not well placed the "DemoApp" folder.

In your real life scenario you should a flutter app like this:

```
- flutter 
  |
  |-> unity
        |
        |-> MyUnityProject
              |
              |-> Assets
                    |-> FlutterUnityIntegration
                    |-> OtherScripts
                    |-> ...
```

So actually `MyUnityProject` is `DemoApp`!

**Comment by jamesncl** [comment]
Thanks for the extra information. I assume your new scene runs okay in the Unity editor without errors? Also, I assume you've run the Flutter -> Export android script again from the Unity menu bar after replacing the demo project with your new project?

It's difficult to suggest what might be wrong. Can you post any error logs you get when the crash occurs (if you're using Android Studio, there should be something appearing in the 'Run' window?)

**Comment by elvispeter1991** [comment]
Did you manage to solve this issue @rmib200 am also facing the same issue and am using latest version of unity 2022.1 and latest unity package from here

**Comment by Ahmadre** [comment]
@rmib200 I uploaded a new version.

please use: 

```yaml
dependencies:
  flutter_unity_widget: 2022.1.1+4
```

**Comment by rmib200** [comment]
> also facing the same issue and am using latest version of unity 2022.1 and latest unity package from here

No I haven't, unfortunately. And you?

**Comment by timbotimbo** [comment]
I did some compatibility testing with the example project, without any scene changes.
I can build and run the example on android with Unity 2019, 2020 and 2021. (Flutter 2.10.5 and 3.0.3)

Any build with unity 2022 results in a crash when launching the screen with the UnityWidget.

**Comment by rmib200** [comment]
But the 2022 version was working for you before? It was working for me until I tried to add new scenes to the demo app.

**Comment by rmib200** [comment]
> 

Hi, in what file does that line goes? I can't find it.

**Comment by rmib200** [comment]
@Ahmadre 
After upgrading to Flutter SDK 3.0.3, I got this message everytime I do `flutter run` :

```
The current Dart SDK version is 2.17.5.

Because flutter_unity_widget_example requires SDK version 3.0.3, version solving failed.
Running "flutter pub get" in example...                                 
pub get failed (1; Because flutter_unity_widget_example requires SDK version 3.0.3, version solving failed.)

```
I downloaded many times the new Flutter SDK now and nothing seems to fix it. I tried updating Dart manually running `choco upgrade dart-sdk` I think I just ruined the last working version of Flutter I had in my computer. Please any idea on how to fix this error about flutter_unity_widget_example requiring SDK v 3.0.3? I'm getting a little bit desperate.

**Comment by rmib200** [comment]
Removing these lines inside Location: android/unityLibrary/build.gradle solved the issue.



commandLineArgs.add("--enable-debugger")

commandLineArgs.add("--profiler-report")

commandLineArgs.add("--profiler-output-file=" + workingDir + "/build/il2cpp_"+ abi + "" + configuration + "/il2cpp_conv.traceevents")

commandLineArgs.add("--print-command-line")

**Comment by elvispeter1991** [comment]
May i know the unity version and flutter package you used. It will be really helpfull.

**Comment by rmib200** [comment]
> May i know the unity version and flutter package you used. It will be really helpfull.

Unity Version 2022.1.0f1
Flutter SDK 3.0.3

**Comment by elvispeter1991** [comment]
@rmib200 thanks a lot. It really helped and i too solved it.

**Comment by timbotimbo** [comment]
I can confirm this with Unity 2022.1.7f1.
Just removing `commandLineArgs.add("--enable-debugger")` is enough, the other lines don't matter here.

Removing `playerOptions.options = BuildOptions.AllowDebugging;` from `Assets/FlutterUnityIntegration/Editor/build.cs`  will ensure that `--enable-debugger` never gets added.
