### ISSUE TITLE
NEW GITTER CHANNEL FOR CONTRIBUTORS AND MEMBERS

### ISSUE THREAD

**Issue by juicycleff** [juicycleff/flutter-unity-view-widget#63]
Please feel free to join, let's improve this project together

https://gitter.im/flutter-unity/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by juicycleff** [comment]
@krispypen @thomas-stockx, please feel free to join in so we can fix issues without conflicting each other

**Comment by juicycleff** [comment]
I would like to state that this project is still actively developed. I am sorry as I busy with preparations for my certificate exams and would update the library once I am less busy. In the meantime any PR is welcomed. I will review and merge :)

**Comment by juicycleff** [comment]
I am back to improving this package. Looking forward to a lot more I can add :)

**Comment by timbotimbo** [comment]
I added this link to https://github.com/juicycleff/flutter-unity-view-widget/issues/652 so these can be a singe pinned issue.
