### ISSUE TITLE
Loading Unity Widget on iOS causes the main game splash screen to flash for a second

### ISSUE THREAD

**Issue by AkhilRaja** [juicycleff/flutter-unity-view-widget#633]
**Describe the bug**
Loading Unity Widget on iOS causes the main game splash screen to flash for a second before loading unity's splash screen. It feels odd when the main app's splash screen launches there.

**Unity (please complete the following information):**
 - OS: [e.g. iOS] 15.4
- Flutter 3.0.2
- Unity 2022.1.0f1

**Smartphone (please complete the following information):**
 - Device: iPhone 13

**Additional context**

**Comment by jamesncl** [comment]
Interesting. I'm not sure this is something that can be fixed @juicycleff ? My guess is that when the package launches a native iOS view to show Unity, iOS thinks the app is launching for the first time?

My suggestion would be to work around this by using [a fixed static colour (eg black) for your Android / iOS system splash image](https://docs.flutter.dev/development/ui/advanced/splash-screen) and then creating your 'proper' splash image in dart / flutter as the first widget that is shown?

**Comment by juicycleff** [comment]
@AkhilRaja how are you loading the  the splash screen and unity screen. There must be something wrong as unity can not render over your splash screen

**Comment by juicycleff** [comment]
Could you replicate this issue and share screenshot because I don't seem to follow @AkhilRaja

**Comment by AkhilRaja** [comment]
@juicycleff I am unable to replicate it now. I think i messed with the Xcode Optimization levels for swift and clang code generation and landed at the issue. Closing it.
