### ISSUE TITLE
Wrong status bar layout on android after opening Unity

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#638]
**Describe the bug**
Once Unity is launched by a UnityWidget, it changes the status bar color and the spacing of the Appbar.
This did not happen on the ` 4.x` versions but does happen in the `2022.x` versions.
The screenshots in the readme do not show this issue.

Was mentioned before in #589

**To Reproduce**
1. Run the example project and click on any example in the app, like "Simple Unity Demo".
2. The Appbar now has additional spacing at the top and the status bar color has changed.
3. Go back to the menu page, the changes still remain.

**Expected behavior**
The Appbar and status bar should not change when showing a UnityWidget.

**Screenshots**
Each set of screenshots is this sequence
1. The menu when launching the example
2. The Simple unity demo
3. The menu after exiting the Simple unity demo
4. Alternative Simple unity demo, with `extendBodyBehindAppBar: true` and a transparent appbar.

flutter_unity_widget 2022.1.0+7 with issue

<table width="100%">
<tr>
<td>Menu before</td>
<td>UnityWidget</td>
<td>Menu after</td>
<td>UnityWidget behind appbar</td>
</tr>
  <tr>
  <td width="25%">

![1](https://user-images.githubusercontent.com/11444698/176143325-7fb79b4a-2bc3-4bc3-bd88-135b70a4e20c.jpg)
</td>
<td width="25%">

![2](https://user-images.githubusercontent.com/11444698/176143337-33cd16c9-970d-4023-a79c-243966ef1baf.jpg)
</td>
<td width="25%">

![3](https://user-images.githubusercontent.com/11444698/176143347-9fbfa7c7-96ab-40cc-a927-52b8e911855d.jpg)
</td>
<td width="25%">

![5](https://user-images.githubusercontent.com/11444698/176147967-c7cadef8-3035-466b-8e76-97c8e614c159.jpg)
</td>
  </tr>
</table>

<details><summary>flutter_unity_widget 4.2.5+1 without issue</summary>
<table width="100%">
<tr>
<td>Menu before</td>
<td>UnityWidget</td>
<td>Menu after</td>
<td>UnityWidget behind appbar</td>
</tr>
  <tr>
  <td width="25%">

![1](https://user-images.githubusercontent.com/11444698/176140995-63e238e0-a980-4ae6-aab5-d961f515847d.jpg) 
</td>
<td width="25%">

![2](https://user-images.githubusercontent.com/11444698/176141020-54546162-4c1d-42dd-bd72-0da818af1990.jpg)
</td>
<td width="25%">

![3](https://user-images.githubusercontent.com/11444698/176141029-1722f292-4231-4b14-b9f2-efc53c4630aa.jpg)
</td>
<td width="25%">

![5](https://user-images.githubusercontent.com/11444698/176147238-0f15464d-c249-4d36-b3be-facc2a7d338c.jpg)
</td>
  </tr>

</table>
</details>
<details><summary>flutter_unity_widget 2022.1.0+7 with FLAG_TRANSLUCENT_STATUS</summary>

<table width="100%">
<tr>
<td>Menu before</td>
<td>UnityWidget</td>
<td>Menu after</td>
<td>UnityWidget behind appbar</td>
</tr>
  <tr>
  <td width="25%">

![1](https://user-images.githubusercontent.com/11444698/176145671-846459a5-9fea-44aa-afd2-22a271a527d5.jpg)
</td>
<td width="25%">

![2](https://user-images.githubusercontent.com/11444698/176145681-766e5a4d-8603-4fc2-911f-bd6e33e52ab8.jpg)
</td>
<td width="25%">

![3](https://user-images.githubusercontent.com/11444698/176145686-64158b4a-092c-4518-a4f9-5685511e2ee9.jpg)
</td>
<td width="25%">

![5](https://user-images.githubusercontent.com/11444698/176148235-0bc566fe-9e7e-4bd9-ac67-974531745aaa.jpg)

</td>
  </tr>
</table>
</details>

</details>

**Possible fix** ***[Update: see the next comment for a better fix]***

The change between the working 4.x versions and the newer versions seems to be a `FLAG_TRANSLUCENT_STATUS`.
Adding that flag makes it behave like it did previously.
@juicycleff  Did you deliberatly remove this flag to fix something else?

`UnityPlayerUtils.kt` around line 70
```
if (!options.fullscreenEnabled) {
    activity!!.window.addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
    activity!!.window.clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);

    //add these lines
    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
        activity!!.window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS)
    }
} 

```

Possible downsides to this fix:
- The translucent status bar will now overlap unity (compare the 4th screenshot of each version)
- A status bar changed by `systemChrome` in Flutter will be reset by the UnityWidget, see the screenshots below

<details><summary>Possible fix will override custom status bar color</summary>

Color was set by adding the following to the menuscreen.
```
await SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(statusBarColor: Colors.red));
```
<table width="100%">
<tr>
<td>Custom status bar color</td>
<td>2022 without fix</td>
<td>2022 with fix</td>
</tr>
  <tr>
  <td width="25%">

![Screenshot_20220628-102820](https://user-images.githubusercontent.com/11444698/176152069-fe5df7cf-f6cf-4269-9ed1-bbf0ff394761.jpg)
</td>
<td width="25%">

![Screenshot_20220628-102652](https://user-images.githubusercontent.com/11444698/176153076-daaa892c-5e59-4340-8ee3-3a790d96e537.jpg)
</td>
<td width="25%">

![2](https://user-images.githubusercontent.com/11444698/176145681-766e5a4d-8603-4fc2-911f-bd6e33e52ab8.jpg)
</td>
  </tr>
</table>
</details>

**Versions**
These screenshots were made on flutter_unity_widget version `2022.1.0+7` because the flutter 2.10.5 version made it easier to switch back to older verions for comparison.
This same issue occurs on the latest `2022.1.1+4` with Flutter 3.0.3

The screenshots were made on a Samsung Galaxy S20FE with Android 12.
The same occurs on a Xiaomi Pocophone F1 with Android 10.

**Comment by timbotimbo** [comment]
I just found an easier solution:

Unity player settings -> Render outside safearea
![safearea](https://user-images.githubusercontent.com/11444698/176205891-888f824f-0e04-4a6d-80c1-c2a6dc7bddc2.jpg)

This keeps the appbar and statusbar the same when you navigate to a page with UnityWidget.
Any color change previously applied to the status bar remains as well.


Tested with both Unity 2019.4.40 and 2021.3.5.
Screenshots from Unity 2021.3.5 and flutter_unity_widget 2022.1.0+7.
<table width="100%">
<tr>
<td>Regular</td>
<td>flutter status bar color</td>
<td>behind appbar</td>
</tr>
  <tr>
  <td width="25%">

![Screenshot_20220628-162409](https://user-images.githubusercontent.com/11444698/176205289-da74afef-963c-4a5f-b1b5-d98079643155.jpg)
</td>
<td width="25%">

![Screenshot_20220628-162551](https://user-images.githubusercontent.com/11444698/176205419-a8e7ce17-38d9-4d3b-ac88-903e8d3ed5b1.jpg)
</td>
<td width="25%">

![Screenshot_20220628-162749](https://user-images.githubusercontent.com/11444698/176205473-7cbce4c0-dd2c-4175-8e28-e4a99ef24525.jpg)
</td>
  </tr>
</table>

**Comment by juicycleff** [comment]
@timbotimbo it has always been like that you fix it in the unity player settings like you just did. Glad you figured it out.
