### ISSUE TITLE
Git push: fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by RoyalCoder88** [juicycleff/flutter-unity-view-widget#640]
Hi friends, I'm countering a new problem in my project when I'm trying to push my project to **GIT**, I tried every solution on the Internet nothing works for me, unfortunately, I get this error:

> > PS C:\Users\burac\Desktop\AppsPro\myapp> git push
> 
> > Enumerating objects: 11468, done.
> 
> > Counting objects: 100% (10767/10767), done.
> 
> > Delta compression using up to 12 threads
> 
> > Compressing objects: 100% (4713/4713), done.
> 
> > error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
> 
> > send-pack: unexpected disconnect while reading sideband packet
> 
> > Writing objects: 100% (10062/10062), 2.37 GiB | 4.36 MiB/s, done.
> 
> > Total 10062 (delta 5638), reused 9585 (delta 5179), pack-reused 0
> 
> > fatal: the remote end hung up unexpectedly
> 
> > Everything up-to-date
> 
> 
> 
> Any ideas on how to fix this :( thanks in advance!

**Comment by DaDummy** [comment]
This has absolutely nothing to do with this project.

See the git documentation for help with how to use git: https://git-scm.com/book/en/v2/Getting-Started-Getting-Help

Please be a little more considerate and don't file bug reports on unrelated projects to ask for help with your developer tools.

**Comment by RoyalCoder88** [comment]
Hi @DaDummy , I posted this issue because in time many people will encounter this issue if their Unity project will have a big size, we need to find solutions in advance!
