### ISSUE TITLE
Change the size of embeddable unity widget.

### ISSUE THREAD

**Issue by omdivyatej** [juicycleff/flutter-unity-view-widget#645]
**Is your feature request related to a problem? Please describe.**
Right now we can only pass full screen prop to make unity fullscreen or not. But it would be better if we could pass something like size : 480x480 which would determine the size of unity widget inside the flutter app.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by timbotimbo** [comment]
You can change the size in Flutter by wrapping it in something like a Container or SizedBox.

<table width="100%">
</tr>
  <tr>
  <td width="25%">

![Screenshot_20220706-135648](https://user-images.githubusercontent.com/11444698/177545033-68cc6f4e-4868-4ff6-86a2-41f1df7d854c.jpg)
</td>
<td width="25%">

![Screenshot_20220706-135708](https://user-images.githubusercontent.com/11444698/177545035-b5320890-8c24-4d6e-a0fc-50e28f45e64b.jpg)
</td>
<td width="25%">

![Screenshot_20220706-135657](https://user-images.githubusercontent.com/11444698/177545038-710229aa-6f6d-41ae-9010-a8e255a22b35.jpg)
</td>
  </tr>
</table>

```dart
 Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Simple Screen'),
      ),
      body: Container(
        color: Colors.white,
        child: Center(
          child: SizedBox(
            height: 200,
            //width: 200,
            child: UnityWidget(
              onUnityCreated: _onUnityCreated,
              onUnityMessage: onUnityMessage,
              onUnitySceneLoaded: onUnitySceneLoaded,
              webUrl: 'http://localhost:6080',
              useAndroidViewSurface: true,
            ),
          ),
        ),
      ),
    );
  }
```

**Comment by Ahmadre** [comment]
Our Unity Plugin provides a non-blocking layout by using PlatformViews for mobile and HTMLElementView for Web.

So you can layout your Unity like you want in Flutter.

Additionaly introduce yourself to Unity: FPS, DPI, and so on....

**Comment by Harsha975** [comment]
hii can anyone tell after modifying the unity-flutter-widget demo with a cube in unity , that changes isn't reflecting in flutter ? can anyone plzz tell the steps !!
