### ISSUE TITLE
Flutter high latency click sound when unity widget is on. 

### ISSUE THREAD

**Issue by Linspirit98** [juicycleff/flutter-unity-view-widget#648]
**Describe the bug**
I am using 
```
SystemSound.play(SystemSoundType.click); 
```
in a flutter page with unity widget and it has very high latency. In pages without unity widget, the latency is very low. When I exit unity widget, the latency remained high. I'm not sure what causes this audio latency problem. 

**To Reproduce**
1. Add the code above in a onTap or onPressed event in page with unity widget.
2. import 'package:flutter/services.dart';
3. Click on the button to hear the latency in sound. 

**Expected behavior**
expect very high latency in click sound effect. 

**Unity (please complete the following information):**
 - Unity Version: 2020.2.6f1
 - unity widget package version 4.2.5+1
 - flutter 2.10.2

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS:  iOS 14.6

**Comment by dawiddszewczyk** [comment]
Hi @Linspirit98, I recommend you to update unity to 2021.3.4f1 and unity package to [fuw-2022.1.1](https://github.com/juicycleff/flutter-unity-view-widget/tree/master/unitypackages).
