### ISSUE TITLE
NEW DISCORD CHANNEL FOR CONTRIBUTORS AND MEMBERS

### ISSUE THREAD

**Issue by dawiddszewczyk** [juicycleff/flutter-unity-view-widget#652]
Feel Free to join to discord channel! Improve this Project Together :)
https://discord.gg/uUEMzrtZ

**Comment by Ahmadre** [comment]
@juicycleff The link in README is not working: 

<img width="499" alt="Bildschirmfoto 2022-07-16 um 22 47 53" src="https://user-images.githubusercontent.com/18512224/179371545-067b39f6-10fe-47eb-b5fc-98a7697d365d.png">

Is the link in this issue the actual one?

**Comment by dawiddszewczyk** [comment]
@Ahmadre Yeah, this is official new link to discord channel.

**Comment by Ahmadre** [comment]
I updated the link in README. It's working now 👍

**Comment by juicycleff** [comment]
I think the link is still expired for me

**Comment by dawiddszewczyk** [comment]
@juicycleff Changed link, with never expired date.
