### ISSUE TITLE
Guide : Play Asset Delivery 

### ISSUE THREAD

**Issue by zamvar** [juicycleff/flutter-unity-view-widget#658]
**Is your feature request related to a problem? Please describe.**
as a new user unfamiliar with unity  i want to be able to use this plugin with play asset delivery, 

**Describe the solution you'd like**
A simple guide on how to implement Play Asset Delivery of Unity Addressable 

**Describe alternatives you've considered**

**Additional context**
I have an app with a base apk size of 30mb but with this package and the unity scenes im loading it reaches 200mb as an aab.
i am not familiar with unity, only tasked to integrate this scenes using this plugin, im encountering an issue right now when uploading to playstore regarding the bundle size.

**Comment by liaufan** [comment]
Hey there, I faced the exact problem as you. I am able to solve it with Unity Addressable, 
https://www.youtube.com/watch?v=cl_2icxKCyQ this is the YouTube tutorial I was referring to. 

Below are the basic steps (Writing these based on my memory, sorry if they are not very accurate): 
1. In Unity Editor, Package Manager > Search and Install Addressables (com.unity.addressables)
2. Enable Addressable Group view tab in Unity editor, (Window> Asset Management > Addressables > Group)
3. Create new Addressable Group,
4. Select assets to be addressable and include in the created Addressable Group, then set the labels to default. (Initially was empty label)
5. Create a game object "AddressableManager" in the scene,
6. Add a script for the AddressableManager game object,
7. In the script, declare AssetReference and assign it with the desire assets in unity editor,
8. In Unity editor Project navigator tab, select Assets folder> AddressableAssetData> Addressable Asset Settings, in Inspector tab select check "Build Remote Catalog" and "Build & Load Paths" should select "Remote".
9. You will need to create a publicly available cloud storage bucket. In my case I used Google Cloud Storage. At this step you will get a storageUrl. (Refer to the documentation/tutorial of your preferred cloud service provider)
10. At the same inspector tab, click Manage Profiles button, under Remote select Custom, and set RemoteBuildPath to "ServerData/[BuildTarget]", and RemoteLoadPath to "storageUrl/[BuildTarget]".
11. From Addressable Groups tab, click Build> New Build> Default Build Setting, to start build the addressable server data.
12.  Go to your file explorer / finder, you will find the ServerData folder at root level of your Unity Project. Upload everything inside as it is to the cloud storage you created before.
13. In the AddressableManager script, you will need to load the addressable asset from your cloud storage. You may refer to the part 1 YouTube tutorial by the same YouTuber https://www.youtube.com/watch?v=0USXRC9f4Iw, example code is attached 
`
void Start()
{
        Addressables.InitializeAsync().Completed += AddressableManager_Completed;
    }

private void AddressableManager_Completed(AsyncOperationHandle<IResourceLocator> obj)
    {
        sceneAssetReference.InstantiateAsync().Completed  += (go) =>
        {
            go.Result.gameObject.transform.Rotate(0, 90, 0);
            go.Result.gameObject.transform.localScale = new Vector3(0.5f, 0.5f, 0.5f);
            go.Result.gameObject.transform.position = new Vector3(0, 0, -1.05f);
            sceneLoaded = true;
            hideLoadingIndicator();
        };
    }`
14. Remove the asset from your local scene, as they will now be loaded at runtime.

**Comment by zamvar** [comment]
sorry for the late response, this worked perfectly for my needs thanks @liaufan !
