### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by martinaskolin** [juicycleff/flutter-unity-view-widget#659]
### The Error:
FAILURE: Build failed with an exception.

* Where:
Build file '/home/martin/flutter_app/android/unityLibrary/build.gradle' line: 73

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> Process 'command '/home/martin/flutter_app/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp'' finished with non-zero exit value 4

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

### Configurations and Versions:
* Unity version 2022.1.10f1
* Flutter v3.0.3
* fuw-2022.1.7f1.unitypackage
* OS: Ubuntu 20.04.4 LTS
* Issue on both physical and virtual device 

### /home/martin/flutter_app/android/unityLibrary/build.gradle:
```gradle
apply plugin: 'com.android.library'


dependencies {
    implementation(name: 'unity-classes', ext:'jar')

}

android {
    compileSdkVersion 30
    buildToolsVersion '30.0.2'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 30
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        versionCode 1
        versionName '0.1'
        consumerProguardFiles 'proguard-unity.txt'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp']
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
    }
}

def getSdkDir() {
    Properties local = new Properties()
    local.load(new FileInputStream("${rootDir}/local.properties"))
    return local.getProperty('sdk.dir')
}

def BuildIl2Cpp(String workingDir, String configuration, String architecture, String abi, String[] staticLibraries) {
    def commandLineArgs = []
    commandLineArgs.add("--compile-cpp")
    commandLineArgs.add("--platform=Android")
    commandLineArgs.add("--architecture=" + architecture)
    commandLineArgs.add("--outputpath=" + workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.so")
    commandLineArgs.add("--libil2cpp-static")
    commandLineArgs.add("--baselib-directory=" + workingDir + "/src/main/jniStaticLibs/" + abi)
    commandLineArgs.add("--incremental-g-c-time-slice=3")
    commandLineArgs.add("--dotnetprofile=unityaot-linux")
    commandLineArgs.add("--profiler-report")
    commandLineArgs.add("--profiler-output-file=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_conv.traceevents")
    commandLineArgs.add("--print-command-line")
    commandLineArgs.add("--generatedcppdir=" + workingDir + "/src/main/Il2CppOutputProject/Source/il2cppOutput")
    commandLineArgs.add("--cachedirectory=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_cache")
    commandLineArgs.add("--tool-chain-path=" + android.ndkDirectory)
    staticLibraries.eachWithIndex {fileName, i->
        commandLineArgs.add("--additional-libraries=" + workingDir + "/src/main/jniStaticLibs/" + abi + "/" + fileName)
    }
    def executableExtension = ""
    if (org.gradle.internal.os.OperatingSystem.current().isWindows())
        executableExtension = ".exe"
    exec {
        executable workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp" + executableExtension
        args commandLineArgs
        environment "ANDROID_SDK_ROOT", getSdkDir()
    }
    delete workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.sym.so"
    ant.move(file: workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.dbg.so", tofile: workingDir + "/symbols/" + abi + "/libil2cpp.so")
}

android {
    task BuildIl2CppTask {
        doLast {
              BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), 'Debug', 'armv7', 'armeabi-v7a', [  ] as String[]);
              BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), 'Debug', 'arm64', 'arm64-v8a', [  ] as String[]);
        }
    }
    afterEvaluate {
        if (project(':unityLibrary').tasks.findByName('mergeDebugJniLibFolders'))
            project(':unityLibrary').mergeDebugJniLibFolders.dependsOn BuildIl2CppTask
        if (project(':unityLibrary').tasks.findByName('mergeReleaseJniLibFolders'))
            project(':unityLibrary').mergeReleaseJniLibFolders.dependsOn BuildIl2CppTask
    }
    sourceSets {
        main {
            jni.srcDirs = ["src/main/Il2CppOutputProject"]
        }
    }
}
```

### Row 73:
```gradle
73: exec { 
74:        executable workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp" + executableExtension
75:        args commandLineArgs
76:        environment "ANDROID_SDK_ROOT", getSdkDir()
77:    }
```
### Notes:
* I've commented out playerOptions.options = BuildOptions.AllowDebugging in Assets/FlutterUnityIntegration/Editor/build.cs as suggested by @timbotimbo in #629 

 * I've also tried commenting out lines straight from inside the unityLibrary build file as suggested by @rmib200 #629

* In #524 by @RoyalCoder88 solved the issue on Windows by changing \ to \\\ (and others with /) in ndk.dir but using linux / is standard, here is mine:
'ndk.dir=/home/martin/Unity/Hub/Editor/2022.1.10f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK'

* Ive also changed android/app/build.gradle minSdkVersion to 22 to match requirements set out by unityLibrarys build file if that might be the wrong way to resolve the issue?

* I have created several new unity projects on 2022.1.10f1 and 2021.3.6f1 using different flutter versions (3.0.0, 3.0.2, 3.0.3, and 3.0.5) but always ended up with this error. (Note: the switching of flutter- and unity versions was to try and recreate the set up of other issues with similar error who had their problems solved).

**Comment by RoyalCoder88** [comment]
@martinaskolin I will take a look, maybe I can help you!

**Comment by dawiddszewczyk** [comment]
Hi @martinaskolin, did you try to re-import flutter unity package again in Unity Project ?

**Comment by martinaskolin** [comment]
Hi @dawiddszewczyk, could you clarify your question regarding re-importing the flutter unity package? I did launch the app on a physical device.

**Comment by dawiddszewczyk** [comment]
@martinaskolin 
Enter into Unity open Project, click assets 
<img width="71" alt="Zrzut ekranu 2022-07-21 o 15 34 39" src="https://user-images.githubusercontent.com/58904662/180226994-f142ce2c-8116-409c-9848-cadeca65f987.png">
Later open 
<img width="515" alt="Zrzut ekranu 2022-07-21 o 15 34 56" src="https://user-images.githubusercontent.com/58904662/180227677-eab59e65-9f59-4773-8566-fb3a3092b19e.png">
Then select the Flutter Unity package
<img width="393" alt="Zrzut ekranu 2022-07-21 o 15 38 07" src="https://user-images.githubusercontent.com/58904662/180227741-d73a73b1-0393-4f6c-b4cb-394138262623.png">

Ensure that you have checked everything under the scripts. 
<img width="350" alt="Zrzut ekranu 2022-07-21 o 15 40 27" src="https://user-images.githubusercontent.com/58904662/180227976-2de77daf-089d-4788-a636-679370598f11.png">

**Comment by martinaskolin** [comment]
@dawiddszewczyk I have imported the unitypackage on several projects and successfully exported for Android (Debug) and followed the steps in the readme file but everytime I end up with the same error.

**Comment by RoyalCoder88** [comment]
@martinaskolin I got the same errors on Unity version **2022**, I tried over 10 Unity versions, and the most stable one is **2021.3.4f1** try this version please, and let us know!

P.S: You can found help as well on Discord: [Flutter & Unity](https://discord.gg/n87QP66k)

**Comment by martinaskolin** [comment]
Thank you @RoyalCoder88, I'll join the discord in a bit but ill first try Unity 2021.3.4f1 which .unitypackage would you recommend for this version of Unity?

**Comment by RoyalCoder88** [comment]
@martinaskolin ok see you there, I'm using: [fuw-2022.1.7f1.unitypackage](https://raw.githubusercontent.com/juicycleff/flutter-unity-view-widget/master/unitypackages/fuw-2022.1.7f1.unitypackage) and I'm able to build without any problems for **Android** & **iOS**

**Comment by martinaskolin** [comment]
The issue was solved by switching from Ubuntu 20.04.4 LTS to Windows 11

**Comment by martinaskolin** [comment]
if you want to solve this error for linux comment out the following lines inside unityLibrary/build.gradle: 

´´´gradle
    // def executableExtension = ""
    // if (org.gradle.internal.os.OperatingSystem.current().isWindows())
    //     executableExtension = ".exe"
    // exec {
    //     executable workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp" + executableExtension
    //     args commandLineArgs
    //     environment "ANDROID_SDK_ROOT", getSdkDir()
    // }
    // delete workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.sym.so"
    // ant.move(file: workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.dbg.so", tofile: workingDir + "/symbols/" + abi + "/libil2cpp.so")
´´´

For some reason the isWindows() dosn't work.

**Comment by opimand** [comment]
> if you want to solve this error for linux comment out the following lines inside unityLibrary/build.gradle:
> 
> ```groovy-gradle
>     def executableExtension = ""
>     if (org.gradle.internal.os.OperatingSystem.current().isWindows())
>          executableExtension = ".exe"
>        exec {
>          executable workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp" + executableExtension
>          args commandLineArgs
>          environment "ANDROID_SDK_ROOT", getSdkDir()
>        }
>     delete workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.sym.so"
>     ant.move(file: workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.dbg.so", tofile: workingDir + "/symbols/" + abi + "/libil2cpp.so")
> ```
> 
> For some reason the isWindows() doesn't work.

Same error and build solution on macOS
