### ISSUE TITLE
how to integrate 2 unity projects in one flutter project

### ISSUE THREAD

**Issue by LeQuangTho** [juicycleff/flutter-unity-view-widget#660]
as title, I wonder, how to integrate 2 unity projects in one fluttert project?
I look forward to hearing from you, thanks?

@juicycleff

**Comment by Drarox** [comment]
As far as I know, you can't. But what you can do is merge your projects into one Unity project with scenes and then load the desired scene when launching with flutter.

**Comment by LeQuangTho** [comment]
> 

thankyou bro!

**Comment by rey-arx** [comment]
> 

How to load the desired scene?im struck in this step.How to use the postmessage to switch scene?Please help!

**Comment by dawiddszewczyk** [comment]
@rey-arx 
To open scene you have to 

```
late UnityWidgetController _unityWidgetController;

...


_unityWidgetController.postMessage(
                'UnityObject',
                'methodName',
                'HomeScene',
              ),

...
```
Also please read method desc below:
<img width="529" alt="Zrzut ekranu 2022-08-9 o 19 01 05" src="https://user-images.githubusercontent.com/58904662/183712628-a77371f2-ad40-4539-8fd2-96dbf6390e8c.png">

**Comment by omarsalem15** [comment]
how to open 2 different scenes from flutter screen
button 1 will open scene 1
button 2 will open scene 2
