### ISSUE TITLE
[Android] Prepare to revert Flutter 3.0 PlatformView workaround

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#667]
## Description
Flutter 3.0 broke the default android platformview (https://github.com/juicycleff/flutter-unity-view-widget/issues/584), rendering the unity widget in the wrong location.
According to https://github.com/flutter/flutter/issues/103630#issuecomment-1190733675, this is now fixed in Flutter beta releases.  

If the original issue is fixed, we can remove the workaround in this plugin.
And if we prepare and test this now, it can be ready to go when theses fixes make it into a new Flutter release.

## Current workaround
@juicycleff fixed this in `flutter_unity_widget 2022.1.1` by ignoring `useAndroidSurfaceView` and always using `initExpensiveAndroidView`.

```
/* /lib/src/io/device_method.dart */

// commented for 3.0.0 changes in platform view rendition
// if (!useAndroidViewSurface) {
//   return AndroidView(
//     viewType: _viewType,
//     onPlatformViewCreated: onPlatformViewCreated,
//     gestureRecognizers: gestureRecognizers,
//     creationParams: creationParams,
//     creationParamsCodec: const StandardMessageCodec(),
//     hitTestBehavior: PlatformViewHitTestBehavior.opaque,
//     layoutDirection: TextDirection.ltr,
//   );
// }

/* return initExpensiveAndroidView below */
```

This works for now, but the ExpensiveAndroidView introduces new bugs that did not happen with Flutter 2.x.

## Flutter beta
The current Flutter beta releases (starting with `3.3.0-0.0.pre`) seem to fix the original issue, meaning we can enable the `AndroidView` option again.

#### Setup:
- Flutter 3.0.5 & 3.3.0-0.0.pre
- Unity 2021.3.5
- flutter_unity_widget 2022.1.7+1  (With the above code uncommented)
- Android 12 (Samsung Galaxy S20FE)

In these videos I open the 'Simple Unity Demo' and 'Native exposed API demo' screens because these show the original issue the best.

<table width="100%">
  <tr>
<td>Flutter 3.0.5 <br> useAndroidSurfaceView: false</td>
<td>Flutter 3.3.0-0.0.pre <br> useAndroidSurfaceView: false</td>
<td>Flutter 3.3.0-0.0.pre <br> useAndroidSurfaceView: true</td>
</tr>
  <tr>
  <td width="33%">

https://user-images.githubusercontent.com/11444698/181485459-0de78c35-96ab-4909-ac31-0f00d8ce4dad.mp4

</td>
<td width="33%">

https://user-images.githubusercontent.com/11444698/181485472-c9c72de9-cd00-46d6-8f36-88bf23ef9cfb.mp4

</td>
<td width="33%">

https://user-images.githubusercontent.com/11444698/181485489-9a940f7c-6d6f-43b3-b883-d12e975d3e3a.mp4

</td>
  </tr>
</table>

## Result

Flutter 3.3.0-0.0-pre seems to fix the issue, so we should enable `AndroidView` again when this makes it to a Flutter release version.
In this way users get to choose which type of PlatformView to use, and might be able to avoid certain bugs,

It also shows that `useAndroidViewSurface: false` now respects the margin and rounded borders that are broken with `useAndroidViewSurface: true`

### [UPDATE] Testing
I tried some more devices to check android compatibility with 3.3.0-0.0.pre:
| Device  | Android | useAndroidViewSurface: false| useAndroidViewSurface: true |
| ------------- | ------------- | ------------- | ------------- |
| Samsung Galaxy S20FE  | 12 | Works | Works |
| Samsung Galaxy S8  | 9 | Works | Works |
| Wileyfox Swift  | 7.1 | Works | broken |
| Samsung Galaxy J5  | 6 | Works | broken |

**Comment by Cheong43** [comment]
Uncomment the `!useAndroidViewSurface`condition mentioned in  `device_method.dart` 

Device | Android | useAndroidViewSurface: false | useAndroidViewSurface: true
-- | -- | -- | --
Samsung Galaxy S10 | 12 | Works | broken
pixel 4a | 11 | Works | Works
Moto g30 | 11 | Works | broken



Also, if`useAndroidViewSurface: true` and using `unityWidget` in Page 1, and `push()`to Page 2, if using `image_picker` or leaving the app on Page 2, the unity view will unexpectedly be invoked(#649 , #637 ...)

But these bugs no longer exist with using`PlatformView`. (Run on flutter 3.3.0 pre)

**Comment by Cheong43** [comment]
I found it interesting that `AndroidViewSurface` works perfectly in google pixel 4a and pixel 6 without any config, and has a 120% improvement on fps and better power dissipation performance than using `PlatformView`. Maybe google has done some native optimization on pixel phone?

But `PlatformView`fit most situations, it's more reliable in my case.

**Comment by timbotimbo** [comment]
@juicycleff  @Ahmadre  Flutter 3.3.0 is now live with the fix included.

**Comment by juicycleff** [comment]
@timbotimbo this is great news, was looking at it myself. Will test done more
