### ISSUE TITLE
Front and rear console switching problem

### ISSUE THREAD

**Issue by lijiaxiang** [juicycleff/flutter-unity-view-widget#670]
I found two grammar problems
The first notification could not be registered.
The second one can't get the controller.
Both of them will cause the front and back-end switching not to be 
![49594E8E-101A-4A34-80AD-233F946CD1D0](https://user-images.githubusercontent.com/13743671/183609469-145a53c5-ecab-4b50-8c20-2ba1d1cca56e.png)

![64EB1827-2DFC-4292-9FE8-471F1F240B83](https://user-images.githubusercontent.com/13743671/183609495-5040d22e-8d55-41f8-9e1b-10f299fa00d5.png)
perceived.

**Comment by timbotimbo** [comment]
Seems to have been fixed in https://github.com/juicycleff/flutter-unity-view-widget/pull/704
