### ISSUE TITLE
My app orientation is portrait but i want to show a landscape fullscreen unity view, how can i make it?

### ISSUE THREAD

**Issue by HuyNguyen1590** [juicycleff/flutter-unity-view-widget#671]
I have a portrait orientation app that contain a preview 3D unity view. When I back from the unity view, my status bar and navigation bar not showing as default. After a while, i can only choose to fullscreen but cannot show navigation bar and status bar as default (need to swipe to see it) or not fullscreen unity. 

**Unity (please complete the following information):**
 - OS: Android 
 - Library Version 2020.3.25

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi note 8
 - OS: Android 11

**Comment by gneL1** [comment]
* In Unity  
&emsp;&emsp;click `File -> Building Settings -> Player -> Android Settings -> Resolution and Presentation`  
&emsp;&emsp;I suggest you change `Fullscreen Mode` to `Windowed`, and then use widget to set fullscreen unity in Flutter. 
Don't select `Portrait` and `Portrait Upside Down`,this can make your UnityWidget keep landscape.    
![unity_01](https://user-images.githubusercontent.com/38184470/183827868-5b206d7e-2df7-43c9-9b34-710c06c2f173.PNG)


* In Flutter  
&emsp;&emsp;You can use `SystemChrome.setPreferredOrientations` to set page orientation.

**Comment by HuyNguyen1590** [comment]
> 

That worked great! But I still have a little bit issue, I cannot hide navigation bar in flutter by 
`    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
`
What should i do to hide it in Unity screen and re open it after leave Unity screen?

**Comment by gneL1** [comment]
> > 
> 
> That worked great! But I still have a little bit issue, I cannot hide navigation bar in flutter by ` SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);` What should i do to hide it in Unity screen and re open it after leave Unity screen?

`SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom,SystemUiOverlay.top]` enable navigation bar.  
`SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []` hide navigation bar.  
Are you sure it doesn't work?

**Comment by HuyNguyen1590** [comment]
> > > 
> > 
> > 
> > That worked great! But I still have a little bit issue, I cannot hide navigation bar in flutter by ` SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);` What should i do to hide it in Unity screen and re open it after leave Unity screen?
> 
> `SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom,SystemUiOverlay.top]` enable navigation bar. `SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []` hide navigation bar. Are you sure it doesn't work?

Yeah, At the first time, I think that issue about flutter hot reload/restart but after kill the app and build in release, the issue still exist. These code work if i don't open Unity screen (unity not start yet) but doesn't work if I already open unity.

**Comment by HuyNguyen1590** [comment]
Maybe Unity force my app to show navigation bar. I even tried to turn on "Hide Navigation bar" option in Unity but the result is I cannot Show Navigation bar in flutter.

**Comment by gneL1** [comment]
> Maybe Unity force my app to show navigation bar. I even tried to turn on "Hide Navigation bar" option in Unity but the result is I cannot Show Navigation bar in flutter.

It seems very weried, maybe it is Flutter SDK issue, you can reference timbotimbo's 
https://github.com/juicycleff/flutter-unity-view-widget/issues/667#issue-1320761736
and https://github.com/flutter/flutter/issues/103630#issue-1234149515
Since Flutter update 3.0, there are many issue about platform view

**Comment by HuyNguyen1590** [comment]
I using Flutter 2.10. But thank you for all of this conversation. You saved my day!

**Comment by timbotimbo** [comment]
Unity will sometimes override orientation or fullscreen settings, that flutter can't seem to change back afterwards.
You might have to send a message from flutter to unity, to reset the fullscreen (for navigation bar) or orientation settings from unity's side.
Like done here to return from fullscreen mode. https://github.com/juicycleff/flutter-unity-view-widget/issues/550

**Comment by HuyNguyen1590** [comment]
Thank you so much, this is what i need

Vào 3:33 CH, Th 6, 12 thg 8, 2022 timbotimbo ***@***.***> đã
viết:
