### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by Haidar-Hammoud** [juicycleff/flutter-unity-view-widget#673]
Will this project be supported on macOS anytime soon?

Are there difficulties in supporting macOS that are unclear how to overcome, or is this just a matter of getting around to supporting it?

**Comment by juicycleff** [comment]
@Haidar-Hammoud Unity as a Library does not support macOS at this, so we can't support it until unity does. Here Is a link https://docs.unity3d.com/2019.3/Documentation/Manual/UnityasaLibrary.html
