### ISSUE TITLE
Old FFI version used and imcompatible with other frameworks

### ISSUE THREAD

**Issue by pjarnfelt** [juicycleff/flutter-unity-view-widget#679]
**Describe the bug**
The project is dependent on an old version of FFI that makes it incompatible with other frameworks like Realm that uses ^2.0.1 

**To Reproduce**
1. Create a new Flutter app
2. Add realm: 0.4.0+beta and flutter_unity_widget: ^2022.1.7+1 dependencies to pubspec.yaml

**Expected behavior**
Being able to use both libraries together.

**Additional context**
Because flutter_unity_widget >=2022.1.1 depends on ffi ^1.2.1 and realm >=0.3.2+beta depends on ffi ^2.0.1, flutter_unity_widget >=2022.1.1 is incompatible with realm >=0.3.2+beta.

**Comment by Ahmadre** [comment]
Every version change needs to be checked if our app still works. Because I'm not involved or developed the ffi part here.

Please use:

```yaml
dependency_overrides:
  ffi: ^2.0.1
```

For further informations, please see: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by Ahmadre** [comment]
@juicycleff can we upgrade ffi here?

**Comment by Ahmadre** [comment]
@pjarnfelt in the latest version we comment out ffi at the first run. So you can use that version now.

I will close this issue and assume that we support latest ffi in future 👍
