### ISSUE TITLE
Request tutorial to make it work on emulator

### ISSUE THREAD

**Issue by Ortes** [juicycleff/flutter-unity-view-widget#680]
I'm always frustrated when I need to connect my phone on my computer to try my app.
Could it be possible to have a bit of explanation on how to make it work on emulator ?

**Comment by dawiddszewczyk** [comment]
Hi @Ortes  currently this package don't support emulators,
@juicycleff  can you say more about this case?

**Comment by juicycleff** [comment]
It's possible, but you will need to export debug versions of your unity project either way up to you.

It has nothing to do with the package but rather a how unity exports device architecture when making an export

**Comment by juicycleff** [comment]
There's an export debug functionality, you should use that
