### ISSUE TITLE
【Android】useAndroidViewSurface=true,closed before will flash when switching between UnityWidget pages

### ISSUE THREAD

**Issue by lantis-of-china** [juicycleff/flutter-unity-view-widget#684]
When the **flutter** page is opened and closed on **UnityWidget**, the screen closed before will flash when switching between UnityWidget pages. I don't know what to do. Please give me your advice.

https://user-images.githubusercontent.com/24745583/187664796-2ea58ffc-2a2c-48a4-b7d1-21edc40789d0.mp4

**Comment by timbotimbo** [comment]
Closing this since this is a limitation of Flutter's Hybrid composition mode (`useAndroidViewSurface=true`) since Flutter 3.  
The only way to avoid this is by setting the parameter to false.
