### ISSUE TITLE
Unable to run the example

### ISSUE THREAD

**Issue by Flucadetena** [juicycleff/flutter-unity-view-widget#688]
**Describe the bug**
When trying to run the example project I get the error:

```Could not resolve project :unityLibrary```

**To Reproduce**
1. Download the package
2. Open the example project
3. Run it on Android device
4. Fails with error "Could not resolve project :unityLibrary"

**Expected behavior**
To run the example project

**Comment by Unrealplace** [comment]
I have the same question, so did you fix it?

**Comment by Flucadetena** [comment]
> I have the same question, so did you fix it?

No, neither on android nor on IOS

**Comment by timbotimbo** [comment]
Did you follow the readme and open and export the Unity project?

Between step 2 and 3, you also need to open the example unity project in the `unity/DemoApp` folder.
If you follow the readme for exporting from Unity, this will export files to the `android/unityLibrary` folder.

**Comment by Flucadetena** [comment]
Hi I was able to run the example on android and IOS after a lot of searching. The readme is not very clear for someone coming totally fresh to this "world". If I have the time I'll do a pull request with a more in depth explanation.

But I was never able to run the examples with the anchor api, all the docs are very confusing as multiple things have change and the api that was used for the example has been deprecated.

Despite that, thank you very much for taking the time to answer and develop the package. If I can I'll try to help in its develop for the future.

**Comment by mohamedelbendary228** [comment]
@Flucadetena  Can you share the steps to run the example, I already see the docs but always end with errors when run.
I use unity 2022.1.7f1
flutter_unity_widget: ^2022.2.0
