### ISSUE TITLE
[iOS] flutter run --profile not working.

### ISSUE THREAD

**Issue by siisee11** [juicycleff/flutter-unity-view-widget#691]
**Describe the bug**
[iOS] flutter run --profile not working.

Debug(flutter run) and build(build on Xcode) are working. But the below error occurred when I ran with the --profile option.

```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): No such module 'UnityFramework'
/Users/siisee11/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-2022.2.0/ios/Classes/FLTUnityView.swift:9:7


Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code
```

Is any setting needed to build successfully with the '--profile' option?

**To Reproduce**
1. Go to project root
2. 'flutter run --profile'

**Expected behavior**
run without error

**Screenshots**

**Unity (please complete the following information):**
 - OS: iOS
 - Version 2021.3.4f

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 15.5

**Additional context**

**Comment by siisee11** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8529835/190945089-9afe1aa2-366f-4a16-919e-9f1fd58b194d.png">

Add profile configuration to Unity-iPhone project by duplicating 'Release' configuration

**Comment by ritolika** [comment]
Having the same issue. Everything is working fine until I try to run in profile mode.

**Comment by vonbv** [comment]
I am commenting on this thread because I have a similar error message. My case is that I have configured flavor and so I run this: `flutter run flavor --dev ` I have added the "Release dev" configuration item and even added just "dev". I'm still getting the error. @juicycleff
