### ISSUE TITLE
Black screen on AR with Vuforia (iOS only)

### ISSUE THREAD

**Issue by Valtensir** [juicycleff/flutter-unity-view-widget#692]
**Describe the bug**
When I open the AR scene, the screen goes black, even accepting the request to enable the camera.
I ran only the unity app, and it ran the AR normally.
I'm using the latest package version (2022.2.0).

**To Reproduce**
1. Create a Vuforia AR scene (image target)
2. Export for iOS

**Expected behavior**
Open the camera and run AR normally.

**Screenshots**
Black screen

**Unity (please complete the following information):**
 - OS: iOS
 - Version 2022.1.16

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.6.1

**Comment by dinomaskot** [comment]
I'm getting the same thing just trying to run the Demo Project Unity 2022.2 and latest Vuforia

**Comment by timbotimbo** [comment]
Sounds like an issue with embedding the right frameworks in xcode.
I haven't had time to play with Vuforia yet, but the last steps in this [comment](https://github.com/juicycleff/flutter-unity-view-widget/issues/314#issuecomment-785302253) look promising.

**Comment by dinomaskot** [comment]
Figured it out. It was the unity version. I was running 2022 unity. When i switched to 2021. Problems solved themselves

**Comment by Valtensir** [comment]
> Hi @Valtensir Black screen is launch when you try to fast run scene after create Unity Player, could you add into code some delay before you call specified scene which you want to open?

Hi @dawiddszewczyk. I'm using the Addressable Asset system to load my scene, so I already have a delay before open the scene. Anyway I added a delay just in case, but it still doesn't work.

**Comment by Valtensir** [comment]
> Sounds like an issue with embedding the right frameworks in xcode. I haven't had time to play with Vuforia yet, but the last steps in this [comment](https://github.com/juicycleff/flutter-unity-view-widget/issues/314#issuecomment-785302253) look promising.

Hi @timbotimbo. I followed the instructions but when it says to add the frameworks, the ARFoundationDriver.framework did not appear.

**Comment by Valtensir** [comment]
> Figured it out. It was the unity version. I was running 2022 unity. When i switched to 2021. Problems solved themselves

Hi. @dinomaskot. What version of unity are you using? I changed to version 2021.3.11 but still the same way.

**Comment by dawiddszewczyk** [comment]
Hi @Valtensir 
Great Unity version for use is 2021.3.4 version.

**Comment by timbotimbo** [comment]
The second time that I show up with an old link, lets hope this one does help.

Here they seem to need to include a vuforia folder in the xcode project.
https://github.com/f111fei/react-native-unity-demo/pull/16

Shouldn't really matter here if you include the project in react or flutter.

**Comment by Valtensir** [comment]
Thank you so much @timbotimbo.
The AR is working fine now.
I'm getting a white screen in the first time I open the unity, but it seems to be another issue.
