### ISSUE TITLE
Is this widget using WebGL build of Unity for Android?

### ISSUE THREAD

**Issue by koreex** [juicycleff/flutter-unity-view-widget#694]
I'm wondering if this widget is using WebGL build or Android build for Android. If it uses WebGL build with web view on Android, the performance wouldn't be enough.

**Comment by timbotimbo** [comment]
It uses an android export from Unity.
In my experience performance is a little worse than a regular android unity app. But way better than webgl on mobile.

**Comment by koreex** [comment]
If it uses Android build, it would be way better than WebGL. Thank you @timbotimbo
