### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by acaero** [juicycleff/flutter-unity-view-widget#695]
Hello there,
After two unsuccessful days of trying to get the example to work I am kindly asking for help.

**Describe the bug**
After clicking on any of the options in the MenuScreen the Appbar from the opened Route shows up but underneath (where the unity widget should show up) the MenuScreen opens up again:

After clicking on "Simple Unity Demo":
![image](https://user-images.githubusercontent.com/75180580/192367926-20b31c46-2845-4666-bb5e-75db059a2f76.png)

After clicking on "No Interaction Unity Demo":
![image](https://user-images.githubusercontent.com/75180580/192368317-cbd8fb72-e331-47bb-aa58-5ea38cc6d66f.png)

When I tried to implement the package myself (without the example-project), I only had one screen and placed the Unity-Widget directly in the body of a Scaffold inside of a MaterialApp. When I started the app, it opened the screen recursively inside of itself:

![image](https://user-images.githubusercontent.com/75180580/192370147-aaa73ccc-0cef-4010-86f1-4fde9b3bd104.png)

meanwhile producting the following log:

_

> [log] *********************************************
> [log] ** flutter unity controller setup complete **
> [log] *********************************************
> Flutter Web Bootstrap: Auto
> TypeError: Cannot read properties of null (reading 'removeChild')
> main.dart.js 72:22                    <fn>
> dwds/src/injected/client.js 24535:40  <fn>
> dwds/src/injected/client.js 3471:15   $protected
> dwds/src/injected/client.js 11541:12  call$2
> dwds/src/injected/client.js 11529:32  call$1
> dwds/src/injected/client.js 3833:18   _rootRunUnary
> dwds/src/injected/client.js 12941:39  runUnary$2$2
> dwds/src/injected/client.js 11973:51  call$0
> dwds/src/injected/client.js 3613:93   _Future__propagateToListeners
> dwds/src/injected/client.js 11799:9   _completeWithValue$1
> dwds/src/injected/client.js 11512:14  complete$1
> dwds/src/injected/client.js 3443:17   _asyncReturn
> dwds/src/injected/client.js 8734:24   <fn>
> dwds/src/injected/client.js 3471:15   $protected
> dwds/src/injected/client.js 11541:12  call$2
> dwds/src/injected/client.js 11529:32  call$1
> dwds/src/injected/client.js 3833:18   _rootRunUnary
> dwds/src/injected/client.js 12941:39  runUnary$2$2
> dwds/src/injected/client.js 11973:51  call$0
> dwds/src/injected/client.js 3613:93   _Future__propagateToListeners
> dwds/src/injected/client.js 11799:9   _completeWithValue$1
> dwds/src/injected/client.js 11512:14  complete$1
> dwds/src/injected/client.js 3443:17   _asyncReturn
> dwds/src/injected/client.js 25007:24  <fn>
> dwds/src/injected/client.js 3471:15   $protected
> dwds/src/injected/client.js 11541:12  call$2
> dwds/src/injected/client.js 11529:32  call$1
> dwds/src/injected/client.js 3833:18   _rootRunUnary
> dwds/src/injected/client.js 12941:39  runUnary$2$2
> dwds/src/injected/client.js 11973:51  call$0
> dwds/src/injected/client.js 3613:93   _Future__propagateToListeners
> dwds/src/injected/client.js 11799:9   _completeWithValue$1
> dwds/src/injected/client.js 11512:14  complete$1
> dwds/src/injected/client.js 3443:17   _asyncReturn
> dwds/src/injected/client.js 24984:24  <fn>
> dwds/src/injected/client.js 3471:15   $protected
> dwds/src/injected/client.js 11541:12  call$2
> dwds/src/injected/client.js 11529:32  call$1
> dwds/src/injected/client.js 3833:18   _rootRunUnary
> dwds/src/injected/client.js 12941:39  runUnary$2$2
> dwds/src/injected/client.js 11973:51  call$0
> dwds/src/injected/client.js 3613:93   _Future__propagateToListeners
> dwds/src/injected/client.js 11799:9   _completeWithValue$1
> dwds/src/injected/client.js 11901:18  call$0
> dwds/src/injected/client.js 3818:16   _rootRun
> dwds/src/injected/client.js 12933:39  run$1$1
> dwds/src/injected/client.js 12876:14  runGuarded$1
> dwds/src/injected/client.js 13071:25  call$0
> dwds/src/injected/client.js 3677:24   _microtaskLoop
> dwds/src/injected/client.js 3683:11   _startMicrotaskLoop
> dwds/src/injected/client.js 11417:9   call$1
> dwds/src/injected/client.js 1277:26   invokeClosure
> dwds/src/injected/client.js 1296:18   <fn>
> Height of Platform View type: [_iframe_b6f1d3f3_3f0b_4f1b_89cb_634b3d5983a9] may not be set. Defaulting to `height: 100%`.
> Set `style.height` to any appropriate value to stop this message.
> Width of Platform View type: [_iframe_b6f1d3f3_3f0b_4f1b_89cb_634b3d5983a9] may not be set. Defaulting to `width: 100%`.
> Set `style.width` to any appropriate value to stop this message.
> [log] *********************************************
> [log] ** flutter unity controller setup complete **
> [log] *********************************************
> TypeError: Cannot read properties of null (reading 'removeChild')
> main.dart.js 72:22                    <fn>
> dwds/src/injected/client.js 24535:40  <fn>
> dwds/src/injected/client.js 3471:15   $protected

_

So to me it seems like the unity-widget experiences a problem while opening, which somehow causes the topmost widget to open up instead.

**To Reproduce**
Steps to reproduce the error in the example project:
1. Cloned the Repo
2. Loaded the Demo Project in Unity with Editor Version 2022.1.13f1
3. Selected the SampleScene
4. Switched Platform to Android, Scripting Backend to IL2CPP and Target Architecture to ARMv7 & ARM64
5. Flutter -> Export Android (Debug)
6. Ran main.dart with Chrome

**Expected behavior**
I expected to see the rotating cube inside of the unity widget

**Unity (please complete the following information):**
 - OS: Windows
 - Version: Unity Hub 3.3.0, Editor 2022.1.13f1

**Smartphone (please complete the following information):**
The emulators did not work (but according to the documentation that was to be expected).
I did not try it with a physical smartphone, because I do not have the necessary cable right now.

I am lost and need help.
Kind regards
David

**Comment by timbotimbo** [comment]
I can't say anything about issues in the web plugin because I only use this plugin on mobile, but I can see a mistake from these steps:
> 4. Switched Platform to Android, Scripting Backend to IL2CPP and Target Architecture to ARMv7 & ARM64
> 5. Flutter -> Export Android (Debug)
> 6. Ran main.dart with Chrome

You export an android version, but run it in chrome, which needs a web version.
That android export will only work if you run the flutter app on an android device.

**Comment by acaero** [comment]
Thank you very much, that might just be the root of the problem. Either way I bought the necessary cable and it works now.

On one hand I feel stupid for not realizing that myself, on the other hand I feel like the documentation could be more explicit about the fact that you apparently need a physical device connected to your pc in order to make the package work.
