### ISSUE TITLE
MissingPluginException(No implementation found for method unity#postMessage on channel plugin.xraph.com/unity_view_0) 

### ISSUE THREAD

**Issue by siisee11** [juicycleff/flutter-unity-view-widget#696]
**Describe the bug**
Unhandled Exception: MissingPluginException(No implementation found for method unity#postMessage on channel plugin.xraph.com/unity_view_0)  occurs on dispose method.

I want to call postMessage to release some memory from unity and stop player loop before navigating to other pages. The problem is dispose() function of unity widget called before I call postMessage function on `my_page.dart`. How can I handle it?

```
my_page.dart

  @override
  void dispose() {
     _unityWidgetController.postMessage(
        'AppManager', 'OnMessageFromFlutter', 'stop');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => _cameraBloc,
      child: Scaffold(
        key: _scaffoldKey,
        body: Stack(
          children: [
            UnityWidget(
              onUnityCreated: _onUnityCreated,
              onUnityMessage: onUnityMessage,
              onUnitySceneLoaded: onUnitySceneLoaded,
              useAndroidViewSurface: true,
              fullscreen: true,
            ),
            
            .
            .
            .


unity_widget.dart

  @override
  Future<void> dispose() async {
    if (!kIsWeb) {
      if (_nextUnityCreationId > 0) --_nextUnityCreationId;
    }
    try {
      _controller?.dispose();
      _controller = null;
    } catch (e) {
      // todo: implement
    }
    super.dispose();
  }
```

**To Reproduce**

**Expected behavior**
postMessage to Unity and then dispose widget

**Screenshots**

**Unity (please complete the following information):**
 - OS: [e.g. iOS] iOS

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 13
 - OS: [e.g. iOS8.1] iOS 15

**Additional context**

**Comment by dawiddszewczyk** [comment]
Hi @siisee11 
Maybe use bloc listener to check sign from Unity and made it with using bloc ? 

That's is easy in maintain with logic state of application.
```dart
BlocConsumer<XCubit, XState>(
            listener: (context, state) => state.mapOrNull(
             closeAction: (state) =>   _unityWidgetController.postMessage(
        'AppManager', 'OnMessageFromFlutter', 'stop'),
            builder: (_, __) => UnityWidget(
              onUnityCreated: onUnityCreated,
              onUnityMessage: onUnityMessage,
              onUnitySceneLoaded: onUnitySceneLoaded,
              useAndroidViewSurface: true,
              fullscreen: true,
            ),
```

**Comment by siisee11** [comment]
@dawiddszewczyk  I put ```     _unityWidgetController.postMessage(
        'AppManager', 'OnMessageFromFlutter', 'stop');``` to deactivate life cycle and it works. I think this is not a good solution, so I'll use bloc as you suggested.
