### ISSUE TITLE
Many people have mentioned the problem of not being able to multi-tap on Unity IOS, but have you solved it after all?

### ISSUE THREAD

**Issue by KuroishiTomoki** [juicycleff/flutter-unity-view-widget#701]
**Describe the bug**
I'm in trouble with the problem that I can't multi-tap IOS in Unity. 
https://github.com/juicycleff/flutter-unity-view-widget/issues/505
Exactly the same problem as here, no clear solution listed here

**To Reproduce**
1. Suppose I have two buttons
2. Tap down and hold "Button1" with one finger.
3. Tap down and hold "Button2" with another finger.
4. Move the first finger away from "Button1".
5. Tap down and hold "Button1".
6. Move the finger away from "Button1" again.

Expected results:
The first 4 steps behave normally. However, step 5 should make "Button1" get pressed, and step 6 should make "Button1" released.

Actual results:
On step 5, when my finger is tapping on "Button1", "Button1" is not tapped! And on step 6, when my finger moves away from "Button1", "Button2" is released!

**Unity (please complete the following information):**
 - OS: [iOS]
 - Version [e.g. 2022.1.7]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS15.6.1]

**Additional context**
What I want to ask about this issue is, has Unity already solved the problem of not being able to multi-tap on iOS with Flutter Unity Wiget? If so, where is the solution documented?
If not, I would appreciate it if you could answer "not solved". @juicycleff

**Comment by timbotimbo** [comment]
Just tested this with Flutter 3.3.5 and the answer is not solved.

This seems to be an issue with platform views in Flutter, and is not related to Unity.
Comments in the linked issue mention issues reporting this in the Flutter repo and those issues are still open.

**Comment by Ahmadre** [comment]
Please follow: https://github.com/flutter/flutter/issues/96640#issuecomment-1147951815
