### ISSUE TITLE
App crashes on iOS16 with Xcode 14

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#703]
**Describe the bug**
Unity will instantly crash when ran on an iOS 16 device using Xcode 14.
This will cause an app using `flutter_unity_widget` to crash on the splash screen.
The exact same project will run like normal with Xcode 14 on iPadOS 15, and probably iOS 15 too.

Looks like the issue was already reported to Flutter [here](https://github.com/flutter/flutter/issues/112233) by @RoyalCoder88, but it was closed because it is a Unity issue. 
Given that we use Unity here, it is important to document this crash here.

I'm not sure which exact Unity versions have this error, but I've seen multiple 2021.3.x versions mentioned.

**To Reproduce**
My setup:
- Unity 2021.3.6
- flutter_unity_widget 2022.2.0
- iPhone XS with iOS16
- Xcode 14.0.1

1. Setup the example project, and export iOS in the Unity project.
2. Click run in Xcode.
3. Xcode will throw errors when the app starts.

**Solution**
[This unity forum thread](https://forum.unity.com/threads/unity-2021-3-6f1-xcode-14-ios-16-problem-unityframework-crash-before-main.1338284/) has a workaround.

In Xcode go to `Product > Scheme > Edit Scheme > Run > Diagnostics` (shortcut `⌘ <`).
Now disable `Thread Performance Checker`.
![scheme](https://user-images.githubusercontent.com/11444698/197397014-2f185943-14b9-4969-8ced-7a26b1f36add.png)

Changing this setting has stopped the crash for me.

**Related**
For another iOS 16 crash, this other [Unity forum thread](https://forum.unity.com/threads/unity-2021-3-9f1-xcode-14-ios-16-problem.1335296/) mentions random crashes in AR on iOS 16. Here disabling Multi-threaded rendering in the Unity player settings seems to get rid of the crashes.

**Comment by timbotimbo** [comment]
- Confirmed the same issue & solution for iPadOS 16.1.
- Setting Run to release mode doesn't seem to crash either.

Looks like this Is also a duplicate of #693.

**Comment by alicanyimaz** [comment]
Helal lan sana

**Comment by timbotimbo** [comment]
This was [fixed by Unity](https://issuetracker.unity3d.com/issues/ios-player-crashes-on-ios-16-devices-when-unityframework-dot-framework-is-added-in-link-binary-with-libraries?_ga=2.146004660.1894360213.1678312546-1768432617.1666480586).


Fix is available since:
`2021.3.17f1`
`2022.2.2f1`
`2023.1.0a20`
