### ISSUE TITLE
error: Could not find file \android\build.gradle

### ISSUE THREAD

**Issue by INTKILOW** [juicycleff/flutter-unity-view-widget#706]
FileNotFoundException: Could not find file "C:\Users\INTKI\android\build.gradle"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string,System.Text.Encoding,bool)
System.IO.File.InternalReadAllText (System.String path, System.Text.Encoding encoding) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
System.IO.File.ReadAllText (System.String path) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
FlutterUnityIntegration.Editor.Build.SetupAndroidProject () (at Assets/FlutterUnityIntegration/Editor/Build.cs:469)
FlutterUnityIntegration.Editor.Build.DoBuildAndroid (System.String buildPath, System.Boolean isPlugin, System.Boolean isReleaseBuild) (at Assets/FlutterUnityIntegration/Editor/Build.cs:237)
FlutterUnityIntegration.Editor.Build.DoBuildAndroidLibraryRelease () (at Assets/FlutterUnityIntegration/Editor/Build.cs:43)

**Comment by timbotimbo** [comment]
The build script expects your Unity project to be in a subfolder of a Flutter project.

It is looking 2 folders up the hierarchy.
```
var androidPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../android"));
var androidAppPath = Path.GetFullPath(Path.Combine(ProjectPath, "../../android/app"));
```
Look at the example
`example/` is the root of the Flutter project.
`example/unity/DemoApp/` is the root of the Unity project.

**Comment by thedrhax14** [comment]
@timbotimbo I believe this is not documented. Please, whenever possible submit a README update that mention this, because this is quite important. It was such a headache in my project

**Comment by ROBYER1** [comment]
Would be neat if the exporter had a clearer error log for this perhaps just to warn the user that there is no flutter project detected above the Unity Project before it tries to build.

**Comment by timbotimbo** [comment]
@ROBYER1    I've added a few fixes like this in personal `build.cs_cleanup` [branch](https://github.com/timbotimbo/flutter-unity-view-widget/commits/build.cs_cleanup).
Including almost exactly what you suggest: https://github.com/timbotimbo/flutter-unity-view-widget/commit/fc67108cbb4e1a6b2df1ed336bbbbba1d1a4087b

Will make a pull request later, but I'm waiting for some others as it feels kind of useless to make tons of pull requests that all need to merge each other again later.
