### ISSUE TITLE
Controller in Web GL doens't work

### ISSUE THREAD

**Issue by RamiroNoronha** [juicycleff/flutter-unity-view-widget#715]
**Describe the bug**
I am having a problem with the controller, when I am using Web GL. The onCreated method doesn't work, because when I try to send a message to unity, nothing happens.

**To Reproduce**
1. I do Flutter Export Web GL
2. I created the method to inicialize the controller
3. I put a print to see the controller
4. The message is Instance of 'WebUnityWidgetController', but doesn't work.

**Expected behavior**
Send a message to unity, for the unity opens the scene.

**Screenshots**
![image](https://user-images.githubusercontent.com/100360738/202207851-c378c985-f977-4539-a111-966acaa24c47.png)

**Unity (please complete the following information):**
 - OS: [e.g. iOS] Web
 - Version [e.g. 22] Chrome
 -  Unity Version 2022.1.17f1

**Additional context**

**Comment by jesseburstrom** [comment]
I found the solution! In the created index.html file for unity under build/web/UnityLibrary you have to add 
.then((unityInstance) => {mainUnityInstance = unityInstance}); on the createUnityInstance method alternatively write mainUnityInstance = await createUnityInstance(... before. Some cut/paste error logic in the build.cs in unity causes this!

**Comment by timbotimbo** [comment]
Did you use the latest unitypackage?
Sending messages seems to work fine when I build the example. (windows Unity 2022.1.23)

And it looks like code similar to your suggestion is already added by build.cs
https://github.com/juicycleff/flutter-unity-view-widget/blob/7f55bc2eddc81a13c32eabe25b53202e11861ba9/example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/Build.cs#L290-L295
