### ISSUE TITLE
Export IOS Error (add NatML)

### ISSUE THREAD

**Issue by East-Nine** [juicycleff/flutter-unity-view-widget#716]
**Describe the bug**
I needed a recording function in Unity, so I developed it using NatML Recorder. ([https://docs.natml.ai/natcorder/](https://docs.natml.ai/natcorder/))
Export went well before attaching the recording function, but export errors occur after adding.
As a test, it works well by removing the recording function code and exporting it.
This bug works fine on Android, but has problems on IOS.

unity: 2022.1.7f1
package: fuw-2022.1.7f1.unitypackage

**Screenshots**
<img width="1262" alt="스크린샷 2022-11-18 오후 4 02 28" src="https://user-images.githubusercontent.com/13677307/202642649-f3395dc9-8a88-48ff-b043-d3f8d2b43f16.png">
<img width="1260" alt="스크린샷 2022-11-18 오후 4 02 55" src="https://user-images.githubusercontent.com/13677307/202642671-c8e3bb10-c8f7-4626-9fd8-92c46b1a9b70.png">
<img width="1261" alt="스크린샷 2022-11-18 오후 4 03 10" src="https://user-images.githubusercontent.com/13677307/202642665-343b794d-35a9-445e-8cf8-0dfb1811b7d6.png">

**Comment by timbotimbo** [comment]
This is response is purely based on similar unity errors on the Unity forums [like this](https://forum.unity.com/threads/build-failing-with-command-failed-to-write-the-following-output-file.1238776/).
But it looks like you are missing a usage description string in the Unity player settings. Probably `Camera Usage Description` or `Microphone Usage Description` given that it is a recorder.

**Comment by East-Nine** [comment]
It's my mistake.
Microphone Usage Description was missing. thank you!!
