### ISSUE TITLE
I want to shut down unity completely while the app is running.

### ISSUE THREAD

**Issue by hu1won** [juicycleff/flutter-unity-view-widget#720]
My app goes back and forth between Web view and unity through Flutter. There is no problem running unity in Webview, but it occurs when you return to Webview after running Unity. If Unity is not completely shut down and you run Unity again, it will be loaded as it was previously run, causing an error or ending the app. This problem will not perform well using resources from memory, CPU, and GPU.

Can you suggest a way to solve it?

**Comment by timbotimbo** [comment]
As far as I know this isn't fully supported.

#### Quit()
`controller.quit()` will kill the entire app on android, making it useless.
Furthermore, the Unity documentation gives another reason why this won't ever work on iOS:
> On iOS, if the Unity runtime quits entirely (after calling `Application.Quit`), it’s not possible to reload Unity again in the same app session.


#### Unload()
The closest thing is unload, but this is only implemented in the plugin on Android, not  iOS.

> On iOS and Android, Unload releases memory used by Scenes and GameObjects, but reserves some memory which is necessary for running Unity in the same process again.

Unload on android:
From my testing `controller.unload()` works, but `UnityWidget(unloadOnDispose:true)` does NOT seem to work.
You will see the last rendered frame if the UnityWidget was still open, and on the next UnityWidget launch the scene at sceneIndex 0 is loaded like new.



According to the [Unity documentation](https://docs.unity3d.com/2022.2/Documentation/Manual/UnityasaLibrary.html), Unity is still using some memory.
> When Unity is in an unloaded state (after calling `Application.Unload`), it retains some amount of memory (between 80–180Mb) to be able to instantly switch back and run again in the same process. The amount of memory that is not released largely depends on the device’s graphics resolution.

You could also try calling `Application.Unload` within Unity on iOS, and see what happens.

**Comment by hu1won** [comment]
Thanks for your reply. Let me try.

**Comment by dawiddszewczyk** [comment]
Hi @hu1won , once initialized unity need to works in background its impossible to quit from unity, but you can unload scene (on Android , on iOS its not works) or change to empty scene like blank page to free resources.
