### ISSUE TITLE
Issues with FlutterUnityIntegration

### ISSUE THREAD

**Issue by fiercepark** [juicycleff/flutter-unity-view-widget#723]
**Describe the bug**
In some cases, when I successfully export the unity project to the android platform, the android apk compilation will stop when compiling on the flutter side because proguard-unity.txt is missing a newline character.

**Note**
As unitypackage cannot produce PR, I am posting my solution here.

line:356 in Build.cs
I've tried:

`proguardText += "\n-keep class com.unity3d.plugin.* { *; }";`

That works for me.

**Comment by timbotimbo** [comment]
As far as I know, they UnityPackage is exported from the example unity project.
Basically the contents of `example\unity\DemoApp\Assets\FlutterUnityIntegration`.

I just PR changes to the build.cs file, and those will probably make it into the next UnityPackage whenever it is updated.

I have yet to get this specific issue, but the fix doesn't seem likely to break anything either.

**Comment by fiercepark** [comment]
@timbotimbo 

I am having this problem on a mac device with m1 chip, using unity-2022.2.0b16 [Silicon beta].

BTW, it is not determined whether the problem is related to the device platform.
