### ISSUE TITLE
Please help me with the "No such module" Error

### ISSUE THREAD

**Issue by hu1won** [juicycleff/flutter-unity-view-widget#735]
__Hello,__

> I haven't been able to solve this problem for a week.
> This issue works fine on Android, but only on iOS.
>
> __First,__ let me introduce my problem.
>
> ![image](https://user-images.githubusercontent.com/71807924/208628656-d4e767a4-7ac8-4125-9098-4bc8110d3ee4.png)

```
UnityFramework cannot be found continuously when flutter is running.
```

> I think this is the problem.
>
> ![image](https://user-images.githubusercontent.com/71807924/208632128-fb196c07-7578-4b4a-b349-f2edc2ab2b02.png)
>
>

```
In Xcode, UnityFramework is also displayed in red and the UnityFramework.Framework file does not exist in its path.
```

I tried __Pod install, rm-Rf build, flutter clean, Xcode version up, and so on,__ but it didn't work.

Also, I tried everything by referring to [similar problems](https://github.com/juicycleff/flutter-unity-view-widget/issues/373), but it didn't help me much. Is there a way to solve this?

__If anyone has solved it or knows how to solve it, please help me.__

* * *

### Additional questions
> Or is there a way to manually create the UnityFramework.Framework file and put it in the path?

**Comment by timbotimbo** [comment]
The 3rd line in your first screenshot:
> Could not build the application for the simulator

You won't get this error on a real iphone, only on a simulator.
This plugin and the unity export have issues with x86 simulators.

If you are on a mac with m1 or m2 processor, you can run it in "mac, designed for iphone" mode.

**Comment by hu1won** [comment]
Thank you for your reply, @timbotimbo .

I recognized the problem and tried to run it on an actual iPhone device, but the error "No such module" occurs the same way.

> I tried building using iPhone X.

**Comment by dawiddszewczyk** [comment]
Hi @hu1won,
Enter into Unity Project, and upload again unity package, then check in targets if unity framework is checked
