### ISSUE TITLE
[Unity 2019] 3d Model gets cropped out when resized in web

### ISSUE THREAD

**Issue by jawaharbabugit** [juicycleff/flutter-unity-view-widget#755]
**Describe the bug**
When I wrap the widget with a container or a sizedbox with a specific height and width, the 3d model is getting cropped instead of getting resized, as oppose to the android where it is getting resized properly.

**To Reproduce**
1. Exported the Unity web files using [fuw-2022.1.7f1.unitypackage]
2.Wrap the unitywidget in sizedbox of height and width 200.
3.run in debug mode in chrome

**Expected behavior**
I expected the model to get resized properly instead of getting cropped.

**Unity (please complete the following information):**
    Platform: Web(Chrome)
    Version: flutter_unity_widget 2022.2.0
    Unity Editor: 2019.4.39f1
    Mode : Debug

**Comment by timbotimbo** [comment]
Looks alright to me using Unity 2022, 2021 or 2020.

<img src="https://user-images.githubusercontent.com/11444698/216439730-53d2ba14-08bf-4ca0-b23b-78adc84ecd17.jpg" width="40%"> <img src="https://user-images.githubusercontent.com/11444698/216439756-a9ff8697-af8a-4de8-8208-f528f12ec4eb.jpg" width="40%">

Both your issues seem related to Unity 2019. Like answered [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/754#issuecomment-1414380827), the export breaks for Unity 2019 as the `unityLibrary/index.html` is different than expected.

I assume you are missing the canvas width and height being set to 100% here.
Looks like unity sets this fixed, which causes your issue.
`<div id="unityContainer" style="width: 960px; height: 600px"></div>`

I would suggest using a newer Unity version.
