### ISSUE TITLE
The apk file cannot be generated.

### ISSUE THREAD

**Issue by alkaou** [juicycleff/flutter-unity-view-widget#762]
Hello everyone, I created a flutter and unity project that works very well locally. But when I'm trying to generate the APK file then I get errors.

Thanks for any help.

Unity 2022.2.1f1
flutter 3.7
flutter_unity_widget_2022.2
package for flutter 2022.1

`flutter build apk`
`flutter build apk --target-platform android-arm,android-arm64`

`
Build succeeded with 2 successful nodes and 0 failed ones

Format incorrect du param�tre -

ERROR : C:\Users\neked\Desktop\Android Studio Projects\fl_uni_app\build\unityLibrary\intermediates\consumer_proguard_dir\release\lib0\proguard.txt:20:56: R8: Expected char '-' at C:\Users\neked\Desktop\Android Studio Projects\fl_uni_app\build\unityLibrary\intermediates\consumer_proguard_dir\release\lib0\proguard.txt:20:56
-dontwarn com.google.android.play.core.tasks.Task-keep class com.unity3d.plugin.* { *; }
                                                       ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: offset: 1095, line: 20, column: 56, origin: C:\Users\neked\Desktop\Android Studio Projects\fl_uni_app\build\unityLibrary\intermediates\consumer_proguard_dir\release\lib0\proguard.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34m 34s
Running Gradle task 'assembleRelease'...                         2086,3s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
`

**Comment by timbotimbo** [comment]
I think there is a line break missing in a proguard file in android/unityLibrary. I think its called `proguard-user.txt`.

The line should be
`-keep class com.unity3d.plugin.* { *; }`, but it looks like it attached to te previous line in your error.

**Comment by alkaou** [comment]
> I think there is a line break missing in a proguard file in android/unityLibrary. I think its called `proguard-user.txt`.
> 
> The line should be `-keep class com.unity3d.plugin.* { *; }`, but it looks like it is attached to te previous line in your error.

I removed the line now it works very well. Thank you very much. But now the problem is that the size of the APK is very large `(284MB)`. whereas I only have a simple scene containing a cube without scripts. Developpement apk size is `(374 mo)` Please how can I reduce its size? Please help me.

![Screenshot_20230209-200030](https://user-images.githubusercontent.com/50831171/218232197-4b169258-0a05-4073-b767-9db254d04273.png)

this is apk build by command  `flutter build apk --target-platform android-arm,android-arm64`
![edit](https://user-images.githubusercontent.com/50831171/218232307-711f6ba0-515f-4fe6-8880-afee05be97db.png)

**Comment by timbotimbo** [comment]
Your screenshot shows a development build. Exporting from Unity in the release setting will make it smaller. You can also look at Unity settings like code stripping.

The apk will also have duplicate data for arm7 and arm64. Downloads from the play store will be smaller because you'll only need one of those.

**Comment by TonyHoyle** [comment]
For anyone encountering this, it can be fixed by changing a line in build.cs.  Since the proguard file is generated just hand modifying it didn't work for us (my build file is heavily modified so making a patch wouldn't work, but it's an easy enough fix).

proguardText += "-keep class com.unity3d.plugin.* { *; }";

to 

proguardText += "\n-keep class com.unity3d.plugin.* { *; }";
