### ISSUE TITLE
open desired scene from button in flutter - multiple scenes

### ISSUE THREAD

**Issue by omarsalem15** [juicycleff/flutter-unity-view-widget#763]
hello all 
I want to make a button in Flutter screen to open a specific scene in unity 
I don't want to change the scenes from unity , I want to change it from the main screen in flutter 

button 1 will open scene 1
button 2 will open scene 2

**Comment by timbotimbo** [comment]
You just posted this exact question on 10+ different issues, some of which already explained exactly what you need.

You send a message from flutter to unity, which calls a function in a unity script. That c# function should change the scene using the scenemanager.

If unity isnt loaded yet, just send it immediately in the onCreated callback of the widget.

**Comment by omarsalem15** [comment]
sorry for the duplication 
can you please send me the steps 
because i am running the demoApp and there is a button "next screen" made in unity and also a c# script "scene loader" but this change the scene from a button in unity 
i want to make the button from flutter to open different scene which has index 2 or 1 
you mean

**Comment by omarsalem15** [comment]
> You just posted this exact question on 10+ different issues, some of which already explained exactly what you need.
> 
> You send a message from flutter to unity, which calls a function in a unity script. That c# function should change the scene using the scenemanager.
> 
> If unity isnt loaded yet, just send it immediately in the onCreated callback of the widget.

i don't know what to write on postMessage as it takes 3 parameters (String gameObject, methodName, message)
and i don't want to change a gameobject i want to change the whole scene

**Comment by RoyalCoder88** [comment]
Hi @omarsalem15 ,

It's very simple to achieve this, for the **postMessage** method you're required to pass 3 parameters:

1.  **gameObject** it's your "game manager" object from Unity's scene for example "**MY_GM**"
2.  **methodName** is the method from **MY_GM** attached script **ChangeTheSceneNow**
3.  **message** is a parameter to pass what you want (string, int, double, json etc.) as a **String**

_Unity script example:_

```
using FlutterUnityIntegration;
using UnityEngine;
using UnityEngine.SceneManagement;

public class MyGameManager: MonoBehaviour
{

    public void ChangeTheSceneNow(string sceneName)
    {
        Debug.Log("Let's change scene to: " + sceneName);
        SceneManager.LoadScene(sceneName, LoadSceneMode.Single);
    }
}

```

_In Flutter:_

```
 _unityWidgetCtrl.postMessage('MY_GM', 'ChangeTheSceneNow', 'scene_1');
```

Hope you will understand now ;)

**Comment by omarsalem15** [comment]
@RoyalCoder88 @timbotimbo 
thanks for your reply

i have one more question 
what about if i have only 1 scene and i want to show or hide specific gameobject in the scene by flutter button

**Comment by AhmedNavaz** [comment]
> Hi @omarsalem15 ,
> 
> It's very simple to achieve this, for the **postMessage** method you're required to pass 3 parameters:
> 
> 1. **gameObject** it's your "game manager" object from Unity's scene for example "**MY_GM**"
> 2. **methodName** is the method from **MY_GM** attached script **ChangeTheSceneNow**
> 3. **message** is a parameter to pass what you want (string, int, double, json etc.) as a **String**
> 
> _Unity script example:_
> 
> ```
> using FlutterUnityIntegration;
> using UnityEngine;
> using UnityEngine.SceneManagement;
> 
> public class MyGameManager: MonoBehaviour
> {
> 
>     public void ChangeTheSceneNow(string sceneName)
>     {
>         Debug.Log("Let's change scene to: " + sceneName);
>         SceneManager.LoadScene(sceneName, LoadSceneMode.Single);
>     }
> }
> ```
> 
> _In Flutter:_
> 
> ```
>  _unityWidgetCtrl.postMessage('MY_GM', 'ChangeTheSceneNow', 'scene_1');
> ```
> 
> Hope you will understand now ;)

Is this you in the dp?
