### ISSUE TITLE
Unity's New Input system breaks touch input on android.

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#766]
**Describe the bug**
There were multiple users on Discord that mentioned touch not working on android.
After some testing it appears to be because of the new input system in Unity.
Once the New Input System is enabled, touch no longer works on android.

It only occurs with the default `useAndroidViewSurface: false`, setting it to true makes touch work again.
This workaround causes quite a few bugs so I would not recommend doing this.

My current advice is to stick with the (default) old input system or use the Both setting.

**To Reproduce**
Enable the new input:
1. Open the example project
2. Change the input system in the unity player settings to the new package.
![input system](https://user-images.githubusercontent.com/11444698/218411129-84565b02-73a3-4abc-9b0e-dc0733c7a76c.jpg)
3. Install the `Input system` package from the package manager.
4. In the scene, open the `EventSystem-> Standalone input module`.
There should be a button to update it to the `Input System UI Input Module`.
5. Canvas buttons now work using the new input system.

1. Make a unity export of the example with the new input system.
2.  Run it on android and no touch input in Unity will work.

|Platform   | Old input   | New input   |
|---|---|---|
| iOS  | ✓| ✓ |
| webGL  | ✓ | ✓  |
| Android (useAndroidViewSurface: false)  | ✓  | ❌  |
| Android (useAndroidViewSurface: true)  | ✓  | ✓  |

### Setup
- Android 7, 9, 12 and 13
- Unity 2021.3.14 and 2022.2.5.

**Comment by kcrebound** [comment]
Got the same problem, disabled useAndroidViewSurface: false to fix problem with handling swipe events on android, for emulators actually it is working good, but for real device it is breaks inputs at all 

> This workaround causes quite a few bugs so I would not recommend doing this.

can you explain this part? Which bugs do you have here?

**Comment by timbotimbo** [comment]
Some drawbacks that I have noticed using `useAndroidViewSurface: true`
- Unity widget is invisible on Android 6 & 7.
- Page transitions look weird due to flutter hybrid composition issues. #683
- Blur & rounded corners etc. don't work on top of it.
- The widget might popup up over other UI on app resume. https://github.com/juicycleff/flutter-unity-view-widget/issues/647

Because of things these (and probably more) I never use that mode.
