### ISSUE TITLE
GameManager 

### ISSUE THREAD

**Issue by yussifm** [juicycleff/flutter-unity-view-widget#775]
**Describe the bug**
global Namespace already contain a definition 
![image_2023-02-25_02-40-33](https://user-images.githubusercontent.com/43506617/221332188-89d81947-3743-49d8-9274-27d036fc8d6e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

![image_2023-02-25_02-40-33](https://user-images.githubusercontent.com/43506617/221332194-1d3f5102-f722-4df6-b78e-25429244db63.png)

**Unity (please complete the following information):**
 - OS: windows 11
 - Version 22
 - 2021.3.17

**Smartphone (please complete the following information):**
 - Device: android
 - OS: 
 - Version [

**Additional context**

**Comment by timbotimbo** [comment]
The demo scene in the unitypackage uses a `GameManager` script to handle pause and play for the webgl export.
If you only use mobile you can just delete the script.

Otherwise just rename it.
