### ISSUE TITLE
Support for Linux Desktop

### ISSUE THREAD

**Issue by zafana1** [juicycleff/flutter-unity-view-widget#787]
Are there any plans or a timeline for adding support for Linux Desktop especially **Ubuntu**? It looks like the only platform currently missing.

**Comment by timbotimbo** [comment]
[Unity as a library](https://docs.unity3d.com/Manual/UnityasaLibrary.html) only supports iOS, android and Windows.

Any other platform can't be supported if Unity doesn't either.

Web is the exception, as that is just including the WebGL build in a webview

**Comment by zafana1** [comment]
Thank you for the quick response @timbotimbo.
I thought because you can publish Unity apps to Linux, there is support. That is odd.
