### ISSUE TITLE
UnityWidgetController has to be initialized

### ISSUE THREAD

**Issue by robertosw** [juicycleff/flutter-unity-view-widget#800]
**Describe the bug**
Using UnityWidget() requires the use of a controller. This controller is shown in all examples without being initialised. However Current Flutter and Dart Versions require the initialisation.

**To Reproduce**
1. write: `UnityWidgetController _unityWidgetController;` in some class.
2. Get initialisation error

**Expected behavior**
Not being forced to initialise the Controller

Newest Flutter and Dart version 
Unity: Ubuntu, 2021.1.3

**Comment by LokeshNakka** [comment]
late UnityWidgetController _unityWidgetController;

**Comment by robertosw** [comment]
Is this really safe to do? I can imagine, calling a method of the widget (at the wrong time) might result in some problems.

**Comment by timbotimbo** [comment]
The current example project is not null-safe, thats why you get these errors in a modern null-safe project.

Check out pull request #732 for a null-safe version.

That uses `UnityWidgetController?` instead of `late`, so you can always check if it is null first.
