### ISSUE TITLE
Feature Request: UPM Support for Unity Package

### ISSUE THREAD

**Issue by k0uhe1D** [juicycleff/flutter-unity-view-widget#821]
@juicycleff @timbotimbo @RoyalCoder88 

Hello,

I hope this message finds you well. I would like to request a feature enhancement for the current Unity package distributed through this repository. 
Specifically, I am interested in adding support for Unity's Package Manager (UPM).

The main reasons for wanting to implement UPM support are as follows:
• To make library updates more convenient and streamlined
• To avoid placing external libraries directly under the Unity project's Assets folder as much as possible

[Ideal distribution format](https://github.com/CyberAgentGameEntertainment/NovaShader#install)

However, I noticed that the original source code is not included in this repository. In order to proceed with the UPM implementation, it would be extremely helpful if you could kindly make the source code publicly available.

I believe this enhancement will greatly benefit the community and improve the usability of this library. Thank you for your time and consideration, and I look forward to your response.

Kind regards,
kouhei.

**Comment by k0uhe1D** [comment]
Note: Another option could be to unpack the Unity package and add its contents to a Git repository for UPM support. While this may not be the most elegant solution, it would still achieve the desired goal.

**Comment by RoyalCoder88** [comment]
Hi @k0uhe1D , 

I think this is an amazing idea, we are not the original authors of this package, but we will support this package as much as we can, I will contact the author to add you as well as the admin if you agree to support and develop this package, as well about your proposal. Good luck!
