### ISSUE TITLE
Facing an issue with webviex version mismatch with webview_flutter version using flutter version 3.7.2

### ISSUE THREAD

**Issue by soma9017** [juicycleff/flutter-unity-view-widget#825]
**Describe the bug**

**To Reproduce**
1. Go to pubspec.yaml
2. Click on dependencies and add   webview_flutter: ^4.0.7 to your dependencies 
3. tap on flutter pub get 

**Expected behavior**
Flutter should start building

**Screenshots**
![image](https://github.com/juicycleff/flutter-unity-view-widget/assets/83583422/589fa5a9-5b62-4209-a2ee-5386d12622ab)

**Unity (please complete the following information):**
 - OS: android
 - Version 

**Additional context**

**Comment by soma9017** [comment]
Thanks @timbotimbo i made the same changes locally it's working but can we expect a fix for this in the upcoming versions..?

**Comment by timbotimbo** [comment]
Looks like pub.dev got a version 2022.2.1 and it includes the linked PR.
