### ISSUE TITLE
How to get cursor input in WebGL?

### ISSUE THREAD

**Issue by mikelpastor24** [juicycleff/flutter-unity-view-widget#827]
I want to make my page to be able to move around unity like the editor, I have a CameraController on my camera that works when I run the unity project, but I cant seem to get mouse/cursor input on my web page.

**Comment by timbotimbo** [comment]
Is this using the example project or based on the example?
Looks like the `PointerInterceptor`  is the parent of the wrong element, causing  mouse/touch to be blocked for the entire screen.

```dart
PointerInterceptor(
       child: Positioned(
              bottom: 0,
              left: 0,
              right: 0,
              child: Card(
                    elevation: 10,

```

It should be a child of `Positioned` or `Card`, to only intercept the mouse where it is actually needed.

**Comment by mikelpastor24** [comment]
The PointerInterceptor is just the parent for the Card not the UnityWidget.

`child: Stack(
            children: <Widget>[
              UnityWidget(
                onUnityCreated: onUnityCreated,
                onUnityMessage: onUnityMessage,
                onUnitySceneLoaded: onUnitySceneLoaded,
                fullscreen: false,
              ),
              PointerInterceptor(
                child: Positioned(
                bottom: 20,
                left: 20,
                right: 20,
                child: Card(
                  elevation: 10,`

**Comment by timbotimbo** [comment]
You code block confirms what I suspected above.

Try moving the`Positioned` out of the PointerInterceptor. The Positioned child causes the size of the interceptor to stretch to fill the entire stack.
```dart
Positioned(
    child:PointerInterceptor(
```

**Comment by mikelpastor24** [comment]
Thank you very much, that worked.
