### ISSUE TITLE
iOS Release build fails

### ISSUE THREAD

**Issue by SachinGanesh** [juicycleff/flutter-unity-view-widget#83]
Hi, Everything works as expected in debug mode, but when building in release mode (Archive) I get `'UnityFramework/UnityFramework.h' file not found` error.  Is there anything I'm missing here?.

**Comment by Slappiz** [comment]
Make sure to clean the previous Unity export from your workspace, that includes the UnityFramework reference in runner. We had a similar issue because we were still trying to reference the previous Unity exports framework.

**Comment by sandrush73** [comment]
@SachinGanesh   I had the similar error too but when i added UnityFramework reference to both pod and runner it works

**Comment by subjectdenied** [comment]
@SachinGanesh could you fix this?

**Comment by sandrush73** [comment]
@Slappiz I tried removig and readding UnityFramework to runner app and also in framework search path i did add my framework path too, but still no help. Were you able to resolve it by any other means ..? if so can you please share the process how you cleared it

**Comment by subjectdenied** [comment]
> @Slappiz I tried removing and re-adding UnityFramework to runner app and also in framework search path i did add my framework path too, but still no help. Were you able to resolve it by any other means ..? if so can you please share the process how you cleared it

i experimented adding the unity sources directly as a subdirectory to the flutter-unity-widget plugin ios directory itself, and changing its include statement to use "UnityFramework.h" directly, but got other missing files than (i think it was il2cpp). maybe it might pay to dive deeper into this approach

**Comment by Darkmax** [comment]
> 
> 
> Hi, Everything works as expected in debug mode, but when building in release mode (Archive) I get `'UnityFramework/UnityFramework.h' file not found` error. Is there anything I'm missing here?.

I'm also having this issue, I already tried to copy the new files on script and same error happens, any idea on how to resolve this issue? Also I tried to delete the previous files and create new ones and export them again with the new scripts and same still happens.

**Comment by devpascoe** [comment]
Also stuck on this one, added UnityFramework.framework to Runner proj but getting UnityFramework/UnityFramework.h file not found in FlutterUnityWidgetPlugin.m

**Comment by sam-parks** [comment]
I am only having this issue when building to the simulator.

**Comment by mlh-dungla** [comment]
I'm having this issue when select Archive from Xcode. But i can build to device normally. It's weird.

**Comment by sarawin008** [comment]
To build archive or release, you need to add unity project to pod too(similar to add file to runner) Then select pod and look at unity-widget-framework target and change architecture from standard to arm64 then in the build phase tab of pod project add unityFramework to dependency. Lastly, build from xcode only do not build from flutter cmd.These seem to work for me, hope it help

**Comment by khalithartmann** [comment]
any fix ??

**Comment by ruslanou** [comment]
how to fix this? i got same problem

**Comment by rinekso** [comment]
up

**Comment by ToddBrawn** [comment]
I am having this issue also. I have tried the new build scripts mentioned by devpascoe. I can build debug fine, but creating an archive build is failing. There appear to be many random answers to this question. I have tried many of them, none seem to work. Let me know what information I could provide to help diagnose the issue.

**Comment by MugOfPaul** [comment]
I am also stuck here. The only thing I can sort out is that the Debug build only builds to the active architecture - but setting Release to do the same makes little to no difference. Unfortunately the patching happening in the Unity build script plus the cocoapods layer is making this difficult for me to trace and track.

**Comment by mrdavidrees** [comment]
Looking at the build logs

```
#include <UnityFramework/UnityFramework.h>
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               1 error generated.

               CompileC /Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/Pods.build/Release-iphoneos/flutter_unity_widget.build/Objects-normal/armv7/FlutterUnityViewController.o /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-3.0.3/ios/Classes/FlutterUnityViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'flutter_unity_widget' from project 'Pods')
```
               
You can see that it's having trouble building the flutter_unity_widget pod, **specifically for the armv7** branch, or the 32 bit version of iOS.
               
Generally we don't need to build the app for the 32 bit version of iOS which was deprecated since iPhone 5s, so we have two options..        
Either only build for arm64 or build the unity game for both architectures.
               
 **Only building for arm64**
               
![Screen Shot 2021-02-24 at 2 54 03 pm](https://user-images.githubusercontent.com/811705/108950225-98d02980-76b1-11eb-81ee-2cd1ddebb5dd.png)

               
 **Building both architectures (universal)**
               
               
<img width="717" alt="Screen Shot 2021-02-24 at 2 54 32 pm" src="https://user-images.githubusercontent.com/811705/108950235-9d94dd80-76b1-11eb-9ab2-1e35deb1ad58.png">

_note that building a universal iOS package will be dropped from unity 2020 onwards_

**Comment by albemala** [comment]
I've posted a comment [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/218#issuecomment-792250376) with a possible solution to this issue. Please check it out.

**Comment by dawiddszewczyk** [comment]
To resolve this bug you have to click on the Data directory below:
<img width="459" alt="Zrzut ekranu 2022-07-16 o 18 30 08" src="https://user-images.githubusercontent.com/58904662/179363651-3169a3c5-f1a9-442b-8f67-bf662516acd8.png">
Later check if you have checked everything like there: 
<img width="267" alt="Zrzut ekranu 2022-07-16 o 18 30 59" src="https://user-images.githubusercontent.com/58904662/179363678-b909ff36-93e4-443e-bd60-045b3acde810.png">
From the Navigator, select Runner, then from the top menu "Product -> Clean Build Folder" Build project.

If you still have problems after building, try to run:

`rm -Rf build/*`
`flutter clean && flutter packages get`

If that didn't help, try reimport [Flutter Unity Package](https://github.com/juicycleff/flutter-unity-view-widget/tree/master/unitypackages) and do these steps again.

I recommend using an updated Flutter Unity Package like fuw-2022.1.1 or  fuw-2022.1.0

**Comment by dawiddszewczyk** [comment]
If you have this problem again please reopen the issue or create new one.
