### ISSUE TITLE
[UnityAppController applicationDidReceiveMemoryWarning:]: unrecognized selector sent to instance...

### ISSUE THREAD

**Issue by JosephCarrington** [juicycleff/flutter-unity-view-widget#842]
**Describe the bug**
If the app receives a memory warning while running a Unity view, it crashes.

**To Reproduce**
1. Follow setup instructions for AR implementation for iOS.
2. Do something that is memory intensive (Like loading a lot of giant images, or just opening the profiler and waiting a few seconds)

**Expected behavior**
applicationDidReceiveMemoryWarning should have a handler of some kind that actually exists.

**Screenshots**
![Screenshot 2023-07-11 at 3 18 52 PM](https://github.com/juicycleff/flutter-unity-view-widget/assets/1017852/55128e26-8403-433f-9f9a-236ccf1de77d)

**Unity (please complete the following information):**
 - OS: iOS
 - Version 2022.3.4f1

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16
 - Version 16.5.1

**Comment by OgiJr** [comment]
Were you able to find a solution to this error? It causes my app to crash every time it has to do something memory intensive.

**Comment by alexandrefresnais** [comment]
I am impacted too on my AR app

**Comment by CodeEagle** [comment]
add 
`- (void) applicationDidReceiveMemoryWarning:(UIApplication *)application {}`
in file `UnityAppController.mm`
to fix this

**Comment by timbotimbo** [comment]
I just noticed the following in the Unity changelogs
> iOS: Bring back the applicationDidReceiveMemoryWarning: to UnityAppController. (UUM-55367)  

This is noted in versions
- [2021.3.33](https://unity.com/releases/editor/whats-new/2021.3.33#release-notes)
- [2022.3.15](https://unity.com/releases/editor/whats-new/2022.3.15)
- [2023.2.2](https://unity.com/releases/editor/whats-new/2023.2.2)

I can't find when they removed it, but it looks like unity removed it, and now they are adding it again.

**Comment by Ahmadre** [comment]
> I just noticed the following in the Unity changelogs
> 
> > iOS: Bring back the applicationDidReceiveMemoryWarning: to UnityAppController. (UUM-55367)
> 
> This is noted in versions
> 
> * [2021.3.33](https://unity.com/releases/editor/whats-new/2021.3.33#release-notes)
> * [2022.3.15](https://unity.com/releases/editor/whats-new/2022.3.15)
> * [2023.2.2](https://unity.com/releases/editor/whats-new/2023.2.2)
> 
> I can't find when they removed it, but it looks like they fixed it themself.

Good to know that they brought it to both 2021 + 2022.

**Comment by timbotimbo** [comment]
For reference, this is the function that Unity adds in 2021.3.33, which matches what @CodeEagle  mentioned earlier.
```
- (void)applicationDidReceiveMemoryWarning:(UIApplication*)application
{
    // We handle it by subscribing for notification, this one is only a placeholder for stuff like forwarding in UaaL setups
}
```
