### ISSUE TITLE
Project with path 'xrmanifest.androidlib' could not be found in project ':unityLibrary'.

### ISSUE THREAD

**Issue by dibenedetto** [juicycleff/flutter-unity-view-widget#844]
**Describe the bug**
Build fails with error:
"Project with path 'xrmanifest.androidlib' could not be found in project ':unityLibrary'".

**To Reproduce**
Include a Unity project which uses the XR management 4.4.0.

**Expected behavior**
Successful build and run.

**Screenshots**
No screenshot needed.

**Unity (please complete the following information):**
 - OS: Windows 11
 - Version: 2022.4.3f1

**Smartphone (please complete the following information):**
It fails on build.

**Additional context**
No additional info.

**Comment by timbotimbo** [comment]
You will likely need to edit your gradle files to include this file.
I haven't tested this yet, but it will probably be something like this:

`android/settings.gradle` 
```
include ":xrmanifest.androidlib"
project(":xrmanifest.androidlib").projectDir = file("./unityLibrary/xrmanifest.androidlib")
```

`android/app/build.gradle`
```diff
  dependencies {
+        implementation project(':xrmanifest.androidlib')
     }
```

**Comment by dibenedetto** [comment]
> You will likely need to edit your gradle files to include this file. I haven't tested this yet, but it will probably be something like this:
> 
> `android/settings.gradle`
> 
> ```
> include ":xrmanifest.androidlib"
> project(":xrmanifest.androidlib").projectDir = file("./unityLibrary/xrmanifest.androidlib")
> ```
> 
> `android/app/build.gradle`
> 
> ```diff
>   dependencies {
> +        implementation project(':xrmanifest.androidlib')
>      }
> ```

thanks, but it fails with the same error :(

**Comment by AdrienGannerie** [comment]
Did you find a solution ? I have the same issue.

**Comment by khangpt** [comment]
me too T_T

**Comment by khangpt** [comment]
I'm not sure this is a solution to make the build is successful. But when I make same with @timbotimbo  said, also comment out this line "implementation project('xrmanifest.androidlib')" in unityLibrary/build.gradle ==> flutter run is OK.

But, when run android device, I got below: 
![Screenshot_20230718_160222](https://github.com/juicycleff/flutter-unity-view-widget/assets/68851147/33f20ade-59c9-4154-ae23-82fa3beea025)

This is log on my console:
<img width="974" alt="Screenshot 2023-07-18 at 16 02 42" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/68851147/1e31878a-d236-479a-b195-794b0e7eacb9">

This is how I'm using the widget in Flutter:
<img width="450" alt="Screenshot 2023-07-18 at 16 02 48" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/68851147/ddb548b5-81ae-439c-a434-e43f3239dd3d">


Hope anybody can help

**Comment by timbotimbo** [comment]
Just made a project to test this out.

Apparenty `xrmanifest.androidlib` is a new folder and not a file like I expected, located in `/unityLibrary`.

Adding a line to `android/settings.gradle` made it compile again for me.

```diff
  include ":unityLibrary"
  project(":unityLibrary").projectDir = file("./unityLibrary")

+ include ':unityLibrary:xrmanifest.androidlib'
```
##
I got this from `/unity/<project folder>/Builds/settings.gradle` which was generated by Unity. The builds folder is the original build created on an export and parts of that get moved to android/unityLibrary for this plugin.

##
While testing this, ARFoundation ran into issue #836, which means it is likely broken (for now) on Unity versions starting with:  
- 2020.3.46
- 2021.3.19
- 2022.2.4

**Comment by dibenedetto** [comment]
> ```diff
> include ':unityLibrary:xrmanifest.androidlib'
> ```

this, combined with [that](https://github.com/juicycleff/flutter-unity-view-widget/issues/832#issuecomment-1627557580), apparently solved the problem: the application is built and it runs on the device, but the AR camera is not open and this error comes out:

```
E/Unity   (  596): AndroidJavaException: java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "mUnityPlayer" in class "Lcom/hyperversexr/hyperversexr/MainActivity;" or its superclasses
E/Unity   (  596): java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "mUnityPlayer" in class "Lcom/hyperversexr/hyperversexr/MainActivity;" or its superclasses
E/Unity   (  596): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E/Unity   (  596): 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
E/Unity   (  596): 	at com.unity3d.player.UnityPlayer$C$a.handleMessage(Unknown Source:122)
E/Unity   (  596): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Unity   (  596): 	at android.os.Looper.loop(Looper.java:233)
E/Unity   (  596): 	at com.unity3d.player.UnityPlayer$C.run(Unknown Source:24)
E/Unity   (  596):   at UnityEngine.AndroidJNISafe.CheckException () [0x00091] in \home\bokken\build\output\unity\unity\Modules\AndroidJNI\AndroidJNISafe.cs:24 
E/Unity   (  596):   at UnityEngine.AndroidJNISafe.GetFieldID (System.IntPtr clazz, System.String name, System.String sig) [0x0000e] in \home\bokken\build\output\unity\unity\Modules\AndroidJNI\AndroidJNISafe.
```

is that related to the original issue?

**Comment by timbotimbo** [comment]
That is a different breaking change in Unity, the last section with `mUnityplayer` I mentioned above.

**Comment by dibenedetto** [comment]
> That is a different breaking change in Unity, the last section with `mUnityplayer` I mentioned above.

oh, that's ok, so i'll close this issue, thanks so much.

**Comment by dibenedetto** [comment]
> That is a different breaking change in Unity, the last section with `mUnityplayer` I mentioned above.

anyway, on my device, using version 2022.2.21f1 i can see the 3d scene (just a cube) but on a black background, e.g., no camera feedback.

with version 2022.2.0f1 it fails to build.

any idea on that?

**Comment by khangpt** [comment]
> > That is a different breaking change in Unity, the last section with `mUnityplayer` I mentioned above.
> 
> anyway, on my device, using version 2022.2.21f1 i can see the 3d scene (just a cube) but on a black background, e.g., no camera feedback.
> 
> with version 2022.2.0f1 it fails to build.
> 
> any idea on that?

I think you should try to enable camera permission on your device first. Hope this help

**Comment by JonFaull** [comment]
Any one have any solutions to this?
