### ISSUE TITLE
Using fuw-2022.2.0.unitypackage to export  is good on iOS, but not ok on Android

### ISSUE THREAD

**Issue by khangpt** [juicycleff/flutter-unity-view-widget#846]
**Describe the bug**
I'm currently using Unity version 2022.3.4f1
Import fuw-2022.2.0.unitypackage to export my unity project to Flutter.
When I follow the guide on pub.dev, then build on iOS device is good, everything run as I expected.
But when I config to build on Android, I got some error when run build in Flutter

<img width="979" alt="Screenshot 2023-07-18 at 8 32 17" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/68851147/318086ce-c2b1-4598-9ba0-eab5fadb89a8">

I can't understand where this manifest file is in unityLibrary folder. This below is all that I have after export from Unity:

<img width="223" alt="Screenshot 2023-07-18 at 8 42 15" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/68851147/5d8cc847-03c5-444b-9dd8-bf786d936091">

**To Reproduce**
1. Click on "Export Android Release" in Unity editor
2. Config same with the guidance
3. Run "flutter run --release" or "flutter run --debug" on real device
4. Get the error

**Expected behavior**
Build on Android is OK

**Unity (please complete the following information):**
 - OS: MacOS 13.4
 - Version [2022.3.4f1]

**Smartphone (please complete the following information):**
 - Device: [Samsung S22]
 - OS: [Android]
 - Version [13]
 - SDK version 33

**Additional context**
No more

**Comment by khangpt** [comment]
After a couple of time I spent to investigate the issue, I recognize that, in file Build.cs, function ModifyAndroidGradle, it should exist the AndroidManifest.xml file in unity/UnityProjectName/src/main/AndroidManifest.xml. But no, at this path in my exported unityLibrary folder, there's no manifest file like this. This is a issue of export script in Unity Editor,  isn't it?

**Comment by timbotimbo** [comment]
The appmanifest is this issue https://github.com/juicycleff/flutter-unity-view-widget/issues/801#issuecomment-1597499527.

It also mentions namespace, which I believe is from Android gradle plugin 8+.
Change that to 7.x, or use the pull request for 8.

**Comment by khangpt** [comment]
> The appmanifest is this issue [#801 (comment)](https://github.com/juicycleff/flutter-unity-view-widget/issues/801#issuecomment-1597499527).
> 
> It also mentions namespace, which I believe is from Android gradle plugin 8+. Change that to 7.x, or use the pull request for 8.

thanks for quick reply. After I upgrade XR management package to 4.4, manifest file is export ok. But now I encounter another error : 

<img width="819" alt="Screenshot 2023-07-18 at 15 47 36" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/68851147/9029bc87-35e3-4843-b377-b55d04797a65">

could you tell me what should I do here :)

**Comment by timbotimbo** [comment]
This second error turns into #844, let's continue that one there.
