### ISSUE TITLE
[Unity 2023.1.5] Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.

### ISSUE THREAD

**Issue by nkrmr** [juicycleff/flutter-unity-view-widget#847]
**Describe the bug**
Each time i tried to launch the app on Android I have this issue

Note: /Volumes/Workspace/www/pacprod_apps/android/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:1 Class 'CustomUnityPlayer' is not abstract and does not implement abstract base class member public abstract fun setMainSurfaceViewAspectRatio(p0: Float): Unit defined in com.unity3d.player.UnityPlayer
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:1 CustomUnityPlayer inherits invisible abstract members: public/*package*/ abstract fun handleFocus(p0: Boolean): Boolean defined in com.unity3d.player.UnityPlayer, public/*package*/ abstract fun getGfxView(): View! defined in com.unity3d.player.UnityPlayer, public/*package*/ abstract fun onOrientationChanged(p0: Int, p1: Int): Unit defined in com.unity3d.player.UnityPlayer, public/*package*/ abstract fun cleanupResourcesForDestroy(): Unit defined in com.unity3d.player.UnityPlayer
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:102 Type mismatch: inferred type is IUnityPlayerLifecycleEvents? but UnityPlayer.h! was expected
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:102 No value passed for parameter 'p2'
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:19:5 'onConfigurationChanged' overrides nothing
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:21:15 Unresolved reference: onConfigurationChanged
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:24:5 'onAttachedToWindow' overrides nothing
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:26:15 Unresolved reference: onAttachedToWindow
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:32:5 'onDetachedFromWindow' overrides nothing
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:36:15 Unresolved reference: onDetachedFromWindow
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:39:5 'dispatchTouchEvent' overrides nothing
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:41:22 Unresolved reference: dispatchTouchEvent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:45:5 'onTouchEvent' overrides nothing
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:49:22 Unresolved reference: onTouchEvent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:337:44 Unresolved reference: parent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:338:45 Unresolved reference: parent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:338:77 Type mismatch: inferred type is CustomUnityPlayer? but View! was expected
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:342:44 Unresolved reference: z
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:359:44 Unresolved reference: parent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/OverrideUnityActivity.kt:45:23 Unresolved reference: lowMemory
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:38:64 Unresolved reference: requestFocus
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:56:31 Unresolved reference: bringToFront
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:57:31 Unresolved reference: requestLayout
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:58:31 Unresolved reference: invalidate
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:177:31 Unresolved reference: parent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:179:65 Type mismatch: inferred type is CustomUnityPlayer? but View! was expected
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:196:19 None of the following functions can be called with the arguments supplied: 
public open fun addView(p0: View!, p1: ViewGroup.LayoutParams!): Unit defined in android.view.ViewGroup
public open fun addView(p0: View!, p1: Int): Unit defined in android.view.ViewGroup
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:203:31 Unresolved reference: parent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:204:32 Unresolved reference: parent
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:204:64 Type mismatch: inferred type is CustomUnityPlayer? but View! was expected
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:207:31 Unresolved reference: z
e: file:///Users/nkrmr/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.0/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:210:39 Type mismatch: inferred type is CustomUnityPlayer? but View! was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1

**To Reproduce**
1. On unity I made "Export Android (Release)"
2. On my VSCode IDE I made "run without debugging'
3. Into the debug console it start to build and I have this issue

**Expected behavior**
Build correctly to Android

**Unity **
 - Version: 2023.1.5f1

**Comment by timbotimbo** [comment]
Unity 2023 is currently broken on android.
See https://github.com/juicycleff/flutter-unity-view-widget/issues/839

**Comment by nkrmr** [comment]
But when i tried to use Unity 2022.3.5f1 I have an issue with AndroidManifest.xml whereas he is generated into 2023




FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:packageDebugResources'.
> Error while evaluating property 'namespace' of task ':unityLibrary:packageDebugResources'
   > Failed to calculate the value of task ':unityLibrary:packageDebugResources' property 'namespace'.
      > Failed to query the value of property 'namespace'.
         > Manifest file does not exist: /Volumes/Workspace/www/pacprod_apps/android/unityLibrary/src/main/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by VishalS4646** [comment]
> The missing manifest file might be caused by the Unitypackage XR Plugin Management. Versions 4.3.1 - 4.3.3 contain a bug that delete that file.
> 
> Even if you don't use AR, the example used to include that package until very recently.

![Screenshot (510)](https://github.com/juicycleff/flutter-unity-view-widget/assets/76813352/f054f66f-3606-4151-bbed-ac15e2aeaf52)
please help ASAP

**Comment by moaznarsun** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 23s
Error: Gradle task assembleDebug failed with exit code 1

I am getting the same issue. Have you been able to resolve it?

**Comment by liushengliuyun** [comment]
My problem is same as you , the following is my specific log.
 * What went wrong:
Execution failed for task ':unityLibrary:res.androidlib:packageDebugResources'.
> Error while evaluating property 'namespace' of task ':unityLibrary:res.androidlib:packageDebugResources'
   > Failed to calculate the value of task ':unityLibrary:res.androidlib:packageDebugResources' property 'namespace'.
      > Failed to query the value of property 'namespace'.
         > Manifest file does not exist: D:\project_unity\..\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\res.androidlib\AndroidManifest.xml
         
         

只要删除:res.androidlib就好了, 目录大概在plugin/Android下面 .
Just delete :res.androidlib, roughly under plugin/Android

**Comment by maherelamary** [comment]
I am getting this error when I exported android debug from unity version 6000

[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:1 Class 'CustomUnityPlayer' is not abstract and does not implement abstract base class member 'getView'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:1 'CustomUnityPlayer' inherits invisible abstract member 'fun handleFocus(p0: Boolean): Boolean' defined in 'com/unity3d/player/UnityPlayer'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:102 Argument type mismatch: actual type is 'com.unity3d.player.IUnityPlayerLifecycleEvents?', but 'com.unity3d.player.u!' was expected.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:13:102 No value passed for parameter 'p2'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:19:5 'onConfigurationChanged' overrides nothing.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:21:15 Unresolved reference 'onConfigurationChanged'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:24:5 'onAttachedToWindow' overrides nothing.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:26:15 Unresolved reference 'onAttachedToWindow'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:32:5 'onDetachedFromWindow' overrides nothing.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:36:15 Unresolved reference 'onDetachedFromWindow'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:39:5 'dispatchTouchEvent' overrides nothing.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:41:22 Unresolved reference 'dispatchTouchEvent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:45:5 'onTouchEvent' overrides nothing.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:58:26 Unresolved reference 'onTouchEvent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/CustomUnityPlayer.kt:60:26 Unresolved reference 'onTouchEvent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:337:44 Unresolved reference 'parent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:338:45 Unresolved reference 'parent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:338:77 Argument type mismatch: actual type is 'com.xraph.plugin.flutter_unity_widget.CustomUnityPlayer?', but 'android.view.View!' was expected.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:342:44 Unresolved reference 'z'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt:359:44 Unresolved reference 'parent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/OverrideUnityActivity.kt:29:23 Unresolved reference 'quit'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/OverrideUnityActivity.kt:45:23 Unresolved reference 'lowMemory'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:38:64 Unresolved reference 'requestFocus'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:56:31 Unresolved reference 'bringToFront'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:57:31 Unresolved reference 'requestLayout'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:58:31 Unresolved reference 'invalidate'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:135:35 Unresolved reference 'quit'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:188:31 Unresolved reference 'parent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:190:65 Argument type mismatch: actual type is 'com.xraph.plugin.flutter_unity_widget.CustomUnityPlayer?', but 'android.view.View!' was expected.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:207:19 None of the following candidates is applicable:
[        ] fun addView(p0: View!, p1: Int): Unit
[        ] fun addView(p0: View!, p1: ViewGroup.LayoutParams!): Unit
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:214:31 Unresolved reference 'parent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:215:32 Unresolved reference 'parent'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:215:64 Argument type mismatch: actual type is 'com.xraph.plugin.flutter_unity_widget.CustomUnityPlayer?', but 'android.view.View!' was expected.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:218:31 Unresolved reference 'z'.
[        ] e: file:///Users/maheralamary/.pub-cache/git/flutter-unity-view-widget-1a38bb555de63dde400c82d8a14470ad52da1f3d/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt:221:39 Argument type mismatch: actual type is 'com.xraph.plugin.flutter_unity_widget.CustomUnityPlayer?', but 'android.view.View!' was expected.


Could you please help @timbotimbo ?
