### ISSUE TITLE
Dependency on deprecated webviewx prevents using latest http

### ISSUE THREAD

**Issue by Velek** [juicycleff/flutter-unity-view-widget#856]
**Is your feature request related to a problem? Please describe.**
Resolving dependencies...
Because flutter_unity_widget >=2022.1.0 depends on webviewx ^0.2.1 which depends on http ^0.13.3, flutter_unity_widget >=2022.1.0 requires http ^0.13.3.
So, because marble_navigator depends on both flutter_unity_widget ^2022.2.0 and http ^1.0.0, version solving failed.

**Describe the solution you'd like**
Remove dependency on webviewx?  I haven't looked to see how much work this is.

**Describe alternatives you've considered**

**Additional context**

**Comment by Velek** [comment]
I see the dependency has been removed, but it hasn't been integrated into the latest release.

**Comment by timbotimbo** [comment]
The updated dependency was included in the 2022.2.1 release.
