### ISSUE TITLE
Value of type 'UnityAppController' has no member 'unityMessageHandler'

### ISSUE THREAD

**Issue by pen110** [juicycleff/flutter-unity-view-widget#867]
<img width="1040" alt="image" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/7963859/abd37b45-d7ce-42d9-abf9-320c726e1018">

 flutter_unity_widget: ^2022.2.0

**Comment by timbotimbo** [comment]
Closing this as it is a duplicate of these without any new info.
https://github.com/juicycleff/flutter-unity-view-widget/issues/486
https://github.com/juicycleff/flutter-unity-view-widget/issues/426
https://github.com/juicycleff/flutter-unity-view-widget/issues/377
