### ISSUE TITLE
The same flutter unity app opening in Android but not in window

### ISSUE THREAD

**Issue by zubair999** [juicycleff/flutter-unity-view-widget#874]
**Describe the bug**
The same flutter unity app is working on android but not on window, although unity window export is successfull, but only blank screen is showing in window but it's working fine on android. What setting I need to change in Build Setting and Player Setting, right now all settings are default and I have changed now settings.

**Expected behavior**

**Screenshots**
![Screenshot 2023-09-09 120805](https://github.com/juicycleff/flutter-unity-view-widget/assets/30196482/21000bb9-421e-4bc5-b624-613ffbd2176c)
![WhatsApp Image 2023-09-09 at 12 08 41](https://github.com/juicycleff/flutter-unity-view-widget/assets/30196482/a56a8309-23bd-4389-9c5d-bee9ed7fee80)

**Unity (please complete the following information):**
 - OS: Android, Window
 - Version 2022.3.7f1.0.15853

**Smartphone (please complete the following information):**
 - Device: Oppo Ak1
 - OS: ColorOS Version v6.0.1
 - Version Android 9

**Additional context**

**Comment by timbotimbo** [comment]
Windows isn't supported on the flutter side of things.
