### ISSUE TITLE
postMessage function not working, created a Counter app in unity and flutter

### ISSUE THREAD

**Issue by zubair999** [juicycleff/flutter-unity-view-widget#875]
**Describe the bug**
I successfully integrated unity into flutter but now stuck in establishing communication between flutter and unity back and forth.
In unity I have created a counter app and in flutter when I increased counter value the count value don't increase or decrease in unity. What setting or code in flutter or unity side I need to change to make it work. 

Basically I want to send json data to Unity App later on. So please help on that too.

**Expected behavior**
As counter value increase in flutter we should see count value in unity.

**Screenshots**

https://github.com/juicycleff/flutter-unity-view-widget/assets/30196482/30ea4f20-0457-46ff-a418-879a0c72ad09

**Flutter Version
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (8 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Unity (please complete the following information):**
 - OS: Android
 - Version  2022.3.7f1.0.15853

**Smartphone (please complete the following information):**
 - Device: Oppo Ak1
 - OS: ColorOS Version v6.0.1
 - Version Android 9

**Additional context**
My flutter postMessage function code

`
void setRotationSpeed(String speed) {
    _unityWidgetController.postMessage(
      'Cube',
      'SetRotationSpeed',
      speed,
    );
}
`

**Comment by altafc22** [comment]
Hi @zubair999, i'm facing same issue, could you please share how did you solved it ?
