### ISSUE TITLE
Issue when exporting from unity 2022.3.xx

### ISSUE THREAD

**Issue by nimr77** [juicycleff/flutter-unity-view-widget#876]
**Describe the bug**
when exporting from unity version 2022.3.xx, it doesn't complete the exporting and it has a missing android build files

**To Reproduce**
1. install unity 2022.3.xxx
2. install flutter_unity_package for unity to export with flutter
3. export with ( flutter => export android )

**Expected behavior**
to have a full unityLibrary ready to use

**Screenshots**

<img width="1449" alt="Screenshot 2023-09-14 at 00 06 55" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/36929077/821a022f-4eb1-41e6-a39c-0030ed0f61cb">

**LOGS FROM UNITY**

```
FileNotFoundException: Could not find file "/Users/nimrsawafta/MyProjects/StreetUP/mobile/android/unityLibrary/src/main/AndroidManifest.xml"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <130809ae6f984869a6663c878f16e3f3>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) (at <130809ae6f984869a6663c878f16e3f3>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <130809ae6f984869a6663c878f16e3f3>:0)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks) (at <130809ae6f984869a6663c878f16e3f3>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string,System.Text.Encoding,bool)
System.IO.File.InternalReadAllText (System.String path, System.Text.Encoding encoding) (at <130809ae6f984869a6663c878f16e3f3>:0)
System.IO.File.ReadAllText (System.String path) (at <130809ae6f984869a6663c878f16e3f3>:0)
FlutterUnityIntegration.Editor.Build.ModifyAndroidGradle (System.Boolean isPlugin) (at Assets/FlutterUnityIntegration/Editor/Build.cs:344)
FlutterUnityIntegration.Editor.Build.DoBuildAndroid (System.String buildPath, System.Boolean isPlugin, System.Boolean isReleaseBuild) (at Assets/FlutterUnityIntegration/Editor/Build.cs:231)
FlutterUnityIntegration.Editor.Build.DoBuildAndroidLibraryDebug () (at Assets/FlutterUnityIntegration/Editor/Build.cs:34)
```

**Additional context**
Workaround is to build with another version like 2021.xxx and replace the src folder of unityLibrary

**Comment by timbotimbo** [comment]
This might be caused by a buggy package installed in your Unity project.
"XR Plugin Management" versions 4.3.x will delete your androidmanifest file, breaking the export process.

Check the unity package manager for this package.
You can also check the packages folder in your Unity project. See if `manifest.json` or `package-lock.json` contain `com.unity.xr.management`.

**Comment by nimr77** [comment]
But we need the Plugin for AR, and  the project doesn't include in the **package-lock.json** or **manifest.json**

**Comment by nimr77** [comment]
https://github.com/juicycleff/flutter-unity-view-widget/issues/801
