### ISSUE TITLE
I want to update the frame when I send data from flutter to unity using Coroutine

### ISSUE THREAD

**Issue by zubair999** [juicycleff/flutter-unity-view-widget#878]
I am sending some data from flutter to unity which contains frame data in an array, this array contains data of rotation from 0 to 90 degree in x-direction, my object is rotating in unity and I successfully rotate the object in unity itself. Now I will send that data from flutter to unity to rotate my object.

**Comment by timbotimbo** [comment]
Now a duplicate with #881
