### ISSUE TITLE
Issue after upgrade to Xcode 15

### ISSUE THREAD

**Issue by likwifi** [juicycleff/flutter-unity-view-widget#883]
**Describe the bug**
After upgrading to Xcode 15 I'm getting following error when unity view launches.
Any ideas what could be possible cause of this?
[        ] [Subsystems] Discovering subsystems at path /var/containers/Bundle/Application/A333446D-9A82-4A63-94A3-FD89CB0328B5/Runner.app/Frameworks/UnityFramework.framework/Data/UnitySubsystems
[        ] GfxDevice: creating device client; threaded=1; jobified=0
[        ] Initializing Metal device caps: Apple A12X GPU
[   +1 ms] Initialize engine version: 2022.3.10f1 (ff3792e53c62)
[+1405 ms] Process 2814 stopped
[   +1 ms] * thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16dc1fff0)
[        ]     frame #0: 0x000000011b2ae448 Flutter`FlutterStandardCodecHelperReadValueOfType + 4
[        ] Flutter`FlutterStandardCodecHelperReadValueOfType:
[        ] ->  0x11b2ae448 <+4>:  stp    x26, x25, [sp, #0x10]
[        ]     0x11b2ae44c <+8>:  stp    x24, x23, [sp, #0x20]
[        ]     0x11b2ae450 <+12>: stp    x22, x21, [sp, #0x30]
[        ]     0x11b2ae454 <+16>: stp    x20, x19, [sp, #0x40]
[        ] Target 0: (Runner) stopped.
[        ] thread backtrace all
[        ] Debugger state set to detached.
[        ] process detach

**Unity (please complete the following information):**
 - OS: Mac os silicon
 - Version 2022.3.10f1 LTS

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro 
 - OS: IOS 17

**Comment by Velek** [comment]
I had it too

https://stackoverflow.com/questions/77136958/flutter-or-react-native-xcode-15-error-xcode-dt-toolchain-dir-cannot-be-used

**Comment by timbotimbo** [comment]
Can you try updating cocoapods using `sudo gem install cocoapods`? Version 1.13 notes a fix for Xcode 15.
