### ISSUE TITLE
[Unity 2023] A problem occurred evaluating project ':unityLibrary'.

### ISSUE THREAD

**Issue by UnityExpert** [juicycleff/flutter-unity-view-widget#885]
Hie,
 I have used the Flutter Unity widget package "fuw-2022.2.0" in Unity editor "2023.1.16f1" and was able to export unity files 
 but in Flutter (Using Android Studio)getting this error while building apk 
 
 Here is the screenshot of the error 
 
![Screenshot 2023-10-09 170722](https://github.com/juicycleff/flutter-unity-view-widget/assets/64929334/7993268b-611d-4c10-ad66-99231e5c7e17)

**Comment by UnityExpert** [comment]
using unity 2022 worked for me

**Comment by timbotimbo** [comment]
Like mentioned on Discord, Unity 2023 breaks compatibility with this plugin on Android.

https://github.com/juicycleff/flutter-unity-view-widget/issues/839
