### ISSUE TITLE
[Emulator] App crashes immediate after launching on mobile phone using flutter unity widget release build

### ISSUE THREAD

**Issue by UnityExpert** [juicycleff/flutter-unity-view-widget#886]
Unity version 2021.3.9f1
flutter unity widget fuw-2022.2.0

tried to run in Android studio emulator getting this error after building a debug apk

Here is the screenshot of error
 
 
![Screenshot 2023-10-11 234143](https://github.com/juicycleff/flutter-unity-view-widget/assets/64929334/2acdb0a7-b93e-45e0-8b3c-0bc3d2297b5b)

**Comment by timbotimbo** [comment]
Android emulators generally won't work unless you are working on an Apple M1/M2 computer.

Use a real phone instead.

Check the github readme for more emulator details. (Noy pub.dev)

**Comment by UnityExpert** [comment]
hie @timbotimbo  thank you for your quick response, Now am facing some strange issues while running the demo app on my real device sometimes it runs properly, or sometimes hangs or crashes.

Here is the video of the gameplay  

https://github.com/juicycleff/flutter-unity-view-widget/assets/64929334/33c54832-ca3f-4f14-9ab6-15598f0bf6f1

using same dart code 
import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

void main() {
  runApp(
    const MaterialApp(
      home: UnityDemoScreen(),
    ),
  );
}

class UnityDemoScreen extends StatefulWidget {
  const UnityDemoScreen({Key? key}) : super(key: key);

  @override
  State<UnityDemoScreen> createState() => _UnityDemoScreenState();
}

class _UnityDemoScreenState extends State<UnityDemoScreen> {
  static final GlobalKey<ScaffoldState> _scaffoldKey =
      GlobalKey<ScaffoldState>();
  UnityWidgetController? _unityWidgetController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: SafeArea(
        bottom: false,
        child: WillPopScope(
          onWillPop: () async {
            // Pop the category page if Android back button is pressed.
            return true;
          },
          child: Container(
            color: Colors.yellow,
            child: UnityWidget(
              onUnityCreated: onUnityCreated,
            ),
          ),
        ),
      ),
    );
  }

  // Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) {
    _unityWidgetController = controller;
  }
}
``
please help me how to solve this issue
