### ISSUE TITLE
App freezing 

### ISSUE THREAD

**Issue by Kiruthika2206** [juicycleff/flutter-unity-view-widget#897]
App is freezing when we close the app and reopen the app from recent apps.
This happens when I add visible before unitywidget.

Unity version - 2021.3.11f1

**Comment by timbotimbo** [comment]
Please add more information like in the issue template, the current issue is pretty useless right now.
- android or ios?
- which flutter version?
- which fuw plugin and unitpackage?
- do you have a screenshot or screen recording?

And what do you mean with "add visible before unitywidget."?

**Comment by Kiruthika2206** [comment]
Android
Flutter version - 3.3.10

child: Stack(
            children: <Widget>[
              Visibility(
                visible: isUnityVisible,
                //visible:false,//!isTutorialVideoPlaying,
                child: UnityWidget(
                  onUnityCreated: _onUnityCreated,
                  onUnityMessage: onUnityMessage,
                  onUnitySceneLoaded: onUnitySceneLoaded,
                  useAndroidViewSurface: false,
                  //enablePlaceholder: true,
                  fullscreen: false,
                ),
              ),


I'm using visible:isUnityVisible inside visibility block for displaying the flutter screen whenever isUnityVisible=true.

When using this app is freezing when we open the app from recent apps
