### ISSUE TITLE
Since "2022.2.0" has been for a while, so can we get a new flutter lib release? Thanks!

### ISSUE THREAD

**Issue by zmhbh** [juicycleff/flutter-unity-view-widget#898]
**Is your feature request related to a problem? Please describe.**
Looks like the flutter lib version is still "2022.2.0", and the github repo has been updated constantly, so is it possible to get a new release?

**Describe the solution you'd like**
Release a new version.

**Comment by timbotimbo** [comment]
Closing this as 2022.2.1 was released after this issue.
