### ISSUE TITLE
Assets/SteamVR/Input/SteamVR_Input.cs(10,13): error CS0234: The type or namespace name 'Newtonsoft' does not exist in the namespace 'Valve' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by ChurikiTenna** [juicycleff/flutter-unity-view-widget#899]
**Describe the bug**

When I tried to Flutter -> Export iOS (Debug or Release), it fails with errors.

```
Assets/SteamVR/Input/SteamVR_Input.cs(10,13): error CS0234: The type or namespace name 'Newtonsoft' does not exist in the namespace 'Valve' (are you missing an assembly reference?)
Assets/SteamVR/Input/SteamVR_Input_ActionFile.cs(8,13): error CS0234: The type or namespace name 'Newtonsoft' does not exist in the namespace 'Valve' (are you missing an assembly reference?)
... 187 more errors like that
```

When I try to run on Unity (with ▶️ button), it builds with no problems.

**To Reproduce**
1. Get SteamVR  here: https://assetstore.unity.com/packages/tools/integration/steamvr-plugin-32647
2. Import SteamVR on Package Manager.
3. Flutter -> Export iOS (Debug or Release)

**Expected behavior**
Export successfully

**Screenshots**
<img width="1016" alt="スクリーンショット 2023-11-20 17 48 52" src="https://github.com/juicycleff/flutter-unity-view-widget/assets/52132649/3afc9f40-40f7-412f-b114-7bca5bcc5f74">

**Unity (please complete the following information):**
 - OS: MacOS
 - Version 2022.2.0b11

**Additional context**
- Flutter: 3.16.0

Export Android works fine.

**Comment by ChurikiTenna** [comment]
@juicycleff

**Comment by timbotimbo** [comment]
Can you make an iOS build without this flutter plugin (using the regular build UI in unity)?
Since StreamVR is meant for desktop platforms, it wouldn't surprise me if building for iOS is not supported.

**Comment by ChurikiTenna** [comment]
The error happened because SteamVR does not support iOS.
Sorry for the buzz. Closing.
