### ISSUE TITLE
Upgrade Webview dependencies

### ISSUE THREAD

**Issue by WouterVandenputte** [juicycleff/flutter-unity-view-widget#909]
when trying to install the Google mobile ads dependency, I got a resolving error regarding the webviewx dependency.

> Because google_mobile_ads >=3.0.0 depends on webview_flutter ^4.0.5 and webviewx >=0.2.1 depends on webview_flutter ^2.0.13, google_mobile_ads >=3.0.0 is incompatible with webviewx >=0.2.1.
> And because flutter_unity_widget >=2022.1.0 depends on webviewx ^0.2.1, google_mobile_ads >=3.0.0 is incompatible with flutter_unity_widget >=2022.1.0.
> So, because [PROJECT_NAME] depends on both flutter_unity_widget ^2022.2.0 and google_mobile_ads ^4.0.0, version solving failed.

So the feature request is to be up to date with latest packages. I noticed that this package has not yet been updated in 16 months so imo I think it would be nice to simply update all dependencies where possible.

**Comment by timbotimbo** [comment]
This should already be fixed on the master branch. #761
I'm just waiting until that gets incorporated into a pub.dev release.

The repo owner recently returned from a long absence, so it might finally happen.

**Comment by timbotimbo** [comment]
Looks like pub.dev got a version 2022.2.1 and it includes the linked PR.
