### ISSUE TITLE
Converting project to Mono Repo

### ISSUE THREAD

**Issue by juicycleff** [juicycleff/flutter-unity-view-widget#913]
**Is your feature request related to a problem? Please describe.**
After building the Flutter Unity Widget, and seeing the bottleneck of painting huge Unity projects with Flutter, I built out ways to easily manage the Unity and Flutter projects without merging the two and keeping the main app repo lite and slim. This tool required a CLI project and some automation scripts that I hope to share with everyone.

**Describe the solution you'd like**
The plan is to convert the project into a mono repo of projects and then build a better release for the packages.
And also while this might not be the best repo to add this to, I've been contemplating adding flutter-unreal-engine4. This is something I have been anticipating working on for a while now and I a read some UE4 articles by Unreal Engine that suggest this Is possible. So I would like to start pushing that code here.

**Additional context**
 I would love to hear your thoughts @krispypen @timbotimbo @Ahmadre

**Comment by timbotimbo** [comment]
The amount of (build) issues coming in already makes it hard to keep track of the real bugs.  
I can't imagine also having random UE compilation issues added in between that mess.

If you want to use the views this github project gets, you could just add  [check out these repos] messages at the top of the readme and stickied issues.

It's already hard to keep this maintained and usable with Flutter/xcode/Unity trying to break stuff at every update. I would prefer to keep it focused and contained.

**Comment by juicycleff** [comment]
I think you are right @timbotimbo. I will just close this.
