### ISSUE TITLE
Merge 2022.2.1 in master

### ISSUE THREAD

**Issue by timbotimbo** [juicycleff/flutter-unity-view-widget#915]
## Description
I see that there is a new 2022.2.1 plugin version on pub.dev.
However there is nothing on the master branch that even hints that this version exists.

If I now were to merge something else into master, there would be no commit in the master that exactly matches 2022.2.1.

Looking at recent branches, it seems to have been made from the `/feat/ci-releases` branch.  https://github.com/juicycleff/flutter-unity-view-widget/commits/feat/ci-releases/
I do see a new CI script throwing errors in that branch, so maybe that is why it couldn't be merged yet.

@juicycleff 
Can you make sure to eventually merge this into master?

**Comment by juicycleff** [comment]
Yeah, I'm trying to automate the release process so I don't block future releases
