### ISSUE TITLE
Is now support windows?

### ISSUE THREAD

**Issue by qiuguian** [juicycleff/flutter-unity-view-widget#916]
Is now support windows?

**Comment by timbotimbo** [comment]
Windows is currently not supported, and as far as I know nobody is actively working on it.

I see open issues in the Flutter repository on them planning to add PlatformView support on windows, which means it might not even be possible right now.

**Comment by qiuguian** [comment]
I need it

**Comment by Mamena2020** [comment]
any updates on this?
