### ISSUE TITLE
[Android][Gradle] Can't build example project to android device

### ISSUE THREAD

**Issue by Byambasurenn** [juicycleff/flutter-unity-view-widget#918]
Hello, I followed the instructions, looked at the similar issues bu no luck. 

I got this error when I try to run flutter application:

>* Where:
>Build file 'H:\HEMAB\androidversion\flutter-unity-view-widget\example\android\build.gradle' line: 31

> * What went wrong:
> A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not open proj generic class cache for build file 'H:\HEMAB\androidversion\flutter-unity-view-widget\example\android\app\build.gradle' (C:\Users\byambaa\.gradle\caches\6.5\scripts\4krocuxnh3ewjlr8r8o07tqsj\projb175e8fd9a0044c7af61444ba048d791).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

Steps to reproduce:
1. Clone project
2. Export Unity to android
3. Add NDK path.
4. Replace '/' with '//'
5. Run -> Start Debugging

I think it's something to do with gradle and jdk version.

Please help me find solution for this!

**Comment by timbotimbo** [comment]
This is the kind of error if your java and gradle versions aren't compatible.

Can you try the versions that I applied in this [pull request](https://github.com/juicycleff/flutter-unity-view-widget/pull/893/files)?
![gradle](https://github.com/juicycleff/flutter-unity-view-widget/assets/11444698/6a1225dc-b595-4c00-8d79-ab403ba20565)

**Comment by timbotimbo** [comment]
Flutter actually has a guide for this exact error, which also mentions updating the gradle version.  https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide

> You can fix this error by upgrading your Gradle project to a compatible version (7.3 through 7.6.1, inclusive)
