### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by bomxo007** [juicycleff/flutter-unity-view-widget#924]
![Screenshot 2024-02-05 145331](https://github.com/juicycleff/flutter-unity-view-widget/assets/64208014/f2422630-d85d-4518-9573-f3157c08a97b)

what wrong 
It seems like you followed the recommendations provided earlier, but encountered an error during the build process. Prior to this error, there were warnings about the usage of deprecated APIs in the `UnityPlayerActivity.java` file. To address this, you may need to recompile with the `-Xlint:deprecation` flag for more details on the deprecation warnings. Could you provide more information about the error that occurred during the build process?

Note: C:\Users\anantasit.ba\Documents\Unity\Fluttertest\ar_tes2\exsample\android\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by timbotimbo** [comment]
Don't use an emulator. Unity doesn't support the x64 buildtarget for android.

**Comment by bomxo007** [comment]
Thank !!!   but  i can  set emu for the project  or cannot be done at all

**Comment by timbotimbo** [comment]
Simple answer: don't use an emulator.

More advanced: Check the [emulator documentation](https://github.com/juicycleff/flutter-unity-view-widget?tab=readme-ov-file#emulators) in the readme.
You might get it working, but in any case it will be buggy and unstable.
