### ISSUE TITLE
menu flutter export  not found / vuforia issues import module 

### ISSUE THREAD

**Issue by bomxo007** [juicycleff/flutter-unity-view-widget#927]
![image](https://github.com/juicycleff/flutter-unity-view-widget/assets/64208014/2adf22a5-8bcb-4504-b062-5b8aa1ea2bc0)

me import  unity packages for project arkit  but i'm don't see menu flutter export

**Comment by timbotimbo** [comment]
I believe the only way this happens if there are compilation errors.
Try to run or build your app to see if that makes any error show up.

Otherwise try importing the unitpackage again.

I have used this on 2022.3.19 and had no issue.

**Comment by bomxo007** [comment]
u have  a ar kit demo last porjcet new version 
 becuse flutter-unity-arkit-demo is old  last  update 5 year a go

**Comment by bomxo007** [comment]
![image](https://github.com/juicycleff/flutter-unity-view-widget/assets/64208014/82dd88bd-9ea9-41f0-9b4f-40d18eafdd3a)

and  me try  import module  .arr    but can't  
how to import this 

i'm follow this https://developermemos.com/posts/import-aar-library-android   it con't  import to sync task

**Comment by bomxo007** [comment]
[ Check the updated instructions in this PR https://github.com/juicycleff/flutter-unity-view-widget/pull/911 ] this for demo project ?

when me build new project follow to setup can it work? or do I need to adjust anything?

**Comment by bomxo007** [comment]
ok i'm got  it   now it work
Check this [#689](https://github.com/juicycleff/flutter-unity-view-widget/issues/689#issuecomment-1868574799)
