### ISSUE TITLE
How to solve the problem of invalid multi-touch

### ISSUE THREAD

**Issue by caicoder** [juicycleff/flutter-unity-view-widget#934]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Unity (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timbotimbo** [comment]
Can't really help you if you don't give any info.

The only multitouch issue I know of is this https://github.com/juicycleff/flutter-unity-view-widget/issues/850, which is a Flutter issue that we can't fix in the plugin.
