### ISSUE TITLE
Build failed with an exception ,  AAPT: error: resource style/UnityThemeSelector (aka com.xraph.plugin.flutter_unity_widget_example:style/UnityThemeSelector) not found.

### ISSUE THREAD

**Issue by stableAhmad** [juicycleff/flutter-unity-view-widget#942]
I am new to flutter and Iam struggling to get this project running for testing.
I cloned this repo, opened unity,changed platform to Android and exported as an android release.
then opened the example project in Android studio , added the unity-classes.jar as a library and everything as described in the readme file. then when i build i find a problem inside AndroidMainfest.xml, its complaining about not finding UnityThemeSelector 

 AAPT: error: resource style/UnityThemeSelector (aka com.xraph.plugin.flutter_unity_widget_example:style/UnityThemeSelector) not found.
 
![avcavc](https://github.com/juicycleff/flutter-unity-view-widget/assets/76495846/cd83e6d8-67e6-49ad-90bf-496fe3e30a14)

**Comment by timbotimbo** [comment]
Check this PR, you need to adjust a couple of lines in the unity script https://github.com/juicycleff/flutter-unity-view-widget/pull/894
