### ISSUE TITLE
Getting black screen on android while loading unity in some devices

### ISSUE THREAD

**Issue by ajavjari** [juicycleff/flutter-unity-view-widget#945]
https://github.com/juicycleff/flutter-unity-view-widget/assets/58842000/3fe58903-d3d6-42c9-afaa-c0f041e26af6

When I try to load unity in some devices I'm getting black screen but audio is being played in the background. When I go back and open it again, after that I'm able to see the unity part. I have attached the screen recording. 
As far as I have noticed that, this issue is occurring in the android version 13 or later.
In the android version 12 or before it is working as expected. 

 - OS: Android
 - Unity Version 2022.3.20f1

I have used 2022.2.0 fuw package for integration

**Comment by timbotimbo** [comment]
Are you using flutter 3.19?

It looks like a variation of [this 3.19 bug](https://github.com/juicycleff/flutter-unity-view-widget/issues/929). 

Try the workarounds mentioned in that issue (flutter <3.19 or `useAndroidViewSurface:true`).

**Comment by ajavjari** [comment]
@timbotimbo 
Yes it worked using `useAndroidViewSurface:true`
As well rotation issue also solved with this.
Thanks
