### ISSUE TITLE
There is no error when the yellow screen appears in android but the unity screen does not appear

### ISSUE THREAD

**Issue by liujunqiang29** [juicycleff/flutter-unity-view-widget#946]
There is no error when the yellow screen appears in android but the unity screen does not appear
![WX20240424-232254@2x](https://github.com/juicycleff/flutter-unity-view-widget/assets/22760963/ee7cfbb7-e158-4b67-bbcf-517cfa26959d)

**Comment by timbotimbo** [comment]
Are you using flutter 3.19?

It looks like a variation of [this 3.19 bug](https://github.com/juicycleff/flutter-unity-view-widget/issues/929). 

Try the workarounds mentioned in that issue (flutter <3.19 or `useAndroidViewSurface:true`).


Also emulators aren't really supported, testing on a real device is better.

**Comment by ranahamdy1** [comment]
Flutter 3.22 fixes the issue
