### ISSUE TITLE
[iOS][Vuforia]: Immediate Crash after App Start

### ISSUE THREAD

**Issue by Ahmadre** [juicycleff/flutter-unity-view-widget#950]
**Describe the bug**
When I use Vuforia with latest Unity 6 it's crashing immediatly without getting any infos out of XCode or Flutter (Direct crash after SplashScreen).

**Unity:**
 - OS: macOS 14.0
 - Version Unity 6.*
 - Vuforia: add-vuforia-package-10-22-5.unitypackage

**Smartphone:**
 - Device: IPhone 15 Pro
 - OS: iOS
 - Version 17.5

**Comment by Ahmadre** [comment]
Related Issue: https://github.com/juicycleff/flutter-unity-view-widget/issues/314

**Comment by timbotimbo** [comment]
Did this work before on a lower Unity version, or is this a general issue with setting up Vuforia?

Given that this plugin doesn't support 2023 on android yet, I probably won't test Unity 6 specific issues yet.

**Comment by Ahmadre** [comment]
> Did this work before on a lower Unity version, or is this a general issue with setting up Vuforia?
> 
> Given that this plugin doesn't support 2023 on android yet, I probably won't test Unity 6 specific issues yet.

It works now with this approach: https://github.com/juicycleff/flutter-unity-view-widget/issues/314#issuecomment-785302253

@timbotimbo can we add this to our README docs? If you want I can create a PR with a `Vuforia` Setup section. There're other options one should keep in mind for third party frameworks embedded.

It works now with Unity 6 and latest Vuforia :)
