### ISSUE TITLE
UnityFramework- undefined symbols and linker command fialed with exit code 1

### ISSUE THREAD

**Issue by vermasrijan19** [juicycleff/flutter-unity-view-widget#954]
![image](https://github.com/juicycleff/flutter-unity-view-widget/assets/60309089/75b3b764-f25f-46a7-b8ae-2100ea0c82ba)

I get the following error when trying to build for IOS.

I have only added the plugin in unity project and made no other changes. The build works when before adding and after removing the plugin.

But i get this error when the plugin is in the project. It works fine on android.

**Comment by anilabansal** [comment]
@vermasrijan19 do you got any solution ?? I'm facing same issue

**Comment by vermasrijan19** [comment]
> @vermasrijan19 do you got any solution ?? I'm facing same issue

Yeah, I had not made the changes in the swift file as mentioned in the wiki
