### ISSUE TITLE
Doesn’t run smoothly on Android phones

### ISSUE THREAD

**Issue by NightRannie** [juicycleff/flutter-unity-view-widget#956]
**Describe the bug**
Currently we are combining flutter and flutter_unity_widget for app development, and we have built some 3D scenes ourselves
It works fine on IOS but not on Android

**Expected behavior**
Hope it works well

**Smartphone (please complete the following information):**
 - Device: Xiaomi12,HUAWEI P30 Pro

https://github.com/juicycleff/flutter-unity-view-widget/assets/50985610/9ee9412b-1ca6-4143-b921-06afb0bb496d

**Comment by timbotimbo** [comment]
The parameter `useAndroidViewSurface` changes the mode in which Flutter displays Unity on android. False is Virtual display (default) and true is Hybrid composition. 
You can compare the performance impact of both.

I'm not aware of anything else that impacts performance besides the settings and assets of your Unity project itself.

**Comment by anonymouszbs** [comment]
最后怎么解决的 我也一样 服啦呀

**Comment by NightRannie** [comment]
> 最后怎么解决的 我也一样 服啦呀

3d资源的问题，检查一下资源是不是太大了，我们压缩减少了一些资源后，就流畅多了
