### ISSUE TITLE
[WEB] Error: UnimplementedError: isPaused() has not been implemented.

### ISSUE THREAD

**Issue by klepov** [juicycleff/flutter-unity-view-widget#971]
**Describe the bug**
When sending a message from flutter[WEB] to unity, an exception is thrown. 

To fix this - you need to comment out the piece of code that is responsible for checking "isPaused". I think this is a workaround

`┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 94:5                                 call
│ #1   packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 89:41                                call
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 UnityRpcService >>> call AssetCreatorSystem CreateRobot with 
│ 🐛 Robot2
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3                   throw_
packages/flutter_unity_widget/src/facade_controller.dart 28:5                                 isPaused
packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 36:32                                isPaused
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                            _async
packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 31:29                                get isPaused
packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 143:15                               _sendMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                            _async
packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 138:28                               [_sendMessage]
packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 107:5                                call
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                            _async
packages/zeros_flutter_app/core/unity/rpc/unity_rpc.dart 89:41                                call
packages/zeros_flutter_app/core/unity/services/asset_creator_service.dart 49:10               createRobot
packages/zeros_flutter_app/features/random_int_viewer/presentation/ui/api_screen.dart 263:50  _createRobot
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                            _async
packages/zeros_flutter_app/features/random_int_viewer/presentation/ui/api_screen.dart 248:20  [_createRobot]
packages/flutter/src/material/ink_well.dart 1171:21                                           handleTap
packages/flutter/src/gestures/recognizer.dart 344:24                                          invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                                 handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 279:7                                                  acceptGesture
packages/flutter/src/gestures/arena.dart 167:12                                               sweep
packages/flutter/src/gestures/binding.dart 499:7                                              handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                             dispatchEvent
packages/flutter/src/rendering/binding.dart 425:11                                            dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                              [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                              handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                              [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                              [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1419:5                                            invoke1
lib/_engine/engine/platform_dispatcher.dart 333:5                                             invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                                [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                                 onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                               <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                                 <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                                 loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37              _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39              dcall
`

**To Reproduce**
Send message to Unity from flutter web

**Expected behavior**
The message is being delivered

**Screenshots**
<img width="844" alt="image" src="https://github.com/user-attachments/assets/c6e5025b-5c67-4705-a528-b8bd497279d2">

**Unity (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by timbotimbo** [comment]
Can you reproduce this using the example project? Last time I checked changing the cube rotation speed from Flutter worked just fine.

A flutter an unity version where this happens would be useful too.

Anyway the web implementation doesn't really implement most of the api calls that ios and android do, because it isn't using unity-as-a-library.
It is just an iframe of unity webgl with not much more than sending/receiving messages to and from Flutter.
Even a simple pause or resume needs a [unity c# script](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/example/unity/DemoApp/Assets/FlutterUnityIntegration/Demo/GameManager.cs) because that isn't even exposed by the unity player.

**Comment by klepov** [comment]
@timbotimbo 
in the example everything works fine!

it probably doesn't work for us because we use protobuf instead of json.

unity - 2022.3.38f
flutter - 3.22.2
dart - 3.4.3

**Comment by klepov** [comment]
looked at my team's code again and found that we are calling the isPaused method for mobile. This is not needed for the web. closing the issue
