### ISSUE TITLE
Vuforia plugin - Black screen, camera doesn't start

### ISSUE THREAD

**Issue by mcloots** [juicycleff/flutter-unity-view-widget#982]
I created a Unity project with the Vuforia plugin configured (ARCamera, ImageTarget). I did the export to flutter. When I run the Flutter application everything starts but I get a black screen where my camera is supposed to work.

A unity project without Vuforia works fine btw!

Below the only error I see in the logs. 

Any ideas?

E/Unity   ( 6186): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;
E/Unity   ( 6186):      at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
E/Unity   ( 6186):      at java.lang.reflect.Method.getReturnType(Method.java:148)
E/Unity   ( 6186):      at java.lang.Class.getDeclaredMethods(Class.java:2728)
E/Unity   ( 6186):      at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:100)
E/Unity   ( 6186):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E/Unity   ( 6186):      at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
E/Unity   ( 6186):      at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
E/Unity   ( 6186):      at android.os.Handler.dispatchMessage(Handler.java:102)
E/Unity   ( 6186):      at android.os.Looper.loopOnce(Looper.java:233)
E/Unity   ( 6186):      at android.os.Looper.loop(Looper.java:344)
E/Unity   ( 6186):      at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
E/Unity   ( 6186): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.OnBackInvokedCallback" on path: DexPathList[[zip fil

**Comment by timbotimbo** [comment]
See [this issue](https://github.com/juicycleff/flutter-unity-view-widget/issues/957). This is caused by a change in Flutter 3.22 triggering a Unity issue.
