### ISSUE TITLE
Question: I want to create 2 or more Unity widgets in one layout widget at the same time. Is this possible?

### ISSUE THREAD

**Issue by nrw123** [juicycleff/flutter-unity-view-widget#994]
I tried to display two unity widgets in a row widget at the same time in the latest 2022.2.1 version, and found that only the last one could be displayed normally, and the first one had no content. Many thanks

```
  const Row(
    children: [
      Expanded(child: MyUnityWidget()), // No content
      Expanded(child: MyUnityWidget()), // Can display
    ],
  ),
```

**Comment by timbotimbo** [comment]
You can only instantiate 1 Unity project. That instance can be shown in various UnityWidgets, but only 1 at a time.
