### ISSUE TITLE
issue in the last part of integration

### ISSUE THREAD

**Issue by Russel907** [juicycleff/flutter-unity-view-widget#996]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_unity_widget'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 904ms
Error: Gradle task assembleDebug failed with exit code 1

**Comment by timbotimbo** [comment]
Same issue as this https://github.com/juicycleff/flutter-unity-view-widget/issues/993
